# $NetBSD: Makefile,v 1.3 2019/12/06 19:29:46 markd Exp $

DISTNAME=	comfortaa.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-3.2
TEXLIVE_REV=	51461

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/comfortaa
COMMENT=	Documentation for tex-comfortaa
LICENSE=	ofl-v1.1 AND lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
