$NetBSD: patch-CMakeModules_WriteVersionHeader.cmake,v 1.5 2021/02/21 18:56:36 bouyer Exp $

Don't use ${CMAKE_MODULE_PATH} directly as it will be changed
and containt multiple directories

--- CMakeModules/WriteVersionHeader.cmake.orig	2020-12-22 21:05:01.000000000 +0100
+++ CMakeModules/WriteVersionHeader.cmake	2021-02-20 10:23:17.103854008 +0100
@@ -23,8 +23,8 @@
 #
 
 # Create the KiCad version strings
-include( ${CMAKE_MODULE_PATH}/KiCadVersion.cmake )
-include( ${CMAKE_MODULE_PATH}/KiCadFullVersion.cmake )
+include( ${CMAKE_CURRENT_LIST_DIR}/KiCadVersion.cmake )
+include( ${CMAKE_CURRENT_LIST_DIR}/KiCadFullVersion.cmake )
 
 set( _wvh_new_version_text
 "/* Do not modify this file, it was automatically generated by CMake. */
