$NetBSD: patch-about.toml,v 1.1 2025/09/22 06:14:46 pin Exp $

Fix build with cargo-about-0.8.2

--- about.toml.orig	2025-09-21 16:16:20.082708194 +0000
+++ about.toml
@@ -14,8 +14,9 @@ accepted = [
     "LicenseRef-UFL-1.0",
     "LGPL-2.1",
     "LGPL-3.0",
+    "LGPL-3.0-only",
     "Apache-2.0 WITH LLVM-exception",
     "GPL-3.0",
     "Unicode-3.0",
     "NCSA",
-]
\ No newline at end of file
+]
