$NetBSD: patch-.._libsignal-38514bdc8acaaffbccd5c96515c68deb2019abe0_Cargo.toml,v 1.1 2026/04/13 09:43:09 wiz Exp $

Use pkgsrc distfile instead of fetch during build.

--- ../libsignal-38514bdc8acaaffbccd5c96515c68deb2019abe0/Cargo.toml.orig	2026-02-19 23:26:34.000000000 +0000
+++ ../libsignal-38514bdc8acaaffbccd5c96515c68deb2019abe0/Cargo.toml
@@ -85,8 +85,8 @@ boring-signal = { git = "https://github.com/signalapp/
 # that want to use the real things can depend on those directly.
 
 boring-signal = { git = "https://github.com/signalapp/boring", tag = "signal-v5.0.2", package = "boring", default-features = false }
-curve25519-dalek-signal = { git = 'https://github.com/signalapp/curve25519-dalek', package = "curve25519-dalek", tag = 'signal-curve25519-4.1.3' }
-spqr = { git = "https://github.com/signalapp/SparsePostQuantumRatchet.git", tag = "v1.4.0" }
+curve25519-dalek-signal = { path = "../curve25519-dalek-7c6d34756355a3566a704da84dce7b1c039a6572/curve25519-dalek", package = "curve25519-dalek" }
+spqr = { path = "../SparsePostQuantumRatchet-d310c99c57a046549be205b9ce50d80dcbe5f3e4" }
 tokio-boring-signal = { git = "https://github.com/signalapp/boring", tag = "signal-v5.0.2", package = "tokio-boring" }
 
 aes = "0.8.3"
