$NetBSD: patch-.._presage-600c4ede51865f7de6ca21507e738a7bd70cc7ae_presage-store-sqlite_Cargo.toml,v 1.1 2026/04/30 08:36:58 wiz Exp $

Use pkgsrc distfile instead of fetch during build.

--- ../presage-600c4ede51865f7de6ca21507e738a7bd70cc7ae/presage-store-sqlite/Cargo.toml.orig	2026-04-11 21:19:36.111846897 +0000
+++ ../presage-600c4ede51865f7de6ca21507e738a7bd70cc7ae/presage-store-sqlite/Cargo.toml
@@ -17,7 +17,7 @@ serde_json = "1.0.135"
 prost = "0.13.4"
 serde_json = "1.0.135"
 # v0.8.6 with one unreleased patch to relax the version requirement for libsqlite3-sys
-sqlx = { version = "0.8.6", git = "https://github.com/gferon/sqlx", rev = "53c3a26c1b484175f3beb21853a1061b488bf7af", features = ["json", "sqlite", "uuid", "runtime-tokio"] }
+sqlx = { path = "../../sqlx-53c3a26c1b484175f3beb21853a1061b488bf7af", features = ["json", "sqlite", "uuid", "runtime-tokio"] }
 thiserror = "2.0.0"
 tracing = "0.1.41"
 uuid = "1.12.0"
