$NetBSD: patch-.._presage-fe3ed54c4844ae51c3a9fa49cf80a7816a31a425_presage_Cargo.toml,v 1.1 2026/04/13 09:43:10 wiz Exp $

Use pkgsrc distfile instead of fetch during build.

--- ../presage-fe3ed54c4844ae51c3a9fa49cf80a7816a31a425/presage/Cargo.toml.orig	2026-04-11 21:18:07.027602337 +0000
+++ ../presage-fe3ed54c4844ae51c3a9fa49cf80a7816a31a425/presage/Cargo.toml
@@ -12,7 +12,7 @@ cdsi = ["libsignal-service/cdsi"]
 cdsi = ["libsignal-service/cdsi"]
 
 [dependencies]
-libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "3d07d8df33482b2d191c075fdc2b750738a89384", default-features = false, features = [
+libsignal-service = { path = "../../libsignal-service-rs-3d07d8df33482b2d191c075fdc2b750738a89384", default-features = false, features = [
     "phonenumber",
 ] }
 
