# $NetBSD: buildlink3.mk,v 1.7 2007/08/05 20:03:35 tnn Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GAMIN_BUILDLINK3_MK:=	${GAMIN_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	gamin
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngamin}
BUILDLINK_PACKAGES+=	gamin
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}gamin

.if ${GAMIN_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.gamin+=	gamin>=0.1.5
BUILDLINK_ABI_DEPENDS.gamin+=	gamin>=0.1.9
BUILDLINK_PKGSRCDIR.gamin?=	../../sysutils/gamin
.endif	# GAMIN_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
