# $NetBSD: buildlink3.mk,v 1.3 2006/04/06 06:22:22 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
YORICK_BUILDLINK3_MK:=	${YORICK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	yorick
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nyorick}
BUILDLINK_PACKAGES+=	yorick

.if !empty(YORICK_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.yorick+=	yorick>=1.5.12
BUILDLINK_DEPMETHOD.yorick?=	build
BUILDLINK_ABI_DEPENDS.yorick?=	yorick>=1.6.02nb1
BUILDLINK_PKGSRCDIR.yorick?=	../../math/yorick
.endif	# YORICK_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
