# $NetBSD: buildlink3.mk,v 1.3 2023/09/08 22:08:18 mef Exp $
#

BUILDLINK_TREE+=	elib

.if !defined(ELIB_BUILDLINK3_MK)
ELIB_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.elib+=	${EMACS_PKGNAME_PREFIX}elib>=1
BUILDLINK_ABI_DEPENDS.elib?=	elib>=1.0nb8
BUILDLINK_PKGSRCDIR.elib?=	../../devel/elib

BUILDLINK_CONTENTS_FILTER.elib=	${EGREP} '.*\.el$$|.*\.elc$$'
.endif # ELIB_BUILDLINK3_MK

BUILDLINK_TREE+=	-elib
