# $NetBSD: Makefile,v 1.4 2012/06/02 00:38:49 taca Exp $

DISTNAME=	gettext_i18n_rails-0.5.4
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/grosser/gettext_i18n_rails
COMMENT=	Simple FastGettext Rails integration
LICENSE=	public-domain

DEPENDS+=	${RUBY_PKGPREFIX}-fast_gettext>=0:../../devel/ruby-fast_gettext

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
