#!@ZOPEDIR@/pcgi/pcgi-wrapper
# $NetBSD: Zope.cgi,v 1.1.1.1 2002/08/22 16:54:49 drochner Exp $
PCGI_NAME=Zope
PCGI_MODULE_PATH=@ZOPEDIR@/lib/python/Zope
PCGI_PUBLISHER=@ZOPEDIR@/pcgi/pcgi_publisher.py
PCGI_EXE=@PYTHONBIN@
PCGI_SOCKET_FILE=@INSTANCEHOME@/var/pcgi.soc
PCGI_PID_FILE=@INSTANCEHOME@/var/pcgi.pid
PCGI_ERROR_LOG=@INSTANCEHOME@/var/pcgi.log
PCGI_DISPLAY_ERRORS=1
BOBO_REALM=@INSTANCEHOME@/Zope.cgi
BOBO_DEBUG_MODE=1
INSTANCE_HOME=@INSTANCEHOME@
