$NetBSD: patch-device_bluetooth_cast__bluetooth.gni,v 1.22 2026/07/06 13:06:52 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- device/bluetooth/cast_bluetooth.gni.orig	2026-06-23 23:37:18.000000000 +0000
+++ device/bluetooth/cast_bluetooth.gni
@@ -6,5 +6,5 @@ import("//build/config/features.gni")
 
 declare_args() {
   force_cast_bluetooth = false
-  use_bluez = (is_linux && !is_castos && use_dbus) || is_chromeos
+  use_bluez = use_dbus && !is_bsd
 }
