$NetBSD: patch-mojo_core_BUILD.gn,v 1.2 2025/05/16 16:08:28 wiz Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- mojo/core/BUILD.gn.orig	2025-05-05 19:21:24.000000000 +0000
+++ mojo/core/BUILD.gn
@@ -163,7 +163,7 @@ source_set("impl_for_embedder") {
       ]
     }
 
-    if ((is_linux || is_chromeos || is_android) && !is_nacl) {
+    if ((is_linux || is_chromeos || is_android) && !is_nacl && !is_bsd) {
       sources += [
         "channel_linux.cc",
         "channel_linux.h",
