$NetBSD: patch-third__party_webrtc_modules_desktop__capture_BUILD.gn,v 1.4 2026/08/09 06:31:24 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/webrtc/modules/desktop_capture/BUILD.gn.orig	2026-08-05 20:17:42.000000000 +0000
+++ third_party/webrtc/modules/desktop_capture/BUILD.gn
@@ -712,6 +712,8 @@ rtc_library("desktop_capture") {
 
       "Xrender",
       "Xtst",
+      "X11-xcb",
+      "xcb-shm"
     ]
   }
 
