$NetBSD: patch-mojo_public_tools_bindings_mojom.gni,v 1.17 2026/04/10 17:31:57 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- mojo/public/tools/bindings/mojom.gni.orig	2026-04-06 16:25:54.000000000 +0000
+++ mojo/public/tools/bindings/mojom.gni
@@ -751,6 +751,21 @@ template("mojom") {
       enabled_features += [ "is_apple" ]
     }
 
+    if (is_openbsd) {
+      enabled_features += [ "is_openbsd" ]
+      enabled_features += [ "is_bsd" ]
+    }
+
+    if (is_netbsd) {
+      enabled_features += [ "is_netbsd" ]
+      enabled_features += [ "is_bsd" ]
+    }
+
+    if (is_freebsd) {
+      enabled_features += [ "is_freebsd" ]
+      enabled_features += [ "is_bsd" ]
+    }
+
     action_outputs = []
     foreach(base_path, output_file_base_paths) {
       filename = get_path_info(base_path, "file")
