$NetBSD: patch-media_mojo_mojom_BUILD.gn,v 1.10 2025/12/11 09:13:40 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- media/mojo/mojom/BUILD.gn.orig	2025-11-19 21:40:05.000000000 +0000
+++ media/mojo/mojom/BUILD.gn
@@ -1037,7 +1037,7 @@ source_set("test_support") {
   sources = []
   deps = []
 
-  if (is_linux || is_chromeos) {
+  if (!is_bsd && (is_linux || is_chromeos)) {
     sources += [
       "buffer_handle_test_util.cc",
       "buffer_handle_test_util.h",
