$NetBSD: patch-third__party_google__benchmark_BUILD.gn,v 1.7 2026/07/06 13:06:58 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/google_benchmark/BUILD.gn.orig	2026-06-23 23:37:18.000000000 +0000
+++ third_party/google_benchmark/BUILD.gn
@@ -79,7 +79,7 @@ component("google_benchmark") {
     "BENCHMARK_VERSION=\"1.9.0\"",
   ]
 
-  if (is_linux) {
+  if (is_linux && !is_bsd) {
     # Include hardware performance counter support.
     defines += [ "HAVE_LIBPFM=1" ]
     deps = [ "//third_party/libpfm4" ]
