$NetBSD: patch-ui_views_BUILD.gn,v 1.4 2025/08/13 07:44:34 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/views/BUILD.gn.orig	2025-07-29 22:51:44.000000000 +0000
+++ ui/views/BUILD.gn
@@ -833,7 +833,6 @@ component("views") {
       "windows_stationarity_monitor_aura.cc",
     ]
     deps += [
-      "//components/crash/core/common:crash_key",
       "//ui/aura",
       "//ui/base/cursor/mojom:cursor_type_shared",
       "//ui/events",
