$NetBSD: patch-device_bluetooth_cast__bluetooth.gni,v 1.17 2026/04/10 17:31:55 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- device/bluetooth/cast_bluetooth.gni.orig	2026-04-06 16:25:54.000000000 +0000
+++ device/bluetooth/cast_bluetooth.gni
@@ -6,5 +6,5 @@ import("//build/config/features.gni")
 
 declare_args() {
   force_cast_bluetooth = false
-  use_bluez = (is_linux && !is_castos && use_dbus) || is_chromeos
+  use_bluez = use_dbus && !is_bsd
 }
