$NetBSD: patch-third__party_node_node.gni,v 1.2 2025/05/16 16:08:32 wiz Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/node/node.gni.orig	2025-05-05 19:21:24.000000000 +0000
+++ third_party/node/node.gni
@@ -22,7 +22,7 @@ template("node") {
 
     # When use_remoteexec=true, node actions may run on remote
     # Linux worker. So it should include linux node binary in inputs.
-    if (is_linux || is_chromeos || use_remoteexec) {
+    if ((is_linux || is_chromeos || use_remoteexec) && !is_bsd) {
       inputs += [ "//third_party/node/linux/node-linux-x64/bin/node" ]
     }
     if (is_win && host_os == "win") {
@@ -35,16 +35,5 @@ template("node") {
         inputs += [ "//third_party/node/mac/node-darwin-x64/bin/node" ]
       }
     }
-
-    # Automatically add a dependency to ":check_version" to ensure NodeJS is
-    # always running the expected version, except when the ':check_version'
-    # target itself is running in which case it shouldn't depend on itself.
-    if (get_label_info(":" + target_name, "label_no_toolchain") !=
-        "//third_party/node:check_version") {
-      if (!defined(deps)) {
-        deps = []
-      }
-      deps += [ "//third_party/node:check_version" ]
-    }
   }
 }
