$NetBSD: patch-build_dotfile__settings.gni,v 1.6 2026/02/15 09:03:56 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- build/dotfile_settings.gni.orig	2026-02-03 22:07:10.000000000 +0000
+++ build/dotfile_settings.gni
@@ -23,6 +23,7 @@ build_dotfile_settings = {
     "//build/config/mac/mac_sdk.gni",
     "//build/config/mac/rules.gni",
     "//build/config/posix/BUILD.gn",
+    "//build/config/rust.gni",
     "//build/config/win/BUILD.gn",
     "//build/config/win/visual_studio_version.gni",
     "//build/rust/analyze.gni",
