$NetBSD: patch-third__party_angle_util_BUILD.gn,v 1.17 2026/04/10 17:31:59 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/angle/util/BUILD.gn.orig	2026-04-06 16:25:54.000000000 +0000
+++ third_party/angle/util/BUILD.gn
@@ -334,7 +334,7 @@ foreach(is_shared_library,
     ]
     libs = []
 
-    if (is_linux || is_chromeos) {
+    if ((is_linux || is_chromeos) && !is_bsd) {
       libs += [
         "rt",
         "dl",
