$NetBSD: patch-build_config_clang_clang.gni,v 1.6 2025/12/23 13:22:11 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- build/config/clang/clang.gni.orig	2025-12-17 23:05:18.000000000 +0000
+++ build/config/clang/clang.gni
@@ -88,7 +88,7 @@ declare_args() {
   #
   # TODO(https://crbug.com/440260716): Enable for Cronet in AOSP once gn2bp
   # supports copy targets.
-  use_clang_modules =
+  use_clang_modules = !is_bsd &&
       # Clang modules doesn't work with translation_unit used in codesearch
       # pipeline http://b/436082487.
       !enable_kythe_annotations && is_clang &&
