$NetBSD: patch-content_test_BUILD.gn,v 1.22 2026/07/06 13:06:51 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/test/BUILD.gn.orig	2026-06-23 23:37:18.000000000 +0000
+++ content/test/BUILD.gn
@@ -1888,7 +1888,7 @@ test("content_browsertests") {
     "--disable-crashpad-for-testing",
   ]
 
-  if (is_linux) {
+  if ((is_linux) && !is_bsd) {
     sources += [ "../browser/network/address_map_linux_browsertest.cc" ]
   }
 
