$NetBSD: patch-third__party_litert_features.gni,v 1.7 2026/09/02 13:13:37 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/litert/features.gni.orig	2026-08-31 22:47:51.000000000 +0000
+++ third_party/litert/features.gni
@@ -4,5 +4,5 @@
 
 declare_args() {
   # This enables building LiteRT with XNNPACK.
-  build_litert_with_xnnpack = current_cpu != "arm" && !is_fuchsia
+  build_litert_with_xnnpack = current_cpu != "arm" && !is_fuchsia && !is_bsd
 }
