$NetBSD: patch-ui_gfx_BUILD.gn,v 1.8 2025/10/16 19:43:37 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/gfx/BUILD.gn.orig	2025-10-13 21:41:26.000000000 +0000
+++ ui/gfx/BUILD.gn
@@ -663,7 +663,7 @@ source_set("memory_buffer_sources") {
     deps += [ "//build/config/linux/libdrm" ]
   }
 
-  if (is_linux || is_chromeos || is_android) {
+  if ((is_linux || is_chromeos || is_android) && !is_bsd) {
     deps += [ "//third_party/libsync" ]
   }
 
