$NetBSD: patch-media_mojo_mojom_BUILD.gn,v 1.7 2025/10/16 19:43:31 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- media/mojo/mojom/BUILD.gn.orig	2025-10-13 21:41:26.000000000 +0000
+++ media/mojo/mojom/BUILD.gn
@@ -962,7 +962,7 @@ source_set("test_support") {
   sources = []
   deps = []
 
-  if (is_linux || is_chromeos) {
+  if (!is_bsd && (is_linux || is_chromeos)) {
     sources += [
       "buffer_handle_test_util.cc",
       "buffer_handle_test_util.h",
