$NetBSD: patch-chrome_browser_extensions_BUILD.gn,v 1.22 2026/07/06 13:06:43 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- chrome/browser/extensions/BUILD.gn.orig	2026-06-23 23:37:18.000000000 +0000
+++ chrome/browser/extensions/BUILD.gn
@@ -1524,6 +1524,10 @@ source_set("extensions") {
       ]
     }
 
+    if (is_bsd) {
+      sources -= [ "api/image_writer_private/removable_storage_provider_linux.cc" ]
+    }
+
     if (enable_pdf) {
       deps += [
         "//chrome/browser/pdf",
