$NetBSD: patch-base_allocator_partition__allocator_src_partition__alloc_BUILD.gn,v 1.5 2025/08/13 07:44:14 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- base/allocator/partition_allocator/src/partition_alloc/BUILD.gn.orig	2025-07-29 22:51:44.000000000 +0000
+++ base/allocator/partition_allocator/src/partition_alloc/BUILD.gn
@@ -893,7 +893,7 @@ if (is_clang_or_gcc) {
         configs -= [ partition_alloc_enable_arc_config ]
       }
     }
-    if (is_chromeos || is_linux) {
+    if ((is_chromeos || is_linux) && !is_bsd) {
       shim_headers += [
         "shim/allocator_shim_override_cpp_symbols.h",
         "shim/allocator_shim_override_glibc_weak_symbols.h",
