$NetBSD: patch-ui_webui_webui__features.gni,v 1.3 2026/08/09 06:31:26 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/webui/webui_features.gni.orig	2026-08-05 20:17:42.000000000 +0000
+++ ui/webui/webui_features.gni
@@ -44,7 +44,8 @@ if (enable_cast_receiver || is_cast_andr
     # Enable the WebUI version of the New Tab Page.
     enable_webui_ntp =
         target_os == "win" || target_os == "mac" || target_os == "linux" ||
-        target_os == "chromeos" || is_desktop_android
+        target_os == "chromeos" || is_desktop_android || target_os == "openbsd" ||
+        target_os == "freebsd" || target_os == "netbsd"
   }
   declare_args() {
     # Enable WebUI Contextual Tasks Composebox.
