$NetBSD: patch-third__party_webrtc_modules_desktop__capture_BUILD.gn,v 1.5 2026/09/02 13:13:38 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/webrtc/modules/desktop_capture/BUILD.gn.orig	2026-08-31 22:47:51.000000000 +0000
+++ third_party/webrtc/modules/desktop_capture/BUILD.gn
@@ -731,6 +731,8 @@ rtc_library("desktop_capture") {
 
       "Xrender",
       "Xtst",
+      "X11-xcb",
+      "xcb-shm"
     ]
   }
 
