$NetBSD: patch-ui_qt_BUILD.gn,v 1.6 2025/09/08 13:24:35 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/qt/BUILD.gn.orig	2025-08-29 18:50:09.000000000 +0000
+++ ui/qt/BUILD.gn
@@ -20,7 +20,7 @@ config("qt_internal_config") {
 
   # It's OK to depend on the system libstdc++ since it's a dependency of QT, so
   # it will get loaded into the process anyway.
-  libs = [ "stdc++" ]
+  # libs = [ "stdc++" ]
 
   configs = [
     "//build/config/linux:runtime_library",
