$NetBSD: patch-services_network_BUILD.gn,v 1.2 2025/05/16 16:08:30 wiz Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/network/BUILD.gn.orig	2025-05-05 19:21:24.000000000 +0000
+++ services/network/BUILD.gn
@@ -400,7 +400,6 @@ if (is_linux || is_chromeos) {
     ]
     deps = [
       "//base:base",
-      "//sandbox/linux:sandbox_services",
       "//sandbox/policy:policy",
     ]
     configs += [ "//build/config/compiler:wexit_time_destructors" ]
