$NetBSD: patch-build_config_clang_clang.gni,v 1.11 2026/04/21 15:21:08 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- build/config/clang/clang.gni.orig	2026-04-14 23:31:37.000000000 +0200
+++ build/config/clang/clang.gni
@@ -40,6 +40,7 @@ android_supported_cpus = [
   "x86",
 ]
 clang_modules_platform_supported =
+    !is_bsd &&
     # s390x should work, but IBM doesn't want it enabled for that cpu arch.
     (is_linux && current_cpu != "s390x") ||
     (is_android &&
