$NetBSD: patch-services_device_serial_BUILD.gn,v 1.19 2026/05/10 15:30:02 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/device/serial/BUILD.gn.orig	2026-04-28 23:05:57.000000000 +0200
+++ services/device/serial/BUILD.gn
@@ -8,7 +8,7 @@ if (is_android) {
   import("//third_party/jni_zero/jni_zero.gni")
 }
 
-if (is_win || ((is_linux || is_chromeos) && use_udev) || is_mac || is_android) {
+if (is_win || ((!is_bsd && is_linux || is_chromeos) && use_udev) || is_mac || is_android) {
   config("platform_support") {
     visibility = [ ":serial" ]
     if (is_win) {
