$NetBSD: patch-gpu_webgpu_dawn__commit__hash.h,v 1.1 2025/11/04 14:55:41 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- gpu/webgpu/dawn_commit_hash.h.orig	2025-11-03 16:55:48.310183294 +0000
+++ gpu/webgpu/dawn_commit_hash.h
@@ -0,0 +1,8 @@
+/* Generated by lastchange.py, do not edit.*/
+
+#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
+#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_
+
+#define DAWN_COMMIT_HASH "cee9cb0d67e749bf42f5e90cb3b8a6f525dbb920"
+
+#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
