$NetBSD: patch-build_nocompile.gni,v 1.2 2025/07/07 09:23:25 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- build/nocompile.gni.orig	2025-06-30 06:54:11.000000000 +0000
+++ build/nocompile.gni
@@ -55,7 +55,7 @@ if (is_win) {
 }
 
 declare_args() {
-  enable_nocompile_tests = is_clang && !is_nacl
+  enable_nocompile_tests = is_clang && !is_nacl && !is_bsd
 }
 
 if (enable_nocompile_tests) {
