$NetBSD: patch-services_device_public_mojom_BUILD.gn,v 1.5 2025/08/13 07:44:29 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/device/public/mojom/BUILD.gn.orig	2025-07-29 22:51:44.000000000 +0000
+++ services/device/public/mojom/BUILD.gn
@@ -107,7 +107,7 @@ mojom("device_service") {
   enable_js_fuzzing = false
 
   enabled_features = []
-  if ((is_linux || is_chromeos) && use_udev) {
+  if ((is_linux || is_chromeos) && !is_bsd && use_udev) {
     enabled_features += [ "enable_input_device_manager" ]
   }
 
