$NetBSD: patch-content_zygote_BUILD.gn,v 1.19 2026/05/10 15:29:58 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/zygote/BUILD.gn.orig	2026-04-28 23:05:57.000000000 +0200
+++ content/zygote/BUILD.gn
@@ -4,7 +4,7 @@
 
 import("//content/public/common/zygote/features.gni")
 
-if (is_linux || is_chromeos) {
+if ((is_linux || is_chromeos) && !is_bsd) {
   source_set("zygote") {
     sources = [
       "zygote_linux.cc",
