$NetBSD: patch-third__party_ffmpeg_BUILD.gn,v 1.6 2025/09/08 13:24:32 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/ffmpeg/BUILD.gn.orig	2025-08-29 18:50:09.000000000 +0000
+++ third_party/ffmpeg/BUILD.gn
@@ -355,7 +355,6 @@ target(link_target_type, "ffmpeg_interna
       libs += [
         "m",
         "z",
-        "rt",
       ]
     }
     if (is_component_ffmpeg) {
