$NetBSD: patch-components_storage__monitor_BUILD.gn,v 1.18 2026/04/21 15:21:14 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- components/storage_monitor/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ components/storage_monitor/BUILD.gn
@@ -66,7 +66,7 @@ component("storage_monitor") {
       deps += [ "//services/device/public/mojom" ]
     }
   } else if (is_linux) {
-    if (use_udev) {
+    if (use_udev && !is_bsd) {
       sources += [
         "mtab_watcher_linux.cc",
         "mtab_watcher_linux.h",
@@ -167,7 +167,7 @@ source_set("unit_tests") {
         "storage_monitor_chromeos_unittest.cc",
       ]
     }
-  } else if (is_linux) {
+  } else if (is_linux && !is_bsd) {
     if (use_udev) {
       sources += [ "storage_monitor_linux_unittest.cc" ]
     }
