$NetBSD: patch-third__party_angle_util_BUILD.gn,v 1.11 2025/12/11 09:13:43 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/angle/util/BUILD.gn.orig	2025-11-19 21:40:05.000000000 +0000
+++ third_party/angle/util/BUILD.gn
@@ -334,7 +334,7 @@ foreach(is_shared_library,
     ]
     libs = []
 
-    if (is_linux || is_chromeos) {
+    if ((is_linux || is_chromeos) && !is_bsd) {
       libs += [
         "rt",
         "dl",
