$NetBSD: patch-services_service__manager_BUILD.gn,v 1.6 2025/09/08 13:24:30 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/service_manager/BUILD.gn.orig	2025-08-29 18:50:09.000000000 +0000
+++ services/service_manager/BUILD.gn
@@ -65,7 +65,7 @@ source_set("service_manager") {
     ]
   }
 
-  if (is_linux || is_chromeos) {
+  if ((is_linux || is_chromeos) && !is_bsd) {
     deps += [ "//sandbox/linux:sandbox_services" ]
   }
 }
