$NetBSD: patch-chrome_browser_extensions_BUILD.gn,v 1.27 2026/09/29 07:42:48 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- chrome/browser/extensions/BUILD.gn.orig	2026-09-22 00:09:16.000000000 +0000
+++ chrome/browser/extensions/BUILD.gn
@@ -1513,6 +1513,10 @@ source_set("extensions") {
       ]
     }
 
+    if (is_bsd) {
+      sources -= [ "api/image_writer_private/removable_storage_provider_linux.cc" ]
+    }
+
     if (enable_pdf) {
       deps += [
         "//chrome/browser/pdf",
