$NetBSD: patch-third__party_openscreen_src_util_BUILD.gn,v 1.3 2026/10/02 11:43:37 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/openscreen/src/util/BUILD.gn.orig	2026-09-22 00:09:16.000000000 +0000
+++ third_party/openscreen/src/util/BUILD.gn
@@ -152,7 +152,7 @@ openscreen_source_set("util") {
     sources += [ "scoped_wake_lock_mac.cc" ]
   }
 
-  if (is_linux) {
+  if (is_linux && !is_bsd) {
     sources += [ "scoped_wake_lock_linux.cc" ]
   }
 
