$NetBSD: patch-content_test_BUILD.gn,v 1.6 2025/09/08 13:24:26 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/test/BUILD.gn.orig	2025-08-29 18:50:09.000000000 +0000
+++ content/test/BUILD.gn
@@ -1810,7 +1810,7 @@ test("content_browsertests") {
     "--disable-crashpad-for-testing",
   ]
 
-  if (is_linux) {
+  if ((is_linux) && !is_bsd) {
     sources += [ "../browser/network/address_map_linux_browsertest.cc" ]
   }
 
