$NetBSD: patch-services_network_BUILD.gn,v 1.18 2026/04/21 15:21:19 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/network/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ services/network/BUILD.gn
@@ -449,7 +449,6 @@ if (is_linux || is_chromeos) {
     ]
     deps = [
       "//base",
-      "//sandbox/linux:sandbox_services",
       "//sandbox/policy",
     ]
     configs += [ "//build/config/compiler:wexit_time_destructors" ]
