$NetBSD: patch-content_zygote_BUILD.gn,v 1.6 2025/09/08 13:24:26 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/zygote/BUILD.gn.orig	2025-08-29 18:50:09.000000000 +0000
+++ content/zygote/BUILD.gn
@@ -4,7 +4,7 @@
 
 import("//content/public/common/zygote/features.gni")
 
-if (is_linux || is_chromeos) {
+if ((is_linux || is_chromeos) && !is_bsd) {
   source_set("zygote") {
     sources = [
       "zygote_linux.cc",
