$NetBSD: patch-headless_BUILD.gn,v 1.16 2026/04/10 17:31:56 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- headless/BUILD.gn.orig	2026-04-06 16:25:54.000000000 +0000
+++ headless/BUILD.gn
@@ -849,7 +849,7 @@ component("headless_shell_lib") {
     "//printing/buildflags",
   ]
 
-  if (!is_fuchsia) {
+  if (!is_fuchsia && !is_bsd) {
     deps += [ "//components/crash/core/app" ]
   }
 
