$NetBSD: patch-v8_src_objects_js-temporal-zoneinfo64.cc,v 1.11 2026/05/10 15:30:09 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- v8/src/objects/js-temporal-zoneinfo64.cc.orig	2026-04-28 23:05:57.000000000 +0200
+++ v8/src/objects/js-temporal-zoneinfo64.cc
@@ -11,7 +11,7 @@
 #include "temporal_rs/TimeZone.hpp"
 
 #ifdef V8_INTL_SUPPORT
-#include "udatamem.h"
+#include "../../third_party/icu/source/common/udatamem.h"
 #else
 // Defined in builtins-temporal-zoneinfo64-data.cc, generated by
 // include-file-as-bytes.py
