$NetBSD: patch-chrome_browser_metrics_BUILD.gn,v 1.4 2026/08/09 06:31:09 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- chrome/browser/metrics/BUILD.gn.orig	2026-08-05 20:17:42.000000000 +0000
+++ chrome/browser/metrics/BUILD.gn
@@ -210,7 +210,7 @@ source_set("metrics") {
     ]
   }
 
-  if (is_linux || is_chromeos) {
+  if (!is_bsd && (is_linux || is_chromeos)) {
     public += [ "bluetooth_metrics_provider.h" ]
   }
 
@@ -221,7 +221,7 @@ source_set("metrics") {
     ]
   }
 
-  if (is_win || is_android || is_linux) {
+  if (!is_bsd && (is_win || is_android || is_linux)) {
     public += [ "chrome_metrics_service_crash_reporter.h" ]
   }
 
@@ -476,7 +476,7 @@ source_set("impl") {
     sources += [ "structured/chrome_structured_metrics_delegate.cc" ]
   }
 
-  if (is_linux || is_chromeos) {
+  if (!is_bsd && (is_linux || is_chromeos)) {
     sources += [ "bluetooth_metrics_provider.cc" ]
   }
 
@@ -491,7 +491,7 @@ source_set("impl") {
     deps += [ "//chrome/browser/updates:update_metrics" ]
   }
 
-  if (is_win || is_android || is_linux) {
+  if (!is_bsd && (is_win || is_android || is_linux)) {
     sources += [ "chrome_metrics_service_crash_reporter.cc" ]
   }
 
