$NetBSD: patch-content_app_BUILD.gn,v 1.10 2025/11/20 08:36:14 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/app/BUILD.gn.orig	2025-11-14 20:31:45.000000000 +0000
+++ content/app/BUILD.gn
@@ -91,7 +91,10 @@ source_set("content_main_runner_app") {
            "//third_party/tflite:buildflags",
            "//tools/v8_context_snapshot:buildflags",
          ]
-  if (build_tflite_with_xnnpack) {
+  if (is_bsd) {
+    deps += [ "//skia" ]
+  }
+  if (!is_bsd && build_tflite_with_xnnpack) {
     deps += [ "//third_party/cpuinfo" ]
   }
 }
