$NetBSD: patch-third__party_ffmpeg_BUILD.gn,v 1.18 2026/04/21 15:21:21 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/ffmpeg/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ third_party/ffmpeg/BUILD.gn
@@ -362,7 +362,6 @@ target(link_target_type, "ffmpeg_interna
       libs += [
         "m",
         "z",
-        "rt",
       ]
     }
     if (is_component_ffmpeg) {
