$NetBSD: patch-third__party_webrtc_system__wrappers_BUILD.gn,v 1.4 2025/07/25 16:17:23 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/webrtc/system_wrappers/BUILD.gn.orig	2025-07-21 19:32:31.000000000 +0000
+++ third_party/webrtc/system_wrappers/BUILD.gn
@@ -56,8 +56,6 @@ rtc_library("system_wrappers") {
     if (!build_with_chromium) {
       sources += [ "source/cpu_features_linux.cc" ]
     }
-
-    libs += [ "rt" ]
   }
 
   if (is_win) {
