$NetBSD: patch-third__party_google__benchmark_BUILD.gn,v 1.3 2026/04/21 15:21:21 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/google_benchmark/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ third_party/google_benchmark/BUILD.gn
@@ -79,7 +79,7 @@ component("google_benchmark") {
     "BENCHMARK_VERSION=\"1.9.0\"",
   ]
 
-  if (is_linux) {
+  if (is_linux && !is_bsd) {
     # Include hardware performance counter support.
     defines += [ "HAVE_LIBPFM=1" ]
     deps = [ "//third_party/libpfm4" ]
