$NetBSD: patch-services_viz_public_mojom_BUILD.gn,v 1.23 2026/08/09 06:31:21 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/viz/public/mojom/BUILD.gn.orig	2026-08-05 20:17:42.000000000 +0000
+++ services/viz/public/mojom/BUILD.gn
@@ -54,7 +54,7 @@ mojom("mojom") {
 
   # Used in thread.mojom
   enabled_features = []
-  if (is_fuchsia || is_apple) {
+  if (is_fuchsia || is_apple || is_bsd) {
     enabled_features += [ "thread_id_is_64_bit" ]
   } else {
     enabled_features += [ "thread_id_is_32_bit" ]
