$NetBSD: patch-third__party_angle_util_BUILD.gn,v 1.20 2026/06/01 10:09:19 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/angle/util/BUILD.gn.orig	2026-05-26 20:39:02.000000000 +0000
+++ third_party/angle/util/BUILD.gn
@@ -334,7 +334,7 @@ foreach(is_shared_library,
     ]
     libs = []
 
-    if (is_linux || is_chromeos) {
+    if ((is_linux || is_chromeos) && !is_bsd) {
       libs += [
         "rt",
         "dl",
