$NetBSD: patch-components_gwp__asan_buildflags_buildflags.gni,v 1.6 2025/09/12 16:02:26 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- components/gwp_asan/buildflags/buildflags.gni.orig	2025-09-08 23:21:33.000000000 +0000
+++ components/gwp_asan/buildflags/buildflags.gni
@@ -10,10 +10,7 @@ import("//build/config/compiler/compiler
 # Android component builds are disabled due to https://crbug.com/976399
 # Android requires frame pointers for unwinding, unwind tables aren't shipped in
 # official builds.
-supported_platform =
-    is_linux || is_chromeos || is_mac || is_ios ||
-    (is_win && (current_cpu == "x64" || current_cpu == "arm64")) ||
-    (is_android && !is_component_build && enable_frame_pointers)
+supported_platform = false
 
 declare_args() {
   # Is GWP-ASan malloc/PartitionAlloc hooking enabled for chrome/ on a given
