$NetBSD: patch-ui_views_BUILD.gn,v 1.16 2026/04/10 17:32:02 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/views/BUILD.gn.orig	2026-04-06 16:25:54.000000000 +0000
+++ ui/views/BUILD.gn
@@ -843,7 +843,6 @@ component("views") {
       "windows_stationarity_monitor_aura.cc",
     ]
     deps += [
-      "//components/crash/core/common:crash_key",
       "//ui/aura",
       "//ui/base/cursor/mojom:cursor_type_shared",
       "//ui/events",
