$NetBSD: patch-services_network_BUILD.gn,v 1.19 2026/05/10 15:30:03 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/network/BUILD.gn.orig	2026-04-28 23:05:57.000000000 +0200
+++ services/network/BUILD.gn
@@ -447,7 +447,6 @@ if (is_linux || is_chromeos) {
     ]
     deps = [
       "//base",
-      "//sandbox/linux:sandbox_services",
       "//sandbox/policy",
     ]
     configs += [ "//build/config/compiler:wexit_time_destructors" ]
