$NetBSD: patch-third__party_test__fonts_fontconfig_BUILD.gn,v 1.19 2026/05/10 15:30:06 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/test_fonts/fontconfig/BUILD.gn.orig	2026-04-28 23:05:57.000000000 +0200
+++ third_party/test_fonts/fontconfig/BUILD.gn
@@ -26,7 +26,7 @@ if (is_linux || is_chromeos) {
 
   copy("fonts_conf") {
     sources = [ "fonts.conf" ]
-    outputs = [ "$root_out_dir/etc/fonts/{{source_file_part}}" ]
+    outputs = [ "$root_out_dir@PKG_SYSCONFBASE@/fontconfig/{{source_file_part}}" ]
   }
 
   if (current_toolchain == host_toolchain) {
@@ -47,9 +47,9 @@ if (is_linux || is_chromeos) {
         "//third_party/test_fonts",
       ]
       args = []
-      inputs = [ "$root_out_dir/etc/fonts/fonts.conf" ]
+      inputs = [ "$root_out_dir@PKG_SYSCONFBASE@/fontconfig/fonts.conf" ]
       outputs = [
-        "$root_out_dir/fontconfig_caches/fb5c91b2895aa445d23aebf7f9e2189c-le64.cache-11",
+        "$root_out_dir/fontconfig_caches/fb5c91b2895aa445d23aebf7f9e2189c-le64.cache-9",
         "$root_out_dir/fontconfig_caches/CACHEDIR.TAG",
       ]
     }
