$NetBSD: patch-third__party_ffmpeg_BUILD.gn,v 1.27 2026/09/29 07:43:04 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/ffmpeg/BUILD.gn.orig	2026-09-22 00:09:16.000000000 +0000
+++ third_party/ffmpeg/BUILD.gn
@@ -389,7 +389,6 @@ target(link_target_type, "ffmpeg_interna
       libs += [
         "m",
         "z",
-        "rt",
       ]
     }
     if (is_component_ffmpeg) {
