$NetBSD: patch-mojo_core_BUILD.gn,v 1.5 2025/08/13 07:44:27 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- mojo/core/BUILD.gn.orig	2025-07-29 22:51:44.000000000 +0000
+++ mojo/core/BUILD.gn
@@ -164,7 +164,7 @@ source_set("impl_for_embedder") {
       ]
     }
 
-    if ((is_linux || is_chromeos || is_android) && !is_nacl) {
+    if ((is_linux || is_chromeos || is_android) && !is_nacl && !is_bsd) {
       sources += [
         "channel_linux.cc",
         "channel_linux.h",
