$NetBSD: patch-chrome_browser_extensions_BUILD.gn,v 1.18 2026/04/21 15:21:09 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- chrome/browser/extensions/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ chrome/browser/extensions/BUILD.gn
@@ -1523,6 +1523,10 @@ source_set("extensions") {
       deps += [ "//chrome/services/printing/public/mojom" ]
     }
 
+    if (is_bsd) {
+      sources -= [ "api/image_writer_private/removable_storage_provider_linux.cc" ]
+    }
+
     if (enable_pdf) {
       deps += [
         "//chrome/browser/pdf",
