$NetBSD: patch-third__party_nasm_BUILD.gn,v 1.24 2026/08/09 06:31:23 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/nasm/BUILD.gn.orig	2026-08-05 20:17:42.000000000 +0000
+++ third_party/nasm/BUILD.gn
@@ -64,6 +64,13 @@ config("nasm_config") {
 
   defines = [ "HAVE_CONFIG_H" ]
 
+  _string_h_lines =
+        read_file("/usr/include/string.h", "list lines")
+  _mempcpy = filter_include(_string_h_lines, [ "*mempcpy*" ])
+  if (_mempcpy != []) {
+    defines += [ "HAVE_MEMPCPY=1" ]
+  }
+
   if (is_clang) {
     cflags = [
       # The inline functions in NASM's headers flag this.
