$NetBSD: patch-build_config_linux_libdrm_BUILD.gn,v 1.7 2025/10/16 19:43:20 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- build/config/linux/libdrm/BUILD.gn.orig	2025-10-13 21:41:26.000000000 +0000
+++ build/config/linux/libdrm/BUILD.gn
@@ -15,7 +15,7 @@ declare_args() {
 }
 
 if (use_system_libdrm) {
-  assert(!is_linux, "System libdrm is not supported in linux")
+#  assert(!is_linux, "System libdrm is not supported in linux")
   pkg_config("libdrm_config") {
     packages = [ "libdrm" ]
   }
