$NetBSD: patch-third__party_pdfium_BUILD.gn,v 1.1 2026/09/29 07:43:05 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/pdfium/BUILD.gn.orig	2026-09-22 00:09:16.000000000 +0000
+++ third_party/pdfium/BUILD.gn
@@ -172,7 +172,7 @@ config("pdfium_core_config") {
     "//build/config/compiler:noshadowing",
   ]
   defines = []
-  if (is_clang) {
+  if (is_clang && !is_bsd) {
     cflags += [
       "-Wcovered-switch-default",
       "-Wlifetime-safety-permissive",
