$NetBSD: patch-third__party_webrtc_system__wrappers_BUILD.gn,v 1.2 2025/05/16 16:08:33 wiz Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/webrtc/system_wrappers/BUILD.gn.orig	2025-05-05 19:21:24.000000000 +0000
+++ third_party/webrtc/system_wrappers/BUILD.gn
@@ -62,8 +62,6 @@ rtc_library("system_wrappers") {
     if (!build_with_chromium) {
       sources += [ "source/cpu_features_linux.cc" ]
     }
-
-    libs += [ "rt" ]
   }
 
   if (is_win) {
