$NetBSD: patch-third__party_webrtc_BUILD.gn,v 1.10 2025/11/20 08:36:23 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/webrtc/BUILD.gn.orig	2025-11-14 20:31:45.000000000 +0000
+++ third_party/webrtc/BUILD.gn
@@ -220,6 +220,9 @@ config("common_inherited_config") {
   if (is_linux || is_chromeos) {
     defines += [ "WEBRTC_LINUX" ]
   }
+  if (is_bsd) {
+    defines += [ "WEBRTC_BSD" ]
+  }
   if (is_mac) {
     defines += [ "WEBRTC_MAC" ]
   }
