$NetBSD: patch-mojo_core_BUILD.gn,v 1.18 2026/04/21 15:21:17 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- mojo/core/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ mojo/core/BUILD.gn
@@ -163,7 +163,7 @@ source_set("impl_for_embedder") {
       "channel_posix.h",
     ]
 
-    if (is_linux || is_chromeos || is_android) {
+    if ((is_linux || is_chromeos || is_android) && !is_bsd) {
       sources += [
         "channel_linux.cc",
         "channel_linux.h",
