$NetBSD: patch-media_BUILD.gn,v 1.15 2026/02/15 09:04:06 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- media/BUILD.gn.orig	2026-02-03 22:07:10.000000000 +0000
+++ media/BUILD.gn
@@ -107,6 +107,12 @@ config("media_config") {
       defines += [ "DLOPEN_PULSEAUDIO" ]
     }
   }
+  if (use_sndio) {
+    defines += [ "USE_SNDIO" ]
+  }
+#  if (use_audioio) {
+#    defines += [ "USE_AUDIOIO" ]
+#  }
 }
 
 # Internal grouping of the configs necessary to support sub-folders having their
