$NetBSD: patch-headless_BUILD.gn,v 1.17 2026/04/21 15:21:17 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- headless/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ headless/BUILD.gn
@@ -849,7 +849,7 @@ component("headless_shell_lib") {
     "//printing/buildflags",
   ]
 
-  if (!is_fuchsia) {
+  if (!is_fuchsia && !is_bsd) {
     deps += [ "//components/crash/core/app" ]
   }
 
