$NetBSD: patch-content_child_BUILD.gn,v 1.19 2026/05/10 15:29:58 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/child/BUILD.gn.orig	2026-04-28 23:05:57.000000000 +0200
+++ content/child/BUILD.gn
@@ -136,6 +136,13 @@ target(link_target_type, "child") {
     ]
   }
 
+  if (is_bsd) {
+    sources -= [
+      "sandboxed_process_thread_type_handler.cc",
+      "sandboxed_process_thread_type_handler.h",
+    ]
+  }
+
   if (is_win) {
     sources += [
       "child_process_sandbox_support_impl_win.cc",
