$NetBSD: patch-third__party_crabbyavif_BUILD.gn,v 1.16 2026/08/09 06:31:22 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/crabbyavif/BUILD.gn.orig	2026-08-05 20:17:42.000000000 +0000
+++ third_party/crabbyavif/BUILD.gn
@@ -203,12 +203,11 @@ rust_static_library("crabbyavif") {
     "dav1d",
     "libyuv",
     "capi",
-    "disable_cfi",
   ]
 
   # Required for disable_cfi feature.
   configs -= [ "//build/config/compiler:disallow_unstable_features" ]
-  rustflags = [ "-Zallow-features=sanitize" ]
+  rustflags = [ "-Zallow-features=no_sanitize" ]
 
   public_deps = [ ":header_files" ]
   deps = [
