$NetBSD: patch-third__party_webrtc_modules_desktop__capture_BUILD.gn,v 1.1 2026/06/08 13:12:48 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/webrtc/modules/desktop_capture/BUILD.gn.orig	2026-05-28 23:24:11.000000000 +0000
+++ third_party/webrtc/modules/desktop_capture/BUILD.gn
@@ -429,6 +429,8 @@ rtc_library("desktop_capture") {
 
       "Xrender",
       "Xtst",
+      "X11-xcb",
+      "xcb-shm"
     ]
   }
 
