$NetBSD: patch-services_viz_public_mojom_BUILD.gn,v 1.1 2025/05/16 16:08:30 wiz Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/viz/public/mojom/BUILD.gn.orig	2025-05-05 19:21:24.000000000 +0000
+++ services/viz/public/mojom/BUILD.gn
@@ -56,7 +56,7 @@ mojom("mojom") {
 
   # Used in thread.mojom
   enabled_features = []
-  if (is_fuchsia || is_apple) {
+  if (is_fuchsia || is_apple || is_bsd) {
     enabled_features += [ "thread_id_is_64_bit" ]
   } else {
     enabled_features += [ "thread_id_is_32_bit" ]
