$NetBSD: patch-chrome_browser_media_router_discovery_BUILD.gn,v 1.25 2026/09/02 13:13:23 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- chrome/browser/media/router/discovery/BUILD.gn.orig	2026-08-31 22:47:51.000000000 +0000
+++ chrome/browser/media/router/discovery/BUILD.gn
@@ -82,7 +82,7 @@ static_library("discovery") {
   ]
   configs += [ "//build/config/compiler:wexit_time_destructors" ]
 
-  if (is_linux || is_chromeos) {
+  if ((is_linux || is_chromeos) && !is_bsd) {
     sources += [ "discovery_network_list_wifi_linux.cc" ]
   }
 
