$NetBSD: patch-ui_gl_BUILD.gn,v 1.13 2026/04/21 15:21:24 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/gl/BUILD.gn.orig	2026-04-14 23:31:37.000000000 +0200
+++ ui/gl/BUILD.gn
@@ -389,7 +389,7 @@ component("gl") {
     ]
   }
 
-  if (is_android || is_chromeos || is_linux) {
+  if ((is_android || is_chromeos || is_linux) && !is_bsd) {
     # Windows doesn't support base::FileDescriptor.
     # libsync isn't supported or needed on MacOSX.
     # Fuchsia is excluded due to a libsync dependency and because it's
