$NetBSD: patch-services_service__manager_BUILD.gn,v 1.16 2026/03/14 12:40:40 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- services/service_manager/BUILD.gn.orig	2026-03-11 22:12:25.000000000 +0000
+++ services/service_manager/BUILD.gn
@@ -65,7 +65,7 @@ source_set("service_manager") {
     ]
   }
 
-  if (is_linux || is_chromeos) {
+  if ((is_linux || is_chromeos) && !is_bsd) {
     deps += [ "//sandbox/linux:sandbox_services" ]
   }
 }
