$NetBSD: patch-content_test_BUILD.gn,v 1.17 2026/04/10 17:31:55 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/test/BUILD.gn.orig	2026-04-06 16:25:54.000000000 +0000
+++ content/test/BUILD.gn
@@ -1870,7 +1870,7 @@ test("content_browsertests") {
     "--disable-crashpad-for-testing",
   ]
 
-  if (is_linux) {
+  if ((is_linux) && !is_bsd) {
     sources += [ "../browser/network/address_map_linux_browsertest.cc" ]
   }
 
