$NetBSD: patch-ui_gfx_BUILD.gn,v 1.28 2026/10/02 11:43:40 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- ui/gfx/BUILD.gn.orig	2026-09-22 00:09:16.000000000 +0000
+++ ui/gfx/BUILD.gn
@@ -640,7 +640,7 @@ source_set("memory_buffer_sources") {
     deps += [ "//build/config/linux/libdrm" ]
   }
 
-  if (is_linux || is_chromeos || is_android) {
+  if ((is_linux || is_chromeos || is_android) && !is_bsd) {
     deps += [ "//third_party/libsync" ]
   }
 
