$NetBSD: patch-content_child_BUILD.gn,v 1.7 2025/09/12 16:02:29 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- content/child/BUILD.gn.orig	2025-09-08 23:21:33.000000000 +0000
+++ content/child/BUILD.gn
@@ -135,6 +135,13 @@ target(link_target_type, "child") {
     ]
   }
 
+  if (is_bsd) {
+    sources -= [
+      "sandboxed_process_thread_type_handler.cc",
+      "sandboxed_process_thread_type_handler.h",
+    ]
+  }
+
   if (is_win) {
     sources += [
       "child_process_sandbox_support_impl_win.cc",
