$NetBSD: patch-media_mojo_mojom_BUILD.gn,v 1.15 2026/03/14 12:40:36 kikadf Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- media/mojo/mojom/BUILD.gn.orig	2026-03-11 22:12:25.000000000 +0000
+++ media/mojo/mojom/BUILD.gn
@@ -1033,7 +1033,7 @@ source_set("test_support") {
   sources = []
   deps = []
 
-  if (is_linux || is_chromeos) {
+  if (!is_bsd && (is_linux || is_chromeos)) {
     sources += [
       "buffer_handle_test_util.cc",
       "buffer_handle_test_util.h",
