# $NetBSD: Makefile,v 1.5 2000/02/25 01:04:16 wiz Exp $
# FreeBSD Id: Makefile,v 1.13 1997/01/03 00:40:55 max Exp
#

    SUBDIR += bash2
    SUBDIR += es
    SUBDIR += scsh
    SUBDIR += tcsh
    SUBDIR += zsh

.include "../mk/bsd.pkg.subdir.mk"
