# $NetBSD: buildlink3.mk,v 1.1 2009/01/07 22:27:48 tonnerre Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY25_OPENSSL_BUILDLINK3_MK:=	${PY25_OPENSSL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py25-OpenSSL
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy25-OpenSSL}
BUILDLINK_PACKAGES+=	py25-OpenSSL
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py25-OpenSSL

.if ${PY25_OPENSSL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.py25-OpenSSL+=	py25-OpenSSL>=0.7
BUILDLINK_PKGSRCDIR.py25-OpenSSL?=	../../security/py-OpenSSL
.endif	# PY25_OPENSSL_BUILDLINK3_MK

.include "../../security/openssl/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
