# $NetBSD: Makefile,v 1.4 2023/04/09 12:28:16 markd Exp $

DISTNAME=	ifptex
PKGNAME=	tex-${DISTNAME}-2.2c
TEXLIVE_REV=	66803

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/ifptex
COMMENT=	Check if the engine is pTeX or one of its derivatives
LICENSE=	mit

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
