$NetBSD: patch-pyproject.toml,v 1.3 2025/12/26 10:49:13 adam Exp $

Relax pydantic-core version requirement.

--- pyproject.toml.orig	2020-02-02 00:00:00.000000000 +0000
+++ pyproject.toml
@@ -48,7 +48,7 @@ dependencies = [
     'typing-extensions>=4.14.1',
     'annotated-types>=0.6.0',
     # Keep this in sync with the version in the `check_pydantic_core_version()` function:
-    'pydantic-core==2.41.5',
+    'pydantic-core>=2.41.5',
     'typing-inspection>=0.4.2',
 ]
 dynamic = ['version', 'readme']
