$NetBSD: patch-pyproject.toml,v 1.1 2025/04/22 11:28:13 adam Exp $

Relax pydantic-core version requirement.

--- pyproject.toml.orig	2025-04-22 11:23:12.931012242 +0000
+++ pyproject.toml
@@ -46,7 +46,7 @@ dependencies = [
     'typing-extensions>=4.12.2',
     'annotated-types>=0.6.0',
     # Keep this in sync with the version in the `check_pydantic_core_version()` function:
-    'pydantic-core==2.33.1',
+    'pydantic-core>=2.33.1',
     'typing-inspection>=0.4.0',
 ]
 dynamic = ['version', 'readme']
