# $NetBSD: Makefile,v 1.1 2015/02/03 14:56:32 taca Exp $

DISTNAME=	colorize-0.7.5
CATEGORIES=	misc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/fazibear/colorize
COMMENT=	Add color methods to String class
LICENSE=	gnu-gpl-v2

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
