# $NetBSD: buildlink3.mk,v 1.1 2004/04/12 02:20:13 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GUILIB_BUILDLINK3_MK:=	${GUILIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	GUIlib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NGUIlib}
BUILDLINK_PACKAGES+=	GUIlib

.if !empty(GUILIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.GUIlib+=	GUIlib>=1.1.0nb2
BUILDLINK_PKGSRCDIR.GUIlib?=	../../graphics/GUIlib
.endif	# GUILIB_BUILDLINK3_MK

.include "../../devel/SDL/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
