$NetBSD: patch-spotify__player_Cargo.toml,v 1.1 2022/08/10 20:38:34 pin Exp $

Don't pull souvlaki from git, wait release.

--- spotify_player/Cargo.toml.orig	2022-08-10 13:47:40.000000000 +0000
+++ spotify_player/Cargo.toml
@@ -37,7 +37,7 @@ tracing = "0.1.36"
 tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
 lyric_finder = { version = "0.1.2", path = "../lyric_finder" , optional = true }
 backtrace = "0.3.66"
-souvlaki = { version = "0.5.1", git = "https://github.com/Sinono3/souvlaki", optional = true }
+souvlaki = { version = "0.5.1", optional = true }
 winit = { version = "0.27.1", optional = true }
 viuer = { version = "0.6.1", optional = true }
 image = { version = "0.24.3", optional = true }
