# $NetBSD: buildlink3.mk,v 1.3 2008/12/17 17:52:33 joerg Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LDNS_BUILDLINK3_MK:=		${LDNS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	ldns
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nldns}
BUILDLINK_PACKAGES+=	ldns
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ldns

.if ${LDNS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.ldns+=	ldns>=1.4
BUILDLINK_PKGSRCDIR.ldns?=	../../net/ldns
.endif	# LDNS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
