# $NetBSD: buildlink3.mk,v 1.11 2006/07/08 22:39:02 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GAIM_BUILDLINK3_MK:=	${GAIM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gaim
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngaim}
BUILDLINK_PACKAGES+=	gaim
BUILDLINK_ORDER+=	gaim

.if !empty(GAIM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.gaim+=	gaim>=1.1.2
BUILDLINK_ABI_DEPENDS.gaim+=	gaim>=1.5.0nb4
BUILDLINK_PKGSRCDIR.gaim?=	../../chat/gaim

PRINT_PLIST_AWK+=	/^@dirrm lib\/gaim$$/ \
				{ print "@comment in gaim: " $$0; next }
.endif  # GAIM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
