# $NetBSD: Makefile,v 1.1.1.1 2002/06/04 16:44:55 cjep Exp $
# FreeBSD Id: ports/x11-fm/xfm/Makefile,v 1.20 2001/02/05 21:00:55 olgeni Exp

DISTNAME=	xfm-1.4.3
CATEGORIES=	sysutils x11
MASTER_SITES=	http://www.musikwissenschaft.uni-mainz.de/~ag/xfm/

MAINTAINER=	rxg@ms25.url.com.tw
HOMEPAGE=	http://www.musikwissenschaft.uni-mainz.de/~ag/xfm/
COMMENT=	The X File Manager

WRKSRC=		${WRKDIR}/xfm-1.4.3

USE_IMAKE=	YES

.include "../../graphics/xpm/buildlink.mk"
.include "../../x11/Xaw3d/buildlink.mk"
.include "../../mk/bsd.pkg.mk"
