# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:10:41 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ALLEGRO_BUILDLINK3_MK:=	${ALLEGRO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	allegro
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nallegro}
BUILDLINK_PACKAGES+=	allegro
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}allegro

.if !empty(ALLEGRO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.allegro+=	allegro>=4.1.13
BUILDLINK_ABI_DEPENDS.allegro?=	allegro>=4.2.0nb1
BUILDLINK_PKGSRCDIR.allegro?=	../../devel/allegro
.endif	# ALLEGRO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
