# $NetBSD: Makefile,v 1.2 2018/05/12 03:27:18 markd Exp $

DISTNAME=	lato
PKGNAME=	tex-${DISTNAME}-3.0
TEXLIVE_REV=	45576

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/lato
COMMENT=	Lato font family and LaTeX support
LICENSE=	lppl-1.3c

TEX_MAP_FILES+=	lato.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
