# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:47 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PCCTS_BUILDLINK3_MK:=	${PCCTS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pccts
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npccts}
BUILDLINK_PACKAGES+=	pccts
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pccts

.if !empty(PCCTS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.pccts+=	pccts>=1.33.22
BUILDLINK_ABI_DEPENDS.pccts?=	pccts>=1.33.22nb1
BUILDLINK_PKGSRCDIR.pccts?=	../../devel/pccts
BUILDLINK_DEPMETHOD.pccts?=	build
.endif	# PCCTS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
