# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/10/11 16:51:54 abs Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
WHOSON_BUILDLINK3_MK:=	${WHOSON_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	whoson
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nwhoson}
BUILDLINK_PACKAGES+=	whoson

.if !empty(WHOSON_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.whoson+=	whoson>=2.03
BUILDLINK_PKGSRCDIR.whoson?=	../../net/whoson
.endif	# WHOSON_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
