# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 06:22:43 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENPAM_BUILDLINK3_MK:=	${OPENPAM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	openpam
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenpam}
BUILDLINK_PACKAGES+=	openpam

.if !empty(OPENPAM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.openpam+=	openpam>=20040210
BUILDLINK_PKGSRCDIR.openpam?=	../../security/openpam
.endif	# OPENPAM_BUILDLINK3_MK

.include "../../mk/dlopen.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
