# $NetBSD: buildlink3.mk,v 1.2 2006/02/05 23:10:01 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FFTWF_BUILDLINK3_MK:=	${FFTWF_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	fftwf
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfftwf}
BUILDLINK_PACKAGES+=	fftwf

.if !empty(FFTWF_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.fftwf+=	fftwf>=3.0
BUILDLINK_RECOMMENDED.fftwf+=	fftwf>=3.0.1nb1
BUILDLINK_PKGSRCDIR.fftwf?=	../../math/fftwf
.endif	# FFTWF_BUILDLINK3_MK

.include "../../math/fftw/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
