# $NetBSD: buildlink3.mk,v 1.1 2004/04/27 03:09:58 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DMALLOC_BUILDLINK3_MK:=	${DMALLOC_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	dmalloc
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndmalloc}
BUILDLINK_PACKAGES+=	dmalloc

.if !empty(DMALLOC_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.dmalloc+=	dmalloc>=4.8.2nb2
BUILDLINK_PKGSRCDIR.dmalloc?=	../../devel/dmalloc
BUILDLINK_DEPMETHOD.dmalloc?=	build
.endif	# DMALLOC_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
