# $NetBSD: Makefile,v 1.6 2023/10/24 17:42:11 pho Exp $

DISTNAME=	hie-compat-0.3.1.1
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	HIE files for GHC 8.6 and other HIE file backports
LICENSE=	apache-2.0

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
