$NetBSD: patch-alire.toml,v 1.3 2026/06/06 06:20:24 dkazankov Exp $

Add NetBSD support

--- alire.toml.orig	2026-05-25 15:21:25.000000000 +0300
+++ alire.toml
@@ -44,6 +44,7 @@
 # GNATCOLL_OS required by gnatcoll
 # PRJ_TARGET required by templates_parser
 [gpr-set-externals."case(os)"]
+netbsd = { ALIRE_OS = "netbsd", GNATCOLL_OS = "unix",    PRJ_TARGET = "NetBSD" }
 freebsd = { ALIRE_OS = "freebsd", GNATCOLL_OS = "unix",    PRJ_TARGET = "FreeBSD" }
 openbsd = { ALIRE_OS = "openbsd", GNATCOLL_OS = "unix",    PRJ_TARGET = "UNIX" }
 linux   = { ALIRE_OS = "linux",   GNATCOLL_OS = "unix",    PRJ_TARGET = "Linux" }
