$NetBSD: patch-alire.toml,v 1.2 2025/04/27 10:43:42 dkazankov Exp $

Add NetBSD support

--- alire.toml.orig	2025-03-04 10:02:00.000000000 +0000
+++ alire.toml
@@ -44,6 +44,7 @@
 [gpr-set-externals."case(os)"]
 freebsd = { ALIRE_OS = "freebsd" }
 openbsd = { ALIRE_OS = "openbsd" }
+netbsd = { ALIRE_OS = "netbsd" }
 linux   = { ALIRE_OS = "linux" }
 macos   = { ALIRE_OS = "macos" }
 windows = { ALIRE_OS = "windows" }
