# $NetBSD: buildlink3.mk,v 1.3 2006/02/05 23:08:37 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SQLITE_BUILDLINK3_MK:=	${SQLITE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sqlite
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsqlite}
BUILDLINK_PACKAGES+=	sqlite

.if !empty(SQLITE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.sqlite+=	sqlite>=2.8.0
BUILDLINK_RECOMMENDED.sqlite+=	sqlite>=2.8.16nb1
BUILDLINK_PKGSRCDIR.sqlite?=	../../databases/sqlite
.endif	# SQLITE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
