# $NetBSD: buildlink3.mk,v 1.4 2006/04/06 06:21:43 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SQLITE_BUILDLINK3_MK:=	${SQLITE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sqlite
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsqlite}
BUILDLINK_PACKAGES+=	sqlite

.if !empty(SQLITE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.sqlite+=	sqlite>=2.8.0
BUILDLINK_ABI_DEPENDS.sqlite+=	sqlite>=2.8.16nb1
BUILDLINK_PKGSRCDIR.sqlite?=	../../databases/sqlite
.endif	# SQLITE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
