# $NetBSD: buildlink3.mk,v 1.1 2007/02/09 21:20:01 drochner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MAC_BUILDLINK3_MK:=	${MAC_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mac
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmac}
BUILDLINK_PACKAGES+=	mac
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mac

.if ${MAC_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mac+=	mac>=3.99u4b5
BUILDLINK_PKGSRCDIR.mac?=	../../audio/mac
.endif	# MAC_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
