# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/07/26 23:35:05 schmonz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XAPIAN_BUILDLINK3_MK:=	${XAPIAN_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xapian
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxapian}
BUILDLINK_PACKAGES+=	xapian
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xapian

.if ${XAPIAN_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xapian+=	xapian>=1.0.7
BUILDLINK_PKGSRCDIR.xapian?=	../../textproc/xapian
.endif	# XAPIAN_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
