# $NetBSD: Makefile.foo_main,v 1.1 2003/01/20 10:04:01 skrll Exp $
#
# This Makefile fragment is included in a KDE package Makefile to
# create foo_main.cpp files needed to fix the linking modules into
# binaries/libraries problem that affects a.out platforms.

post-patch:
	@for f in ${FOO_MAIN_FILES}; do \
		${LN} -s ${.CURDIR}/../../x11/kde3/files/foo_main.cpp \
		    ${WRKSRC}/$${f}; \
	done
