# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/04/02 07:40:57 rh Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
ADDRESSES_BUILDLINK3_MK:=	${ADDRESSES_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	Addresses
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NAddresses}
BUILDLINK_PACKAGES+=	Addresses

.if !empty(ADDRESSES_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.Addresses+=	Addresses>=0.4.5
BUILDLINK_PKGSRCDIR.Addresses?=	../../misc/Addresses
.endif	# ADDRESSES_BUILDLINK3_MK

.include "../../x11/gnustep-back/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
