# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/05/20 02:42:27 heinz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
OSSP_UUID_BUILDLINK3_MK:=	${OSSP_UUID_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ossp-uuid
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nossp-uuid}
BUILDLINK_PACKAGES+=	ossp-uuid
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ossp-uuid

.if !empty(OSSP_UUID_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.ossp-uuid+=	ossp-uuid>=1.6.0
BUILDLINK_ABI_DEPENDS.ossp-uuid+=	ossp-uuid>=1.6.0
BUILDLINK_PKGSRCDIR.ossp-uuid?=		../../devel/ossp-uuid
.endif	# OSSP_UUID_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
