# $NetBSD: buildlink3.mk,v 1.1 2007/09/21 12:59:54 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSIGCPP1_BUILDLINK3_MK:=	${LIBSIGCPP1_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libsigcpp1
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsigcpp1}
BUILDLINK_PACKAGES+=	libsigcpp1
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libsigcpp1

.if !empty(LIBSIGCPP1_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libsigcpp1+=	libsigc++1>=1.2.3nb1
BUILDLINK_ABI_DEPENDS.libsigcpp1+=	libsigc++1>=1.2.7nb1
BUILDLINK_PKGSRCDIR.libsigcpp1?=	../../devel/libsigc++1
.endif	# LIBSIGCPP1_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
