# $NetBSD: buildlink3.mk,v 1.1 2004/03/06 17:28:59 xtraeme Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDL_NET_BUILDLINK3_MK:=	${SDL_NET_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	SDL_net
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NSDL_net}
BUILDLINK_PACKAGES+=	SDL_net

.if !empty(SDL_NET_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.SDL_net+=	SDL_net>=1.2.5nb1
BUILDLINK_PKGSRCDIR.SDL_net?=	../../net/SDL_net

.include "../../devel/SDL/buildlink3.mk"

.endif	# SDL_NET_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
