# $NetBSD: buildlink3.mk,v 1.1 2004/04/25 00:25:01 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBARES_BUILDLINK3_MK:=	${LIBARES_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libares
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibares}
BUILDLINK_PACKAGES+=	libares

.if !empty(LIBARES_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libares+=	libares>=1.1.1
BUILDLINK_PKGSRCDIR.libares?=	../../net/libares
.endif	# LIBARES_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
