# $NetBSD: Makefile,v 1.8 2002/01/02 16:39:39 augustss Exp $
#

DISTNAME=       birda-0.7
CATEGORIES=	comms
MASTER_SITES=   ftp://ftp.augustsson.net/pub/netbsd/

MAINTAINER=	lennart@augustsson.net
COMMENT=	Bohlin's IrDA utilities

.include "../../mk/bsd.pkg.mk"
