# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/18 17:38:15 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBLINEBREAK_BUILDLINK3_MK:=	${LIBLINEBREAK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	liblinebreak
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nliblinebreak}
BUILDLINK_PACKAGES+=	liblinebreak
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}liblinebreak

.if ${LIBLINEBREAK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.liblinebreak+=	liblinebreak>=1.0
BUILDLINK_PKGSRCDIR.liblinebreak?=	../../textproc/liblinebreak
.endif	# LIBLINEBREAK_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
