# $NetBSD: buildlink3.mk,v 1.4 2006/07/08 22:39:16 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LRMI_BUILDLINK3_MK:=	${LRMI_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lrmi
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlrmi}
BUILDLINK_PACKAGES+=	lrmi
BUILDLINK_ORDER+=	lrmi

.if !empty(LRMI_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.lrmi+=	lrmi>=0.8nb1
BUILDLINK_PKGSRCDIR.lrmi?=	../../emulators/lrmi
.endif	# LRMI_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
