# $NetBSD: buildlink3.mk,v 1.5 2006/04/06 06:22:53 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CGILIB_BUILDLINK3_MK:=	${CGILIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cgilib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncgilib}
BUILDLINK_PACKAGES+=	cgilib

.if !empty(CGILIB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.cgilib+=	cgilib>=0.5nb1
BUILDLINK_ABI_DEPENDS.cgilib+=	cgilib>=0.5nb2
BUILDLINK_PKGSRCDIR.cgilib?=	../../www/cgilib
.endif	# CGILIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
