# $NetBSD: buildlink3.mk,v 1.10 2009/03/05 21:10:27 joerg Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
OPENOBEX_BUILDLINK3_MK:=	${OPENOBEX_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	openobex
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenobex}
BUILDLINK_PACKAGES+=	openobex
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}openobex

.if ${OPENOBEX_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.openobex+=	openobex>=1.3
BUILDLINK_PKGSRCDIR.openobex?=	../../comms/openobex
.endif	# OPENOBEX_BUILDLINK3_MK

.include "../../devel/libusb/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
