$NetBSD: patch-cmake_Modules_FindLibUSB.cmake,v 1.1 2016/01/26 09:10:39 dbj Exp $

--- cmake/Modules/FindLibUSB.cmake.orig	2014-02-07 01:04:24.000000000 +0000
+++ cmake/Modules/FindLibUSB.cmake
@@ -32,11 +32,6 @@ if(LIBUSB_LIBRARIES)
     set(CMAKE_REQUIRED_LIBRARIES ${LIBUSB_LIBRARIES})
 endif()
 
-CHECK_FUNCTION_EXISTS("libusb_handle_events_timeout_completed" HAVE_LIBUSB_HANDLE_EVENTS_TIMEOUT_COMPLETED)
-if(HAVE_LIBUSB_HANDLE_EVENTS_TIMEOUT_COMPLETED)
-    add_definitions(-DHAVE_LIBUSB_HANDLE_EVENTS_TIMEOUT_COMPLETED=1)
-endif(HAVE_LIBUSB_HANDLE_EVENTS_TIMEOUT_COMPLETED)
-
 CHECK_FUNCTION_EXISTS("libusb_error_name" HAVE_LIBUSB_ERROR_NAME)
 if(HAVE_LIBUSB_ERROR_NAME)
     add_definitions(-DHAVE_LIBUSB_ERROR_NAME=1)
