# $NetBSD: buildlink3.mk,v 1.4 2006/02/05 23:08:39 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDLMM_BUILDLINK3_MK:=	${SDLMM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	SDLmm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NSDLmm}
BUILDLINK_PACKAGES+=	SDLmm

.if !empty(SDLMM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.SDLmm+=	SDLmm>=0.1.8nb1
BUILDLINK_RECOMMENDED.SDLmm?=	SDLmm>=0.1.8nb5
BUILDLINK_PKGSRCDIR.SDLmm?=	../../devel/SDLmm
.endif	# SDLMM_BUILDLINK3_MK

.include "../../devel/SDL/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
