# $NetBSD: buildlink3.mk,v 1.5 2004/05/17 21:32:34 seb Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LTDL_BUILDLINK3_MK:=	${LTDL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ltdl
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nltdl}
BUILDLINK_PACKAGES+=	ltdl

.if !empty(LTDL_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ltdl+=	libtool-base>=1.5.2
BUILDLINK_PKGSRCDIR.ltdl?=	../../devel/libtool-base
.endif	# LTDL_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
