# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:11:07 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBMCRYPT_BUILDLINK3_MK:=	${LIBMCRYPT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmcrypt
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmcrypt}
BUILDLINK_PACKAGES+=	libmcrypt
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmcrypt

.if !empty(LIBMCRYPT_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libmcrypt+=	libmcrypt>=2.5.6
BUILDLINK_ABI_DEPENDS.libmcrypt+=	libmcrypt>=2.5.7nb1
BUILDLINK_PKGSRCDIR.libmcrypt?=	../../security/libmcrypt
.endif	# LIBMCRYPT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
