# $NetBSD: buildlink3.mk,v 1.1 2004/04/24 23:29:23 xtraeme Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBMCRYPT_BUILDLINK3_MK:=	${LIBMCRYPT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmcrypt
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmcrypt}
BUILDLINK_PACKAGES+=	libmcrypt

.if !empty(LIBMCRYPT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libmcrypt+=	libmcrypt>=2.5.6
BUILDLINK_PKGSRCDIR.libmcrypt?=	../../security/libmcrypt
.endif	# LIBMCRYPT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
