$NetBSD: patch-Cargo.toml,v 1.3 2025/08/06 17:57:17 pin Exp $

Fix build on NetBSD.
https://github.com/o2sh/onefetch/pull/1599

--- Cargo.toml.orig	2025-07-05 22:15:03.000000000 +0000
+++ Cargo.toml
@@ -41,14 +41,14 @@ byte-unit = "5.1.6"
 clap.workspace = true
 clap_complete = "4.5.54"
 crossbeam-channel = "0.5.15"
-gix = { version = "0.72.1", default-features = false, features = [
+gix = { version = "0.73.0", default-features = false, features = [
     "max-performance-safe",
     "blob-diff",
     "mailmap",
     "index",
     "status",
 ] }
-gix-features = { version = "0.42.1", features = ["zlib-ng"] }
+gix-features = { version = "0.43.1", features = ["zlib-ng"] }
 globset = "0.4.16"
 human-panic = "2.0.2"
 image.workspace = true
