$NetBSD: patch-pyproject.toml,v 1.1 2025/12/22 09:04:23 adam Exp $

Don't install examples.

--- pyproject.toml.orig	2025-12-22 09:00:06.415451379 +0000
+++ pyproject.toml
@@ -101,6 +101,7 @@ path = "tortoise/__init__.py"
 excludes = [
     "./**/.git",
     "./**/.*_cache",
+    "examples",
 ]
 include = [
     "CHANGELOG.rst",
