.TH XGNUBOY "6" "July 2001" 
.SH NAME
xgnuboy \- gnuboy  Game Boy Emulator. 
.SH SYNOPSIS
.B xgnuboy 
[\fIoptions\fR] \fIromfile\fR
.SH DESCRIPTION
.TP
\fB\-\-source\fR FILE
read rc commands from FILE
.TP
\fB\-\-bind\fR KEY COMMAND
bind KEY to perform COMMAND
.TP
\fB\-\-VAR\fR=\fIVALUE\fR
set rc variable VAR to VALUE
.TP
\fB\-\-VAR\fR
set VAR to 1 (turn on boolean options)
.TP
\fB\-\-no\-VAR\fR
set VAR to 0 (turn off boolean options)
.TP
\fB\-\-showvars\fR
list all available rc variables
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-\-copying\fR
show copying permissions
.SH AUTHOR
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
This manual page was written by Davide Puricelli <evo@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
