# $NetBSD: Makefile,v 1.1 2015/04/26 03:39:03 markd Exp $

DISTNAME=	apnum
PKGNAME=	tex-${DISTNAME}-1.1
TEXLIVE_REV=	35958

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Arbitrary precision numbers implemented by TeX macros
LICENSE=	public-domain

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
