# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 22:03:23 joerg Exp $

BUILDLINK_DEPMETHOD.resourceproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
RESOURCEPROTO_BUILDLINK3_MK:=	${RESOURCEPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	resourceproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nresourceproto}
BUILDLINK_PACKAGES+=	resourceproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}resourceproto

.if ${RESOURCEPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.resourceproto+=	resourceproto>=1.0.1
BUILDLINK_PKGSRCDIR.resourceproto?=	../../x11/resourceproto
.endif	# RESOURCEPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
