# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/02/06 07:08:11 bjs Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY24_BOTO_BUILDLINK3_MK:=	${PY24_BOTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py24-boto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy24-boto}
BUILDLINK_PACKAGES+=	py24-boto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py24-boto

.if ${PY24_BOTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.py24-boto+=	py24-boto>=1.0a
BUILDLINK_PKGSRCDIR.py24-boto?=	../../net/py-boto
.endif	# PY24_BOTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
