# $NetBSD: Makefile,v 1.9 2021/03/07 15:05:59 taca Exp $

DISTNAME=	getopt-1.6.0
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/djberg96/getopt
COMMENT=	Another option parsers for Ruby
LICENSE=	apache-2.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
