$NetBSD: patch-Cargo.toml,v 1.1 2022/02/10 13:55:43 pin Exp $

Bump cursive version to latest for NetBSD support

--- Cargo.toml.orig	2021-04-10 16:54:39.000000000 +0000
+++ Cargo.toml
@@ -5,7 +5,7 @@ authors = ["Julien Blanchard <julien@typ
 edition = "2018"
 
 [dependencies]
-cursive = "0.15"
+cursive = "0.17"
 native-tls = "*"
 url = "*"
 regex = "*"
