$NetBSD: patch-four-bar-ui_Cargo.toml,v 1.4 2025/12/03 07:55:38 wiz Exp $

Don't pull git version of ron.

--- four-bar-ui/Cargo.toml.orig	2025-11-10 12:08:26.000000000 +0000
+++ four-bar-ui/Cargo.toml
@@ -39,7 +39,7 @@ image = { version = "0.25", default-feat
     "gif",
 ] }
 rfd = "0.15"
-ron = { git = "https://github.com/ron-rs/ron" }
+ron = "0.8.1"
 serde = { version = "1", features = ["derive"] }
 smartcore = { version = "0.3", features = ["ndarray-bindings"] }
 
