# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:11:02 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GEOIP_BUILDLINK3_MK:=	${GEOIP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	GeoIP
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NGeoIP}
BUILDLINK_PACKAGES+=	GeoIP
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}GeoIP

.if !empty(GEOIP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.GeoIP+=	GeoIP>=1.3.1
BUILDLINK_ABI_DEPENDS.GeoIP+=	GeoIP>=1.3.4nb1
BUILDLINK_PKGSRCDIR.GeoIP?=	../../net/GeoIP
.endif	# GEOIP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
