# $NetBSD: buildlink3.mk,v 1.3 2004/10/03 00:17:48 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GEOIP_BUILDLINK3_MK:=	${GEOIP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	GeoIP
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NGeoIP}
BUILDLINK_PACKAGES+=	GeoIP

.if !empty(GEOIP_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.GeoIP+=	GeoIP>=1.3.1
BUILDLINK_RECOMMENDED.GeoIP+=	GeoIP>=1.3.4nb1
BUILDLINK_PKGSRCDIR.GeoIP?=	../../net/GeoIP
.endif	# GEOIP_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
