# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/07/03 23:29:50 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBVISUAL0.2_BUILDLINK3_MK:=	${LIBVISUAL0.2_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libvisual0.2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibvisual0.2}
BUILDLINK_PACKAGES+=	libvisual0.2

.if ${LIBVISUAL0.2_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libvisual0.2+=	libvisual0.2>=0.2.0
BUILDLINK_PKGSRCDIR.libvisual0.2?=	../../audio/libvisual0.2
.endif	# LIBVISUAL0.2_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
