# $NetBSD: Makefile,v 1.1 2015/05/08 13:47:38 wiz Exp $

DISTNAME=	cmarrows
PKGNAME=	tex-${DISTNAME}-v0.9
TEXLIVE_REV=	24378

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/cmarrows
COMMENT=	MetaPost arrows and braces in the Computer Modern style
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
