# $NetBSD: buildlink3.mk,v 1.4 2004/06/26 20:24:03 recht Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBPIXMAN_BUILDLINK3_MK:=	${LIBPIXMAN_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libpixman
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibpixman}
BUILDLINK_PACKAGES+=	libpixman

.if !empty(LIBPIXMAN_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libpixman+=	libpixman>=0.1.1
BUILDLINK_PKGSRCDIR.libpixman?=	../../graphics/libpixman
.endif	# LIBPIXMAN_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
