# $NetBSD: buildlink3.mk,v 1.10 2006/07/08 23:10:52 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBPIXMAN_BUILDLINK3_MK:=	${LIBPIXMAN_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libpixman
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibpixman}
BUILDLINK_PACKAGES+=	libpixman
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libpixman

.if !empty(LIBPIXMAN_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libpixman+=	libpixman>=0.1.4
BUILDLINK_PKGSRCDIR.libpixman?=	../../graphics/libpixman
.endif	# LIBPIXMAN_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
