# $NetBSD: Makefile,v 1.2 2016/01/27 10:00:26 markd Exp $

DISTNAME=	notoccite
PKGNAME=	tex-${DISTNAME}-2009
TEXLIVE_REV=	18129

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Prevent trouble from citations in table of contents, etc
LICENSE=	public-domain

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
