===========================================================================
$NetBSD: MESSAGE.module,v 1.3 2001/01/29 11:34:47 wiz Exp $

To enable this package, add the following lines to php.ini:

    extension_dir=${PREFIX}/${PHP_EXTENSION_DIR}
    extension=${MODNAME}.so

and restart your PHP4-enabled HTTP server to load this module.

===========================================================================
