===========================================================================
$NetBSD: MESSAGE.module,v 1.2 2001/01/15 16:32:28 jlam Exp $

To enable this package, add the following lines to php.ini:

    extension_dir=@PREFIX@/@PHP_EXTENSION_DIR@
    extension=@MODNAME@.so

and restart your PHP4-enabled HTTP server to load this module.
===========================================================================
