# $NetBSD: buildlink3.mk,v 1.7 2008/11/03 22:01:29 bjs Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PCIUTILS_BUILDLINK3_MK:=	${PCIUTILS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pciutils
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npciutils}
BUILDLINK_PACKAGES+=	pciutils
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pciutils

.if !empty(PCIUTILS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.pciutils+=	pciutils>=3.0.2
BUILDLINK_PKGSRCDIR.pciutils?=	../../sysutils/pciutils
BUILDLINK_DEPMETHOD.pciutils?=	build
.endif	# PCIUTILS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
