# $NetBSD: Makefile,v 1.10 2013/03/03 10:40:12 shattered Exp $
#

DISTNAME=	photopc-3.05
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=photopc/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://photopc.sourceforge.net/
COMMENT=	Manipulate digital cameras on Fujitsu chipset

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
