# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/01/12 14:05:17 dillo Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
WBXML2_BUILDLINK3_MK:=	${WBXML2_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	wbxml2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nwbxml2}
BUILDLINK_PACKAGES+=	wbxml2
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}wbxml2

.if ${WBXML2_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.wbxml2+=	wbxml2>=0.9.2
BUILDLINK_PKGSRCDIR.wbxml2?=	../../textproc/wbxml2
.endif	# WBXML2_BUILDLINK3_MK

.include "../../textproc/expat/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
