# $NetBSD: buildlink3.mk,v 1.2 2008/11/15 09:59:59 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGNOMEKBD_BUILDLINK3_MK:=	${LIBGNOMEKBD_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libgnomekbd
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgnomekbd}
BUILDLINK_PACKAGES+=	libgnomekbd
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libgnomekbd

.if ${LIBGNOMEKBD_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libgnomekbd+=	libgnomekbd>=2.18.0
BUILDLINK_PKGSRCDIR.libgnomekbd?=	../../x11/libgnomekbd
.endif	# LIBGNOMEKBD_BUILDLINK3_MK

.include "../../x11/libxklavier/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
