# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/04/10 19:20:37 drochner Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGNOMEKBD_BUILDLINK3_MK:=	${LIBGNOMEKBD_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libgnomekbd
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgnomekbd}
BUILDLINK_PACKAGES+=	libgnomekbd
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libgnomekbd

.if ${LIBGNOMEKBD_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libgnomekbd+=	libgnomekbd>=2.18.0
BUILDLINK_PKGSRCDIR.libgnomekbd?=	../../x11/libgnomekbd
.endif	# LIBGNOMEKBD_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
