# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:11:01 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBDV_BUILDLINK3_MK:=	${LIBDV_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdv
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdv}
BUILDLINK_PACKAGES+=	libdv
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libdv

.if !empty(LIBDV_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libdv+=	libdv>=0.102
BUILDLINK_ABI_DEPENDS.libdv+=	libdv>=0.104nb2
BUILDLINK_PKGSRCDIR.libdv?=	../../multimedia/libdv
.endif	# LIBDV_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
