# $NetBSD: buildlink3.mk,v 1.6 2006/04/12 10:27:27 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBDV_BUILDLINK3_MK:=	${LIBDV_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdv
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdv}
BUILDLINK_PACKAGES+=	libdv

.if !empty(LIBDV_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libdv+=	libdv>=0.102
BUILDLINK_ABI_DEPENDS.libdv+=	libdv>=0.104nb2
BUILDLINK_PKGSRCDIR.libdv?=	../../multimedia/libdv
.endif	# LIBDV_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
