# $NetBSD: buildlink3.mk,v 1.3 2005/06/03 15:40:31 jmmv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBDV_BUILDLINK3_MK:=	${LIBDV_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdv
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdv}
BUILDLINK_PACKAGES+=	libdv

.if !empty(LIBDV_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libdv+=	libdv>=0.102
BUILDLINK_RECOMMENDED.libdv+=	libdv>=0.102nb1
BUILDLINK_PKGSRCDIR.libdv?=	../../multimedia/libdv
.endif	# LIBDV_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
