# $NetBSD: buildlink3.mk,v 1.5 2004/03/05 19:25:09 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DB3_BUILDLINK3_MK:=	${DB3_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	db3
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndb3}
BUILDLINK_PACKAGES+=	db3

.if !empty(DB3_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.db3+=		db3>=2.9.2
BUILDLINK_PKGSRCDIR.db3?=	../../databases/db3
.endif	# DB3_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
