# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 18:19:58 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBXEXT_BUILDLINK3_MK:=	${LIBXEXT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libXext
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NlibXext}
BUILDLINK_PACKAGES+=	libXext
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libXext

.if ${LIBXEXT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libXext+=	libXext>=0.99.0
BUILDLINK_PKGSRCDIR.libXext?=	../../x11/libXext
.endif	# LIBXEXT_BUILDLINK3_MK

.include "../../x11/libX11/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
