#! /bin/sh
# $NetBSD: test.subr,v 1.7 2020/03/22 12:15:59 rillig Exp $
set -eu

# This file defines utilities for testing Makefile fragments in a mocked
# environment. It is used primarily to test the pkgsrc infrastructure.
#
# It defines the following shell variables:
#
#	cleanup
#		If yes (the default), clean up the temporary directory
#		after the test has run successfully.
#
# It defines the following shell functions:
#
#	mock_cmd
#		Returns the path to a newly created shell program whose
#		behavior (output and exit status) is specified by pairs
#		of --when-args/--then-output or --when-args/--then-exit.
#		Example:
#
#		hello=$(mock_cmd mock-hello \
#			--when-args "" --then-output "Hello, world!" \
#			--when-args "-t" --then-output "hello, world" \
#			--when-args "-?" --then-exit 1
#		)
#
#	create_file $filename <<EOF ... EOF
#		Creates a file in the temporary directory. The filename
#		is relative to the temporary directory.
#
#	create_file_lines $filename $line1 $line2 ...
#		Creates a file in the temporary directory containing the
#		given lines.
#
#	create_pkgsrc_file $filename <<EOF ... EOF
#		Creates a file in the temporary pkgsrc directory. This
#		file will be included instead of the one in the real
#		pkgsrc infrastructure. The filename is relative to the
#		pkgsrc directory, such as mk/defaults/mk.conf.
#
#		This is typically used for creating an empty file for
#		mk/bsd.prefs.mk or similar files that are included by the
#		file that is currently under test.
#
#	test_file $filename $bmake_args...
#		Runs bmake with the correct environment so that it picks
#		up the mocked infrastructure files first and then the ones
#		from the real pkgsrc installation. The filename is
#		relative to the temporary directory.
#
#	assert_that $actual --equals $expected
#		Complains loudly if $actual is not equal to $expected.

: "${cleanup:=yes}"
: "${make:=bmake}"
: "${if_verbose=:}"
tmpdir="${TMP:-/tmp}/infra-unittests-$$"
mocked_pkgsrcdir="$tmpdir/pkgsrc"
rm -rf "$tmpdir"
mkdir -p "$mocked_pkgsrcdir"

real_pkgsrcdir=""
for rel in .. ../.. ../../..; do
	[ -f "$rel/mk/bsd.pkg.mk" ] || continue
	real_pkgsrcdir="$rel"
done
[ "$real_pkgsrcdir" ] || {
	printf 'error: must be run from somewhere inside the pkgsrc directory\n' 1>&2
	exit 1
}

verbose_printf() {
	$if_verbose printf "$@"
}

test_case_name="unknown test"
test_case_begun=0
test_case_ended=0

test_case_begin() {
	test_case_name="$1"
	test_case_begun="`expr "$test_case_begun" + 1`"
	verbose_printf 'running test case "%s"\n' "$test_case_name"

	test_case_set_up
}

# Can be redefined by actual tests.
test_case_set_up() {
}

# Can be redefined by actual tests.
test_case_tear_down() {
}

test_case_end() {
	test_case_tear_down

	test_case_ended="`expr "$test_case_ended" + 1`"
	test "$test_case_ended" = "$test_case_begun" \
	|| assert_fail 'unbalanced test_case_begin (%d) and test_case_end (%d)\n' \
		"$test_case_begun" "$test_case_ended"

	test_case_name="unknown test"
}

test_subr_cleanup() {
	exit_status=$?
	if [ $exit_status -ne 0 ]; then
		printf 'info: the test files are in %s\n' "$tmpdir" 1>&2
		exit $exit_status
	fi

	[ "$cleanup" = "yes" ] && rm -rf "$tmpdir"

	verbose_printf '%s%d assertions succeeded, %d failed\n' \
		"$assert_fail_sep" "$assert_succeeded" "$assert_failed"

	if [ "$assert_failed" != 0 ]; then
		exit 1
	fi
}
trap "test_subr_cleanup" EXIT

mock_cmd() {
	cmdname="$1"
	shift 1

	{
	printf '#! /bin/sh\n\n'
	while [ $# -ge 4 ]; do
		case $1,$3 in
		(--when-args,--then-output)
			cat <<EOF
[ "x\$*" = "x$2" ] && { printf '%s\n' "$4" && exit 0; }

EOF
			shift 4
			;;
		(--when-args,--then-exit)
			cat <<EOF
[ "x\$*" = "x$2" ] && exit $4

EOF
			shift 4
			;;
		*)	printf 'error: invalid arguments to mock_cmd: %s\n' "$*" 1>&2
			exit 1
			;;
		esac
	done
	cat <<EOF
printf 'error: %s: no mock behavior defined for arguments %s\n' "\$0" "\$*" 1>&2
exit 1
EOF
	} > "$tmpdir/$cmdname"
	chmod +x "$tmpdir/$cmdname"

	printf '%s\n' "$tmpdir/$cmdname"
}

create_file() {
	assert_that "$#" --equals 1
	cat > "$tmpdir/$1"
}

create_file_lines() {
	_cfl_filename="$1"; shift
	printf '%s\n' "$@" > "$tmpdir/$_cfl_filename"
}

create_pkgsrc_file() {
	mkdir -p "$mocked_pkgsrcdir/$(dirname "$1")"
	cat > "$mocked_pkgsrcdir/$1"
}

test_file() {
	cat <<EOF > "$tmpdir/test.subr.main.mk"
PKGSRCDIR=	$real_pkgsrcdir
.PATH:		$mocked_pkgsrcdir
.PATH:		$real_pkgsrcdir
.include "$1"
EOF
	shift

	"$make" -f "$tmpdir/test.subr.main.mk" "$@"
}

assert_succeeded=0
assert_failed=0
assert_fail_sep=''

assert_succeed() {
	assert_succeeded=`expr "$assert_succeeded" + 1`
}

assert_fail() {
	printf '%s' "$assert_fail_sep" 1>&2
	assert_fail_sep='
'

	printf 'assertion failed in "%s": ' "$test_case_name" 1>&2

	printf "$@" 1>&2
	assert_failed=`expr "$assert_failed" + 1`
}

tmpdir_equal() {
	(cd "$tmpdir" && diff -u -- "$@" >/dev/null) || return 1
}

tmpdir_diff() {
	# removes the timestamps from the diff files since these are not
	# useful in tests.
	(cd "$tmpdir" && diff -u -- "$@" || true) \
	| awk '/^(---|[+][+][+]) / { print($1, $2); next } { print }' 1>&2
}

assert_that() {
	case "$2" in
	(--equals)
		if [ "x$1" = "x$3" ]; then
			assert_succeed
			return 0
		fi
		assert_fail '\n  expected: <%s>\n  but was:  <%s>\n' "$3" "$1"
		;;

	(--file-contains-exactly)
		printf '%s\n' "$3" > "$tmpdir/expected"
		if tmpdir_equal "expected" "$1"; then
			assert_succeed
			return 0
		fi
		assert_fail 'file "%s" has unexpected content:\n' "$1"
		tmpdir_diff "expected" "$1"
		;;

	(--file-equals)
		if tmpdir_equal "$3" "$1"; then
			assert_succeed
			return 0
		fi
		assert_fail 'files "%s" and "%s" differ:\n' "$1" "$3"
		tmpdir_diff "$3" "$1"
		;;

	(--file-is-empty)
		if tmpdir_equal "/dev/null" "$1"; then
			assert_succeed
			return 0
		fi
		assert_fail 'file "%s" is not empty:\n' "$1"
		tmpdir_diff "/dev/null" "$1"
		;;

	(--file-is-lines)
		_assert_that_tmp_actual="$1"
		_assert_that_filename="$1"; shift 2

		printf '%s\n' "$@" > "$tmpdir/expected"
		if tmpdir_equal "expected" "$_assert_that_tmp_actual"; then
			assert_succeed
			return 0
		fi
		assert_fail 'file "%s" has unexpected content:\n' "$_assert_that_filename"
		tmpdir_diff "expected" "$_assert_that_tmp_actual"
		;;

	(*)
		printf 'usage: assert_that <expr> --equals <expr>\n' 1>&2
		exit 1
	esac
}
