$NetBSD: patch-js_src_jit_GenerateAtomicOperations.py,v 1.3 2022/10/08 21:18:55 ryoon Exp $

Fix build under NetBSD/i386 9 with GCC.
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1792159

--- js/src/jit/GenerateAtomicOperations.py.orig	2022-10-07 15:25:40.000000000 +0000
+++ js/src/jit/GenerateAtomicOperations.py
@@ -707,6 +707,8 @@ HEADER_TEMPLATE = """\
 
 /* This file is generated by jit/GenerateAtomicOperations.py. Do not edit! */
 
+#include "mozilla/Attributes.h"
+
 namespace js {
 namespace jit {
 
