# $NetBSD: buildlink3.mk,v 1.3 2006/02/05 23:08:49 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ODE_BUILDLINK3_MK:=	${ODE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ode
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Node}
BUILDLINK_PACKAGES+=	ode

.if !empty(ODE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ode+=		ode>=0.039
BUILDLINK_RECOMMENDED.ode?=	ode>=0.5nb1
BUILDLINK_PKGSRCDIR.ode?=	../../devel/ode
.endif	# ODE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
