# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/12 11:46:21 jmmv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PCIIDS_BUILDLINK3_MK:=	${PCIIDS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	pciids
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npciids}
BUILDLINK_PACKAGES+=	pciids
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pciids

.if ${PCIIDS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.pciids+=	pciids>=20061026
BUILDLINK_PKGSRCDIR.pciids?=	../../misc/pciids
.endif	# PCIIDS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
