# $NetBSD: Makefile,v 1.7 1998/04/15 10:38:32 agc Exp $
# Id: Makefile,v 1.5 1996/12/03 10:41:49 asami Exp
#

    SUBDIR += imm
#    SUBDIR += mbone_vcr
    SUBDIR += nte
    SUBDIR += rat
#    SUBDIR += rtpmon
    SUBDIR += sdr
#    SUBDIR += speak_freely
    SUBDIR += vat
    SUBDIR += vic
#    SUBDIR += wb

.include "../mk/bsd.pkg.subdir.mk"
