$NetBSD: patch-src_lexi.c,v 1.3 2016/02/15 09:38:10 jperkin Exp $

Remove bogus __inline.

--- src/lexi.c.orig	2008-03-11 18:50:42.000000000 +0000
+++ src/lexi.c
@@ -197,9 +197,6 @@ int main (void)
 #endif
 
 /* Include code generated by gperf */
-#ifdef __GNUC__
-__inline
-#endif
 templ_ty *is_reserved (const char *str, unsigned int len);
 
 #include "gperf.c"
@@ -211,9 +208,6 @@ templ_ty *is_reserved (const char *str, 
 #undef MIN_WORD_LENGTH
 #undef MAX_WORD_LENGTH
 
-#ifdef __GNUC__
-__inline
-#endif
 templ_ty *is_reserved_cc (register const char *str, register unsigned int len);
 
 #include "gperf-cc.c"
