# $NetBSD: Makefile,v 1.1 2016/10/26 10:56:30 jperkin Exp $

VERSION=	0.800
DISTNAME=	authres-${VERSION}
PKGNAME=	${PYPKGPREFIX}-authres-${VERSION}
CATEGORIES=	mail python
MASTER_SITES=	${MASTER_SITE_PYPI:=a/authres/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.python.org/pypi/authres
COMMENT=	Python implementation of RFC 5451/7001
LICENSE=	apache-2.0

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
