#	$NetBSD: sfiles.mk,v 1.3 2004/10/06 16:44:52 tv Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	content-types.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.RedHat.2.1.bfc
SFILES+=	fontconfig.RedHat.2.1.properties.src
SFILES+=	fontconfig.RedHat.3.bfc
SFILES+=	fontconfig.RedHat.3.properties.src
SFILES+=	fontconfig.RedHat.8.0.bfc
SFILES+=	fontconfig.RedHat.8.0.properties.src
SFILES+=	fontconfig.RedHat.bfc
SFILES+=	fontconfig.RedHat.properties.src
SFILES+=	fontconfig.SuSE.bfc
SFILES+=	fontconfig.SuSE.properties.src
SFILES+=	fontconfig.Sun.2003.bfc
SFILES+=	fontconfig.Sun.2003.properties.src
SFILES+=	fontconfig.Sun.bfc
SFILES+=	fontconfig.Sun.properties.src
SFILES+=	fontconfig.Turbo.8.0.bfc
SFILES+=	fontconfig.Turbo.8.0.properties.src
SFILES+=	fontconfig.Turbo.bfc
SFILES+=	fontconfig.Turbo.properties.src
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	i386/jvm.cfg
SFILES+=	images/cursors/cursors.properties
SFILES+=	javaws/messages.properties
SFILES+=	javaws/messages_zh_TW.properties
SFILES+=	javaws/messages_de.properties
SFILES+=	javaws/messages_es.properties
SFILES+=	javaws/messages_fr.properties
SFILES+=	javaws/messages_it.properties
SFILES+=	javaws/messages_ja.properties
SFILES+=	javaws/messages_ko.properties
SFILES+=	javaws/messages_sv.properties
SFILES+=	javaws/messages_zh_CN.properties
SFILES+=	javaws/messages_zh_HK.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	sound.properties
