#	$NetBSD: sfiles.mk,v 1.2 2004/10/06 01:42:35 tv Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	content-types.properties
SFILES+=	flavormap.properties
SFILES+=	i386/jvm.cfg
SFILES+=	images/cursors/cursors.properties
SFILES+=	javaws/messages.properties
SFILES+=	javaws/messages_zh_TW.properties
SFILES+=	javaws/messages_de.properties
SFILES+=	javaws/messages_es.properties
SFILES+=	javaws/messages_fr.properties
SFILES+=	javaws/messages_it.properties
SFILES+=	javaws/messages_ja.properties
SFILES+=	javaws/messages_ko.properties
SFILES+=	javaws/messages_sv.properties
SFILES+=	javaws/messages_zh_CN.properties
SFILES+=	javaws/messages_zh_HK.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	sound.properties
