#	$NetBSD: sfiles-x86_64.mk,v 1.1 2006/12/03 00:51:22 wiz Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	amd64/jvm.cfg
SFILES+=	content-types.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.RedHat.2.1.bfc
SFILES+=	fontconfig.RedHat.2.1.properties.src
SFILES+=	fontconfig.RedHat.3.bfc
SFILES+=	fontconfig.RedHat.3.properties.src
SFILES+=	fontconfig.RedHat.8.0.bfc
SFILES+=	fontconfig.RedHat.8.0.properties.src
SFILES+=	fontconfig.RedHat.9.0.bfc
SFILES+=	fontconfig.RedHat.9.0.properties.src
SFILES+=	fontconfig.RedHat.bfc
SFILES+=	fontconfig.RedHat.properties.src
SFILES+=	fontconfig.SuSE.bfc
SFILES+=	fontconfig.SuSE.properties.src
SFILES+=	fontconfig.Sun.2003.bfc
SFILES+=	fontconfig.Sun.2003.properties.src
SFILES+=	fontconfig.Sun.bfc
SFILES+=	fontconfig.Sun.properties.src
SFILES+=	fontconfig.Turbo.8.0.bfc
SFILES+=	fontconfig.Turbo.8.0.properties.src
SFILES+=	fontconfig.Turbo.bfc
SFILES+=	fontconfig.Turbo.properties.src
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	images/cursors/cursors.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	sound.properties
