# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/19 18:02:22 abs Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
P5_B_HOOKS_OP_PPADDR_BUILDLINK3_MK:=	${P5_B_HOOKS_OP_PPADDR_BUILDLINK3_MK}+

BUILDLINK_DEPMETHOD.p5-B-Hooks-OP-PPAddr?=	build

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	p5-B-Hooks-OP-PPAddr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-B-Hooks-OP-PPAddr}
BUILDLINK_PACKAGES+=	p5-B-Hooks-OP-PPAddr
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}p5-B-Hooks-OP-PPAddr

.if ${P5_B_HOOKS_OP_PPADDR_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.p5-B-Hooks-OP-PPAddr+=	p5-B-Hooks-OP-PPAddr>=0.02
BUILDLINK_PKGSRCDIR.p5-B-Hooks-OP-PPAddr?=	../../devel/p5-B-Hooks-OP-PPAddr
.endif	# P5_B_HOOKS_OP_PPADDR_BUILDLINK3_MK

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH:S/+$//}
