$NetBSD: patch-CMakeModules_Findilmbase.cmake,v 1.1 2021/07/09 10:30:11 markd Exp $

openexr3 fix

--- CMakeModules/Findilmbase.cmake.orig	2020-01-31 11:03:07.000000000 +0000
+++ CMakeModules/Findilmbase.cmake
@@ -10,7 +10,7 @@
 # Created by Robert Osfield. 
 
 
-FIND_PATH(ILMBASE_INCLUDE_DIR OpenEXR/ImathVec.h
+FIND_PATH(ILMBASE_INCLUDE_DIR Imath/ImathVec.h
     $ENV{ILMBASE_DIR}/include
     $ENV{ILMBASE_DIR}
     ~/Library/Frameworks
@@ -28,7 +28,7 @@ FIND_PATH(ILMBASE_INCLUDE_DIR OpenEXR/Im
 # example: ILMBASE_FIND_VAR(OPENEXR_IlmThread_LIBRARY IlmThread)
 MACRO(ILMBASE_FIND_VAR varname libname)
     FIND_LIBRARY( ${varname}
-        NAMES ${libname} ${libname}-2_1 ${libname}-2_2
+        NAMES ${libname} ${libname}-2_1 ${libname}-2_2 ${libname}-3_0
         PATHS
         $ENV{ILMBASE_DIR}/lib
         $ENV{ILMBASE_DIR}
@@ -53,11 +53,11 @@ ENDMACRO(ILMBASE_FIND)
 
 ILMBASE_FIND(IlmThread)
 ILMBASE_FIND(Iex)
-ILMBASE_FIND(Half)
+ILMBASE_FIND(Imath)
 
 SET(ILMBASE_FOUND "NO")
-IF(ILMBASE_INCLUDE_DIR AND ILMBASE_IlmThread_LIBRARY AND ILMBASE_Iex_LIBRARY AND ILMBASE_Half_LIBRARY)
-    SET(ILMBASE_LIBRARIES ${ILMBASE_IlmThread_LIBRARY} ${ILMBASE_Half_LIBRARY} ${ILMBASE_Iex_LIBRARY} )
-    SET(ILMBASE_LIBRARIES_VARS ILMBASE_IlmThread_LIBRARY ILMBASE_Half_LIBRARY ILMBASE_Iex_LIBRARY )
+IF(ILMBASE_INCLUDE_DIR AND ILMBASE_IlmThread_LIBRARY AND ILMBASE_Iex_LIBRARY AND ILMBASE_Imath_LIBRARY)
+    SET(ILMBASE_LIBRARIES ${ILMBASE_IlmThread_LIBRARY} ${ILMBASE_Imath_LIBRARY} ${ILMBASE_Iex_LIBRARY} )
+    SET(ILMBASE_LIBRARIES_VARS ILMBASE_IlmThread_LIBRARY ILMBASE_Imath_LIBRARY ILMBASE_Iex_LIBRARY )
     SET(ILMBASE_FOUND "YES")
-ENDIF(ILMBASE_INCLUDE_DIR AND ILMBASE_IlmThread_LIBRARY AND ILMBASE_Iex_LIBRARY AND ILMBASE_Half_LIBRARY)
+ENDIF(ILMBASE_INCLUDE_DIR AND ILMBASE_IlmThread_LIBRARY AND ILMBASE_Iex_LIBRARY AND ILMBASE_Imath_LIBRARY)
