$NetBSD: patch-pyproject.toml,v 1.3 2026/04/22 09:05:05 adam Exp $

Do not install tests, some filenames contain UTF characters.

--- pyproject.toml.orig	2026-04-20 15:29:45.000000000 +0000
+++ pyproject.toml
@@ -119,6 +119,7 @@ source-includes = [
 ]
 excludes = [
     "pelican/build/",
+    "pelican/tests/",
 ]
 
 [tool.ruff.lint]
