$NetBSD: patch-pyproject.toml,v 1.2 2025/08/26 13:09:10 adam Exp $

Do not install tests, some filenames contain UTF characters.

--- pyproject.toml.orig	2025-01-15 17:04:08.303952500 +0000
+++ pyproject.toml
@@ -118,6 +118,7 @@ source-includes = [
     "docs/changelog.rst",
     "samples/",
 ]
+excludes = ["pelican/tests"]
 
 [tool.ruff.lint]
 select = [
