# $NetBSD: options.mk,v 1.9 2019/03/22 17:58:27 adam Exp $

PKG_OPTIONS_VAR=	PKG_OPTIONS.uhd
PKG_SUPPORTED_OPTIONS=	doxygen

.include "../../mk/bsd.options.mk"

PLIST_SRC=	${PKGDIR}/PLIST

.if !empty(PKG_OPTIONS:Mdoxygen)
BUILD_DEPENDS+=	doxygen>=1.8.15:../../devel/doxygen
PLIST_SRC+=	${PKGDIR}/PLIST.doxygen
CMAKE_ARGS+=	-DENABLE_MANUAL=ON
CMAKE_ARGS+=	-DENABLE_DOXYGEN=ON
.else
CMAKE_ARGS+=	-DENABLE_MANUAL=OFF
CMAKE_ARGS+=	-DENABLE_DOXYGEN=OFF
.endif
