# $NetBSD: Makefile,v 1.2 2019/12/06 20:17:03 markd Exp $

DISTNAME=	2up
PKGNAME=	tex-${DISTNAME}-1.3
TEXLIVE_REV=	18310

MAINTAINER=	minskim@NetBSD.org
COMMENT=	TeX package to print a document two-up

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
