# $NetBSD: buildlink3.mk,v 1.33 2008/04/24 11:57:35 tnn Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLU_BUILDLINK3_MK:=	${GLU_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglu}
BUILDLINK_PACKAGES+=	glu
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}glu

.if !empty(GLU_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.glu+=	glu>=3.4.2
BUILDLINK_ABI_DEPENDS.glu+=	glu>=7.0.3
BUILDLINK_PKGSRCDIR.glu?=	../../graphics/glu
.endif	# GLU_BUILDLINK3_MK

.include "../../graphics/MesaLib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
