# $NetBSD: buildlink3.mk,v 1.30 2006/07/08 22:39:18 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLU_BUILDLINK3_MK:=	${GLU_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglu}
BUILDLINK_PACKAGES+=	glu
BUILDLINK_ORDER+=	glu

.if !empty(GLU_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.glu+=		glu>=3.4.2
BUILDLINK_ABI_DEPENDS.glu+=	glu>=6.4.1nb1
BUILDLINK_PKGSRCDIR.glu?=	../../graphics/glu
.endif	# GLU_BUILDLINK3_MK

.include "../../graphics/MesaLib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
