# $NetBSD: buildlink3.mk,v 1.2 2004/02/20 11:13:52 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LAME_BUILDLINK3_MK:=	${LAME_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lame
.endif

.if !empty(LAME_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		lame
BUILDLINK_DEPENDS.lame+=	lame>=3.93.1nb2
BUILDLINK_PKGSRCDIR.lame?=	../../audio/lame
.endif # LAME_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
