# $NetBSD: buildlink2.mk,v 1.1 2002/10/20 14:32:10 wiz Exp $
#

.if !defined(KDELIBS_BUILDLINK2_MK)
KDELIBS_BUILDLINK2_MK=	# defined

BUILDLINK_PACKAGES+=			kdelibs
BUILDLINK_DEPENDS.kdelibs?=		kdelibs>=1.1.2nb1
BUILDLINK_PKGSRCDIR.kdelibs?=		../../x11/kdelibs

EVAL_PREFIX+=	BUILDLINK_PREFIX.kdelibs=kdelibs
BUILDLINK_PREFIX.kdelibs_DEFAULT=	${X11PREFIX}
BUILDLINK_FILES.kdelibs+=	include/addressbook.h
BUILDLINK_FILES.kdelibs+=	include/bison2cpp.h
BUILDLINK_FILES.kdelibs+=	include/booktoken.h
BUILDLINK_FILES.kdelibs+=	include/builtin.h
BUILDLINK_FILES.kdelibs+=	include/ckey.h
BUILDLINK_FILES.kdelibs+=	include/configDB.h
BUILDLINK_FILES.kdelibs+=	include/dither.h
BUILDLINK_FILES.kdelibs+=	include/drag.h
BUILDLINK_FILES.kdelibs+=	include/html.h
BUILDLINK_FILES.kdelibs+=	include/htmlclue.h
BUILDLINK_FILES.kdelibs+=	include/htmldata.h
BUILDLINK_FILES.kdelibs+=	include/htmlfont.h
BUILDLINK_FILES.kdelibs+=	include/htmlform.h
BUILDLINK_FILES.kdelibs+=	include/htmlframe.h
BUILDLINK_FILES.kdelibs+=	include/htmliter.h
BUILDLINK_FILES.kdelibs+=	include/htmlobj.h
BUILDLINK_FILES.kdelibs+=	include/htmltable.h
BUILDLINK_FILES.kdelibs+=	include/htmltoken.h
BUILDLINK_FILES.kdelibs+=	include/htmlview.h
BUILDLINK_FILES.kdelibs+=	include/jscript.h
BUILDLINK_FILES.kdelibs+=	include/jserror.h
BUILDLINK_FILES.kdelibs+=	include/jsexec.h
BUILDLINK_FILES.kdelibs+=	include/jstree.h
BUILDLINK_FILES.kdelibs+=	include/kab.h
BUILDLINK_FILES.kdelibs+=	include/kabapi.h
BUILDLINK_FILES.kdelibs+=	include/kaccel.h
BUILDLINK_FILES.kdelibs+=	include/kapp.h
BUILDLINK_FILES.kdelibs+=	include/kaudio.h
BUILDLINK_FILES.kdelibs+=	include/kbutton.h
BUILDLINK_FILES.kdelibs+=	include/kbuttonbox.h
BUILDLINK_FILES.kdelibs+=	include/kcharsets.h
BUILDLINK_FILES.kdelibs+=	include/kckey.h
BUILDLINK_FILES.kdelibs+=	include/kclipboard.h
BUILDLINK_FILES.kdelibs+=	include/kcolorbtn.h
BUILDLINK_FILES.kdelibs+=	include/kcolordlg.h
BUILDLINK_FILES.kdelibs+=	include/kcolorgroup.h
BUILDLINK_FILES.kdelibs+=	include/kcombiview.h
BUILDLINK_FILES.kdelibs+=	include/kcombo.h
BUILDLINK_FILES.kdelibs+=	include/kconfig.h
BUILDLINK_FILES.kdelibs+=	include/kconfigbase.h
BUILDLINK_FILES.kdelibs+=	include/kconfigdata.h
BUILDLINK_FILES.kdelibs+=	include/kcontainer.h
BUILDLINK_FILES.kdelibs+=	include/kcontrol.h
BUILDLINK_FILES.kdelibs+=	include/kcursor.h
BUILDLINK_FILES.kdelibs+=	include/kdatepik.h
BUILDLINK_FILES.kdelibs+=	include/kdatetbl.h
BUILDLINK_FILES.kdelibs+=	include/kdbtn.h
BUILDLINK_FILES.kdelibs+=	include/kde.pot
BUILDLINK_FILES.kdelibs+=	include/kdebug.h
BUILDLINK_FILES.kdelibs+=	include/kdir.h
BUILDLINK_FILES.kdelibs+=	include/kdirlistbox.h
BUILDLINK_FILES.kdelibs+=	include/keditcl.h
BUILDLINK_FILES.kdelibs+=	include/keyvaluemap.h
BUILDLINK_FILES.kdelibs+=	include/kfilebookmark.h
BUILDLINK_FILES.kdelibs+=	include/kfiledetaillist.h
BUILDLINK_FILES.kdelibs+=	include/kfiledialog.h
BUILDLINK_FILES.kdelibs+=	include/kfilefilter.h
BUILDLINK_FILES.kdelibs+=	include/kfileinfo.h
BUILDLINK_FILES.kdelibs+=	include/kfileinfocontents.h
BUILDLINK_FILES.kdelibs+=	include/kfilepreview.h
BUILDLINK_FILES.kdelibs+=	include/kfilesimpleview.h
BUILDLINK_FILES.kdelibs+=	include/kfm.h
BUILDLINK_FILES.kdelibs+=	include/kfmclient_ipc.h
BUILDLINK_FILES.kdelibs+=	include/kfmipc.h
BUILDLINK_FILES.kdelibs+=	include/kfontdialog.h
BUILDLINK_FILES.kdelibs+=	include/kglobalaccel.h
BUILDLINK_FILES.kdelibs+=	include/kiconloader.h
BUILDLINK_FILES.kdelibs+=	include/kiconloaderdialog.h
BUILDLINK_FILES.kdelibs+=	include/kimgio.h
BUILDLINK_FILES.kdelibs+=	include/kintegerline.h
BUILDLINK_FILES.kdelibs+=	include/kkeydialog.h
BUILDLINK_FILES.kdelibs+=	include/kled.h
BUILDLINK_FILES.kdelibs+=	include/kledlamp.h
BUILDLINK_FILES.kdelibs+=	include/klined.h
BUILDLINK_FILES.kdelibs+=	include/klocale.h
BUILDLINK_FILES.kdelibs+=	include/kmenubar.h
BUILDLINK_FILES.kdelibs+=	include/kmisc.h
BUILDLINK_FILES.kdelibs+=	include/kmsgbox.h
BUILDLINK_FILES.kdelibs+=	include/knewpanner.h
BUILDLINK_FILES.kdelibs+=	include/knotebook.h
BUILDLINK_FILES.kdelibs+=	include/kpanner.h
BUILDLINK_FILES.kdelibs+=	include/kpixmap.h
BUILDLINK_FILES.kdelibs+=	include/kpoint.h
BUILDLINK_FILES.kdelibs+=	include/kpopmenu.h
BUILDLINK_FILES.kdelibs+=	include/kpreview.h
BUILDLINK_FILES.kdelibs+=	include/kprocctrl.h
BUILDLINK_FILES.kdelibs+=	include/kprocess.h
BUILDLINK_FILES.kdelibs+=	include/kprocio.h
BUILDLINK_FILES.kdelibs+=	include/kprogress.h
BUILDLINK_FILES.kdelibs+=	include/kquickhelp.h
BUILDLINK_FILES.kdelibs+=	include/krect.h
BUILDLINK_FILES.kdelibs+=	include/kremotefile.h
BUILDLINK_FILES.kdelibs+=	include/krestrictedline.h
BUILDLINK_FILES.kdelibs+=	include/krootprop.h
BUILDLINK_FILES.kdelibs+=	include/kruler.h
BUILDLINK_FILES.kdelibs+=	include/ksconfig.h
BUILDLINK_FILES.kdelibs+=	include/kselect.h
BUILDLINK_FILES.kdelibs+=	include/kseparator.h
BUILDLINK_FILES.kdelibs+=	include/ksimpleconfig.h
BUILDLINK_FILES.kdelibs+=	include/ksize.h
BUILDLINK_FILES.kdelibs+=	include/kslider.h
BUILDLINK_FILES.kdelibs+=	include/ksock.h
BUILDLINK_FILES.kdelibs+=	include/kspell.h
BUILDLINK_FILES.kdelibs+=	include/kspelldlg.h
BUILDLINK_FILES.kdelibs+=	include/kspinbox.h
BUILDLINK_FILES.kdelibs+=	include/kstatusbar.h
BUILDLINK_FILES.kdelibs+=	include/kstdaccel.h
BUILDLINK_FILES.kdelibs+=	include/kstring.h
BUILDLINK_FILES.kdelibs+=	include/ktabbar.h
BUILDLINK_FILES.kdelibs+=	include/ktabctl.h
BUILDLINK_FILES.kdelibs+=	include/ktablistbox.h
BUILDLINK_FILES.kdelibs+=	include/ktmainwindow.h
BUILDLINK_FILES.kdelibs+=	include/ktoolbar.h
BUILDLINK_FILES.kdelibs+=	include/ktoolboxmgr.h
BUILDLINK_FILES.kdelibs+=	include/ktopwidget.h
BUILDLINK_FILES.kdelibs+=	include/ktreelist.h
BUILDLINK_FILES.kdelibs+=	include/kurl.h
BUILDLINK_FILES.kdelibs+=	include/kurllabel.h
BUILDLINK_FILES.kdelibs+=	include/kwizard.h
BUILDLINK_FILES.kdelibs+=	include/kwm.h
BUILDLINK_FILES.kdelibs+=	include/kwmmapp.h
BUILDLINK_FILES.kdelibs+=	include/mediatool.h
BUILDLINK_FILES.kdelibs+=	include/sections.h
BUILDLINK_FILES.kdelibs+=	include/stl_headers.h
BUILDLINK_FILES.kdelibs+=	include/xview.h
BUILDLINK_FILES.kdelibs+=	lib/libjscript.*
BUILDLINK_FILES.kdelibs+=	lib/libkab.*
BUILDLINK_FILES.kdelibs+=	lib/libkdecore.*
BUILDLINK_FILES.kdelibs+=	lib/libkdeui.*
BUILDLINK_FILES.kdelibs+=	lib/libkfile.*
BUILDLINK_FILES.kdelibs+=	lib/libkfm.*
BUILDLINK_FILES.kdelibs+=	lib/libkhtmlw.*
BUILDLINK_FILES.kdelibs+=	lib/libkimgio.*
BUILDLINK_FILES.kdelibs+=	lib/libkspell.*
BUILDLINK_FILES.kdelibs+=	lib/libmediatool.*

.include "../../graphics/jpeg/buildlink2.mk"
.include "../../graphics/png/buildlink2.mk"
.include "../../graphics/tiff/buildlink2.mk"
.include "../../x11/qt1/buildlink2.mk"

BUILDLINK_TARGETS+=	kdelibs-buildlink

kdelibs-buildlink: _BUILDLINK_USE

.endif	# KDELIBS_BUILDLINK2_MK
