# $NetBSD: buildlink3.mk,v 1.5 2006/04/12 10:27:37 rillig Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBUNICODE_BUILDLINK3_MK:=	${LIBUNICODE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libunicode
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibunicode}
BUILDLINK_PACKAGES+=	libunicode

.if !empty(LIBUNICODE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libunicode+=		libunicode>=0.4
BUILDLINK_ABI_DEPENDS.libunicode+=	libunicode>=0.4nb1
BUILDLINK_PKGSRCDIR.libunicode?=	../../textproc/libunicode
.endif	# LIBUNICODE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
