# $NetBSD: Makefile,v 1.11 2023/10/26 12:06:39 pho Exp $

DISTNAME=	unix-compat-0.7
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Portable POSIX-compatibility layer
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
