# $NetBSD: Makefile,v 1.12 2021/01/11 13:34:41 taca Exp $

DISTNAME=	ttfunk-1.7.0
CATEGORIES=	fonts

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	# unknown
COMMENT=	TrueType Font Metrics Parser
LICENSE=	gnu-gpl-v2 OR gnu-gpl-v3 OR ruby-license

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
