# $NetBSD: Makefile,v 1.1 2017/06/05 15:30:17 taca Exp $

DISTNAME=	iso8601-0.9.1
CATEGORIES=	time

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/arnau/ISO8601
COMMENT=	Ruby parser to work with ISO 8601 dateTimes and durations
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
