# $NetBSD: buildlink3.mk,v 1.1 2007/04/13 23:21:38 xtraeme Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
P5_CAIRO_BUILDLINK3_MK:=	${P5_CAIRO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	p5-cairo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-cairo}
BUILDLINK_PACKAGES+=	p5-cairo
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}p5-cairo

.if ${P5_CAIRO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.p5-cairo+=	p5-cairo>=1.023
BUILDLINK_PKGSRCDIR.p5-cairo?=	../../graphics/p5-cairo
.endif	# P5_CAIRO_BUILDLINK3_MK

.include "../../graphics/cairo/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
