$NetBSD: patch-src_mesa_drivers_dri_i965_brw__oa__metrics.c,v 1.1 2019/01/10 22:30:11 tnn Exp $

XXX compilation takes forever with clang 7.0

--- src/mesa/drivers/dri/i965/brw_oa_metrics.c.orig	2018-12-11 21:14:35.000000000 +0000
+++ src/mesa/drivers/dri/i965/brw_oa_metrics.c
@@ -1,3 +1,6 @@
+#if defined(__clang__)
+#pragma clang optimize off
+#endif
 /* Autogenerated file, DO NOT EDIT manually! generated by brw_oa.py
  *
  * Copyright (c) 2015 Intel Corporation
