$NetBSD: patch-Cargo.toml,v 1.1 2025/12/13 17:47:21 vins Exp $

Do not attempt to fetch sources at build time.

--- Cargo.toml.orig	2025-10-07 20:56:06.000000000 +0000
+++ Cargo.toml
@@ -31,7 +31,7 @@ nix = { version = "0.30.1", default-feat
 ] }
 num-traits = "0.2.19"
 once_cell = "1.19.0"
-pcre2 = { git = "https://github.com/fish-shell/rust-pcre2", tag = "0.2.9-utf32", default-features = false, features = [
+pcre2 = { path = "../rust-pcre2-0.2.9-utf32", default-features = false, features = [
     "utf32",
 ] }
 phf = { version = "0.12", default-features = false }
