$NetBSD: patch-lib_Net_CUPS.pm,v 1.1 2025/08/31 12:45:24 wiz Exp $

Fix build with libcupsfilters 2.x. From
https://launchpadlibrarian.net/698897992/libnet-cups-perl_0.64-3_0.64-3ubuntu1.diff.gz

--- lib/Net/CUPS.pm.orig	2017-06-08 18:09:35.818415994 +0000
+++ lib/Net/CUPS.pm
@@ -23,6 +23,12 @@ our @ISA = qw(Exporter);
 # will save memory.
 our %EXPORT_TAGS = ( 'all' => [ qw(
 	AF_LOCAL
+	CF_IMAGE_BLACK
+	CF_IMAGE_CMY
+	CF_IMAGE_CMYK
+	CF_IMAGE_RGB
+	CF_IMAGE_RGB_CMYK
+	CF_IMAGE_WHITE
 	CUPS_ACCEPT_JOBS
 	CUPS_ADD_CLASS
 	CUPS_ADD_MODIFY_CLASS
@@ -53,12 +59,6 @@ our %EXPORT_TAGS = ( 'all' => [ qw(
 	CUPS_GET_DEVICES
 	CUPS_GET_PPDS
 	CUPS_GET_PRINTERS
-	CUPS_IMAGE_BLACK
-	CUPS_IMAGE_CMY
-	CUPS_IMAGE_CMYK
-	CUPS_IMAGE_RGB
-	CUPS_IMAGE_RGB_CMYK
-	CUPS_IMAGE_WHITE
 	CUPS_ISO8859_1
 	CUPS_ISO8859_10
 	CUPS_ISO8859_11
@@ -493,6 +493,12 @@ our @EXPORT_OK = ( @{ $EXPORT_TAGS{'all'
 
 our @EXPORT = qw(
 	AF_LOCAL
+	CF_IMAGE_BLACK
+	CF_IMAGE_CMY
+	CF_IMAGE_CMYK
+	CF_IMAGE_RGB
+	CF_IMAGE_RGB_CMYK
+	CF_IMAGE_WHITE
 	CUPS_ACCEPT_JOBS
 	CUPS_ADD_CLASS
 	CUPS_ADD_MODIFY_CLASS
@@ -523,12 +529,6 @@ our @EXPORT = qw(
 	CUPS_GET_DEVICES
 	CUPS_GET_PPDS
 	CUPS_GET_PRINTERS
-	CUPS_IMAGE_BLACK
-	CUPS_IMAGE_CMY
-	CUPS_IMAGE_CMYK
-	CUPS_IMAGE_RGB
-	CUPS_IMAGE_RGB_CMYK
-	CUPS_IMAGE_WHITE
 	CUPS_ISO8859_1
 	CUPS_ISO8859_10
 	CUPS_ISO8859_11
