$NetBSD: patch-lib_Net_CUPS_Destination.pm,v 1.1 2025/08/31 12:45:24 wiz Exp $

Fix build with libcupsfilters 2.x. From
https://launchpadlibrarian.net/698897992/libnet-cups-perl_0.64-3_0.64-3ubuntu1.diff.gz

--- lib/Net/CUPS/Destination.pm.orig	2017-06-08 18:06:22.597793032 +0000
+++ lib/Net/CUPS/Destination.pm
@@ -25,6 +25,12 @@ our @ISA = qw(Exporter);
 # will save memory.
 our %EXPORT_TAGS = ( 'all' => [ qw(
 	AF_LOCAL
+	CF_IMAGE_BLACK
+	CF_IMAGE_CMY
+	CF_IMAGE_CMYK
+	CF_IMAGE_RGB
+	CF_IMAGE_RGB_CMYK
+	CF_IMAGE_WHITE
 	CUPS_ACCEPT_JOBS
 	CUPS_ADD_CLASS
 	CUPS_ADD_MODIFY_CLASS
@@ -55,12 +61,6 @@ our %EXPORT_TAGS = ( 'all' => [ qw(
 	CUPS_GET_DEVICES
 	CUPS_GET_PPDS
 	CUPS_GET_PRINTERS
-	CUPS_IMAGE_BLACK
-	CUPS_IMAGE_CMY
-	CUPS_IMAGE_CMYK
-	CUPS_IMAGE_RGB
-	CUPS_IMAGE_RGB_CMYK
-	CUPS_IMAGE_WHITE
 	CUPS_ISO8859_1
 	CUPS_ISO8859_10
 	CUPS_ISO8859_11
@@ -495,6 +495,12 @@ our @EXPORT_OK = ( @{ $EXPORT_TAGS{'all'
 
 our @EXPORT = qw(
 	AF_LOCAL
+	CF_IMAGE_BLACK
+	CF_IMAGE_CMY
+	CF_IMAGE_CMYK
+	CF_IMAGE_RGB
+	CF_IMAGE_RGB_CMYK
+	CF_IMAGE_WHITE
 	CUPS_ACCEPT_JOBS
 	CUPS_ADD_CLASS
 	CUPS_ADD_MODIFY_CLASS
@@ -525,12 +531,6 @@ our @EXPORT = qw(
 	CUPS_GET_DEVICES
 	CUPS_GET_PPDS
 	CUPS_GET_PRINTERS
-	CUPS_IMAGE_BLACK
-	CUPS_IMAGE_CMY
-	CUPS_IMAGE_CMYK
-	CUPS_IMAGE_RGB
-	CUPS_IMAGE_RGB_CMYK
-	CUPS_IMAGE_WHITE
 	CUPS_ISO8859_1
 	CUPS_ISO8859_10
 	CUPS_ISO8859_11
