# $NetBSD: buildlink3.mk,v 1.1 2005/11/05 06:16:55 martti Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
P5_CONFIG_INIFILES_BUILDLINK3_MK:=	${P5_CONFIG_INIFILES_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	p5-Config-IniFiles
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-Config-IniFiles}
BUILDLINK_PACKAGES+=	p5-Config-IniFiles

.if !empty(P5_CONFIG_INIFILES_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.p5-Config-IniFiles+=	p5-Config-IniFiles>=2.38nb2
BUILDLINK_PKGSRCDIR.p5-Config-IniFiles?=	../../devel/p5-Config-IniFiles
.endif	# P5_CONFIG_INIFILES_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
