$NetBSD: patch-lib_tasks_initializers.rake,v 1.1 2021/02/28 16:50:03 taca Exp $

Generate secret_token.rb with safe mode.

--- lib/tasks/initializers.rake.orig	2020-04-06 17:00:48.000000000 +0000
+++ lib/tasks/initializers.rake
@@ -3,7 +3,7 @@ desc 'Generates a secret token for the a
 file 'config/initializers/secret_token.rb' do
   path = File.join(Rails.root, 'config', 'initializers', 'secret_token.rb')
   secret = SecureRandom.hex(40)
-  File.open(path, 'w') do |f|
+  File.open(path, 'w', 0640) do |f|
     f.write <<"EOF"
 # This file was generated by 'rake generate_secret_token', and should
 # not be made visible to public.
