# $NetBSD: Makefile,v 1.25 2025/08/13 11:07:15 pho Exp $

DISTNAME=	nats-1.1.2
PKGREVISION=	11
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell 98 natural numbers
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-hashable/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
