# $NetBSD: Makefile,v 1.10 2021/02/13 10:27:35 markd Exp $

DISTNAME=	caption.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-20201026
TEXLIVE_REV=	56771

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/caption
COMMENT=	Documentation for tex-caption
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
