# $NetBSD: Makefile,v 1.11 2013/04/06 03:45:18 rodent Exp $
#

DISTNAME=	vttest-20120506
CATEGORIES=	misc benchmarks
MASTER_SITES=	ftp://dickey.his.com/vttest/
EXTRACT_SUFX=	.tgz

MAINTAINER=	drochner@NetBSD.org
HOMEPAGE=	http://invisible-island.net/vttest/vttest.html
COMMENT=	Utility to test vt100/vt220/xterm

GNU_CONFIGURE=	yes
MAKE_FILE=	makefile

.include "../../mk/bsd.pkg.mk"
