# $NetBSD: buildlink3.mk,v 1.1 2007/03/18 18:56:30 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ENCA_BUILDLINK3_MK:=	${ENCA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	enca
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nenca}
BUILDLINK_PACKAGES+=	enca
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}enca

.if ${ENCA_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.enca+=	enca>=1.9
BUILDLINK_PKGSRCDIR.enca?=	../../textproc/enca
.endif	# ENCA_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
