.\" $NetBSD: cdpack.1,v 1.6 2001/12/03 19:03:22 wiz Exp $
.\"
.\" Copyright (c) 2001 Dan McMahill, All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Dan McMahill
.\" 4. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY DAN MCMAHILL
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 25, 2001
.Dt CDPACK 1
.Os
.Sh NAME
.Nm cdpack
.Nd produce multi-CD binary package images
.Sh SYNOPSIS
.Nm ""
.Op -l logfile
.Op -nRvV
.Op -x common_directory
.Op -X extras_directory
.Ar packages_directory
.Ar cd_image_directory
.Sh DESCRIPTION
The
.Nm
utility produces ISO 9660 image files for
a multiple CD-ROM collection of binary packages.
.Pp
The
.Nm
utility extracts the dependency information from the binary
packages in the directory
.Ar packages_directory
specified on the command line.  The dependency information is
used to determine which packages are placed on which CD.  The
directory
.Ar cd_image_directory
is used as a staging area and the final ISO 9660 images are left in
that directory.  A file,
.Ar .index ,
which lists the contents of each CD will be left in the root
directory of each CD image.
.Bl -tag -width "-x directory "
.It Fl l Ar logfile
Log the output of mkisofs -v -v to the file
.Ar logfile .
.It Fl n
Do not duplicate packages in order to prevent inter-CD dependencies.
The default without the
.Fl n
option will place a package and all of its dependencies on the same
CD.  If a particular package is also required by pacakges on other
CD's, it will be placed there as well.
When the
.Fl n
option is used packages are not duplicated.  This results in slightly
smaller ISO 9660 images.
.Nm
places packages which are lower in the dependency tree on lower
numbered CD-ROM's and packages which are higher on the higher numbered
CD-ROM's.  In this fashion, a package on CD number n
will have all of its dependencies on CD numbers 1 through n
.It Fl R
Generate a file,
.Ar README.txt ,
which will be placed in the root directory of each CD image.  This
README file contains a small amount of information about the contents
of the CD set.
.It Fl v
Be verbose.  Currently does not change things much.
.It Fl V
Print the program version number and exit.
.It Fl x Ar directory
Includes the contents of
.Ar directory
on each CD.  This is useful for README files, etc., which you want
to be present on each CD in the set.
.It Fl X Ar directory
Includes the contents of
.Ar directory
on the last CD in the set.  This is useful for adding
a pkgsrc.tar.gz tarball, i.e. a file which does not
need to be on each CD.
.El
.Pp
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh ENVIRONMENT
.Nm
uses the fillowing environment variables if set.
.Bl -tag -width "TMPDIR"
.It Ev TMPDIR
Directory for holding temporary files during the image creation.
Defaults to
.Dq Li /tmp .
.El
.Sh EXAMPLES
This example takes all of the binary packages found in
/usr/pkgsrc/packages/All and creates cd images in
/u2/cdimages/cd{1,2,...}.iso.  The directories
/u2/cdimages/cd{1,2,...} are used to create the ISO 9660 layouts.
.D1 cdpack /usr/pkgsrc/packages/All /u2/cdimages
.Pp
To include a common set of files on all CD's, place them in a
directory, /tmp/foo, in this example, and pass in the directory name
with the
.Fl x
option.
.Dl cdpack -x /tmp/foo /usr/pkgsrc/packages/All /u2/cdimages
.Sh SEE ALSO
.Xr mkisofs 1
.Sh HISTORY
The
.Nm
utility first appeared in the
.Nx
packages collection in April, 2001.
.Sh AUTHORS
The
.Nm
utility was written by Dan McMahill (dmcmahill@netbsd.org).  The
idea of duplicating packages to eliminate inter-CD dependencies
came from Todd Vierling (tv@netbsd.org).
