# $NetBSD: Makefile,v 1.10 2025/03/05 03:39:36 pho Exp $

DISTNAME=	vector-stream-0.1.0.1
PKGREVISION=	3
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Efficient Streams for Haskell
LICENSE=	modified-bsd

HASKELL_UNRESTRICT_DEPENDENCIES+=	\
	base

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
