# $NetBSD: Makefile,v 1.1 2015/04/27 06:56:30 markd Exp $

DISTNAME=	fancyref
PKGNAME=	tex-${DISTNAME}-0.9c
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD,org
COMMENT=	A LaTeX package for fancy cross-referencing
LICENSE=	gnu-gpl-v2

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
