@comment $NetBSD: PLIST.sieve,v 1.3 2010/04/30 10:43:26 ghen Exp $
bin/sieve-test
bin/sievec
bin/sieved
include/dovecot/sieve/dsieve-config.h
include/dovecot/sieve/rfc2822.h
include/dovecot/sieve/sieve-actions.h
include/dovecot/sieve/sieve-address-parts.h
include/dovecot/sieve/sieve-address.h
include/dovecot/sieve/sieve-ast.h
include/dovecot/sieve/sieve-binary-dumper.h
include/dovecot/sieve/sieve-binary.h
include/dovecot/sieve/sieve-code-dumper.h
include/dovecot/sieve/sieve-code.h
include/dovecot/sieve/sieve-commands.h
include/dovecot/sieve/sieve-common.h
include/dovecot/sieve/sieve-comparators.h
include/dovecot/sieve/sieve-config.h
include/dovecot/sieve/sieve-dump.h
include/dovecot/sieve/sieve-error-private.h
include/dovecot/sieve/sieve-error.h
include/dovecot/sieve/sieve-ext-enotify.h
include/dovecot/sieve/sieve-ext-environment.h
include/dovecot/sieve/sieve-ext-variables.h
include/dovecot/sieve/sieve-extensions.h
include/dovecot/sieve/sieve-generator.h
include/dovecot/sieve/sieve-interpreter.h
include/dovecot/sieve/sieve-lexer.h
include/dovecot/sieve/sieve-limits.h
include/dovecot/sieve/sieve-match-types.h
include/dovecot/sieve/sieve-match.h
include/dovecot/sieve/sieve-message.h
include/dovecot/sieve/sieve-objects.h
include/dovecot/sieve/sieve-parser.h
include/dovecot/sieve/sieve-plugins.h
include/dovecot/sieve/sieve-result.h
include/dovecot/sieve/sieve-script-private.h
include/dovecot/sieve/sieve-script.h
include/dovecot/sieve/sieve-settings.h
include/dovecot/sieve/sieve-types.h
include/dovecot/sieve/sieve-validator.h
include/dovecot/sieve/sieve.h
lib/dovecot/lda/lib90_sieve_plugin.la
man/man1/sieve-test.1
man/man1/sievec.1
man/man1/sieved.1
share/doc/dovecot/sieve/spamtest-virustest.txt
