# $NetBSD: buildlink3.mk,v 1.1 2004/02/10 00:20:29 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBTASN1_BUILDLINK3_MK:=	${LIBTASN1_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libtasn1
.endif

.if !empty(LIBTASN1_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		libtasn1
BUILDLINK_DEPENDS.libtasn1+=	libtasn1>=0.1.2
BUILDLINK_PKGSRCDIR.libtasn1?=	../../security/libtasn1
.endif # LIBTASN1_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
