# $NetBSD: buildlink3.mk,v 1.4 2004/10/03 00:18:10 tv Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBTASN1_BUILDLINK3_MK:=	${LIBTASN1_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libtasn1
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibtasn1}
BUILDLINK_PACKAGES+=	libtasn1

.if !empty(LIBTASN1_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libtasn1+=	libtasn1>=0.2.7
BUILDLINK_RECOMMENDED.libtasn1+=	libtasn1>=0.2.10nb1
BUILDLINK_PKGSRCDIR.libtasn1?=	../../security/libtasn1
.endif	# LIBTASN1_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
