# $NetBSD: buildlink3.mk,v 1.3 2006/01/24 07:32:06 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GPSIM_BUILDLINK3_MK:=	${GPSIM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gpsim
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngpsim}
BUILDLINK_PACKAGES+=	gpsim

.if !empty(GPSIM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.gpsim+=	gpsim>=20050905
BUILDLINK_RECOMMENDED.gpsim+=	gpsim>=20050905nb1
BUILDLINK_PKGSRCDIR.gpsim?=	../../emulators/gpsim-devel
.endif	# GPSIM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}

.include "../../x11/gtk2/buildlink3.mk"
