# $NetBSD: Makefile,v 1.13 2025/05/10 23:55:00 markd Exp $

DISTNAME=	titlesec
PKGNAME=	tex-${DISTNAME}-2.17
TEXLIVE_REV=	73302

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/titlesec
COMMENT=	Select alternative section titles
LICENSE=	mit

DEPENDS+=	tex-graphics-[0-9]*:../../print/tex-graphics

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
