# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 20:18:23 joerg Exp $

BUILDLINK_DEPMETHOD.videoproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
VIDEOPROTO_BUILDLINK3_MK:=	${VIDEOPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	videoproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nvideoproto}
BUILDLINK_PACKAGES+=	videoproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}videoproto

.if ${VIDEOPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.videoproto+=	videoproto>=2.2.1
BUILDLINK_PKGSRCDIR.videoproto?=	../../x11/videoproto
.endif	# VIDEOPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
