#!/bin/sh
#
# $NetBSD: DEINSTALL,v 1.1 2006/06/15 20:40:16 jlam Exp $

case ${STAGE} in
DEINSTALL)
	if [ "${PKG_PREFIX}" != "${LOCALBASE}" ]; then
		${RM} -f ${LOCALBASE}/share/aclocal/gtk.m4
	fi
	;;
esac
