# $NetBSD: buildlink3.mk,v 1.10 2006/08/02 02:30:28 schmonz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BGLIBS_BUILDLINK3_MK:=	${BGLIBS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	bglibs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbglibs}
BUILDLINK_PACKAGES+=	bglibs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}bglibs

.if !empty(BGLIBS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.bglibs+=	bglibs>=1.100
BUILDLINK_PKGSRCDIR.bglibs?=	../../devel/bglibs
.endif	# BGLIBS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
