# $NetBSD: buildlink3.mk,v 1.6 2006/04/06 06:21:44 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BGLIBS_BUILDLINK3_MK:=	${BGLIBS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	bglibs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbglibs}
BUILDLINK_PACKAGES+=	bglibs

.if !empty(BGLIBS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.bglibs+=	bglibs>=1.040
BUILDLINK_PKGSRCDIR.bglibs?=	../../devel/bglibs
BUILDLINK_DEPMETHOD.bglibs?=	build
.endif	# BGLIBS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
