# $NetBSD: buildlink3.mk,v 1.3 2005/08/19 20:46:45 schmonz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BGLIBS_BUILDLINK3_MK:=	${BGLIBS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	bglibs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbglibs}
BUILDLINK_PACKAGES+=	bglibs

.if !empty(BGLIBS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.bglibs+=	bglibs>=1.026
BUILDLINK_PKGSRCDIR.bglibs?=	../../devel/bglibs
BUILDLINK_DEPMETHOD.bglibs?=	build
.endif	# BGLIBS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
