# $NetBSD: Makefile,v 1.75 2025/03/09 02:48:02 gutteridge Exp $

.include "../../meta-pkgs/xfce4/Makefile.common"

DISTNAME=	xfce4-diskperf-plugin-2.7.1
CATEGORIES=	sysutils
MASTER_SITES=	https://archive.xfce.org/src/panel-plugins/xfce4-diskperf-plugin/2.7/

HOMEPAGE=	https://goodies.xfce.org/projects/panel-plugins/xfce4-diskperf-plugin
COMMENT=	Xfce disk performance plugin

.include "../../x11/xfce4-panel/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
