# $NetBSD: Makefile,v 1.4 2016/08/07 09:01:08 markd Exp $

DISTNAME=	animate.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-20160727
TEXLIVE_REV=	41770

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/animate
COMMENT=	Documentation for tex-animate
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
