# $NetBSD: Makefile,v 1.8 2021/05/23 08:19:31 taca Exp $

DISTNAME=	bindata-2.4.10
CATEGORIES=	devel

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/dmendel/bindata
COMMENT=	Declarative way to read and write structured binary data
LICENSE=	2-clause-bsd

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
