# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:11:00 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PROJ_BUILDLINK3_MK:=	${PROJ_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	proj
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nproj}
BUILDLINK_PACKAGES+=	proj
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}proj

.if !empty(PROJ_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.proj+=	proj>=4.4.7nb1
BUILDLINK_ABI_DEPENDS.proj?=	proj>=4.4.7nb2
BUILDLINK_PKGSRCDIR.proj?=	../../misc/proj
.endif	# PROJ_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
