# $NetBSD: buildlink3.mk,v 1.3 2006/02/05 23:11:31 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XBAE_BUILDLINK3_MK:=	${XBAE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	Xbae
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NXbae}
BUILDLINK_PACKAGES+=	Xbae

.if !empty(XBAE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.Xbae+=	Xbae>=4.8.4
BUILDLINK_RECOMMENDED.Xbae+=	Xbae>=4.51.01nb2
BUILDLINK_PKGSRCDIR.Xbae?=	../../x11/Xbae
.endif	# XBAE_BUILDLINK3_MK

.include "../../mk/motif.buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
