# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 23:10:40 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDBM_BUILDLINK3_MK:=	${SDBM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sdbm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsdbm}
BUILDLINK_PACKAGES+=	sdbm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}sdbm

.if !empty(SDBM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.sdbm+=	sdbm>=90.12.1
BUILDLINK_PKGSRCDIR.sdbm?=	../../databases/sdbm
.endif	# SDBM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
