# $NetBSD: buildlink3.mk,v 1.1 2005/04/05 10:24:41 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDBM_BUILDLINK3_MK:=	${SDBM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sdbm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsdbm}
BUILDLINK_PACKAGES+=	sdbm

.if !empty(SDBM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.sdbm+=	sdbm>=90.12.1
BUILDLINK_PKGSRCDIR.sdbm?=	../../databases/sdbm
.endif	# SDBM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
