# $NetBSD: Makefile,v 1.5 2025/01/30 04:43:49 pho Exp $

DISTNAME=	text-iso8601-0.1.1
CATEGORIES=	time converters

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Converting time to and from ISO 8601 text
LICENSE=	modified-bsd

.include "../../math/hs-integer-conversion/buildlink3.mk"
.include "../../time/hs-time-compat/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
