# $NetBSD: buildlink3.mk,v 1.1 2004/02/12 08:40:23 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GDBM_BUILDLINK3_MK:=	${GDBM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gdbm
.endif

.if !empty(GDBM_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		gdbm
BUILDLINK_DEPENDS.gdbm+=	gdbm>=1.8.3
BUILDLINK_PKGSRCDIR.gdbm?=	../../databases/gdbm
.endif # GDBM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
