# $NetBSD: Makefile,v 1.54 2018/01/28 19:40:22 wiz Exp $

.include "Makefile.common"

COMMENT=	The GNU database manager

INFO_FILES=		yes

.include "../../converters/libiconv/buildlink3.mk"
.include "../../devel/gettext-lib/buildlink3.mk"
.include "../../devel/readline/buildlink3.mk"
.include "../../mk/curses.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
