# $NetBSD: buildlink3.mk,v 1.2 2011/12/19 14:36:28 wiz Exp $

BUILDLINK_TREE+=	xsd

.if !defined(XSD_BUILDLINK3_MK)
XSD_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.xsd+=	xsd>=3.2
BUILDLINK_ABI_DEPENDS.xsd+=	xsd>=3.2
BUILDLINK_PKGSRCDIR.xsd?=	../../devel/xsd

BUILDLINK_DEPMETHOD.xsd?=	build
.endif # XSD_BUILDLINK3_MK

BUILDLINK_TREE+=	-xsd
