.\" $NetBSD: genrpm.8,v 1.2 2005/04/21 14:55:44 wiz Exp $
.Dd April 20, 2005
.Os
.Dt GENRPM 8
.Sh NAME
.Nm genrpm
.Sh SYNOPSIS
.Nm
.Op Fl sv
.Ar package ...
.Sh DESCRIPTION
The
.Nm
program takes an installed pkgsrc package and creates a
Redhat Package Manager package from that, optionally creating
an RPM-style src RPM in addition.
If the
.Fl v
option is specified,
.Nm
will carry out its work in a verbose manner (the rpm utility is
already a fairly verbose utility).
.Pp
Package version extension will be done automatically by
.Nm
so that rpm packages do not need to know the individual version
numbers of pkgsrc packages.
.Pp
An optional source rpm package can also
be created by using the
.Fl s
flag.
.Sh SEE ALSO
.Xr pkg_tarup 1 ,
.Xr rpm 8
and
.Rs
.%T "Documentation on the NetBSD Package System"
.Re
@PKGSRCDIR@/doc/pkgsrc.txt
.Sh HISTORY
The
.Nm
command was added to
.Nx Ap s
pkgsrc on April 20, 2005.
.Sh AUTHORS
The
.Nm
command was written by
.An Alistair Crooks Aq agc@NetBSD.org .
