# $NetBSD: Makefile,v 1.3 2004/11/27 18:07:04 wiz Exp $
#

DISTNAME=		rss2html-0.7
CATEGORIES=		converters
MASTER_SITES=		ftp://ftp.nopcode.org/prj/rss2html/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.nopcode.org/?t=rss2html
COMMENT=		RSS to HTML converter

PKG_INSTALLATION_TYPES=	overwrite pkgviews

USE_BUILDLINK3=		YES
USE_GNU_TOOLS+=		make

INSTALLATION_DIRS+=	bin

.include "../../mk/bsd.pkg.mk"
