# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 23:10:44 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBHFS_BUILDLINK3_MK:=	${LIBHFS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libhfs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibhfs}
BUILDLINK_PACKAGES+=	libhfs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libhfs

.if !empty(LIBHFS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libhfs+=	libhfs>=3.2.6nb1
BUILDLINK_PKGSRCDIR.libhfs?=	../../devel/libhfs
.endif	# LIBHFS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
