# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:37 wiz Exp $

DISTNAME=	dice
PKGNAME=	tex-${DISTNAME}-2014
TEXLIVE_REV=	28501

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/dice
COMMENT=	Font for die faces
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
