# $NetBSD: buildlink3.mk,v 1.1 2004/04/18 18:48:41 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBIDEA_BUILDLINK3_MK:=	${LIBIDEA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libidea
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibidea}
BUILDLINK_PACKAGES+=	libidea

.if !empty(LIBIDEA_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libidea+=	libidea>=0.8.2
BUILDLINK_PKGSRCDIR.libidea?=	../../security/libidea
BUILDLINK_DEPMETHOD.libidea?=	build
.endif	# LIBIDEA_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
