$NetBSD: patch-src_3rdparty_chromium_services_network_BUILD.gn,v 1.1 2025/12/21 09:38:37 markd Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/services/network/BUILD.gn.orig	2024-12-17 17:58:49.000000000 +0000
+++ src/3rdparty/chromium/services/network/BUILD.gn
@@ -401,7 +401,6 @@ if (is_linux || is_chromeos) {
     ]
     deps = [
       "//base:base",
-      "//sandbox/linux:sandbox_services",
       "//sandbox/policy:policy",
     ]
     configs += [ "//build/config/compiler:wexit_time_destructors" ]
