$NetBSD: patch-src_3rdparty_chromium_build_config_rust.gni,v 1.1 2025/12/21 09:38:17 markd Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/build/config/rust.gni.orig	2024-12-17 17:58:49.000000000 +0000
+++ src/3rdparty/chromium/build/config/rust.gni
@@ -321,6 +321,10 @@ if (is_linux || is_chromeos) {
   }
 }
 
+if (is_bsd) {
+  rust_abi_target = string_replace(rust_abi_target, "linux-gnu", current_os)
+}
+
 assert(!toolchain_has_rust || rust_abi_target != "")
 
 # This variable is passed to the Rust libstd build.
