$NetBSD: patch-src_3rdparty_chromium_services_device_serial_BUILD.gn,v 1.1 2025/12/21 09:38:37 markd Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/services/device/serial/BUILD.gn.orig	2025-10-02 00:36:39.000000000 +0000
+++ src/3rdparty/chromium/services/device/serial/BUILD.gn
@@ -4,7 +4,7 @@
 
 import("//build/config/features.gni")
 
-if (is_win || ((is_linux || is_chromeos) && use_udev) || is_mac) {
+if (is_win || ((!is_bsd && is_linux || is_chromeos) && use_udev) || is_mac) {
   config("platform_support") {
     visibility = [ ":serial" ]
     if (is_win) {
