$NetBSD: patch-src_3rdparty_chromium_services_resource__coordinator_public_cpp_memory__instrumentation_BUILD.gn,v 1.1 2025/12/21 09:38:38 markd Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/services/resource_coordinator/public/cpp/memory_instrumentation/BUILD.gn.orig	2024-12-17 17:58:49.000000000 +0000
+++ src/3rdparty/chromium/services/resource_coordinator/public/cpp/memory_instrumentation/BUILD.gn
@@ -29,10 +29,14 @@ component("memory_instrumentation") {
     sources += [ "os_metrics_win.cc" ]
   }
 
-  if (is_android || is_linux || is_chromeos) {
+  if ((is_android || is_linux || is_chromeos) && !is_bsd) {
     sources += [ "os_metrics_linux.cc" ]
   }
 
+  if (is_bsd) {
+    sources += [ "os_metrics_bsd.cc" ]
+  }
+
   if (is_fuchsia) {
     sources += [ "os_metrics_fuchsia.cc" ]
   }
