$NetBSD: patch-src_3rdparty_chromium_base_allocator_partition__allocator_partition__alloc.gni,v 1.3 2026/04/30 06:39:35 adam Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/base/allocator/partition_allocator/partition_alloc.gni.orig	2026-03-16 11:40:07.000000000 +0000
+++ src/3rdparty/chromium/base/allocator/partition_allocator/partition_alloc.gni
@@ -87,7 +87,7 @@ if (current_cpu == "x64" || current_cpu 
 # TODO(crbug.com/329199197): Clean this up when experiments are complete.
 use_large_empty_slot_span_ring = true
 
-has_memory_tagging = current_cpu == "arm64" && is_clang && !is_asan &&
+has_memory_tagging = current_cpu == "arm64" && !is_bsd && is_clang && !is_asan &&
                      !is_hwasan && (is_linux || is_android)
 
 declare_args() {
@@ -493,7 +493,7 @@ assert(!use_asan_backup_ref_ptr || use_r
 # dependencies that use partition_allocator are compiled in AOSP against a
 # version of glibc that does not include pkeys syscall numbers.
 is_pkeys_available =
-    (is_linux || is_chromeos) && current_cpu == "x64" && !is_cronet_build
+    !is_bsd && (is_linux || is_chromeos) && current_cpu == "x64" && !is_cronet_build
 declare_args() {
   enable_pkeys = is_pkeys_available
 }
