$NetBSD: patch-src_3rdparty_chromium_services_viz_public_mojom_BUILD.gn,v 1.1 2026/04/30 06:39:43 adam Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/services/viz/public/mojom/BUILD.gn.orig	2026-03-16 11:40:07.000000000 +0000
+++ src/3rdparty/chromium/services/viz/public/mojom/BUILD.gn
@@ -51,7 +51,7 @@ mojom("mojom") {
 
   # Used in thread.mojom
   enabled_features = []
-  if (is_fuchsia || is_apple) {
+  if (is_fuchsia || is_apple || is_bsd) {
     enabled_features += [ "thread_id_is_64_bit" ]
   } else {
     enabled_features += [ "thread_id_is_32_bit" ]
