$NetBSD: patch-src_3rdparty_chromium_ui_gfx_x_BUILD.gn,v 1.1 2025/12/21 09:38:48 markd Exp $

* Based on OpenBSD's qt6-qtwebengine patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/ui/gfx/x/BUILD.gn.orig	2024-11-21 04:36:37.000000000 +0000
+++ src/3rdparty/chromium/ui/gfx/x/BUILD.gn
@@ -7,8 +7,6 @@ import("//build/config/ozone.gni")
 import("//build/config/ui.gni")
 import("//tools/generate_library_loader/generate_library_loader.gni")
 
-assert(ozone_platform_x11)
-
 declare_args() {
   regenerate_x11_protos = false
 }
