$NetBSD: patch-src_3rdparty_chromium_build_config_rust.gni,v 1.2 2026/04/30 06:39:35 adam Exp $

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- src/3rdparty/chromium/build/config/rust.gni.orig	2026-03-16 11:40:07.000000000 +0000
+++ src/3rdparty/chromium/build/config/rust.gni
@@ -195,7 +195,7 @@ if (is_linux || is_chromeos) {
     rust_abi_target = "aarch64-unknown-linux-gnu"
     cargo_target_abi = ""
   } else if (current_cpu == "x86") {
-    rust_abi_target = "i686-unknown-linux-gnu"
+    rust_abi_target = "i586-unknown-linux-gnu"
     cargo_target_abi = ""
   } else if (current_cpu == "x64") {
     rust_abi_target = "x86_64-unknown-linux-gnu"
@@ -377,7 +377,11 @@ if (is_linux || is_chromeos) {
   }
 }
 
-if (toolchain_has_rust) {
+if (is_bsd) {
+  rust_abi_target = string_replace(rust_abi_target, "linux-gnu", current_os)
+}
+
+if (toolchain_has_rust && !is_bsd) {
   assert(rust_abi_target != "")
 
   _known_rust_target_triples_filepath = "//build/rust/known-target-triples.txt"
