# $NetBSD: Makefile,v 1.8 2001/02/16 13:59:27 wiz Exp $
#

DISTNAME=		recode-3.5
CATEGORIES=		converters
MASTER_SITES=		${MASTER_SITE_GNU:=recode/}

MAINTAINER=		kleink@netbsd.org
HOMEPAGE=		http://www.gnu.org/software/recode/recode.html
COMMENT=		Convert files between character sets and usages

GNU_CONFIGURE=		yes

INFO_FILES=     	recode.info

.include "../../mk/bsd.pkg.mk"
