.\"	$NetBSD: mkpatches.1,v 1.3 2005/12/13 12:05:08 wiz Exp $
.\"
.\" Copyright (c) 2000 by Thomas Klausner <wiz@NetBSD.org>
.\" All Rights Reserved.  Absolutely no warranty.
.\"
.Dd June 25, 2000
.Dt MKPATCHES 1
.Os
.Sh NAME
.Nm mkpatches
.Nd create patch files appropriate for pkgsrc
.Sh SYNOPSIS
.Nm
.Op Fl d Ar output-directory
.Sh DESCRIPTION
.Nm
is a perl script that simplifies creating patches from a changed work
tree if for each changed file the original was kept with an added
extension
.Dq .orig .
.Pp
.Nm
must be called from the package's main directory, that is
.Pa ${PKGSRC}/category/program .
It then proceeds to find all files that
match the pattern
.Dq *.orig .
Each of these is then compared to the
changed file of the same name (with no
.Dq .orig
extension) using
.Xr pkgdiff 1 .
.Pp
The resulting patches are saved in the directory
.Pa ${WRKDIR}/.newpatches
or the directory specified after
.Fl d ,
and can be easily compared to the currently existing set using
.Xr patchdiff 1 .
.Sh SEE ALSO
.Xr patchdiff 1 ,
.Xr pkgdiff 1
