.\"	$NetBSD: mkpatches.1,v 1.4 2011/02/02 10:23:02 wiz Exp $
.\"
.\" Copyright (c) 2000-2011 by Thomas Klausner <wiz@NetBSD.org>
.\" All Rights Reserved.  Absolutely no warranty.
.\"
.Dd January 31, 2011
.Dt MKPATCHES 1
.Os
.Sh NAME
.Nm mkpatches
.Nd create patch files appropriate for pkgsrc
.Sh SYNOPSIS
.Nm
.Oo Fl c | Fl r Oc
.Op Fl hv
.Sh DESCRIPTION
.Nm
is a perl script that simplifies creating patches from a changed work
tree if for each changed file the original was kept with an added
extension
.Dq .orig .
.Pp
.Nm
must be called from the package's main directory, that is
.Pa ${PKGSRC}/category/program .
It then proceeds to find all files that
match the pattern
.Dq *.orig .
Each of these is then compared to the
changed file of the same name (with no
.Dq .orig
extension) using
.Xr pkgdiff 1 .
.Pp
The resulting patches are saved in the package's patches directory
(usually
.Pa patches/ )
and can be easily compared to the currently existing set using
.Xr patchdiff 1
or
.Ic "cvs diff" .
.Pp
Supported options are:
.Bl -tag -width 3n
.It Fl c
Clean up backup patches of previous runs.
Use this after you're finished working on the patch set and committed
it.
.It Fl h
Show a short usage.
.It Fl r
Revert the changes.
Removes the new patches and puts the original patches back.
.It Fl v
More verbose output.
.El
.Sh SEE ALSO
.Xr cvs 1 ,
.Xr patchdiff 1 ,
.Xr pkgdiff 1
