.\"	$NetBSD: patchdiff.1,v 1.3 2005/12/13 12:05:08 wiz Exp $
.\"
.\" Copyright (c) 2000 by Thomas Klausner <wiz@NetBSD.org>
.\" All Rights Reserved.  Absolutely no warranty.
.\"
.Dd June 25, 2000
.Dt PATCHDIFF 1
.Os
.Sh NAME
.Nm patchdiff
.Nd compare sets of patches
.Sh SYNOPSIS
.Nm
.Op Fl d Ar output-directory
.Sh DESCRIPTION
.Nm
is a perl script that simplifies comparing a set of previously
existing patches with a new one created with
.Xr mkpatches 1 .
.Pp
.Nm
must be called from the package's main directory, that is
.Pa ${PKGSRC}/category/program .
For each patch existing in either the
patches or the
.Pa ${WRKDIR}/.newpatches
directory (the second of which can be overridden by the argument of the
.Fl d
option), a matching patch is
looked for in the other directory, and, if one is found, the two are
compared with
.Xr diff 1 .
.Sh SEE ALSO
.Xr diff 1 ,
.Xr patchdiff 1 ,
.Xr pkgdiff 1
