.\"	$NetBSD: patchdiff.1,v 1.4 2011/02/02 10:23:02 wiz Exp $
.\"
.\" Copyright (c) 2000-2011 by Thomas Klausner <wiz@NetBSD.org>
.\" All Rights Reserved.  Absolutely no warranty.
.\"
.Dd January 31, 2011
.Dt PATCHDIFF 1
.Os
.Sh NAME
.Nm patchdiff
.Nd compare sets of patches
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a perl script that simplifies comparing a set of previously
existing patches with a new one created with
.Xr mkpatches 1 .
.Pp
.Nm
must be called from the package's main directory, that is
.Pa ${PKGSRC}/category/program .
For each patch existing in either the
.Pa patches
directory, it is compared with its backup file
.Pq Pa patch-foo.orig
using
.Xr diff 1 .
If no relevant differences are found, the original patch is restored.
.Sh SEE ALSO
.Xr diff 1 ,
.Xr patchdiff 1 ,
.Xr pkgdiff 1
