.\"	$NetBSD: pkgdiff.1,v 1.4 2003/06/14 19:12:41 atatat Exp $
.\"
.\" Copyright (c) 2000 by Hubert Feyrer <hubertf@netbsd.org>
.\" All Rights Reserved.  Absolutely no warranty.
.\"
.Dd Jun 14, 2003
.Dt PKGDIFF 1
.Os
.Sh NAME
.Nm pkgdiff
.Nd diff files in a way appropriate for pkgsrc
.Sh SYNOPSIS
.Nm
.Op Ar options
.Ar oldfile
.Ar newfile
.Sh DESCRIPTION
The
.Nm
utility runs
.Xr diff 1
on the named files, and generates output on stdout that is appropriate
to be put as patch file into pkgsrc.  An empty
.Nx
RCS ID is output
first, and some effort is made to ensure that the generated patch does
not include any RCS IDs.
.Pp
.Ar options
can be any options that are allowed for
.Xr diff 1 .
.Sh ENVIRONMENT
.Ss PKGDIFF_FMT
The flags passed to
.Xr diff 1
when generating patches.
If not set, the flags
.Fl u
and
.Fl p
are used.
Though only unified format patches are used in pkgsrc as proper
patches, sometimes it can be useful to have context or plain diffs
available.
.Sh SEE ALSO
.Xr cvs 1 ,
.Xr diff 1 ,
.Xr mkpatches 1 ,
.Xr patch 1 ,
.Xr pkgvi 1
