# $NetBSD: buildlink3.mk,v 1.1 2008/12/29 10:13:12 markd Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CFITSIO_BUILDLINK3_MK:=	${CFITSIO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	cfitsio
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncfitsio}
BUILDLINK_PACKAGES+=	cfitsio
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}cfitsio

.if ${CFITSIO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.cfitsio+=	cfitsio>=3.100
BUILDLINK_PKGSRCDIR.cfitsio?=	../../devel/cfitsio
.endif	# CFITSIO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
