.\"	$NetBSD: cvs_checksum.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH CVS_CHECKSUM 1 "Jan 29, 2008" "" ""
.SH NAME
cvs_checksum \- outputs checksum of all files and their revisions
from the CVS working directory
.SH SYNOPSIS
.BI cvs_checksum " [OPTIONS] [cvsdirs ...]"
.SH DESCRIPTION
.B cvs_checksum
analyses CVS/Entries file and (with -l option) outputs a list of all
files with their revisions in the working CVS directory. By default
checksum is output.
.SH OPTIONS
.TP
.B "-h"
display help message
.TP
.B "-l"
List of files and their revisions are output
.SH ENVIRONMENT
.TP
.B CKSUM
problem for calculating a checksum, By default
the standard utility cksum is used.
.SH EXAMPLES
.VB
cvs_checksum /usr/src/bin/sh
cvs_checksum -l /usr/pkgsrc/devel/libjudy /usr/pkgsrc/x11/xxkb
env CKSUM=md5 cvs_checksum /usr/src/bin/sh
.VE
.SH SEE ALSO
.BR cvs(1) ,
.BR cksum(1) ,
.BR md5(1) ,
.B pkg_summary-utils(7)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
