.\"	$NetBSD: pkg_update_src_summary.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_UPDATE_SRC_SUMMARY 1 "Jan 29, 2008" "" ""
.SH NAME
pkg_update_src_summary \- incrementally updates source pkg_summary
.SH SYNOPSIS
.BI pkg_update_src_summary " [OPTIONS] pkg_src_summary_filename"
.SH DESCRIPTION
.B pkg_update_src_summary
incrementally updates source packages summary about all packages in
pkgsrc source tree.
Algorithm. 1) pkg_update_src_summary quickly obtains micro summary
information about all packages
from pkgsrc source tree, "micro" means PKGNAME and PKGPATH fields only.
2) compares package versions in summary_filename
and micro summary collected in step 1
by PKGNAME field using pkg_cmp_summary(1).
3) copies summary from summary_filename about unchanged packages.
4) collects full summary information about all changed and new packages
using pkg_src_summary(1).
5) new summary = step3 + step4
.SH OPTIONS
.TP
.B "-h"
display help message
.TP
.BI "-f" " filename"
package names are obtained from a specified file, not from pkgsrc tree
.TP
.BI "-i" " fields"
list of fields (separated by space character or comma) to be
generated. By default full summary is generated, see
pkg_src_summary(1)
.SH ENVIRONMENT
.TP
.B PKGSRCDIR
pkgsrc root directory
.TP
.B BMAKE
path to pkgsrc friendly make utility
.TP
.B PSS_OPTIONS
passed to pkg_src_summary subprocesses
.SH EXAMPLES
.VB
pkg_update_src_summary /usr/pkgsrc/pkg_src_summary.txt
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_cmp_summary(1)
.B pkg_src_summary(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
