.\"	$NetBSD: pkg_lint_summary.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_LINT_SUMMARY 1 "Feb 10, 2010" "" ""
.SH NAME
pkg_lint_summary \- attempts to detect problems in input summaries
.SH SYNOPSIS
.BI pkg_lint_summary " [OPTIONS] [files...]"
.SH DESCRIPTION
.B pkg_lint_summary
attempts to detect problems in input summaries.
.SH OPTIONS
.TP
.B "-h"
display help message
.TP
.B "-l"
analyses REQUIRES/PROVIDES fields of pkg_summary(5) given on
input. Format of the output:
.VB

   l: not_found SO_LIBRARY PKGPATH PKGNAME

.VE
This means that the package PKGNAME from PKGPATH requires SO_LIBRARY but
there is no package that provide it.
Sample of usage:
.VB

   # pkg_info -Xa | pkg_lint_summary -l
   l: not_found /usr/pkg/lib/libmaa.so.2 wip/dict dict-1.11.2
   l: not_found /usr/pkg/lib/libz.so.1 wip/dict dict-1.11.2
   l: not_found /usr/pkg/lib/libz.so.1 wip/dictd dictd-1.11.2
   #

.VE
.TP
.B "-L"
checks that files listed in REQUIRES exist. Format of the output:
.VB

   L: not_found SO_LIBRARY PKGPATH PKGNAME

.VE
This means that the package PKGNAME from PKGPATH requires file ABSENT but
it doesn't exist.
Sample of usage:
.VB

   # pkg_delete -f libmaa
   # pkg_info -Xa | pkg_lint_summary -L
   L: not_found /usr/pkg/lib/libmaa.so.2 textproc/dict dict-1.11.2
   L: not_found /usr/pkg/lib/libmaa.so.2 textproc/dictd dictd-1.11.2
   L: not_found /usr/pkg/lib/libmaa.so.2 wip/paexec paexec-0.15.0
   #

.VE
.TP
.B "-d"
checks that ALL required DEPENDS are present and their versions
are good to satisfy requirements. Format of the output:
.VB

   d: not_found ABSENT <- PKGPATH PKGBASE

.VE
This means that the package PKGBASE from PKGPATH requires package ABSENT but
it is absent in input summary or requirements are not satisfied.
Sample of usage:
.VB

   # pkg_delete -f gtk2+
   # pkg_delete -f paexec
   # pkg_info -Xa | pkg_lint_summary -d
   d: not_found gtk2+ <- net/avahi avahi
   d: not_found gtk2+ <- devel/xulrunner xulrunner
   d: not_found gtk2+ <- graphics/graphviz graphviz
   d: not_found paexec <- wip/distbb distbb
   d: not_found gtk2+ <- www/firefox firefox
   d: not_found gtk2+ <- devel/libglade libglade
   d: not_found gtk2+ <- www/nspluginwrapper nspluginwrapper
   #

.VE
.TP
.B "-D"
the same as "-d" but for BUILD_DEPENDS
.TP
.B "-c"
summary given on input is analysed for CONFLICTS, found conflicts are
output in the following format:
.VB

   c: conflict CNFLCT_REQD CNFLCT_PATH CNFLCT_NAME <- PKGPATH PKGBASE

.VE
.TP
.B "-u"
check unicity of PKGBASE of packages given on input and outputs found
problems to stderr in the following format:
.VB

   u: unicity PKGBASE <- PKGPATH1 PKGPATH2 ... PKGPATHn

.VE
.SH EXIT STATUS
Non-zero value if errors were encountered, zero otherwise.
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.BR pkg_src_summary(1) ,
.BR pkg_info(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
