.\"	$NetBSD: pkg_cleanup_distdir.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_CLEANUP_DISTDIR 1 "Jan 29, 2008" "" ""
.SH NAME
PKG_CLEANUP_DISTDIR \- cleanups DISTDIR directory
.SH SYNOPSIS
.BI pkg_cleanup_distdir " [OPTIONS] [files ...]"
.SH DESCRIPTION
.B pkg_cleanup_distdir
analyses ALLSRCFILES field of pkg_src_summary given on input and
outputs list of files found in DISTDIR that are not referenced
by any package.
With option
.B "-r"
it removes all those files and empty subdirectories.
.SH OPTIONS
.TP
.B "-h"
display help message
.TP
.BI "-r"
Remove unreferenced files and empty subdirectories
.SH ENVIRONMENT
.TP
.B DISTDIR
Directory that contains distfiles
.SH EXAMPLES
.VB
pkg_cleanup_distdir -r /usr/pkgsrc/pkg_src_summary.txt
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.B pkg_summary(5)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
