.\"	$NetBSD: pkg_bin_summary.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_BIN_SUMMARY 1 "Nov 7, 2010" "" ""
.SH NAME
.B pkg_bin_summary
wrapper for pkg_info that outputs a package summary
.SH SYNOPSIS
.BI pkg_bin_summary " [OPTIONS] [-- [PKG_INFO_ARGS]] [packages...]"
.SH DESCRIPTION
.B pkg_bin_summary
is a wrapper for 'pkg_info -X' that outputs
build information and installation information
variables as well some special variables for installed or binary packages,
e.g. ASSIGNMENTS (settings to build multivariant packages), PLIST (a list of files
of the package) and
REQUIREDBY. By default it is equivalent to pkg_info -Xa.
.SH OPTIONS
.TP
.B "-h"
Display help message.
.TP
.B "-a <fields>"
add to the output the specified fields,
fields are separated by space or comma.
.TP
.B "-f <fields>"
output only specified fields,
fields are separated by space or comma.
.TP
.B "-r <fields>"
remove from output the specified fields,
fields are separated by space or comma.
.TP
PKG_INFO_ARGS are
options passed to pkg_info(1) that default to -a.
In addition to these options -X is always applied to pkg_info
as well as -B if needed. "--" is required
if PKG_INFO_ARGS is not empty.
.SH EXAMPLES
.VB
  pkg_bin_summary -f PKGNAME,automatic,REQUIREDBY |
  pkg_grep_summary -e REQUIREDBY |
  pkg_grep_summary -s automatic yes

  pkg_bin_summary -a automatic,ASSIGNMENTS

  pkg_bin_summary -r 'DESCRIPTION REQUIRES PROVIDES' -- -u

  pkg_bin_summary -a automatic -r REQUIRES 'lib*'

  pkg_bin_summary -f PKGNAME,PKGPATH,DEPENDS,BUILD_DEPENDS,ASSIGNMENTS |
  pkg_summary2deps -pdt |
  tsort
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
