.\"	$NetBSD: pkg_micro_src_summary.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_MICRO_SRC_SUMMARY 1 "Jan 29, 2008" "" ""
.SH NAME
pkg_micro_src_summary \- build micro summary for source packages
.SH SYNOPSIS
.BI pkg_micro_src_summary " [OPTIONS] [category1/pkg1 category2/pkg2 ...]"
.SH DESCRIPTION
.B pkg_micro_src_summary
builds micro summary information about source packages specified in
arguments or read from stdin (one package per line).  The word micro
means that only PKGNAME and PKGPATH fields (by default) are
generated. Format of this summary is the same as used in
pkg_summary(5) built from binary packages. The main advantage of this
utility is that is works DRAMMATICALLY faster than pkg_src_summary(1)
in most cases.  This is possible because special hack is used (only
when it is possible!) to fetch variables values instead of running
make. And for ~90% of all packages (pkgsrc + wip) it is possible to
use this hack and fallback to make for other ~10%. As a result
pkg_micro_src_summary works approximately 10 times faster than using
make for all packages.
.SH OPTIONS
.TP
.BR "-h"
display help message
.TP
.BI "-f" " fields"
A list of fields (separated by space character) to be generated. By
default the following fields are generated: PKGNAME, PKGPATH.  Fields
here are actually Makefile's variable names and should be fetchable by
pkg_src_fetch_var from Makefile itself, for example, COMMENT,
MAINTAINER etc., but not PLIST, DESCRIPTION, GZIP_CMD or similar.
.SH ENVIRONMENT
.TP
.B PKGSRCDIR
pkgsrc root directory
.TP
.B BMAKE
path to pkgsrc friendly make utility
.SH EXAMPLES
.VB
pkg_micro_src_summary wip/dict-server wip/dict-mueller7 x11/xxkb
printf 'wip/dict-server\\ntextproc/dictem\\n' | pkg_micro_src_summary
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_src_summary(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
