.\"	$NetBSD: pkg_summary2build_graph.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (cheusov@tut.by)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_SUMMARY2BUILD_GRAPH 1 "Jan 29, 2008" "" ""
.SH NAME
.B pkg_summary2build_graph
converts src_summary to build dependency graph
.SH SYNOPSIS
.BI pkg_summary2build_graph " [files...]"
.SH DESCRIPTION
.B pkg_summary2build_graph
converts src_summary to build dependency graph analysing
{alter,native}:../../dep/endencies entries in DEPENDS and
BUILD_DEPENDS fields.  Format of the output:
.VB
   package2 package3
   package1
   ...
.VE
Here package1 has no dependencies and package3 depends on package2.
.SH EXAMPLES
.VB
pkg_list_all_pkgs | pkg_src_summary | pkg_summary2build_graph
pkg_src_summary -A wip/distbb | pkg_summary2build_graph
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.BR pkg_src_summary(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
