.\"	$NetBSD: pkg_summary2leaves.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_SUMMARY2LEAVES 1 "Jan 2, 2011" "" ""
.SH NAME
.B pkg_summary2leaves
output leaf packages
.SH SYNOPSIS
.BI pkg_summary2leaves " [OPTIONS] file1 [file2...]"
.SH DESCRIPTION
.B pkg_summary2leaves
takes package summaries on input
and outputs summaries for leaf packages.
.SH OPTIONS
.TP
.B "-h"
Display help message.
.TP
.B "-r"
Select leaf packages recursively, implies -a.
.TP
.B "-a"
Output automatically installed leaves only,
a field 'automatic' is expected on input.
.TP
.B "-p"
Output PKGPATHs instead of summaries.
.TP
.B "-v"
Invert the sense of match.
.SH EXAMPLES
.VB
   pkg_bin_summary -f PKGPATH,automatic >summaries.txt; \\
   pkg_summary2leaves summaries.txt
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
