.\"	$NetBSD: pkg_uniq_summary.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_UNIQ_SUMMARY 1 "Feb 10, 2008" "" ""
.SH NAME
pkg_uniq_summary \- filter out repeated package summaries
.SH SYNOPSIS
.BI pkg_uniq_summary " [OPTIONS] [files...]"
.SH DESCRIPTION
.B pkg_uniq_summary
filters out repeated package summaries.
Summaries are compared by (PKGPATH, PKGBASE, ASSIGNMENTS) triple.
.SH OPTIONS
.TP
.B "-h"
display help message.
.TP
.B "-n"
only PKGBASE field of packages are compared.
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.BR pkg_src_summary(1) ,
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
