.\"	$NetBSD: pkg_digger.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_DIGGER 1 "Nov 22, 2010" "" ""
.SH NAME
pkg_digger \- package searcher for PkgSrc
.SH SYNOPSIS
.BI pkg_digger " -h"
.br
.BI pkg_digger " -f"
.br
.BI pkg_digger " -s"
.br
.BI pkg_digger " [-1|-3-9|-i] [-r] [-q] query1 [query2 ...]"
.SH DESCRIPTION
.B pkg_digger
is a package searcher for PkgSrc. Unlike other searchers
it scans (by default) prebuilt package summary file, but the pkgsrc tree
thus working much faster.
.I Query
is either
.IR field ":" strategy ":" "text"
or just
.IR text ,
for example,
.IR PKGNAME:substring:dict " or " dictionary .
.I Field
means field to search in listed by 
.IR -f .
.I Strategy
means search strategy listed by 
.IR -s .
If neither field nor strategy are specified, those listed
in PKG_DIGGER_FALLBACK_RULES variable are used.
PKG_DIGGER_FALLBACK_RULES can be set in environment or in configuration file.
Optional leading
.IR - " (minus) or " ! " (exclamation mark)"
invert the sense of match, for example,
.br
COMMENT:word:dictionary -spell -japanese -chinese -korean
.SH OPTIONS
.TP
.B "-h"
display help message
.TP
.B "-s"
display supported search strategies. A list of supported search strategies
are detetermined by backend search program
.br
.RB ( pkg_digger_backend " by default)."
In addition to full search strategy, short single-letter synonyms may be used,
they are determined by
.br
.I pkg_digger_strat__<synonym>
variable set in environment or in configuration file.
.TP
.B "-f"
display supported fields to search in, for example PKGNAME, PKGPATH, COMMENT,
DEPENDS etc.
A list of supported fields
are detetermined by backend search program
.RB ( pkg_digger_backend " by default)."
In addition to full fields, short single-letter synonyms may be used,
they are determined by
.br
.I pkg_digger_field__<synonym>
variable set in environment or in configuration file.
.TP
.B "-1"
only PKGPATH, PKGNAME (if needed) and COMMENT are output (oneline format)
.TP
.B "-3"
only basic fields are output, i.e. PKGNAME, PKGPATH, COMMENT, DESCRIPTION
and some others.
.TP
.B "-9"
all fields present in input are output
.TP
.B "-r"
output raw summary,
.I "-r"
requires either
.IR -3 " or " -9 .
.TP
.B "-q"
quiet mode, do not print "No matches found" to stderr
.BR pkg_digger .
.SH ENVIRONMENT
.TP
.B PKG_DIGGER_BACKEND
backend searcher. Possible values:
.IR pkg_digger_backend " (the default), " pkg_online_client .
.TP
.B PKG_DIGGER_SUMMARY
Path to package summary file. Actually this is
.br
.BR pkg_digger_backend "'s variable"
.SH EXAMPLES
.VB
  export PKG_DIGGER_SUMMARY=/usr/pkgsrc/packages/pkg_summary.txt
  pkg_digger -h
  pkg_digger -s
  pkg_digger -f
  pkg_digger DEPENDS:substring:libmaa
  pkg_digger PKGNAME:prefix:dict
  pkg_digger COMMENT:word:dns PKGPATH:prefix:net
  pkg_digger c:kw:'dns server'
  pkg_digger n:p:lua
  pkg_digger ::emacs
  pkg_digger -9 lang/mawk
  pkg_digger oberon
  pkg_digger dns server
  pkg_digger -3 dictionary -spell -japanese -chinese -korean
  pkg_digger -q9r spreadsheet
  pkg_digger FILE_SIZE:awk:'fvalue+0 > 100000000'

  export PKG_DIGGER_BACKEND=pkg_online_client
  export PKG_ONLINE_SERVER=dictd.xdsl.by
  export PKG_ONLINE_PORT=26280
  pkg_digger -s
  pkg_digger -f
  pkg_digger -9 mawk -p:p:wip/
  pkg_digger m:p:joerg
  pkg_digger bulk build
  pkg_digger dictionary -spell -japanese -chinese -korean
.VE
.SH FILES
.TP
.IR "~/.pkg_digger" ", " SYSCONFDIR/pkg_digger.conf
configuration file
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.BR pkg_grep_summary(1) ,
.BR pkg_online_client(1) ,
.B pkg_digger_backend(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
