.\"	$NetBSD: pkg_list_all_pkgs.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_LIST_ALL_PKGS 1 "Jan 29, 2008" "" ""
.SH NAME
pkg_list_all_pkgs \- list all packages in pkgsrc source tree
.SH SYNOPSIS
.BI pkg_list_all_pkgs " [OPTIONS]"
.SH DESCRIPTION
.B pkg_list_all_pkgs
analyses /usr/pkgsrc/Makefile file (SUBDIR
variable defined there) and outputs all available packages
in category/directory format. One package per line.
.SH OPTIONS
.TP
.B "-h"
display help message
.SH ENVIRONMENT
.TP
.B PKGSRCDIR
pkgsrc root directory
.TP
.B BMAKE
path to pkgsrc friendly make utility
.SH EXAMPLES
.VB
pkg_list_all_pkgs
.VE
.SH "SEE ALSO"
.B pkg_summary-utils(7)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
