.\"	$NetBSD: pkg_summary4view.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2008-2010 by Aleksey Cheusov (cheusov@tut.by)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_SUMMARY4VIEW 1 "Jan 29, 2008" "" ""
.SH NAME
.B pkg_summary4view
converts pkg_summary(5) to human readable format
.SH SYNOPSIS
.BI pkg_summary4view " [files...]"
.SH DESCRIPTION
.B pkg_summary4view
converts package summary (pkg_summary(5)) to the format
easily read by human but still easily parsable by standard UNIX utilities.
An empty line separates packages.
.SH EXAMPLES
.VB
pkg_src_summary textproc/dictem | pkg_summary4view
zcat pkg_summary.gz | pkg_summary4view
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.BR pkg_src_summary(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
