.\"	$NetBSD: pkg_update_summary.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2007-2010 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_UPDATE_SUMMARY 1 "Aug 2, 2007" "" ""
.SH NAME
pkg_update_summary \- update, or create a summary file (pkg_summary(5))
.SH SYNOPSIS
.BI pkg_update_summary " summary_file bin_pkg_dir [decompress compress]"
.SH DESCRIPTION
.B pkg_update_summary
updates (or creates if it does not exist)
summary information about binary packages 
and stores it in
.I summary_file
file. That is
.B pkg_update_summary
checks
whether
.I bin_pkg_dir
directory contains binary packages (files) newer than
.I summary_file
file.
If they exist, it updates the summary. NOTE: modification time of
the binary package file is checked, not the content of the package.
Also
.B pkg_update_summary
removes from 
.I summary_file
the information about packages removed from 
.I bin_pkg_dir
directory.
.PP
The options are as follows:
.SH OPTIONS
.TP
.B "-h"
display help message
.TP
.B "-r"
only newest versions for each PKGPATH:PKGBASE pair is kept in summary
.SH ENVIRONMENT
.TP
.B PKG_SUFX
Binary package extension (either .tgz or .tbz).
.TP
.B TEST_CMD
Solaris's test command does not like option -nt, defaults to 'test'
.TP
.B PKG_INFO_CMD
Path to pkg_info command
.SH EXAMPLES
.VB
pkg_update_summary /srv/packages/All/pkg_summary.txt /srv/packages/All
pkg_update_summary /dir/pkg_summary.gz /dir 'gzip -dc' 'gzip -c'
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
