.\"	$NetBSD: pkg_subgraph_deps.1,v 1.1.1.1 2011/05/11 19:24:47 cheusov Exp $
.\"
.\" Copyright (c) 2010 by Aleksey Cheusov (cheusov@tut.by)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_SUBGRAPH_DEPS 1 "Nov 7, 2010" "" ""
.SH NAME
.B pkg_subgraph_deps
takes a dependency graph of packages on input and outputs subgraph
.SH SYNOPSIS
.BI pkg_subgraph_deps " [OPTIONS] [files...]"
.SH DESCRIPTION
.B pkg_subgraph_deps
takes a dependency graph of packages on input and outputs a subgraph
consisting of dependent (by default) packages, that is packages that depend
on listed ones directly or indirectly. Sample of input is below
.VB

   jpeg emacs
   tiff emacs
   libXaw emacs
   libXpm emacs
   libungif emacs
   png emacs
   perl emacs
   jpeg tiff
   perl libungif
   libjudy
   runawk

.VE
.SH OPTIONS
.TP
.B "-h"
Display help message.
.TP
.B "-f <file>"
Specify a filename that contains packages, one package per line.
.TP
.B "-p <packages>"
Specify packages separated by space character.
.TP
.B "-r"
By default dependent packages are output.
With this option dependencies are output.
.TP
.B "-x"
By default packages specified with a help of -p or -f options are output.
With this option they are skipped.
.TP
.B "-n"
Output only packages without information about dependencies between them.
.TP
.B "-v"
Invert condition.
.TP
.B "-t"
Produce output compatible with
.B tsort(1)
command
.SH EXAMPLES
.VB
pkg_info -Xa | pkg_summary2deps -nd |
pkg_subgraph_deps -xr -p 'graphviz emacs'
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_summary(5) ,
.BR tsort(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
