# $NetBSD: buildlink3.mk,v 1.2 2024/01/05 01:53:35 taca Exp $

BUILDLINK_TREE+=	bind

.if !defined(BIND_BUILDLINK3_MK)
BIND_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.bind+=	bind>=9.18.0
BUILDLINK_ABI_DEPENDS.bind?=	bind>=9.18.21
BUILDLINK_PKGSRCDIR.bind?=	../../net/bind918
.endif # BIND_BUILDLINK3_MK

BUILDLINK_TREE+=	-bind
