# $NetBSD: Makefile,v 1.14 2020/08/31 18:11:51 wiz Exp $
#

DISTNAME=		Number-Spell-0.04
PKGNAME=		p5-${DISTNAME}
PKGREVISION=		11
CATEGORIES=		textproc perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=Number/}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		https://metacpan.org/release/Number-Spell
COMMENT=		Perl extension for spelling out numbers

PERL5_PACKLIST=		auto/Number/Spell/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
