# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 22:39:10 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBDFUI_BUILDLINK3_MK:=	${LIBDFUI_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdfui
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdfui}
BUILDLINK_PACKAGES+=	libdfui
BUILDLINK_ORDER+=	libdfui

.if !empty(LIBDFUI_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libdfui+=	libdfui>=4.1
BUILDLINK_PKGSRCDIR.libdfui?=	../../devel/libdfui
.endif	# LIBDFUI_BUILDLINK3_MK

.include "../../devel/libaura/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
