#!/usr/bin/perl
#

eval '(exit $?0)' && eval 'exec /usr/bin/perl -S $0 ${1+"$@"}'
& eval 'exec /usr/bin/perl -S $0 $argv:q'
if 0;

if( $> ) {
	print "\nYou must be root to run this step!\n\n";
	exit 1;
} 

@ARGV = "backup" unless @ARGV;

$backup = $ARGV[0];

if( getpwnam( $backup ) ) {
	( $null, $null, $newUID ) = getpwnam( $backup );
	$addname = 0;
} else {
	$newUID = 70;
	while( getpwuid( $newUID ) ) {
		$newUID++;
	}
	$addname = 1;
}

if( getgrnam( $backup ) ) {
	( $null, $null, $newGID ) = getgrnam( $backup );
} else {
	$newGID = 70;
	while( getgrgid( $newGID ) ) {
		$newGID++;
	}
	&append_file( "/etc/group", "${backup}:*:${newGID}:" );
}

print "Amanda user $backup using uid $newUID\n";
print "Amanda user $backup using gid $newGID\n";

if ($addname) {
	system( "/usr/bin/chpass -a \"$backup:*************:${newUID}:${newGID}::0:0:Amanda backup user:$ENV{'PREFIX'}/$backup:/bin/sh\"" );
}

sub append_file {
	local($file,@list) = @_;
	local($LOCK_EX) = 2;
	local($LOCK_NB) = 4;
	local($LOCK_UN) = 8;

	open(F, ">> $file") || die "$file: $!\n";
	while( ! flock( F, $LOCK_EX | $LOCK_NB ) ) {
		exit 1;
	}
	print F join( "\n", @list) . "\n";
	close F;
	flock( F, $LOCK_UN );
}
