# $NetBSD: Makefile,v 1.1.1.1 2000/12/17 23:32:21 wiz Exp $
#

DISTNAME=	wmMoonClock-1.27
CATEGORIES=	x11 time
MASTER_SITES=	http://nis-www.lanl.gov/~mgh/WindowMaker/

MAINTAINER=	tron@netbsd.org
HOMEPAGE=	http://nis-www.lanl.gov/~mgh/WindowMaker/DockApps.shtml

USE_GMAKE=	YES
USE_X11BASE=	YES
USE_XPM=	YES
WRKSRC=         ${WRKDIR}/${DISTNAME}/Src

.include "../../mk/bsd.pkg.mk"
