# $NetBSD: Makefile,v 1.55 2025/06/15 10:55:55 taca Exp $

MODNAME=		xdebug
PECL_VERSION=		3.4.4
CATEGORIES=		devel
EXTRACT_SUFX=		.tgz

MAINTAINER=		jdolecek@NetBSD.org
HOMEPAGE=		https://xdebug.org/
COMMENT=		PHP extension for debugging
LICENSE=		php

PHP_ZEND_EXTENSION=	yes

PHP_VERSIONS_ACCEPTED=	81 82 83

.include "../../lang/php/ext.mk"
.include "../../mk/bsd.pkg.mk"
