# $NetBSD: buildlink3.mk,v 1.1 2004/04/24 22:53:55 snj Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSNERT_BUILDLINK3_MK:=	${LIBSNERT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libsnert
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsnert}
BUILDLINK_PACKAGES+=	libsnert

.if !empty(LIBSNERT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libsnert+=	libsnert>=1.23
BUILDLINK_PKGSRCDIR.libsnert?=	../../mail/libsnert
BUILDLINK_DEPMETHOD.libsnert?=	build
.endif	# LIBSNERT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
