# $NetBSD: buildlink3.mk,v 1.6 2007/12/30 14:34:18 obache Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PCREXX_BUILDLINK3_MK:=	${PCREXX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pcrexx
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npcrexx}
BUILDLINK_PACKAGES+=	pcrexx
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pcrexx

.if !empty(PCREXX_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.pcrexx+=	pcre++>=0.9.5
BUILDLINK_PKGSRCDIR.pcrexx?=	../../devel/pcre++
.endif	# PCREXX_BUILDLINK3_MK

.include "../../devel/pcre/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
