# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/12/30 11:56:01 rh Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
EDCOMMON_BUILDLINK3_MK:=	${EDCOMMON_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	edcommon
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nedcommon}
BUILDLINK_PACKAGES+=	edcommon

.if !empty(EDCOMMON_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.edcommon+=	edcommon>=32
BUILDLINK_PKGSRCDIR.edcommon?=	../../devel/edcommon
.endif	# EDCOMMON_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
