# $NetBSD: buildlink3.mk,v 1.2 2006/01/24 07:32:01 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
EDCOMMON_BUILDLINK3_MK:=	${EDCOMMON_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	edcommon
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nedcommon}
BUILDLINK_PACKAGES+=	edcommon

.if !empty(EDCOMMON_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.edcommon+=	edcommon>=32
BUILDLINK_RECOMMENDED.edcommon?=	edcommon>=32nb1
BUILDLINK_PKGSRCDIR.edcommon?=	../../devel/edcommon
.endif	# EDCOMMON_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
