# $NetBSD: Makefile,v 1.30 2014/05/16 07:59:34 tron Exp $

PKGREVISION=	29
CATEGORIES=	editors

CONFLICTS+=	emacs21-nox11-[0-9]*

USE_TOOLS+=	imake

.include "options.mk"

.include "../../editors/emacs21/Makefile.common"

.include "../../mk/bsd.pkg.mk"
