# $NetBSD: buildlink3.mk,v 1.1 2007/07/29 21:34:31 seb Exp $

BUILDLINK_DEPMETHOD.flow-tools?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FLOW_TOOLS_BUILDLINK3_MK:=	${FLOW_TOOLS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	flow-tools
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nflow-tools}
BUILDLINK_PACKAGES+=	flow-tools
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}flow-tools

.if ${FLOW_TOOLS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.flow-tools+=	flow-tools>=0.68nb2
BUILDLINK_PKGSRCDIR.flow-tools?=	../../net/flow-tools
.endif	# FLOW_TOOLS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
