# $NetBSD: Makefile,v 1.20 2001/10/20 22:21:49 jlam Exp $
#

COMMENT=	communication programs

SUBDIR+=	bitchx
SUBDIR+=	blackened
SUBDIR+=	bnc
SUBDIR+=	dircproxy
SUBDIR+=	epic4
SUBDIR+=	fugu
SUBDIR+=	gaim
SUBDIR+=	gale
SUBDIR+=	gnomeicu
SUBDIR+=	icb
SUBDIR+=	icqlib
SUBDIR+=	ircII
SUBDIR+=	irchat
SUBDIR+=	ircu
SUBDIR+=	irssi
SUBDIR+=	kicq
SUBDIR+=	kxicq
SUBDIR+=	kyahoo
SUBDIR+=	libirc
SUBDIR+=	libyahoo
SUBDIR+=	micq
SUBDIR+=	sirc
SUBDIR+=	tik
SUBDIR+=	tirc
SUBDIR+=	tkicb
SUBDIR+=	tkirc
SUBDIR+=	tkirc2
SUBDIR+=	xchat
SUBDIR+=	ymessenger
SUBDIR+=	zenicb
SUBDIR+=	zenirc
SUBDIR+=	zircon

.include "../mk/bsd.pkg.subdir.mk"
