# $NetBSD: Makefile,v 1.6 2023/10/09 04:54:23 pho Exp $

DISTNAME=	microlens-th-0.4.3.11
PKGREVISION=	2
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Automatic generation of record lenses for microlens
LICENSE=	modified-bsd

.include "../../devel/hs-microlens/buildlink3.mk"
.include "../../devel/hs-th-abstraction/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
