# $NetBSD: Makefile,v 1.1 2022/02/24 01:02:19 pho Exp $

DISTNAME=	basic-prelude-0.7.0
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Enhanced core prelude; a common foundation for alternate preludes
LICENSE=	mit

.include "../../devel/hs-hashable/buildlink3.mk"
.include "../../devel/hs-unordered-containers/buildlink3.mk"
.include "../../devel/hs-vector/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
