# $NetBSD: buildlink3.mk,v 1.1 2008/01/09 03:53:10 smb Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBYTNEF_BUILDLINK3_MK:=	${LIBYTNEF_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libytnef
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibytnef}
BUILDLINK_PACKAGES+=	libytnef
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libytnef

.if ${LIBYTNEF_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libytnef+=	libytnef>=1.5
BUILDLINK_PKGSRCDIR.libytnef?=	../../mail/libytnef
.endif	# LIBYTNEF_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
