# $NetBSD: buildlink3.mk,v 1.7 2005/06/01 18:03:30 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RENDER_BUILDLINK3_MK:=	${RENDER_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	render
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nrender}
BUILDLINK_PACKAGES+=	render

.if !empty(RENDER_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.render+=	render>=0.2
BUILDLINK_PKGSRCDIR.render?=	../../x11/render
BUILDLINK_DEPMETHOD.render?=	build
.endif	# RENDER_BUILDLINK3_MK

.include "../../mk/x11.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
