# $NetBSD: buildlink3.mk,v 1.6 2004/03/10 17:57:15 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RENDER_BUILDLINK3_MK:=	${RENDER_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	render
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nrender}
BUILDLINK_PACKAGES+=	render

.if !empty(RENDER_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.render+=	render>=0.2
BUILDLINK_PKGSRCDIR.render?=	../../x11/render
BUILDLINK_DEPMETHOD.render?=	build

USE_X11=	yes

.endif	# RENDER_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
