# $NetBSD: buildlink3.mk,v 1.9 2006/07/08 23:11:05 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PVM_BUILDLINK3_MK:=	${PVM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pvm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npvm}
BUILDLINK_PACKAGES+=	pvm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pvm

.if !empty(PVM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.pvm+=		pvm>=3.4.3
BUILDLINK_ABI_DEPENDS.pvm+=	pvm>=3.4.5nb1
BUILDLINK_PKGSRCDIR.pvm?=	../../parallel/pvm3

.  include "${BUILDLINK_PKGSRCDIR.pvm}/arch.mk"
BUILDLINK_INCDIRS.pvm?=		pvm3/include
BUILDLINK_LIBDIRS.pvm?=		pvm3/lib/${PVM_ARCH}

.endif	# PVM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
