# $NetBSD: buildlink3.mk,v 1.2 2004/03/05 19:25:39 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PVM_BUILDLINK3_MK:=	${PVM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pvm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npvm}
BUILDLINK_PACKAGES+=	pvm

.if !empty(PVM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pvm+=		pvm>=3.4.3
BUILDLINK_PKGSRCDIR.pvm?=	../../parallel/pvm3
.endif	# PVM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
