# $NetBSD: Makefile,v 1.28 2005/10/07 22:52:21 wulf Exp $
#

COMMENT=	Collections of other packages

SUBDIR+=	XFree86
SUBDIR+=	boost
SUBDIR+=	fxtv-capture
SUBDIR+=	gnome
SUBDIR+=	gnome-base
SUBDIR+=	gnome-devel
SUBDIR+=	gnuradio
SUBDIR+=	gnustep
SUBDIR+=	gtk2-extras
SUBDIR+=	kde3
SUBDIR+=	netbsd-doc
SUBDIR+=	netbsd-doc-print
SUBDIR+=	netbsd-www
SUBDIR+=	php4-extensions
SUBDIR+=	php5-extensions
SUBDIR+=	suse9
SUBDIR+=	web-server
SUBDIR+=	windowmaker-desktop
SUBDIR+=	xfce4
SUBDIR+=	xfce4-extras
SUBDIR+=	xorg

.include "../mk/bsd.pkg.subdir.mk"
