$NetBSD: patch-contrib_chem_Makefile.sub,v 1.1 2013/09/19 10:11:47 fhajny Exp $

Drop unneeded targets that break bmake.
--- contrib/chem/Makefile.sub.orig	2009-01-09 14:25:52.000000000 +0000
+++ contrib/chem/Makefile.sub
@@ -52,8 +52,7 @@ chem: $(srcdir)/chem.pl $(SH_DEPS_SED_SC
 
 install_data: chem \
               README examples/README \
-              $(srcdir)/chem.pic \
-              $(srcdir)/examples/*.chem $(srcdir)/examples/122/*
+              $(srcdir)/chem.pic
 	-test -d $(DESTDIR)$(bindir) || $(mkinstalldirs) $(DESTDIR)$(bindir)
 	$(RM) $(DESTDIR)$(bindir)/$(g)chem
 	$(INSTALL_SCRIPT) chem $(DESTDIR)$(bindir)/$(g)chem
