$NetBSD: patch-src_preproc_eqn_eqn.ypp,v 1.1 2020/03/30 19:32:24 joerg Exp $

--- src/preproc/eqn/eqn.ypp.orig	2020-03-29 11:19:42.584035045 +0000
+++ src/preproc/eqn/eqn.ypp
@@ -16,6 +16,10 @@ for more details.
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>. */
 %{
+#ifdef HAVE_CONFIG_H
+# include "config.h"
+#endif
+
 #include <stdio.h>
 #include <string.h>
 #include <stdlib.h>
