# $NetBSD: Makefile,v 1.2 2010/04/15 22:52:21 minskim Exp $
# TeX Live Revision 15878

DISTNAME=	tools.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-tools

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
