# $NetBSD: buildlink3.mk,v 1.1 2008/10/06 07:24:31 uebayasi Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RIECE_BUILDLINK3_MK:=	${RIECE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	riece
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nriece}
BUILDLINK_PACKAGES+=	riece
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}riece

.if ${RIECE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.riece+=	${EMACS_PKGNAME_PREFIX}riece>=4
BUILDLINK_PKGSRCDIR.riece?=	../../chat/riece
.endif	# RIECE_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.riece=	${EGREP} '.*\.el$$|.*\.elc$$'

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
