# $NetBSD: Makefile,v 1.2 2024/05/09 01:32:40 pho Exp $

DISTNAME=	clay-0.15.0
PKGREVISION=	1
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://fvisser.nl/clay/
COMMENT=	CSS preprocessor as embedded Haskell
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
