# $NetBSD: Makefile,v 1.5 2023/02/07 01:40:27 pho Exp $

DISTNAME=	auto-update-0.1.6
PKGREVISION=	4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficiently run periodic, on-demand actions
LICENSE=	mit

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
