package lib

const SQLITE_BUSY = 5
const SQLITE_LOCKED = 6
const SQLITE_CONSTRAINT = 19
const SQLITE_BUSY_RECOVERY = 261
const SQLITE_LOCKED_SHAREDCACHE = 262
const SQLITE_BUSY_SNAPSHOT = 517
const SQLITE_BUSY_TIMEOUT = 773
const SQLITE_CONSTRAINT_PRIMARYKEY = 1555
const SQLITE_CONSTRAINT_UNIQUE = 2067
