# $NetBSD: Makefile,v 1.10 2020/11/05 09:08:40 ryoon Exp $

DISTNAME=	kdeedu-data-${KAPPSVER}
PKGREVISION=	2
CATEGORIES=	misc

HOMEPAGE=	https://kde.org/applications/education/
COMMENT=	Common data for KDE Edu applications
LICENSE=	gnu-gpl-v2

.include "../../meta-pkgs/kde/applications.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../x11/qt5-qtbase/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
