# $NetBSD: buildlink3.mk,v 1.1 2007/02/01 19:07:24 drochner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CHECK_BUILDLINK3_MK:=	${CHECK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	check
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncheck}
BUILDLINK_PACKAGES+=	check
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}check

.if ${CHECK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.check+=	check>=0.9.5
BUILDLINK_PKGSRCDIR.check?=	../../devel/check
.endif	# CHECK_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
