# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 19:53:21 joerg Exp $

BUILDLINK_DEPMETHOD.printproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PRINTPROTO_BUILDLINK3_MK:=	${PRINTPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	printproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nprintproto}
BUILDLINK_PACKAGES+=	printproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}printproto

.if ${PRINTPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.printproto+=	printproto>=1.0.3
BUILDLINK_PKGSRCDIR.printproto?=	../../x11/printproto
.endif	# PRINTPROTO_BUILDLINK3_MK

.include "../../x11/xproto/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
