# $NetBSD: Makefile,v 1.5 2006/02/05 23:10:03 joerg Exp $
#

DISTNAME=	fpconst-0.7.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
PKGREVISION=	1
CATEGORIES=	math python
MASTER_SITES=	http://www.analytics.washington.edu/~warnes/fpconst/

MAINTAINER=	recht@NetBSD.org
HOMEPAGE=	http://www.analytics.washington.edu/statcomp/projects/rzope/fpconst/
COMMENT=	IEEE 754 floating point special handling for Python

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
