# $NetBSD: buildlink3.mk,v 1.5 2006/04/12 10:27:05 rillig Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_LDAP_BUILDLINK3_MK:=	${PY_LDAP_BUILDLINK3_MK}+

.include "../../lang/python/pyversion.mk"

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pyldap
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npyldap}
BUILDLINK_PACKAGES+=	pyldap

.if !empty(PY_LDAP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.pyldap+=	${PYPKGPREFIX}-ldap>=2.0.10nb1
BUILDLINK_ABI_DEPENDS.pyldap?=	${PYPKGPREFIX}-ldap>=2.0.10nb2
BUILDLINK_PKGSRCDIR.pyldap?=	../../databases/py-ldap
.endif	# PY_LDAP_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
