$NetBSD: patch-pyproject.toml,v 1.2 2026/09/02 14:01:41 adam Exp $

Don't install ndiff.

--- pyproject.toml.orig	2026-08-05 21:12:13.000000000 +0000
+++ pyproject.toml
@@ -24,11 +24,8 @@ Changelog = "https://nmap.org/changelog"
 [project.gui-scripts]
 zenmap = "zenmapGUI.App:run"
 
-[project.scripts]
-ndiff = "ndiff:run_main"
 
 [tool.setuptools]
-py-modules = ["ndiff"]
 include-package-data = true
 
 [tool.setuptools.packages.find]
