# $NetBSD: buildlink3.mk,v 1.2 2009/01/04 00:56:32 adrianp Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
ISC_DHCP_BUILDLINK3_MK:=	${ISC_DHCP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	isc-dhcp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nisc-dhcp}
BUILDLINK_PACKAGES+=	isc-dhcp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}isc-dhcp

.if ${ISC_DHCP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.isc-dhcp+=	isc-dhcp>=4.1.0
BUILDLINK_PKGSRCDIR.isc-dhcp?=	../../net/isc-dhcp4
.endif	# ISC_DHCP_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
