# $NetBSD: Makefile,v 1.11 2024/05/09 01:32:44 pho Exp $

DISTNAME=	prettyprinter-ansi-terminal-1.1.3
PKGREVISION=	7
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	ANSI terminal backend for the "prettyprinter" package
LICENSE=	2-clause-bsd

.include "../../devel/hs-ansi-terminal/buildlink3.mk"
.include "../../textproc/hs-prettyprinter/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
