# $NetBSD: buildlink3.mk,v 1.1 2021/05/04 14:19:51 prlw1 Exp $

BUILDLINK_TREE+=	PEGTL

.if !defined(PEGTL_BUILDLINK3_MK)
PEGTL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.PEGTL+=	PEGTL>=2.8.3
BUILDLINK_PKGSRCDIR.PEGTL?=	../../textproc/PEGTL
BUILDLINK_DEPMETHOD.PEGTL?=	build
.endif	# PEGTL_BUILDLINK3_MK

BUILDLINK_TREE+=	-PEGTL
