.\"	$NetBSD: pkgdepgraph.1,v 1.1.1.1 2002/11/07 23:18:01 atatat Exp $
.\"
.\" Copyright (c) 2002 by Andrew Brown <atatat@netbsd.org>
.\" Absolutely no warranty.
.\"
.Dd November 6, 2002
.Dt PKGDEPGRAPH 1
.Sh NAME
.Nm pkgdepgraph
.Nd visual representation of installed packages
.Sh SYNOPSIS
.Nm
.Op Fl d Ar pkg_dbdir
.Op Fl clov
.Op Pa lintpkgsrc output ...
.Sh DESCRIPTION
.Nm
emits a
.Pa dot
language description of the locally installed packages, with the
inter-dependencies reduced to a minimal set of edges.
It scans each directory under the package database directory for files
named
.Pa +BUILD_INFO
and
.Pa +REQUIRED_BY
in order to gather its data.
.Nm
will also read any files passed to it as arguments (or stdin if it
is not connected to a tty), in search of output that resembles that
of either
.Xr lintpkgsrc 1
or
.Xr audit-packages 1 .
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl c
Use colors.
The graph defaults to black, but if this option is used and the output
from
.Xr lintpkgsrc 1
or
.Pa audit-packages
is given, then nodes (and edges leading from them) will be colored in
the following manner:
.Bl -tag -width purple
.It green
The package is completely up to date.
.It orange
The package is up to date, but some of its dependencies require updating.
.It red
The package is out of date or has had a security advisory issued
against it, and should be replaced.
.It purple
The package was not found in the local pkgsrc tree.
.El
.It Fl d Ar pkg_dbdir
The location of the package database files.
This defaults to the value of the
.Pa PKG_DBDIR
environment variable, if it is set, or to
.Pa @PKG_DBDIR@ .
.It Fl l
Adds package 
.Dq location
information to the labels on the nodes.
This is the path to the package under the local pkgsrc tree.
.It Fl o
Adds a package
.Dq order
number to each node's label.
The number indicates only the place of the node in the hierarchy, such
that each node has a number greater than that of anything which
depends on it, and with the
.Dq leaf
nodes numbered one.
.It Fl v
Adds the package version number to the node's label in the graph.
.El
.Sh ENVIRONMENT
.Ss PKG_DBDIR
Where to find registered packages instead of
.Pa @PKG_DBDIR@ .
.Sh EXAMPLES
The default output:
.Bd -literal -offset indent
$ pkgdepgraph | dotty -
.Ed
.Pp
To generate colored graph output for later use, and a postscript image
of it:
.Bd -literal -offset indent
$ lintpkgsrc -i \> pkgdepgraph.in
$ audit-packages \>\> pkgdepgraph.in
$ pkgdepgraph -clv pkgdepgraph.in \> pkgdepgraph.dot
$ dot -Tps pkgdepgraph.dot \> pkgdepgraph.ps
.Ed
.Pp
To subsequently generate a graph of just the out-of-date nodes as a
gif:
.Bd -literal -offset indent
$ grep -v green pkgdepgraph.dot | \\
	sed 's/"packages"/"out of date packages"/' | \\
	dot -Tgif \> pkgdepgraph.ood.gif
.Ed
.Pp
To make a list of packages that need to be removed in order to bring
all packages up to date:
.Bd -literal -offset indent
$ grep -v green pkgdepgraph.dot \> out-of-date
$ grep label out-of-date | \\
	sort -t\\# +1n | \\
	sed 's/\\(.\\)".*/\\1/;s/"//' \> delete_order
$ grep LEAF out-of-date | \\
	sort -t\\# +1nr | \\
	sed 's/.*label="//;s/\\\\.*//' \> rebuild_order
.Ed
.Sh SEE ALSO
.Xr dot 1 ,
.Xr dotty 1 ,
.Xr lintpkgsrc 1
.Sh AUTHORS
.An Andrew Brown Aq atatat@netbsd.org
.Sh BUGS
.Nm
was written in
.Xr perl 1 ,
but I believe the balance of code layout and comments is actually
reasonable, despite what you may think of perl.
