# $NetBSD: buildlink3.mk,v 1.3 2006/04/06 06:22:49 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BTPARSE_BUILDLINK3_MK:=	${BTPARSE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	btparse
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbtparse}
BUILDLINK_PACKAGES+=	btparse

.if !empty(BTPARSE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.btparse+=	btparse>=0.34
BUILDLINK_PKGSRCDIR.btparse?=	../../textproc/btparse
.endif	# BTPARSE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
