# $NetBSD: buildlink3.mk,v 1.1 2004/04/11 07:14:05 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BTPARSE_BUILDLINK3_MK:=	${BTPARSE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	btparse
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbtparse}
BUILDLINK_PACKAGES+=	btparse

.if !empty(BTPARSE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.btparse+=	btparse>=0.33
BUILDLINK_PKGSRCDIR.btparse?=	../../textproc/btparse
BUILDLINK_DEPMETHOD.btparse?=	build
.endif	# BTPARSE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
