${PKGNAME}/program/classes/ScriptProviderForJavaScript.jar
${PKGNAME}/program/classes/js.jar
${PKGNAME}/program/services/scriptproviderforjavascript.rdb
${PKGNAME}/share/Scripts/javascript/ExportSheetsToHTML/exportsheetstohtml.js
${PKGNAME}/share/Scripts/javascript/ExportSheetsToHTML/parcel-descriptor.xml
${PKGNAME}/share/Scripts/javascript/HelloWorld/helloworld.js
${PKGNAME}/share/Scripts/javascript/HelloWorld/parcel-descriptor.xml
${PKGNAME}/share/Scripts/javascript/Highlight/ButtonPressHandler.js
${PKGNAME}/share/Scripts/javascript/Highlight/ShowDialog.js
${PKGNAME}/share/Scripts/javascript/Highlight/parcel-descriptor.xml
