# $NetBSD: buildlink2.mk,v 1.2 2002/10/25 17:12:51 wiz Exp $
#

.if !defined(NBITOOLS_BUILDLINK2_MK)
NBITOOLS_BUILDLINK2_MK=	# defined

BUILDLINK_PACKAGES+=		nbitools
BUILDLINK_DEPENDS.nbitools?=	nbitools>=6.3
BUILDLINK_PKGSRCDIR.nbitools?=	../../devel/nbitools
BUILDLINK_DEPMETHOD.nbitools?=	build

EVAL_PREFIX+=	BUILDLINK_PREFIX.nbitools=nbitools
BUILDLINK_PREFIX.nbitools_DEFAULT=	${LOCALBASE}
BUILDLINK_FILES.nbitools+=	include/itools/X11/Xfuncproto.h
BUILDLINK_FILES.nbitools+=	include/itools/X11/Xos.h
BUILDLINK_FILES.nbitools+=	include/itools/X11/Xosdefs.h
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Amoeba.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/DGUX.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Darwin.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/FreeBSD.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Imake.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Imake.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Imake.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Library.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Mips.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Motif.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Motif.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/NetBSD.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Oki.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/OpenBSD.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/QNX.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/QNX.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Server.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/ServerLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Threads.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Win32.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/Win32.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/WinLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/X11.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/X11.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/apollo.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/bsd.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/bsdLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/bsdLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/bsdi.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/cde.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/cde.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/convex.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/cray.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/fujitsu.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/generic.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/gnu.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/gnuLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/gnuLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/host.def
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/hp.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/hpLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/hpLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/ibm.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/ibmLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/ibmLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/isc.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/linux-pmac.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/linux.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/lnxLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/lnxLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/lnxdoc.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/lnxdoc.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/luna.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/lynx.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/macII.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/mach.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/minix.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/moto.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/ncr.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/nec.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/necLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/necLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/noop.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/nto.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/nto.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/oldlib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/os2.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/os2.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/os2Lib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/os2Lib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/osf1.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/osfLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/osfLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/pegasus.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sco.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sco5.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/scoLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sequent.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sgi.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sgiLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sgiLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/site.def
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sony.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sun.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sunLib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sunLib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sv3Lib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sv3Lib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sv4Lib.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/sv4Lib.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/svr3.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/svr4.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/ultrix.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/usl.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/x386.cf
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/xf86.rules
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/xf86.tmpl
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/xf86site.def
BUILDLINK_FILES.nbitools+=	lib/itools/X11/config/xfree86.cf

BUILDLINK_TARGETS+=	nbitools-buildlink

XMKMF_CMD=	${BUILDLINK_PREFIX.nbitools}/libexec/itools/xmkmf

nbitools-buildlink: _BUILDLINK_USE

.endif	# NBITOOLS_BUILDLINK2_MK
