# $NetBSD: buildlink3.mk,v 1.1 2007/10/29 12:41:18 uebayasi Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SPEEDBAR_BUILDLINK3_MK:=	${SPEEDBAR_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	speedbar
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nspeedbar}
BUILDLINK_PACKAGES+=	speedbar
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}speedbar

.if ${SPEEDBAR_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.speedbar+=	${EMACS_PKGNAME_PREFIX}speedbar>=0.14rc0
BUILDLINK_PKGSRCDIR.speedbar?=	../../editors/speedbar
.endif	# SPEEDBAR_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.speedbar=	${EGREP} '.*\.el$$|.*\.elc$$'

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
