# $NetBSD: Makefile,v 1.4 2022/02/12 08:50:50 pho Exp $

DISTNAME=	annotated-wl-pprint-0.7.0
PKGREVISION=	3
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Wadler/Leijen Pretty Printer, with annotation support
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
