# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/04/25 15:18:28 kefren Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
NDESK_DBUS_BUILDLINK3_MK:=	${NDESK_DBUS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	ndesk-dbus
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nndesk-dbus}
BUILDLINK_PACKAGES+=	ndesk-dbus
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ndesk-dbus

.if ${NDESK_DBUS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.ndesk-dbus+=	ndesk-dbus>=0.6.1a
BUILDLINK_PKGSRCDIR.ndesk-dbus?=	../../sysutils/ndesk-dbus
.endif	# NDESK_DBUS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
