# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/10 08:35:29 markd Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY25_PYCUPS_BUILDLINK3_MK:=	${PY25_PYCUPS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py25-pycups
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy25-pycups}
BUILDLINK_PACKAGES+=	py25-pycups
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py25-pycups

.if ${PY25_PYCUPS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.py25-pycups+=	py25-pycups>=1.9.44
BUILDLINK_PKGSRCDIR.py25-pycups?=	../../wip/py-pycups
.endif	# PY25_PYCUPS_BUILDLINK3_MK

#.include "../../print/cups/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
