# $NetBSD: Makefile,v 1.5 2020/04/26 12:21:13 markd Exp $

DISTNAME=	countriesofeurope
PKGNAME=	tex-${DISTNAME}-0.23
TEXLIVE_REV=	54512

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/countriesofeurope
COMMENT=	Font with the images of the countries of Europe
LICENSE=	ofl-v1.1 AND lppl-1.3c

TEX_MAP_FILES+=	countriesofeurope.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
