# $NetBSD: Makefile,v 1.5 2022/12/18 07:06:41 mef Exp $

R_PKGNAME=	ISLR
R_PKGVER=	1.4

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Data for the "ISLR" book
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
