# $NetBSD: Makefile,v 1.12 2020/11/05 09:07:25 ryoon Exp $
#

GST_PLUGINS0.10_NAME=	faac
GST_PLUGINS0.10_DIRS=	ext/faac
PKGREVISION=		5

.include "../../multimedia/gst-plugins0.10-bad/Makefile.common"

.include "../../audio/faac/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
