# $NetBSD: Makefile,v 1.11 2020/03/22 09:48:36 nia Exp $

DISTNAME=	cantarell-fonts-0.201
CATEGORIES=	fonts gnome
MASTER_SITES=	${MASTER_SITE_GNOME:=sources/cantarell-fonts/${PKGVERSION_NOREV}/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://wiki.gnome.org/Projects/CantarellFonts
COMMENT=	Contemporary Humanist sans serif font designed for on-screen reading
LICENSE=	ofl-v1.1

.include "../../mk/fonts.mk"
.include "../../mk/bsd.pkg.mk"
