# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/03/01 08:29:07 obache Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SARY_BUILDLINK3_MK:=	${SARY_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	sary
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsary}
BUILDLINK_PACKAGES+=	sary
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}sary

.if ${SARY_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.sary+=	sary>=1.2.0
BUILDLINK_PKGSRCDIR.sary?=	../../textproc/sary
.endif	# SARY_BUILDLINK3_MK

.include "../../devel/glib2/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
