.\" $NetBSD: getpapersize.1,v 1.4 2003/08/15 12:51:39 reed Exp $
.Dd November 9, 1998
.Dt GETPAPERSIZE 1
.Os
.Sh NAME
.Nm getpapersize
.Nd Show the default paper size for various packages
.Sh SYNOPSIS
.Nm
.Op package ...
.Sh DESCRIPTION
The
.Nm
utility shows the default paper size for a number of packages.
At the present time, these are the a2ps, ddd, enscript, ghostscript,
gv, magicfilter, and psutils packages.
If no package argument is given, all packages are assumed.
The
.Xr setpapersize 1
utility can be used to set the default paper size for the packages.
.Sh DIAGNOSTICS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr setpapersize 1
