# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 17:33:21 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBSM_BUILDLINK3_MK:=	${LIBSM_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libSM
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NlibSM}
BUILDLINK_PACKAGES+=	libSM
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libSM

.if ${LIBSM_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libSM+=	libSM>=0.99.2
BUILDLINK_PKGSRCDIR.libSM?=	../../x11/libSM
.endif	# LIBSM_BUILDLINK3_MK

.include "../../x11/libICE/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
