# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/14 14:53:41 joerg Exp $

BUILDLINK_DEPMETHOD.xf86miscproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XF86MISCPROTO_BUILDLINK3_MK:=	${XF86MISCPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xf86miscproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxf86miscproto}
BUILDLINK_PACKAGES+=	xf86miscproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xf86miscproto

.if ${XF86MISCPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xf86miscproto+=	xf86miscproto>=0.9.2
BUILDLINK_PKGSRCDIR.xf86miscproto?=	../../x11/xf86miscproto
.endif	# XF86MISCPROTO_BUILDLINK3_MK

.include "../../x11/xproto/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
