# $NetBSD: Makefile,v 1.2 2010/09/14 00:18:18 minskim Exp $

DISTNAME=	placeins-plain
PKGNAME=	tex-${DISTNAME}-2.0
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Insertions that keep their place

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
