# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/09/24 21:10:12 dmcmahill Exp $
#

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
TK_BWIDGET_BUILDLINK3_MK:=	${TK_BWIDGET_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tk-BWidget
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntk-BWidget}
BUILDLINK_PACKAGES+=	tk-BWidget

.if !empty(TK_BWIDGET_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.tk-BWidget+=	tk-BWidget>=1.7.0
BUILDLINK_PKGSRCDIR.tk-BWidget?=	../../x11/tk-BWidget
.endif	# TK_BWIDGET_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
