# $NetBSD: buildlink3.mk,v 1.3 2006/04/06 06:23:04 reed Exp $
#

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
TK_BWIDGET_BUILDLINK3_MK:=	${TK_BWIDGET_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tk-BWidget
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntk-BWidget}
BUILDLINK_PACKAGES+=	tk-BWidget

.if !empty(TK_BWIDGET_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.tk-BWidget+=	tk-BWidget>=1.7.0
BUILDLINK_ABI_DEPENDS.tk-BWidget?=	tk-BWidget>=1.7.0nb1
BUILDLINK_PKGSRCDIR.tk-BWidget?=	../../x11/tk-BWidget
.endif	# TK_BWIDGET_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
