# $NetBSD: Makefile,v 1.4 2026/03/29 03:35:09 markd Exp $

DISTNAME=	flowfram.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.1
TEXLIVE_REV=	78101

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/flowfram
COMMENT=	Documentation for tex-flowfram
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
