# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/02/26 21:51:06 plunky Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBFPRINT_BUILDLINK3_MK:=	${LIBFPRINT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libfprint
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibfprint}
BUILDLINK_PACKAGES+=	libfprint
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libfprint

.if !empty(LIBFPRINT_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libfprint+=	libfprint>=0.0.6
BUILDLINK_ABI_DEPENDS.libfprint+=	libfprint>=0.0.6
BUILDLINK_PKGSRCDIR.libfprint?=		../../security/libfprint
.endif	# LIBFPRINT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
