# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:41 wiz Exp $

DISTNAME=	fetamont.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.4
TEXLIVE_REV=	34500

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/fetamont
COMMENT=	Documentation for tex-fetamont
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
