# $NetBSD: buildlink3.mk,v 1.1 2004/04/25 04:25:11 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBNIDS_BUILDLINK3_MK:=	${LIBNIDS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libnids
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibnids}
BUILDLINK_PACKAGES+=	libnids

.if !empty(LIBNIDS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libnids+=	libnids>=1.18
BUILDLINK_PKGSRCDIR.libnids?=	../../net/libnids
BUILDLINK_DEPMETHOD.libnids?=	build
.endif	# LIBNIDS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
