#!/bin/sh
#
# $NetBSD: DEINSTALL,v 1.1 2004/08/18 17:52:25 ben Exp $
#

case $2 in
	DEINSTALL) cat << EOF

=============================================================
The records, log and bones were not wiped out by this
deletion process. If you don't want them around, please
remove ${PKG_PREFIX}/share/ivan.
=============================================================

EOF
	;;
esac
