# $NetBSD: Makefile,v 1.11 2024/05/09 01:32:47 pho Exp $

DISTNAME=	stringsearch-0.3.6.6
PKGREVISION=	8
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings
LICENSE=	modified-bsd

HASKELL_UNRESTRICT_DEPENDENCIES+=	\
	containers

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
