#	$NetBSD: sfiles-linux-i386.mk,v 1.2 2015/08/30 10:52:16 ryoon Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	fontconfig.RedHat.5.bfc
SFILES+=	fontconfig.RedHat.5.properties.src
SFILES+=	fontconfig.RedHat.6.bfc
SFILES+=	fontconfig.RedHat.6.properties.src
SFILES+=	fontconfig.SuSE.10.bfc
SFILES+=	fontconfig.SuSE.10.properties.src
SFILES+=	fontconfig.SuSE.11.bfc
SFILES+=	fontconfig.SuSE.11.properties.src
SFILES+=	fontconfig.Turbo.bfc
SFILES+=	fontconfig.Turbo.properties.src
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	hijrah-config-umalqura.properties
