#	$NetBSD: sfiles-macosx-x86_64.mk,v 1.1 2015/11/10 11:35:30 jperkin Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	calendars.properties
SFILES+=	content-types.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	hijrah-config-umalqura.properties
SFILES+=	images/cursors/cursors.properties
SFILES+=	javafx.properties
SFILES+=	jvm.cfg
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	sound.properties
