#	$NetBSD: sfiles-solaris-x86_64.mk,v 1.3 2016/01/22 14:18:42 ryoon Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	amd64/jvm.cfg
SFILES+=	calendars.properties
SFILES+=	content-types.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	hijrah-config-umalqura.properties
SFILES+=	images/cursors/cursors.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	security/ucrypto-solaris.cfg
SFILES+=	security/sunpkcs11-solaris.cfg
SFILES+=	sound.properties
