# $NetBSD: Makefile,v 1.1 2013/05/23 15:05:39 taca Exp $
#

LICENSE=	gnu-lgpl-v3

CT_VERS=	31

.include "../../www/contao/Makefile.example"
.include "../../lang/php/phpversion.mk"
.include "../../mk/bsd.pkg.mk"
