# $NetBSD: Makefile,v 1.1.1.1 2006/01/05 19:12:35 garbled Exp $

DISTNAME=	ffproxy-1.6
CATEGORIES=	www
MASTER_SITES=	http://faith.eu.org/ffproxy/

MAINTAINER=	niklas@noxa.de
HOMEPAGE=	http://faith.eu.org/programs.html\#ffproxy
COMMENT=	Filtering HTTP/HTTPS proxy server

GNU_CONFIGURE=	yes

CONF_FILES=	${PREFIX}/share/ffproxy/sample.config ${PKG_SYSCONFDIR}/ffproxy.conf
.include "../../mk/bsd.pkg.mk"
