# $NetBSD: buildlink3.mk,v 1.5 2004/10/03 00:13:06 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBAO_BUILDLINK3_MK:=	${LIBAO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libao
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibao}
BUILDLINK_PACKAGES+=	libao

.if !empty(LIBAO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libao+=	libao>=0.8.4
BUILDLINK_RECOMMENDED.libao+=	libao>=0.8.4nb1
BUILDLINK_PKGSRCDIR.libao?=	../../audio/libao
.endif	# LIBAO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
