# $NetBSD: tests.subr,v 1.1 2005/11/24 19:18:45 rillig Exp $
#

# usage: testcase_start <testname>
testcase_start() {
	printf "  Running testcase %s\\n" "$1"
}

# usage: assert_equal <testname> <expected> <got>
assert_equal() {
	case $2 in
	"$3")	;;
	*)	echo "[assert_equal:$1] expected \"$2\", got \"$3\"." 1>&2
		return 1;;
	esac
}

# usage: test_assignment <testname> <input> <expected-output>
test_assignment() {
	testcase_start "$1"
	o=`echo "" | awk '{print var}' var="$2"`
	assert_equal "$1" "$3" "${o}"
}

# usage: test_passline <testname> <input>
test_passline() {
	testcase_start "$1"
	o=`awk '{print}' <<EOF
$2
EOF
`
	assert_equal "$1" "$2" "${o}"
}
