# $NetBSD: Makefile,v 1.2 2016/04/15 14:20:00 wiz Exp $

GST_PLUGINS1_NAME=	soundtouch
GST_PLUGINS1_DIRS=	ext/soundtouch

USE_LANGUAGES=		c c++
.include "../../multimedia/gst-plugins1-bad/Makefile.common"

.include "../../audio/soundtouch/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
