# $NetBSD: buildlink3.mk,v 1.1 2008/10/08 09:34:00 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DIALOG_BUILDLINK3_MK:=	${DIALOG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	dialog
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndialog}
BUILDLINK_PACKAGES+=	dialog
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}dialog

.if ${DIALOG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.dialog+=	dialog>=1.1.20080819nb1
BUILDLINK_PKGSRCDIR.dialog?=	../../misc/dialog
.endif	# DIALOG_BUILDLINK3_MK

.include "../../devel/ncurses/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
