# $NetBSD: Makefile,v 1.8 2021/06/06 22:35:19 markd Exp $

DISTNAME=	tlshell.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2021
TEXLIVE_REV=	58984

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Documentation for tex-tlshell
LICENSE=	gnu-gpl-v2

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
