# $NetBSD: Makefile,v 1.6 2018/05/06 03:04:36 markd Exp $

DISTNAME=	fontools.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2018
TEXLIVE_REV=	47134

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/fontools
COMMENT=	Documentation for tex-fontools
LICENSE=	gnu-gpl-v2

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
