# $NetBSD: buildlink3.mk,v 1.1 2007/09/21 13:00:18 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBART_BUILDLINK3_MK:=	${LIBART_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libart
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibart}
BUILDLINK_PACKAGES+=	libart
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libart

.if !empty(LIBART_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libart+=	libart>=2.3.10nb1
BUILDLINK_ABI_DEPENDS.libart+=	libart>=2.3.16nb1
BUILDLINK_PKGSRCDIR.libart?=	../../graphics/libart
.endif	# LIBART_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
