# $NetBSD: buildlink3.mk,v 1.7 2004/10/03 00:17:49 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BIND_BUILDLINK3_MK:=	${BIND_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	bind
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbind}
BUILDLINK_PACKAGES+=	bind

.if !empty(BIND_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.bind+=	bind>=9.2.2
BUILDLINK_RECOMMENDED.bind+=	bind>=9.2.3nb5
BUILDLINK_PKGSRCDIR.bind?=	../../net/bind9

BUILDLINK_INCDIRS.bind?=	include/bind
BUILDLINK_LDFLAGS.bind?=	${BUILDLINK_LDADD.bind}
.endif	# BIND_BUILDLINK3_MK

.include "../../security/openssl/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
