# $NetBSD: Makefile,v 1.7 1998/10/15 19:51:09 agc Exp $
# FreeBSD Id: Makefile,v 1.2 1997/06/15 10:44:39 asami Exp
#

DISTNAME=	xtimer-8087
PKGNAME=	xtimer-0.8087
CATEGORIES=	x11
MASTER_SITES=	http://spock.vector.co.jp/authors/VA004959/xtimer/

MAINTAINER=	candy@fct.kgc.co.jp

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
