# $NetBSD: Makefile,v 1.4 2003/09/08 17:49:47 cjep Exp $
#

DISTNAME=       	x2vnc-1.4
PKGREVISION=		1
CATEGORIES=		net x11
MASTER_SITES=   	http://fredrik.hubbe.net/

MAINTAINER=	 	mike@ethmoid.org
HOMEPAGE=		http://fredrik.hubbe.net/x2vnc.html
COMMENT=		Multi-console display using X and VNC

USE_IMAKE=		yes
USE_BUILDLINK2=		yes

.include "../../mk/bsd.pkg.mk"
