# $NetBSD: apache-osticket.conf,v 1.1 2025/06/30 14:34:14 hauke Exp $
#
# osTicket configuration fragment for Apache 2.4+

<IfModule mod_alias.c>
    Alias /support/ "@PREFIX@/share/osticket/"
</IfModule>

<Directory "@PREFIX@/share/osticket">

    DirectoryIndex index.php

    # Required for automail pipelining
    Options FollowSymlinks
    AllowOverride AuthConfig FileInfo

    Require all granted

</Directory>
