# $NetBSD: buildlink3.mk,v 1.2 2004/03/05 19:25:06 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
CDPARANOIA_BUILDLINK3_MK:=	${CDPARANOIA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cdparanoia
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncdparanoia}
BUILDLINK_PACKAGES+=	cdparanoia

.if !empty(CDPARANOIA_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.cdparanoia+=		cdparanoia>=3.0
BUILDLINK_PKGSRCDIR.cdparanoia?=	../../audio/cdparanoia
.endif	# CDPARANOIA_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
