# $NetBSD: Makefile,v 1.1 2015/09/02 10:50:40 markd Exp $

DISTNAME=	mcf2graph.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-3.53
TEXLIVE_REV=	38004

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/mcf2graph
COMMENT=	Documentation for tex-mcf2graph
LICENSE=	modified-bsd

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
