# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/14 15:55:20 joerg Exp $

BUILDLINK_DEPMETHOD.xf86dgaproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XF86DGAPROTO_BUILDLINK3_MK:=	${XF86DGAPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xf86dgaproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxf86dgaproto}
BUILDLINK_PACKAGES+=	xf86dgaproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xf86dgaproto

.if ${XF86DGAPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xf86dgaproto+=	xf86dgaproto>=2.0.2
BUILDLINK_PKGSRCDIR.xf86dgaproto?=	../../x11/xf86dgaproto
.endif	# XF86DGAPROTO_BUILDLINK3_MK

.include "../../x11/xproto/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
