$NetBSD: patch-server_etc_snapserver.conf,v 1.4 2026/03/12 05:56:40 adam Exp $

Don't hardcode various paths, allow pkgsrc to substitute them.

--- server/etc/snapserver.conf.orig	2026-03-08 20:00:51.000000000 +0000
+++ server/etc/snapserver.conf
@@ -30,7 +30,7 @@
 #threads = -1
 
 # the pid file when running as daemon (-d or --daemon)
-#pidfile = /var/run/snapserver/pid
+#pidfile = @VARBASE@/run/snapserver/pid
 
 # the user to run as when daemonized (-d or --daemon)
 #user = snapserver
@@ -39,7 +39,7 @@
 
 # directory where persistent data is stored (server.json)
 # if empty, data dir will be
-#  - "/var/lib/snapserver/" when running as daemon
+#  - "@VARBASE@/lib/snapserver/" when running as daemon
 #  - "$HOME/.config/snapserver/" when not running as daemon
 #datadir =
 
@@ -194,10 +194,10 @@ source = pipe:///tmp/snapfifo?name=defau
 # default_source = default
 
 # Plugin directory, containing scripts, referred by "controlscript"
-#plugin_dir = /usr/share/snapserver/plug-ins
+#plugin_dir = @PREFIX@/share/snapserver/plug-ins
 
 # Sandbox directory, containing executables, started by "process" and "librespot" streams
-#sandbox_dir = /usr/share/snapserver/sandbox
+#sandbox_dir = @PREFIX@/share/snapserver/sandbox
 
 # Default sample format: <sample rate>:<bits per sample>:<channels>
 #sampleformat = 48000:16:2
