# $NetBSD: Makefile,v 1.11 2021/02/20 00:27:36 markd Exp $

DISTNAME=	newpx.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.414
TEXLIVE_REV=	56845

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/newpx
COMMENT=	Documentation for tex-newpx
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
