# $NetBSD: Makefile,v 1.2 2003/12/19 09:22:30 agc Exp $

DISTNAME=	HTML_Select-1.2
CATEGORIES=	www

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE= 	http://pear.php.net/package/HTML_Common
COMMENT=	HTML_Select is a PHP class for generating HTML form select elements

DEPENDS+=	pear-HTML_Common>=1.1:../../www/pear-HTML_Common

.include "../../www/php4/pear.mk"
.include "../../mk/bsd.pkg.mk"
