# $NetBSD: Makefile,v 1.2 2015/02/01 14:45:18 taca Exp $

DISTNAME=	mercenary-0.3.5
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	${MASTER_SITE_RUBYGEMS:=mercenary/}
COMMENT=	Lightweight and flexible library for writing command-line apps
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
