# $NetBSD: buildlink3.mk,v 1.4 2006/02/05 23:08:11 joerg Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBVISUAL_BUILDLINK3_MK:=	${LIBVISUAL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libvisual
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibvisual}
BUILDLINK_PACKAGES+=	libvisual

.if !empty(LIBVISUAL_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libvisual+=	libvisual>=0.2.0
BUILDLINK_RECOMMENDED.libvisual?=	libvisual>=0.2.0nb1
BUILDLINK_PKGSRCDIR.libvisual?=	../../audio/libvisual
.endif	# LIBVISUAL_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
