# $NetBSD: Makefile,v 1.7 2002/10/13 20:20:24 wiz Exp $
#

DISTNAME=	tnef-1.1.2
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=tnef/}

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://world.std.com/~damned/software.html
COMMENT=	decode MS-TNEF MIME attachments

USE_BUILDLINK2=		YES
GNU_CONFIGURE=		YES

.include "../../devel/gettext-lib/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
