# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/09/06 19:56:40 adam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CAIROMM_BUILDLINK3_MK:=	${CAIROMM_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	cairomm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncairomm}
BUILDLINK_PACKAGES+=	cairomm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}cairomm

.if ${CAIROMM_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.cairomm+=	cairomm>=1.2.2
BUILDLINK_PKGSRCDIR.cairomm?=	../../graphics/cairomm
.endif	# CAIROMM_BUILDLINK3_MK

.include "../../graphics/cairo/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
