# $NetBSD: buildlink3.mk,v 1.2 2004/10/03 00:13:17 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
UULIB_BUILDLINK3_MK:=	${UULIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	uulib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nuulib}
BUILDLINK_PACKAGES+=	uulib

.if !empty(UULIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.uulib+=	uulib>=0.5.20
BUILDLINK_RECOMMENDED.uulib+=	uulib>=0.5.20nb2
BUILDLINK_PKGSRCDIR.uulib?=	../../converters/uulib
.endif	# UULIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
