# $NetBSD: buildlink3.mk,v 1.1 2004/04/19 13:38:11 markd Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
UULIB_BUILDLINK3_MK:=	${UULIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	uulib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nuulib}
BUILDLINK_PACKAGES+=	uulib

.if !empty(UULIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.uulib+=	uulib>=0.5.20
BUILDLINK_PKGSRCDIR.uulib?=	../../converters/uulib
.endif	# UULIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
