# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/08/31 00:09:13 gdt Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
GTKIMAGEVIEW_BUILDLINK3_MK:=	${GTKIMAGEVIEW_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	gtkimageview
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngtkimageview}
BUILDLINK_PACKAGES+=	gtkimageview
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}gtkimageview

.if ${GTKIMAGEVIEW_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.gtkimageview+=	gtkimageview>=1.3.0
BUILDLINK_PKGSRCDIR.gtkimageview?=	../../graphics/gtkimageview
.endif	# GTKIMAGEVIEW_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
