# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:45 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBMIMEDIR_BUILDLINK3_MK:=	${LIBMIMEDIR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmimedir
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmimedir}
BUILDLINK_PACKAGES+=	libmimedir
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmimedir

.if !empty(LIBMIMEDIR_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libmimedir+=	libmimedir>=0.4nb1
BUILDLINK_PKGSRCDIR.libmimedir?=	../../devel/libmimedir
.endif	# LIBMIMEDIR_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
