# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:50 wiz Exp $

DISTNAME=	newtxsf.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.02
TEXLIVE_REV=	36746

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/newtxsf
COMMENT=	Documentation for tex-newtxsf
LICENSE=	ofl-v1.1

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
