$NetBSD: patch-Cargo.toml,v 1.13 2025/12/13 19:55:16 pin Exp $

Work around unpublished crate.

--- Cargo.toml.orig	2025-12-03 17:36:28.602478465 +0000
+++ Cargo.toml
@@ -33,7 +33,7 @@ typst-syntax = { path = "crates/typst-sy
 typst-timing = { path = "crates/typst-timing", version = "0.14.2" }
 typst-utils = { path = "crates/typst-utils", version = "0.14.2" }
 typst-assets = "0.14.2"
-typst-dev-assets = { git = "https://github.com/typst/typst-dev-assets", tag = "v0.14.2" }
+typst-dev-assets = { path = "typst-dev-assets-fe6cad916d8b20c20742512b2a3f3b247a2bc4f8" }
 arrayvec = "0.7.4"
 az = "1.2"
 base64 = "0.22"
