.\"                                      Hey, EMACS: -*- nroff -*-
.TH GTKSEE 1 "March 28, 2001"
.SH NAME
gtksee \- GTK-based clone of ACDSee (an image viewer)
.SH SYNOPSIS
.B gtksee
.RI [ option ]...\ [FILE]...
.SH DESCRIPTION
GTKsee is an image viewer/browser. The browser shows thumbnails, you
can quickly watch a picture in large or fullscreen by simply tapping
on return. Also has slideshow capabilities.
.SH OPTIONS
.TP
.B -R
Use current directory as root
.TP
.B -R<directory>
Use <directory> as root
.TP
.B -f
Enable full-screen mode
.TP
.B -i
Enable fit-screen mode
.TP
.B -s
Enable slide-show mode
.TP
.B -h
Print the list of the options
.SH AUTHOR
This manual page was written by Lenart Janos <ocsi@debian.org>,
for the Debian GNU system (but may be used by others).
