# $NetBSD: Makefile,v 1.17 2021/12/08 16:05:47 adam Exp $
#

GST_PLUGINS0.10_NAME=	mpeg2dec
GST_PLUGINS0.10_DIRS=	ext/mpeg2dec
PKGREVISION=		7

.include "../../multimedia/gst-plugins0.10-ugly/Makefile.common"

.include "../../multimedia/libmpeg2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
