# $NetBSD: buildlink3.mk,v 1.1 2008/04/14 22:25:55 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LINK_GRAMMAR_BUILDLINK3_MK:=	${LINK_GRAMMAR_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	link-grammar
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlink-grammar}
BUILDLINK_PACKAGES+=	link-grammar
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}link-grammar

.if ${LINK_GRAMMAR_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.link-grammar+=	link-grammar>=4.3.4
BUILDLINK_PKGSRCDIR.link-grammar?=	../../textproc/link-grammar
.endif	# LINK_GRAMMAR_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
