# $NetBSD: Makefile,v 1.7 2022/02/11 09:46:16 pho Exp $

DISTNAME=	ansi-terminal-0.11.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Simple ANSI terminal support for Haskell
LICENSE=	modified-bsd

.include "../../devel/hs-colour/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
