# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/02/26 18:00:34 hasso Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
AKODE_BUILDLINK3_MK:=	${AKODE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	akode
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nakode}
BUILDLINK_PACKAGES+=	akode
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}akode

.if !empty(AKODE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.akode+=	akode>=2.0.2
BUILDLINK_PKGSRCDIR.akode?=	../../akode/akode
.endif	# AKODE_BUILDLINK3_MK

.include "../../devel/libltdl/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
