# $NetBSD: Makefile,v 1.3 2016/03/15 16:09:04 taca Exp $

DISTNAME=	cookiejar-0.3.3
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/dwaite/cookiejar
COMMENT=	Client-side HTTP Cookie library
LICENSE=	2-clause-bsd

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
