$NetBSD: patch-setup.py,v 1.1 2021/11/21 11:06:18 bsiegert Exp $

Use setuptools because egg.mk expects it.

--- setup.py.orig	1970-01-01 00:00:00.000000000 +0000
+++ setup.py
@@ -1,7 +1,7 @@
 #!/usr/bin/env python
 # setup.py generated by flit for tools that don't yet use PEP 517
 
-from distutils.core import setup
+from setuptools import setup
 
 install_requires = \
 ['six>=1.9', 'mutagen>=1.45']
