$NetBSD: patch-yazi-dds_Cargo.toml,v 1.1 2025/07/22 14:36:15 he Exp $

Use portable-atomic.

--- yazi-dds/Cargo.toml.orig	2025-07-22 13:32:21.086791774 +0000
+++ yazi-dds/Cargo.toml
@@ -13,6 +13,7 @@ default      = [ "vendored-lua" ]
 vendored-lua = [ "mlua/vendored" ]
 
 [dependencies]
+portable-atomic = "1"
 yazi-binding = { path = "../yazi-binding", version = "25.4.8" }
 yazi-boot    = { path = "../yazi-boot", version = "25.4.8" }
 yazi-fs      = { path = "../yazi-fs", version = "25.4.8" }
