$NetBSD: patch-yazi-shared_Cargo.toml,v 1.1 2025/07/22 14:36:15 he Exp $

--- yazi-shared/Cargo.toml.orig	2025-07-22 12:13:51.218622996 +0000
+++ yazi-shared/Cargo.toml
@@ -19,6 +19,7 @@ futures          = { workspace = true }
 memchr           = "2.7.4"
 parking_lot      = { workspace = true }
 percent-encoding = "2.3.1"
+portable-atomic  = "1"
 ratatui          = { workspace = true }
 serde            = { workspace = true }
 tokio            = { workspace = true }
