# $NetBSD: includes.mk,v 1.1 2009/08/05 15:52:11 tnn Exp $

NS_EXTRA_INCLUDES=			\
commandhandler/nsICommandManager.h	\
commandhandler/nsICommandParams.h	\
content/nsISelectionController.h	\
content/nsISelectionDisplay.h		\
content/nsPIDOMEventTarget.h		\
docshell/nsIContentViewer.h		\
docshell/nsIDocShell.h			\
docshell/nsIDocShellTreeItem.h		\
docshell/nsIDocShellTreeNode.h		\
docshell/nsIMarkupDocumentViewer.h	\
docshell/nsIScrollable.h		\
docshell/nsITextScroll.h		\
docshell/nsIWebNavigation.h		\
dom/nsIDOMKeyEvent.h			\
dom/nsIDOMKeyListener.h			\
dom/nsIDOMLocation.h			\
dom/nsIDOMMouseListener.h		\
dom/nsIDOMNSEvent.h			\
dom/nsIDOMUIListener.h			\
dom/nsIDOMWindowInternal.h		\
dom/nsIDOMXULCommandDispatcher.h	\
dom/nsPIDOMWindow.h			\
embedcomponents/nsIAppStartupNotifier.h	\
fastfind/nsITypeAheadFind.h		\
gfx/gfxCore.h				\
gfx/nsColor.h				\
gfx/nsCoord.h				\
gfx/nsIDeviceContext.h			\
gfx/nsIRenderingContext.h		\
gfx/nsITheme.h				\
gfx/nsMargin.h				\
gfx/nsPoint.h				\
gfx/nsRect.h				\
gfx/nsSize.h				\
gtkembedmoz/gtkmozembed.h		\
gtkembedmoz/gtkmozembed_glue.cpp	\
gtkembedmoz/gtkmozembed_internal.h	\
intl/nsIStringBundle.h			\
layout/nsIPrintProgressParams.h		\
mozilla-config.h			\
necko/nsIFileStreams.h			\
necko/nsIInputStreamChannel.h		\
necko/nsNetCID.h			\
pref/nsIPref.h				\
profdirserviceprovider/nsProfileDirServiceProvider.h	\
thebes/gfxPoint.h			\
thebes/gfxTypes.h			\
webbrwsr/nsCWebBrowser.h		\
webbrwsr/nsIPrintingPromptService.h	\
widget/nsEvent.h			\
widget/nsIAppShell.h			\
widget/nsIBaseWindow.h			\
widget/nsIPrintOptions.h		\
widget/nsIPrintSettings.h		\
widget/nsIPrintSettingsService.h	\
widget/nsIWidget.h			\
widget/nsWidgetsCID.h			\
xpcom/nsAutoPtr.h			\
xpcom/nsCRT.h				\
xpcom/nsCppSharedAllocator.h		\
xpcom/nsIServiceManagerObsolete.h	\
xpcom/nsMathUtils.h			\
xpcom/nsWeakPtr.h
