# $NetBSD: buildlink3.mk,v 1.1 2014/01/01 06:55:23 ryoon Exp $

BUILDLINK_TREE+=	${PYPKGPREFIX}-newt

.if !defined(PY_NEWT_BUILDLINK3_MK)
PY_NEWT_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.${PYPKGPREFIX}-newt+=	${PYPKGPREFIX}-newt>=0.52.16
BUILDLINK_PKGSRCDIR.${PYPKGPREFIX}-newt?=	../../devel/py-newt

.endif	# PY_NEWT_BUILDLINK3_MK

BUILDLINK_TREE+=	-${PYPKGPREFIX}-newt
