# $NetBSD: buildlink3.mk,v 1.3 2004/10/03 00:12:56 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LAPACK_BUILDLINK3_MK:=	${LAPACK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lapack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlapack}
BUILDLINK_PACKAGES+=	lapack

.if !empty(LAPACK_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.lapack+=	lapack>=20010201nb1
BUILDLINK_RECOMMENDED.lapack+=	lapack>=20010201nb2
BUILDLINK_PKGSRCDIR.lapack?=	../../math/lapack
.endif	# LAPACK_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
