# $NetBSD: Makefile,v 1.7 2017/09/06 16:49:30 wiz Exp $

DISTNAME=	amscls.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2015
TEXLIVE_REV=	36804

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-amscls
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
