# $NetBSD: Makefile,v 1.5 2025/05/07 20:45:28 markd Exp $

DISTNAME=	mltex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.2.71363
TEXLIVE_REV=	71363

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/mltex
COMMENT=	Documentation for tex-mltex

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
