# $NetBSD: Makefile,v 1.2 2020/03/08 16:47:47 wiz Exp $

GST_PLUGINS1_NAME=	gdk_pixbuf
GST_PLUGINS1_DIRS=	ext/gdk_pixbuf
GST_PLUGINS1_FLAGS=	gdk_pixbuf

PKGREVISION= 1
.include "../../multimedia/gst-plugins1-good/Makefile.common"
.include "../../graphics/gdk-pixbuf2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
