# $NetBSD: buildlink3.mk,v 1.9 2006/07/08 23:11:01 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FFMPEG_BUILDLINK3_MK:=	${FFMPEG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ffmpeg
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nffmpeg}
BUILDLINK_PACKAGES+=	ffmpeg
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ffmpeg

.if !empty(FFMPEG_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.ffmpeg+=	ffmpeg>=0.4.9pre1
BUILDLINK_ABI_DEPENDS.ffmpeg?=	ffmpeg>=0.4.9pre1
BUILDLINK_PKGSRCDIR.ffmpeg?=	../../multimedia/ffmpeg
.endif	# FFMPEG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
