# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/10/11 18:43:48 drochner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RARIAN_BUILDLINK3_MK:=	${RARIAN_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	rarian
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nrarian}
BUILDLINK_PACKAGES+=	rarian
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}rarian

.if ${RARIAN_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.rarian+=	rarian>=0.6.0
BUILDLINK_PKGSRCDIR.rarian?=	../../textproc/rarian
.endif	# RARIAN_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
