# $NetBSD: Makefile,v 1.4 2019/08/08 19:53:43 brook Exp $

R_PKGNAME=	viridisLite
R_PKGVER=	0.3.0
CATEGORIES=	graphics

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Default color maps from 'matplotlib' (lite version)
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
