# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/09/10 15:32:48 xtraeme Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBMCS_BUILDLINK3_MK:=	${LIBMCS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libmcs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmcs}
BUILDLINK_PACKAGES+=	libmcs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmcs

.if ${LIBMCS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libmcs+=	libmcs>=0.4.1
BUILDLINK_PKGSRCDIR.libmcs?=	../../devel/libmcs
.endif	# LIBMCS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
