# $NetBSD: buildlink3.mk,v 1.9 2007/03/12 06:42:33 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CMAKE_BUILDLINK3_MK:=	${CMAKE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	cmake
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncmake}
BUILDLINK_PACKAGES+=	cmake
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}cmake

.if ${CMAKE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.cmake+=	cmake>=2.4.6nb3
BUILDLINK_PKGSRCDIR.cmake?=	../../devel/cmake
BUILDLINK_DEPMETHOD.cmake?=	build
BUILDLINK_FILES.cmake+=		share/cmake-*/include/*
.endif	# CMAKE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
