# $NetBSD: buildlink3.mk,v 1.2 2005/03/19 16:48:21 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
CRYPTOPP_BUILDLINK3_MK:=	${CRYPTOPP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cryptopp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncryptopp}
BUILDLINK_PACKAGES+=	cryptopp

.if !empty(CRYPTOPP_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.cryptopp+=	cryptopp>=5.1
BUILDLINK_DEPMETHOD.cryptopp?=	build
BUILDLINK_PKGSRCDIR.cryptopp?=	../../security/cryptopp
.endif	# CRYPTOPP_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
