$NetBSD: patch-platform_media_libvpx_config_linux_arm64_vpx__config.h,v 1.1 2026/03/15 10:10:21 nia Exp $

From e502735eb2609befcdf0761e9c59826d8555e5be Mon Sep 17 00:00:00 2001
From: Basilisk-Dev <basiliskdev@protonmail.com>
Date: Wed, 11 Mar 2026 12:21:28 -0400
Subject: [PATCH] Issue #2993 - only use SVE instructions on Apple Silicon

--- platform/media/libvpx/config/linux/arm64/vpx_config.h.orig	2026-03-01 22:37:59.000000000 +0000
+++ platform/media/libvpx/config/linux/arm64/vpx_config.h
@@ -8,7 +8,7 @@
 /* This file automatically generated by configure. Do not edit! */
 #ifndef VPX_CONFIG_H
 #define VPX_CONFIG_H
-#define RESTRICT    
+#define RESTRICT
 #define INLINE      inline
 #define VPX_ARCH_ARM 1
 #define VPX_ARCH_AARCH64 1
@@ -21,8 +21,8 @@
 #define HAVE_NEON 1
 #define HAVE_NEON_DOTPROD 1
 #define HAVE_NEON_I8MM 1
-#define HAVE_SVE 1
-#define HAVE_SVE2 1
+#define HAVE_SVE 0
+#define HAVE_SVE2 0
 #define HAVE_MIPS32 0
 #define HAVE_DSPR2 0
 #define HAVE_MSA 0
