# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/11/04 10:52:53 markd Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBCLUCENE_BUILDLINK3_MK:=	${LIBCLUCENE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libclucene
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibclucene}
BUILDLINK_PACKAGES+=	libclucene
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libclucene

.if ${LIBCLUCENE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libclucene+=	libclucene>=0.9.21
BUILDLINK_PKGSRCDIR.libclucene?=	../../textproc/libclucene
.endif	# LIBCLUCENE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
