# $NetBSD: buildlink3.mk,v 1.3 2004/04/22 20:02:46 ben Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PORTAUDIO_BUILDLINK3_MK:=	${PORTAUDIO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	portaudio
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nportaudio}
BUILDLINK_PACKAGES+=	portaudio

.if !empty(PORTAUDIO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.portaudio+=	portaudio>=18.1
BUILDLINK_PKGSRCDIR.portaudio?=	../../audio/portaudio
.endif	# PORTAUDIO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
