echo "POST $FROMSITE/servlet/EComActionServlet/ECom.RegisterPageInfo;\$sessionid\$$SESS HTTP/1.0"
echo "Content-type: application/x-www-form-urlencoded"
echo "Content-length: $LEN"
echo ""
echo -n "form.userId=$ACCT&"
echo -n "form.password=$PASS&"
echo -n "form.passwordVerify=$PASS&"
echo -n "form.email=$EMAIL&"
echo -n "form.firstName=$FIRSTNAME&"
echo -n "form.lastName=$LASTNAME&"
echo -n "form.address1=$ADDR&"
echo -n "form.city=$CITY&"
echo -n "form.province=$STATE&"
echo -n "form.postalCode=$ZIP&"
echo -n "form.country=$COUNTRY&"
echo -n "form.phone=$PHONE&"
echo "form.sendMail=No&form.sendMailPartner=No&RegisterPageAction/form.register=Register"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
