$NetBSD: patch-dictionary_user__dictionary__storage.h,v 1.1 2020/06/19 05:45:30 taca Exp $

Fix from https://github.com/google/mozc/issues/460

--- dictionary/user_dictionary_storage.h.orig	2017-11-02 13:32:47.000000000 +0000
+++ dictionary/user_dictionary_storage.h
@@ -72,13 +72,15 @@ namespace mozc {
 class Mutex;
 class ProcessMutex;
 
-// Inherit from ProtocolBuffer
-// TODO(hidehiko): Get rid of this implementation.
-class UserDictionaryStorage : public user_dictionary::UserDictionaryStorage {
+class UserDictionaryStorage {
  public:
   typedef user_dictionary::UserDictionary UserDictionary;
   typedef user_dictionary::UserDictionary::Entry UserDictionaryEntry;
 
+  // Instance of base class generated by Protocol Buffers compiler.
+  // Regular inheritance strongly discouraged.
+  user_dictionary::UserDictionaryStorage user_dictionary_storage_base;
+
   enum UserDictionaryStorageErrorType {
     USER_DICTIONARY_STORAGE_NO_ERROR = 0,  // default
     FILE_NOT_EXISTS,
