# $NetBSD: buildlink3.mk,v 1.1 2024/05/03 10:09:48 wiz Exp $

BUILDLINK_TREE+=	QXlsx

.if !defined(QXLSX_BUILDLINK3_MK)
QXLSX_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.QXlsx?=	build

BUILDLINK_API_DEPENDS.QXlsx+=	QXlsx>=1.4.7
BUILDLINK_PKGSRCDIR.QXlsx?=	../../math/QXlsx
.endif	# QXLSX_BUILDLINK3_MK

BUILDLINK_TREE+=	-QXlsx
