# $NetBSD: buildlink3.mk,v 1.1 2004/02/10 00:14:41 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GSS_BUILDLINK3_MK:=	${GSS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gss
.endif

.if !empty(GSS_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		gss
BUILDLINK_DEPENDS.gss+=		gss>=0.0.6
BUILDLINK_PKGSRCDIR.gss?=	../../security/gss
.endif # GSS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
