# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/10 01:02:47 markd Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EIGEN_BUILDLINK3_MK:=	${EIGEN_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	eigen
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Neigen}
BUILDLINK_PACKAGES+=	eigen
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}eigen

.if ${EIGEN_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.eigen+=	eigen>=2.0beta3
BUILDLINK_PKGSRCDIR.eigen?=	../../math/eigen2
BUILDLINK_DEPMETHOD.eigen?=	build
.endif	# EIGEN_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
