# $NetBSD: Makefile,v 1.2 2017/09/06 16:49:39 wiz Exp $

DISTNAME=	index
PKGNAME=	tex-${DISTNAME}-4.1beta
TEXLIVE_REV=	24099

MAINTAINER=	jaapb@NetBSD.org
COMMENT=	Reimplementation of LaTeX's indexing macros

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
