# $NetBSD: Makefile,v 1.3 2019/12/06 20:21:53 markd Exp $
# TeX Live Revision 17373

DISTNAME=	listing.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.2

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-listing
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
