===========================================================================
$NetBSD: MESSAGE.module,v 1.1 2002/01/10 13:17:11 jlam Exp $

To enable this module, add the following to ${PKG_SYSCONFDIR}/php3.ini:

    extension_dir=${PREFIX}/${PHP_EXTENSION_DIR}
    extension=${MODNAME}.so

and restart your PHP3-enabled HTTP server to load this module.
===========================================================================
