# $NetBSD: buildlink3.mk,v 1.9 2008/01/09 19:00:25 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MOWITZ_BUILDLINK3_MK:=	${MOWITZ_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	Mowitz
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NMowitz}
BUILDLINK_PACKAGES+=	Mowitz
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}Mowitz

.if !empty(MOWITZ_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.Mowitz+=	Mowitz>=0.3.0
BUILDLINK_PKGSRCDIR.Mowitz?=	../../x11/mowitz
.endif	# MOWITZ_BUILDLINK3_MK

.include "../../x11/libXpm/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
