# $NetBSD: Makefile,v 1.3 2025/03/05 03:39:11 pho Exp $

DISTNAME=	file-io-0.1.5
PKGREVISION=	2
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Basic file IO operations via 'OsPath'
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
