# $NetBSD: Makefile,v 1.37 2015/10/10 01:58:09 ryoon Exp $
#

PKGNAME=	eog-plugins-map-2.30.2
PKGREVISION=	31
COMMENT=	Plugin collection for eog - map plugin

BUILD_DIRS=	plugins/map
INSTALL_DIRS=	plugins/map

.include "../../graphics/eog-plugins/Makefile.common"
.include "../../geography/libchamplain08/buildlink3.mk"
.include "../../graphics/libexif/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
