# $NetBSD: Makefile,v 1.2 2003/08/28 20:05:20 xtraeme Exp $
#

DISTNAME=	puf-0.93.2a
PKGNAME=	${DISTNAME:S/a$/.1/}
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=puf/}

MAINTAINER=	xtraeme@NetBSD.org
HOMEPAGE=	http://puf.sourceforge.net/
COMMENT=	Parallel URL fetcher

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
