# $NetBSD: buildlink3.mk,v 1.4 2006/02/05 23:11:31 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XAW_XPM_BUILDLINK3_MK:=	${XAW_XPM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	Xaw-Xpm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NXaw-Xpm}
BUILDLINK_PACKAGES+=	Xaw-Xpm

.if !empty(XAW_XPM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.Xaw-Xpm+=	Xaw-Xpm>=1.1
BUILDLINK_RECOMMENDED.Xaw-Xpm?=	Xaw-Xpm>=1.1nb2
BUILDLINK_PKGSRCDIR.Xaw-Xpm?=	../../x11/Xaw-Xpm
.endif	# XAW_XPM_BUILDLINK3_MK

.include "../../mk/bsd.prefs.mk"
.include "../../graphics/xpm/buildlink3.mk"

LIBXAW?=	-L${BUILDLINK_PREFIX.Xaw-Xpm}/lib			\
		${COMPILER_RPATH_FLAG}${BUILDLINK_PREFIX.Xaw-Xpm}/lib	\
		-L${BUILDLINK_PREFIX.xpm}/lib				\
		${COMPILER_RPATH_FLAG}${BUILDLINK_PREFIX.xpm}/lib	\
		-lXaw3d -lXpm

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
