# $NetBSD: options.mk,v 1.4 2006/07/21 14:27:56 jlam Exp $

PKG_OPTIONS_VAR=	PKG_OPTIONS.netbsd-tap
PKG_SUPPORTED_OPTIONS=	bpf
PKG_SUGGESTED_OPTIONS=	bpf

.include "../../mk/bsd.options.mk"

.if !empty(PKG_OPTIONS:Mbpf)
PKGSRC_MAKE_ENV+=	USE_BPF=YES
.endif

TAP_KERNEL_ENV?=	# empty
BUILD_DEFS+=	TAP_KERNEL_ENV
MAKE_ENV+=	TAP_KERNEL_ENV=${TAP_KERNEL_ENV:Q}
