# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/07/13 14:50:17 drochner Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FREEALUT_BUILDLINK3_MK:=	${FREEALUT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	freealut
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfreealut}
BUILDLINK_PACKAGES+=	freealut
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}freealut

.if ${FREEALUT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.freealut+=	freealut>=1.1.0
BUILDLINK_PKGSRCDIR.freealut?=	../../audio/freealut
.endif	# FREEALUT_BUILDLINK3_MK

.include "../../audio/openal/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
