$NetBSD: patch-pyproject.toml,v 1.1 2026/04/06 16:20:01 wiz Exp $

https://github.com/nicolargo/glances/commit/6940195b1a11dd3c0c02108ea8dd721ca1a7b5a7

--- pyproject.toml.orig	2026-03-31 06:06:45.000000000 +0000
+++ pyproject.toml
@@ -133,7 +133,9 @@ version = {attr = "glances.__version__"}
 version = {attr = "glances.__version__"}
 
 [tool.setuptools.packages.find]
+exclude = ["*__pycache__*"]
 include = ["glances*"]
+where = ["."]
 
 [tool.ruff]
 line-length = 120
