# $NetBSD: buildlink3.mk,v 1.1 2007/10/29 12:41:17 uebayasi Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FLIM_BUILDLINK3_MK:=	${FLIM_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	flim
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nflim}
BUILDLINK_PACKAGES+=	flim
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}flim

.if ${FLIM_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.flim+=	${EMACS_PKGNAME_PREFIX}flim>=1.14
BUILDLINK_PKGSRCDIR.flim?=	../../devel/flim
.endif	# FLIM_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.flim=	${EGREP} '.*\.el$$|.*\.elc$$'

.include "../../devel/apel/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
