# $NetBSD: Makefile,v 1.9 2001/09/08 19:55:41 jlam Exp $
#

DISTNAME=	dinotrace-9.1d
CATEGORIES=	cad
MASTER_SITES=	http://www.veripool.com/ftp/

MAINTAINER=	dmcmahill@netbsd.org
HOMEPAGE= 	http://www.veripool.com/dinotrace/
COMMENT=	tool for viewing the output of digital simulators

INFO_FILES=	dinotrace.info

USE_BUILDLINK_ONLY=	YES
GNU_CONFIGURE=		YES

.include "../../mk/motif.buildlink.mk"
.include "../../mk/bsd.pkg.mk"
