# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/04/12 20:43:27 rillig Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JACK_BUILDLINK3_MK:=	${JACK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njack}
BUILDLINK_PACKAGES+=	jack

.if !empty(JACK_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.jack=	jack>=0.100.0
BUILDLINK_PKGSRCDIR.jack?=	../../audio/jack
.endif	# JACK_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
