# $NetBSD: buildlink3.mk,v 1.2 2006/07/08 22:39:00 jlam Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JACK_BUILDLINK3_MK:=	${JACK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njack}
BUILDLINK_PACKAGES+=	jack
BUILDLINK_ORDER+=	jack

.if !empty(JACK_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.jack=	jack>=0.100.0
BUILDLINK_PKGSRCDIR.jack?=	../../audio/jack
.endif	# JACK_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
