# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:11:05 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
IJS_BUILDLINK3_MK:=	${IJS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ijs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nijs}
BUILDLINK_PACKAGES+=	ijs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ijs

.if !empty(IJS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.ijs+=	ijs>=0.34
BUILDLINK_ABI_DEPENDS.ijs+=	ijs>=0.34nb2
BUILDLINK_PKGSRCDIR.ijs?=	../../print/ijs
.endif	# IJS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
