# $NetBSD: Makefile,v 1.5 1997/10/30 00:31:47 augustss Exp $
#

    SUBDIR += amp
    SUBDIR += cam
    SUBDIR += cddbd
    #SUBDIR += gmod		# GUS specific
    SUBDIR += gsm
    SUBDIR += maplay
    SUBDIR += mikmod
    #SUBDIR += mpegaudio	# obsolete
    SUBDIR += mpg123
    #SUBDIR += mxv		# needs Interviews
    #SUBDIR += nas
    #SUBDIR += nspmod
    #SUBDIR += playmidi		# needs sequencer
    #SUBDIR += radio
    #SUBDIR += rosegarden	# needs sequencer
    #SUBDIR += rplay
    #SUBDIR += rsynth
    #SUBDIR += s3mod		# needs sequencer
    SUBDIR += sox
    #SUBDIR += splay
    SUBDIR += timidity
    #SUBDIR += tosha		# needs libscsi
    SUBDIR += tracker
    #SUBDIR += workman
    #SUBDIR += xcd
    #SUBDIR += xcdplayer
    SUBDIR += xmcd
    SUBDIR += xmix
    SUBDIR += xmmix

.include <bsd.port.subdir.mk>
