# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 17:14:03 joerg Exp $

BUILDLINK_DEPMETHOD.fontsproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FONTSPROTO_BUILDLINK3_MK:=	${FONTSPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	fontsproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfontsproto}
BUILDLINK_PACKAGES+=	fontsproto

.if !empty(FONTSPROTO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.fontsproto+=	fontsproto>=2.0
BUILDLINK_PKGSRCDIR.fontsproto?=	../../x11/fontsproto
.endif	# FONTSPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
