# $NetBSD: Makefile,v 1.1 2004/02/13 18:05:12 jschauma Exp $

DISTNAME= 		opera-acroread5-1.0

MAINTAINER=		jschauma@NetBSD.org
COMMENT=		Acrobat Reader 5 plugin for opera

DEPENDS+=		acroread5-5.[0-9]*:../../print/acroread5
CONFLICTS+=		opera-acroread-[0-9]*
CONFLICTS+=		opera-acroread3-[0-9]*

ACROREAD=		Acrobat5

.include "../../www/opera-acroread/Makefile.common"
