# $NetBSD: buildlink3.mk,v 1.4 2006/02/05 23:08:25 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBOTR_BUILDLINK3_MK:=	${LIBOTR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libotr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibotr}
BUILDLINK_PACKAGES+=	libotr

.if !empty(LIBOTR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libotr+=	libotr>=2.0.1
BUILDLINK_RECOMMENDED.libotr?=	libotr>=2.0.2nb1
BUILDLINK_PKGSRCDIR.libotr?=	../../chat/libotr
.endif	# LIBOTR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
