# $NetBSD: buildlink3.mk,v 1.9 2006/07/08 23:10:38 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBOTR_BUILDLINK3_MK:=	${LIBOTR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libotr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibotr}
BUILDLINK_PACKAGES+=	libotr
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libotr

.if !empty(LIBOTR_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libotr+=	libotr>=3.0.0
BUILDLINK_PKGSRCDIR.libotr?=	../../chat/libotr
.endif	# LIBOTR_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
