# $NetBSD: buildlink3.mk,v 1.5 2006/02/13 14:44:31 salo Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBOTR_BUILDLINK3_MK:=	${LIBOTR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libotr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibotr}
BUILDLINK_PACKAGES+=	libotr

.if !empty(LIBOTR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libotr+=	libotr>=3.0.0
BUILDLINK_PKGSRCDIR.libotr?=	../../chat/libotr
.endif	# LIBOTR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
