# $NetBSD: Makefile,v 1.3 2020/01/18 23:32:28 rillig Exp $

DISTNAME=	mparrows
PKGNAME=	tex-${DISTNAME}-0.1
TEXLIVE_REV=	39729

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/mparrows
COMMENT=	MetaPost module with different types of arrow heads
LICENSE=	public-domain

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
