# $NetBSD: Makefile,v 1.8 2019/07/31 18:49:48 brook Exp $

CATEGORIES=	math R

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	${R_HOMEPAGE_BASE}/abind/
COMMENT=	Combine multi-dimensional arrays
LICENSE=	gnu-lgpl-v2 OR gnu-lgpl-v2.1 OR gnu-lgpl-v3

R_PKGNAME=	abind
R_PKGVER=	1.4-5

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
