# $NetBSD: buildlink3.mk,v 1.3 2006/02/05 23:08:26 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ZEPHYR_BUILDLINK3_MK:=	${ZEPHYR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	zephyr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nzephyr}
BUILDLINK_PACKAGES+=	zephyr

.if !empty(ZEPHYR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.zephyr+=	zephyr>=20010518nb1
BUILDLINK_RECOMMENDED.zephyr?=	zephyr>=20010518nb4
BUILDLINK_PKGSRCDIR.zephyr?=	../../chat/zephyr
BUILDLINK_DEPMETHOD.zephyr?=	build
.endif	# ZEPHYR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
