# $NetBSD: buildlink2.mk,v 1.5 2003/09/28 09:13:59 jlam Exp $
#

.if !defined(KDEBASE_BUILDLINK2_MK)
KDEBASE_BUILDLINK2_MK=	# defined

BUILDLINK_PACKAGES+=			kdebase
BUILDLINK_DEPENDS.kdebase?=		kdebase>=1.1.2nb3
BUILDLINK_PKGSRCDIR.kdebase?=		../../x11/kdebase

EVAL_PREFIX+=	BUILDLINK_PREFIX.kdebase=kdebase
BUILDLINK_PREFIX.kdebase_DEFAULT=	${X11PREFIX}
BUILDLINK_FILES.kdebase+=	include/addressbook.h
BUILDLINK_FILES.kdebase+=	include/bison2cpp.h
BUILDLINK_FILES.kdebase+=	include/booktoken.h
BUILDLINK_FILES.kdebase+=	include/builtin.h
BUILDLINK_FILES.kdebase+=	include/ckey.h
BUILDLINK_FILES.kdebase+=	include/configDB.h
BUILDLINK_FILES.kdebase+=	include/dither.h
BUILDLINK_FILES.kdebase+=	include/drag.h
BUILDLINK_FILES.kdebase+=	include/html.h
BUILDLINK_FILES.kdebase+=	include/htmlclue.h
BUILDLINK_FILES.kdebase+=	include/htmldata.h
BUILDLINK_FILES.kdebase+=	include/htmlfont.h
BUILDLINK_FILES.kdebase+=	include/htmlform.h
BUILDLINK_FILES.kdebase+=	include/htmlframe.h
BUILDLINK_FILES.kdebase+=	include/htmliter.h
BUILDLINK_FILES.kdebase+=	include/htmlobj.h
BUILDLINK_FILES.kdebase+=	include/htmltable.h
BUILDLINK_FILES.kdebase+=	include/htmltoken.h
BUILDLINK_FILES.kdebase+=	include/htmlview.h
BUILDLINK_FILES.kdebase+=	include/jscript.h
BUILDLINK_FILES.kdebase+=	include/jserror.h
BUILDLINK_FILES.kdebase+=	include/jsexec.h
BUILDLINK_FILES.kdebase+=	include/jstree.h
BUILDLINK_FILES.kdebase+=	include/kab.h
BUILDLINK_FILES.kdebase+=	include/kabapi.h
BUILDLINK_FILES.kdebase+=	include/kaccel.h
BUILDLINK_FILES.kdebase+=	include/kapp.h
BUILDLINK_FILES.kdebase+=	include/kaudio.h
BUILDLINK_FILES.kdebase+=	include/kbutton.h
BUILDLINK_FILES.kdebase+=	include/kbuttonbox.h
BUILDLINK_FILES.kdebase+=	include/kcharsets.h
BUILDLINK_FILES.kdebase+=	include/kckey.h
BUILDLINK_FILES.kdebase+=	include/kclipboard.h
BUILDLINK_FILES.kdebase+=	include/kcolorbtn.h
BUILDLINK_FILES.kdebase+=	include/kcolordlg.h
BUILDLINK_FILES.kdebase+=	include/kcolorgroup.h
BUILDLINK_FILES.kdebase+=	include/kcombiview.h
BUILDLINK_FILES.kdebase+=	include/kcombo.h
BUILDLINK_FILES.kdebase+=	include/kconfig.h
BUILDLINK_FILES.kdebase+=	include/kconfigbase.h
BUILDLINK_FILES.kdebase+=	include/kconfigdata.h
BUILDLINK_FILES.kdebase+=	include/kcontainer.h
BUILDLINK_FILES.kdebase+=	include/kcontrol.h
BUILDLINK_FILES.kdebase+=	include/kcursor.h
BUILDLINK_FILES.kdebase+=	include/kdatepik.h
BUILDLINK_FILES.kdebase+=	include/kdatetbl.h
BUILDLINK_FILES.kdebase+=	include/kdbtn.h
BUILDLINK_FILES.kdebase+=	include/kde.pot
BUILDLINK_FILES.kdebase+=	include/kdebug.h
BUILDLINK_FILES.kdebase+=	include/kdir.h
BUILDLINK_FILES.kdebase+=	include/kdirlistbox.h
BUILDLINK_FILES.kdebase+=	include/keditcl.h
BUILDLINK_FILES.kdebase+=	include/keyvaluemap.h
BUILDLINK_FILES.kdebase+=	include/kfilebookmark.h
BUILDLINK_FILES.kdebase+=	include/kfiledetaillist.h
BUILDLINK_FILES.kdebase+=	include/kfiledialog.h
BUILDLINK_FILES.kdebase+=	include/kfilefilter.h
BUILDLINK_FILES.kdebase+=	include/kfileinfo.h
BUILDLINK_FILES.kdebase+=	include/kfileinfocontents.h
BUILDLINK_FILES.kdebase+=	include/kfilepreview.h
BUILDLINK_FILES.kdebase+=	include/kfilesimpleview.h
BUILDLINK_FILES.kdebase+=	include/kfm.h
BUILDLINK_FILES.kdebase+=	include/kfmclient_ipc.h
BUILDLINK_FILES.kdebase+=	include/kfmipc.h
BUILDLINK_FILES.kdebase+=	include/kfontdialog.h
BUILDLINK_FILES.kdebase+=	include/kglobalaccel.h
BUILDLINK_FILES.kdebase+=	include/kiconloader.h
BUILDLINK_FILES.kdebase+=	include/kiconloaderdialog.h
BUILDLINK_FILES.kdebase+=	include/kimgio.h
BUILDLINK_FILES.kdebase+=	include/kintegerline.h
BUILDLINK_FILES.kdebase+=	include/kkeydialog.h
BUILDLINK_FILES.kdebase+=	include/kled.h
BUILDLINK_FILES.kdebase+=	include/kledlamp.h
BUILDLINK_FILES.kdebase+=	include/klined.h
BUILDLINK_FILES.kdebase+=	include/klocale.h
BUILDLINK_FILES.kdebase+=	include/kmenubar.h
BUILDLINK_FILES.kdebase+=	include/kmisc.h
BUILDLINK_FILES.kdebase+=	include/kmsgbox.h
BUILDLINK_FILES.kdebase+=	include/knewpanner.h
BUILDLINK_FILES.kdebase+=	include/knotebook.h
BUILDLINK_FILES.kdebase+=	include/kpanner.h
BUILDLINK_FILES.kdebase+=	include/kpixmap.h
BUILDLINK_FILES.kdebase+=	include/kpoint.h
BUILDLINK_FILES.kdebase+=	include/kpopmenu.h
BUILDLINK_FILES.kdebase+=	include/kpreview.h
BUILDLINK_FILES.kdebase+=	include/kprocctrl.h
BUILDLINK_FILES.kdebase+=	include/kprocess.h
BUILDLINK_FILES.kdebase+=	include/kprocio.h
BUILDLINK_FILES.kdebase+=	include/kprogress.h
BUILDLINK_FILES.kdebase+=	include/kquickhelp.h
BUILDLINK_FILES.kdebase+=	include/krect.h
BUILDLINK_FILES.kdebase+=	include/kremotefile.h
BUILDLINK_FILES.kdebase+=	include/krestrictedline.h
BUILDLINK_FILES.kdebase+=	include/krootprop.h
BUILDLINK_FILES.kdebase+=	include/kruler.h
BUILDLINK_FILES.kdebase+=	include/ksconfig.h
BUILDLINK_FILES.kdebase+=	include/kselect.h
BUILDLINK_FILES.kdebase+=	include/kseparator.h
BUILDLINK_FILES.kdebase+=	include/ksimpleconfig.h
BUILDLINK_FILES.kdebase+=	include/ksize.h
BUILDLINK_FILES.kdebase+=	include/kslider.h
BUILDLINK_FILES.kdebase+=	include/ksock.h
BUILDLINK_FILES.kdebase+=	include/kspell.h
BUILDLINK_FILES.kdebase+=	include/kspelldlg.h
BUILDLINK_FILES.kdebase+=	include/kspinbox.h
BUILDLINK_FILES.kdebase+=	include/kstatusbar.h
BUILDLINK_FILES.kdebase+=	include/kstdaccel.h
BUILDLINK_FILES.kdebase+=	include/kstring.h
BUILDLINK_FILES.kdebase+=	include/ktabbar.h
BUILDLINK_FILES.kdebase+=	include/ktabctl.h
BUILDLINK_FILES.kdebase+=	include/ktablistbox.h
BUILDLINK_FILES.kdebase+=	include/ktmainwindow.h
BUILDLINK_FILES.kdebase+=	include/ktoolbar.h
BUILDLINK_FILES.kdebase+=	include/ktoolboxmgr.h
BUILDLINK_FILES.kdebase+=	include/ktopwidget.h
BUILDLINK_FILES.kdebase+=	include/ktreelist.h
BUILDLINK_FILES.kdebase+=	include/kurl.h
BUILDLINK_FILES.kdebase+=	include/kurllabel.h
BUILDLINK_FILES.kdebase+=	include/kwizard.h
BUILDLINK_FILES.kdebase+=	include/kwm.h
BUILDLINK_FILES.kdebase+=	include/kwmmapp.h
BUILDLINK_FILES.kdebase+=	include/mediatool.h
BUILDLINK_FILES.kdebase+=	include/sections.h
BUILDLINK_FILES.kdebase+=	include/stl_headers.h
BUILDLINK_FILES.kdebase+=	include/xview.h
BUILDLINK_FILES.kdebase+=	lib/libjscript.*
BUILDLINK_FILES.kdebase+=	lib/libkab.*
BUILDLINK_FILES.kdebase+=	lib/libkdecore.*
BUILDLINK_FILES.kdebase+=	lib/libkdeui.*
BUILDLINK_FILES.kdebase+=	lib/libkfile.*
BUILDLINK_FILES.kdebase+=	lib/libkfm.*
BUILDLINK_FILES.kdebase+=	lib/libkhtmlw.*
BUILDLINK_FILES.kdebase+=	lib/libkimgio.*
BUILDLINK_FILES.kdebase+=	lib/libkspell.*
BUILDLINK_FILES.kdebase+=	lib/libmediatool.*

.include "../../devel/ncurses/buildlink2.mk"
.include "../../graphics/libungif/buildlink2.mk"
.include "../../graphics/MesaLib/buildlink2.mk"
.include "../../graphics/glu/buildlink2.mk"
.include "../../graphics/xpm/buildlink2.mk"
.include "../../x11/kdelibs/buildlink2.mk"

BUILDLINK_TARGETS+=	kdebase-buildlink

kdebase-buildlink: _BUILDLINK_USE

.endif	# KDEBASE_BUILDLINK2_MK
