# $NetBSD: Makefile,v 1.4 2023/10/09 04:54:59 pho Exp $

DISTNAME=	open-browser-0.2.1.0
PKGREVISION=	3
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Open a web browser from Haskell
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
