# $NetBSD: Makefile,v 1.5 2021/04/23 12:44:47 pho Exp $

DISTNAME=	split-0.2.3.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Combinator library for splitting lists
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
