# $NetBSD: Makefile,v 1.6 2019/12/06 20:23:01 markd Exp $

DISTNAME=	pdfcomment.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.4a
TEXLIVE_REV=	49047

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/pdfcomment
COMMENT=	Documentation for tex-pdfcomment
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
