# $NetBSD: buildlink3.mk,v 1.4 2006/04/06 06:21:40 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DBH_BUILDLINK3_MK:=	${DBH_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	dbh
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndbh}
BUILDLINK_PACKAGES+=	dbh

.if !empty(DBH_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.dbh+=		dbh>=1.0.22
BUILDLINK_PKGSRCDIR.dbh?=	../../databases/dbh
.endif	# DBH_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
