# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:39 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DBH_BUILDLINK3_MK:=	${DBH_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	dbh
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndbh}
BUILDLINK_PACKAGES+=	dbh
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}dbh

.if !empty(DBH_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.dbh+=		dbh>=1.0.22
BUILDLINK_PKGSRCDIR.dbh?=	../../databases/dbh
.endif	# DBH_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
