# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/05 12:31:06 jmcneill Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY25_KIWI_BUILDLINK3_MK:=	${PY25_KIWI_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py25-kiwi
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy25-kiwi}
BUILDLINK_PACKAGES+=	py25-kiwi
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py25-kiwi

.if ${PY25_KIWI_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.py25-kiwi+=	py25-kiwi>=1.9.22
BUILDLINK_PKGSRCDIR.py25-kiwi?=	../../x11/py-kiwi
.endif	# PY25_KIWI_BUILDLINK3_MK

.include "../../x11/py-gtk2/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
