# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:46 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LWP_BUILDLINK3_MK:=	${LWP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lwp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlwp}
BUILDLINK_PACKAGES+=	lwp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}lwp

.if !empty(LWP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.lwp+=	lwp>=1.6
BUILDLINK_ABI_DEPENDS.lwp+=	lwp>=1.10nb1
BUILDLINK_PKGSRCDIR.lwp?=	../../devel/lwp
.endif	# LWP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
