# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/02/05 21:59:32 adrianp Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBSPF2_BUILDLINK3_MK:=	${LIBSPF2_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libspf2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibspf2}
BUILDLINK_PACKAGES+=	libspf2
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libspf2

.if ${LIBSPF2_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libspf2+=	libspf2>=1.2.5
BUILDLINK_PKGSRCDIR.libspf2?=	../../mail/libspf2
.endif	# LIBSPF2_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
