# $NetBSD: Makefile,v 1.1.1.1 2010/09/11 23:54:24 taca Exp $

DISTNAME=	dm-validations-1.0.2
CATEGORIES=	databases

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/datamapper/dm-validations
COMMENT=	Library for validations on DM models and pure Ruby object
LICENSE=	mit

DEPENDS+=	${RUBY_PKGPREFIX}-dm-core>=1.0.2:../../databases/ruby-dm-core

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
