# $NetBSD: buildlink3.mk,v 1.1 2004/04/25 21:38:03 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SUPERLU_BUILDLINK3_MK:=	${SUPERLU_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	superlu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsuperlu}
BUILDLINK_PACKAGES+=	superlu

.if !empty(SUPERLU_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.superlu+=	superlu>=2.0nb2
BUILDLINK_PKGSRCDIR.superlu?=	../../math/superlu
BUILDLINK_DEPMETHOD.superlu?=	build
.endif	# SUPERLU_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
