# $NetBSD: buildlink3.mk,v 1.9 2006/07/08 23:10:51 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JPEG_BUILDLINK3_MK:=	${JPEG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jpeg
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njpeg}
BUILDLINK_PACKAGES+=	jpeg
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}jpeg

.if !empty(JPEG_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.jpeg+=	jpeg>=6b
BUILDLINK_ABI_DEPENDS.jpeg+=	jpeg>=6bnb2
BUILDLINK_PKGSRCDIR.jpeg?=	../../graphics/jpeg
.endif	# JPEG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
