# $NetBSD: buildlink3.mk,v 1.1 2006/10/19 22:57:13 bouyer Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XENTOOLS30_BUILDLINK3_MK:=	${XENTOOLS30_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xentools30
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxentools30}
BUILDLINK_PACKAGES+=	xentools30
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xentools30

.if ${XENTOOLS30_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xentools30+=	xentools30>=3.0.2.2
BUILDLINK_PKGSRCDIR.xentools30?=	../../sysutils/xentools30
.endif	# XENTOOLS30_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
