# $NetBSD: Makefile,v 1.13 2025/02/02 13:05:21 pho Exp $

DISTNAME=	safe-0.3.21
PKGREVISION=	2
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Library for safe (pattern match free) functions
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
