# $NetBSD: buildlink3.mk,v 1.3 2004/11/30 18:26:41 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_GNOME_BUILDLINK3_MK:=	${PY_GNOME_BUILDLINK3_MK}+

.include "../../lang/python/pyversion.mk"

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pygnome
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npygnome}
BUILDLINK_PACKAGES+=	pygnome

.if !empty(PY_GNOME_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pygnome+=	${PYPKGPREFIX}-gnome>=1.4.4nb7
BUILDLINK_PKGSRCDIR.pygnome?=	../../x11/gnome-python
.endif	# PY_GNOME_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
