# $NetBSD: buildlink3.mk,v 1.4 2006/04/12 10:27:02 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENAL_BUILDLINK3_MK:=	${OPENAL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	openal
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenal}
BUILDLINK_PACKAGES+=	openal

.if !empty(OPENAL_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.openal+=	openal>=20030125nb1
BUILDLINK_ABI_DEPENDS.openal?=	openal>=20040816nb1
BUILDLINK_PKGSRCDIR.openal?=	../../audio/openal
.endif	# OPENAL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
