# $NetBSD: buildlink3.mk,v 1.7 2007/01/03 07:03:15 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENAL_BUILDLINK3_MK:=	${OPENAL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	openal
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenal}
BUILDLINK_PACKAGES+=	openal
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}openal

.if !empty(OPENAL_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.openal+=	openal>=0.0.8
BUILDLINK_PKGSRCDIR.openal?=	../../audio/openal
.endif	# OPENAL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
