# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:10:37 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSIDPLAY_BUILDLINK3_MK:=	${LIBSIDPLAY_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libsidplay
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsidplay}
BUILDLINK_PACKAGES+=	libsidplay
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libsidplay

.if !empty(LIBSIDPLAY_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libsidplay+=		libsidplay>=1.36.38
BUILDLINK_ABI_DEPENDS.libsidplay+=	libsidplay>=1.36.59nb2
BUILDLINK_PKGSRCDIR.libsidplay?=	../../audio/libsidplay
.endif	# LIBSIDPLAY_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
