# $NetBSD: Makefile,v 1.3 2019/12/06 19:29:43 markd Exp $

DISTNAME=	cinzel.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2019
TEXLIVE_REV=	51101

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/cinzel
COMMENT=	Documentation for tex-cinzel
LICENSE=	ofl-v1.1 AND lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
