# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:35 wiz Exp $

DISTNAME=	cinzel.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2014
TEXLIVE_REV=	34408

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/cinzel
COMMENT=	Documentation for tex-cinzel
LICENSE=	ofl-v1.1

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
