# $NetBSD: Makefile,v 1.4 2019/07/31 15:27:53 brook Exp $

CATEGORIES=	devel R

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	${R_HOMEPAGE_BASE}/lazyeval/
COMMENT=	Lazy (non-standard) evaluation
LICENSE=	gnu-gpl-v3

R_PKGNAME=	lazyeval
R_PKGVER=	0.2.2

USE_LANGUAGES=	c

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
