# $NetBSD: Makefile,v 1.2 2023/11/02 06:37:25 pho Exp $

DISTNAME=	posix-paths-0.3.0.0
PKGREVISION=	1
CATEGORIES=	sysutils

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	POSIX filepath/directory functionality
LICENSE=	modified-bsd

.include "../../devel/hs-unliftio/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
