# $NetBSD: Makefile,v 1.3 2020/10/25 03:19:22 wen Exp $

R_PKGNAME=	Formula
R_PKGVER=	1.2-4
CATEGORIES=	math

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Extended model formulas
LICENSE=	gnu-gpl-v2 OR gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
