# $NetBSD: buildlink3.mk,v 1.1 2004/04/11 03:16:36 rh Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GWLIB_BUILDLINK3_MK:=	${GWLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	GWLib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NGWLib}
BUILDLINK_PACKAGES+=	GWLib

.if !empty(GWLIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.GWLib?=	GWLib>=0.5.3nb2
BUILDLINK_RECOMMENDED.GWLib?=	GWLib>=0.5.3nb4
BUILDLINK_PKGSRCDIR.GWLib?=	../../sysutils/GWLib
.endif	# GWLIB_BUILDLINK3_MK

.include "../../x11/gnustep-back/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
