$NetBSD: patch-rebar.config.script,v 1.1 2015/11/04 13:45:46 fhajny Exp $

Deps are handled by pkgsrc.

--- rebar.config.script.orig	2015-10-07 13:51:14.000000000 +0000
+++ rebar.config.script
@@ -13,8 +13,6 @@ Config = [
     {port_env, [{"CFLAGS", "$CFLAGS " ++ CfgCFlags},
 	        {"LDFLAGS", "$LDFLAGS " ++ CfgLDFlags}]},
 
-    {deps, [{p1_utils, ".*", {git, "git://github.com/processone/p1_utils"}}]},
-
     {port_specs, [{"priv/lib/p1_yaml.so", ["c_src/p1_yaml.c"]}]}
 ].
 
