# $NetBSD: Makefile,v 1.3 2019/12/06 20:19:33 markd Exp $

DISTNAME=	everypage.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.1
TEXLIVE_REV=	15878

MAINTAINER=	reed@reedmedia.net
COMMENT=	Documentation for tex-everypage
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
