# $NetBSD: Makefile,v 1.2 2002/10/30 03:11:19 rh Exp $
#

.include "Makefile.common"

COMMENT=		GNU Database access library

PKGCONFIG_OVERRIDE=	${WRKSRC}/libgda.pc.in

.include "../../mk/bsd.pkg.mk"
