$NetBSD: patch-Cargo.toml,v 1.1 2020/03/14 22:40:47 tnn Exp $

disable rust debug_info in shared libraries

--- Cargo.toml.orig	2020-02-13 00:58:58.000000000 +0000
+++ Cargo.toml
@@ -6,4 +6,4 @@ members = [
 ]
 
 [profile.release]
-debug = true
+debug = false
