$NetBSD: patch-pyproject.toml,v 1.1 2026/03/05 16:40:32 wiz Exp $

https://gitlab.torproject.org/tpo/network-health/sbws/-/merge_requests/242

--- pyproject.toml.orig	2025-10-15 08:10:52.000000000 +0000
+++ pyproject.toml
@@ -84,8 +84,9 @@ include-package-data = true
 [tool.setuptools]
 include-package-data = true
 
-[tool.setuptools.packages]
-find = {namespaces = false}
+[tool.setuptools.packages.find]
+namespaces = false
+exclude = ["tests*"]
 
 [tool.setuptools.package-data]
 tests = ["*"]
