# $NetBSD: Makefile,v 1.57 2025/04/24 14:15:24 wiz Exp $

DISTNAME=	kdenetwork-filesharing-${_KDE_VERSION}
PKGREVISION=	48
CATEGORIES=	net
COMMENT=	Properties dialog plugin to share directory with local network

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
