# $NetBSD: buildlink3.mk,v 1.6 2025/02/24 16:39:46 manu Exp $

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE_BUILDLINK3_MK)
SOPE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=2.4.3<3
BUILDLINK_ABI_DEPENDS.SOPE+=	SOPE>=2.4.3<3
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE
.endif # SOPE_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
