# $NetBSD: buildlink3.mk,v 1.4 2015/09/25 06:00:29 taca Exp $

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE_BUILDLINK3_MK)
SOPE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=2.3.2
BUILDLINK_ABI_DEPENDS.SOPE+=	SOPE>=2.3.0
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE
.endif # SOPE_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
