# $NetBSD: buildlink3.mk,v 1.5 2023/07/03 12:46:09 wiz Exp $

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE_BUILDLINK3_MK)
SOPE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=2.3.2<3
BUILDLINK_ABI_DEPENDS.SOPE+=	SOPE>=2.3.0<3
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE
.endif # SOPE_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
