# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:11:00 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBUTF_BUILDLINK3_MK:=	${LIBUTF_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libutf
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibutf}
BUILDLINK_PACKAGES+=	libutf
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libutf

.if ${LIBUTF_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libutf+=	libutf>=3.0
BUILDLINK_PKGSRCDIR.libutf?=	../../misc/libutf
.endif	# LIBUTF_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
