#	$NetBSD: sfiles-x86_64.mk,v 1.1 2012/12/11 14:47:17 ryoon Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	amd64/jvm.cfg
SFILES+=	calendars.properties
SFILES+=	content-types.properties
SFILES+=	deploy/messages_zh_HK.properties
SFILES+=	deploy/messages_es.properties
SFILES+=	deploy/messages.properties
SFILES+=	deploy/messages_zh_CN.properties
SFILES+=	deploy/messages_ja.properties
SFILES+=	deploy/messages_sv.properties
SFILES+=	deploy/messages_fr.properties
SFILES+=	deploy/messages_ko.properties
SFILES+=	deploy/messages_de.properties
SFILES+=	deploy/messages_pt_BR.properties
SFILES+=	deploy/messages_it.properties
SFILES+=	deploy/messages_zh_TW.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.RedHat.5.bfc
SFILES+=	fontconfig.RedHat.5.properties.src
SFILES+=	fontconfig.RedHat.6.bfc
SFILES+=	fontconfig.RedHat.6.properties.src
SFILES+=	fontconfig.SuSE.10.bfc
SFILES+=	fontconfig.SuSE.10.properties.src
SFILES+=	fontconfig.SuSE.11.bfc
SFILES+=	fontconfig.SuSE.11.properties.src
SFILES+=	fontconfig.Turbo.bfc
SFILES+=	fontconfig.Turbo.properties.src
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	images/cursors/cursors.properties
SFILES+=	javafx.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	sound.properties
