#	$NetBSD: sfiles-solaris-i386.mk,v 1.1 2013/03/06 16:21:13 jperkin Exp $
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	calendars.properties
SFILES+=	content-types.properties
SFILES+=	deploy/messages_es.properties
SFILES+=	deploy/messages_zh_TW.properties
SFILES+=	deploy/messages_ko.properties
SFILES+=	deploy/messages_fr.properties
SFILES+=	deploy/messages_pt_BR.properties
SFILES+=	deploy/messages_ja.properties
SFILES+=	deploy/messages_it.properties
SFILES+=	deploy/messages_sv.properties
SFILES+=	deploy/messages_zh_CN.properties
SFILES+=	deploy/messages_de.properties
SFILES+=	deploy/messages_zh_HK.properties
SFILES+=	deploy/messages.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	i386/jvm.cfg
SFILES+=	images/cursors/cursors.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	security/ucrypto-solaris.cfg
SFILES+=	security/sunpkcs11-solaris.cfg
SFILES+=	sound.properties
