# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:46 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBTAR_BUILDLINK3_MK:=	${LIBTAR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libtar
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibtar}
BUILDLINK_PACKAGES+=	libtar
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libtar

.if !empty(LIBTAR_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libtar+=	libtar>=1.2.11
BUILDLINK_PKGSRCDIR.libtar?=	../../devel/libtar
.endif	# LIBTAR_BUILDLINK3_MK

.include "../../devel/zlib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
