# $NetBSD: buildlink3.mk,v 1.2 2004/03/05 19:25:11 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBTAR_BUILDLINK3_MK:=	${LIBTAR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libtar
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibtar}
BUILDLINK_PACKAGES+=	libtar

.if !empty(LIBTAR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libtar+=	libtar>=1.2.11
BUILDLINK_PKGSRCDIR.libtar?=	../../devel/libtar

.include "../../devel/zlib/buildlink3.mk"

.endif	# LIBTAR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
