# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/02/26 19:14:12 minskim Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
EVAS_SOFTWARE_X11_BUILDLINK3_MK:=	${EVAS_SOFTWARE_X11_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	evas-software-x11
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nevas-software-x11}
BUILDLINK_PACKAGES+=	evas-software-x11
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}evas-software-x11

.if ${EVAS_SOFTWARE_X11_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.evas-software-x11+=	evas-software-x11>=0.9.9.050
BUILDLINK_PKGSRCDIR.evas-software-x11?=	../../graphics/evas-software-x11
.endif	# EVAS_SOFTWARE_X11_BUILDLINK3_MK

.include "../../x11/libX11/buildlink3.mk"

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH:S/+$//}
