# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/04 00:21:36 adrianp Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BIND_BUILDLINK3_MK:=	${BIND_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	bind
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbind}
BUILDLINK_PACKAGES+=	bind
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}bind

.if ${BIND_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.bind+=	bind>=9.6.0
BUILDLINK_PKGSRCDIR.bind?=	../../net/bind96
.endif	# BIND_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
