# $NetBSD: buildlink3.mk,v 1.4 2004/01/24 03:26:46 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
DLCOMPAT_BUILDLINK3_MK:=	${DLCOMPAT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	dlcompat
.endif

.if !empty(DLCOMPAT_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		dlcompat
BUILDLINK_DEPENDS.dlcompat+=	dlcompat>=20020606
BUILDLINK_PKGSRCDIR.dlcompat?=	../../devel/dlcompat
.endif  # DLCOMPAT_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
