# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 23:10:45 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBMEMCACHE_BUILDLINK3_MK:=	${LIBMEMCACHE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmemcache
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmemcache}
BUILDLINK_PACKAGES+=	libmemcache
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmemcache

.if !empty(LIBMEMCACHE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libmemcache+=	libmemcache>=1.4.0beta5
BUILDLINK_PKGSRCDIR.libmemcache?=	../../devel/libmemcache
.endif	# LIBMEMCACHE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
