# $NetBSD: Makefile,v 1.5 2026/03/29 03:43:11 markd Exp $

DISTNAME=	fontaxes.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.0.2
TEXLIVE_REV=	77682

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/fontaxes
COMMENT=	Documentation for tex-fontaxes
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
