# $NetBSD: Makefile,v 1.3 2021/05/03 19:00:58 pho Exp $

DISTNAME=	either-5.0.1.1
PKGREVISION=	1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Combinators for working with sums
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../math/hs-bifunctors/buildlink3.mk"
.include "../../math/hs-profunctors/buildlink3.mk"
.include "../../math/hs-semigroupoids/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
