.\"	$NetBSD: url2pkg.8,v 1.15 2022/01/01 14:04:11 rillig Exp $
.\"
.\" Copyright (c) 2001, 2019 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Emmanuel Dreyfus and Roland Illig.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd January 1, 2022
.Dt URL2PKG 8
.Os
.Sh NAME
.Nm url2pkg
.Nd Automatic pkgsrc package generator
.Sh SYNOPSIS
.Nm
.Op Fl v|--verbose
.Op Ar URL
.Sh DESCRIPTION
.Nm
takes the
.Ar URL
to a package's distfile that should be turned into a package.
It fetches the distfile, extracts it, and by looking at the extracted files,
fills in some variables in the package
.Pa Makefile .
.Pp
.Nm
helps creating a package;
it is not intended to fly on autopilot, though.
.Pp
.Sh ENVIRONMENT
.Bl -tag -width indent
.It PKGMAINTAINER, REPLYTO
Name used for the MAINTAINER field in the package
.Pa Makefile .
.El
.Sh EXAMPLES
The following command will generate a template pkgsrc package
for the software that can be found at
.Lk https://www.example.org/download/buz-19.3.tar.gz :
.Bd -literal
url2pkg https://www.example.org/download/buz-19.3.tar.gz
.Ed
.Sh SEE ALSO
.Xr pkgsrc 7
.Sh AUTHORS
.An Roland Illig Aq Mt rillig@NetBSD.org
wrote the current version.
.An Hubert Feyrer Aq Mt hubertf@NetBSD.org
wrote the initial version.
.An Emmanuel Dreyfus Aq Mt manu@NetBSD.org
initially wrote this man page.
