# $NetBSD: Makefile,v 1.26 2020/06/02 08:06:14 adam Exp $

MPG123_MODULE=	pulse

.include "../../audio/mpg123/Makefile.common"

.include "../../audio/mpg123/buildlink3.mk"
.include "../../audio/pulseaudio/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
