$NetBSD: patch-setup.py,v 1.5 2021/11/19 21:53:29 adam Exp $

Use setuptools.

--- setup.py.orig	2021-11-19 14:22:46.000000000 +0000
+++ setup.py
@@ -1,7 +1,7 @@
 #!/usr/bin/env python
 # setup.py generated by flit for tools that don't yet use PEP 517
 
-from distutils.core import setup
+from setuptools import setup
 
 packages = \
 ['weasyprint',
