# $NetBSD: buildlink3.mk,v 1.5 2006/04/12 10:27:01 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBA52_BUILDLINK3_MK:=	${LIBA52_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	liba52
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nliba52}
BUILDLINK_PACKAGES+=	liba52

.if !empty(LIBA52_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.liba52+=	liba52>=0.7.4
BUILDLINK_ABI_DEPENDS.liba52+=	liba52>=0.7.4nb3
BUILDLINK_PKGSRCDIR.liba52?=	../../audio/liba52
.endif	# LIBA52_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
