# $NetBSD: buildlink3.mk,v 1.4 2004/03/18 09:12:11 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CAL3D_BUILDLINK3_MK:=	${CAL3D_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cal3d
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncal3d}
BUILDLINK_PACKAGES+=	cal3d

.if !empty(CAL3D_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.cal3d+=	cal3d>=0.9.1
BUILDLINK_PKGSRCDIR.cal3d?=	../../graphics/cal3d
.endif	# CAL3D_BUILDLINK3_MK

.include "../../graphics/Mesa/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
