# $NetBSD: Makefile,v 1.2 2015/04/22 10:15:29 markd Exp $

DISTNAME=	bezos.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-25507
TEXLIVE_REV=	25507

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-bezos

CONFLICTS=	teTeX-texmf<=3.0nb29

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
