# $NetBSD: Makefile,v 1.7 2012/10/31 11:19:47 asau Exp $
#

DISTNAME=	spiff-1.0
PKGREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://www.darwinsys.com/freeware/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.darwinsys.com/freeware/
COMMENT=	Make controlled approximate comparisons between files

AUTO_MKDIRS=	yes
BUILD_TARGET=	spiff

.include "../../mk/termcap.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
