# $NetBSD: Makefile,v 1.3 2019/12/06 20:18:44 markd Exp $

DISTNAME=	abstract.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.2a
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Documentation for tex-abstract
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
