# $NetBSD: Makefile,v 1.1 2015/05/14 17:07:35 wiz Exp $

DISTNAME=	r_und_s.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.3i
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/r_und_s
COMMENT=	Documentation for tex-r_und_s
#LICENSE=	other-free

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
