# $NetBSD: Makefile,v 1.29 2018/12/13 19:52:00 adam Exp $

DISTNAME=	kde-base-artwork-15.08.3
PKGREVISION=	10
CATEGORIES=	graphics
COMMENT=	KDE KSplash theme
MASTER_SITES=	${MASTER_SITE_KDE:=applications/15.08.3/src/}

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
