# $NetBSD: buildlink3.mk,v 1.2 2006/07/20 17:53:42 minskim Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
GRAPHICSMAGICK_BUILDLINK3_MK:=	${GRAPHICSMAGICK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	GraphicsMagick
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NGraphicsMagick}
BUILDLINK_PACKAGES+=	GraphicsMagick
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}GraphicsMagick

.if ${GRAPHICSMAGICK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.GraphicsMagick+=	GraphicsMagick>=1.1.7
BUILDLINK_PKGSRCDIR.GraphicsMagick?=	../../graphics/GraphicsMagick
.endif	# GRAPHICSMAGICK_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
