# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:11:01 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBDVDREAD_BUILDLINK3_MK:=	${LIBDVDREAD_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdvdread
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdvdread}
BUILDLINK_PACKAGES+=	libdvdread
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libdvdread

.if !empty(LIBDVDREAD_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libdvdread+=		libdvdread>=0.9.4
BUILDLINK_ABI_DEPENDS.libdvdread+=	libdvdread>=0.9.5nb2
BUILDLINK_PKGSRCDIR.libdvdread?=	../../multimedia/libdvdread
.endif	# LIBDVDREAD_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
