# $NetBSD: buildlink3.mk,v 1.3 2004/10/03 00:13:02 tv Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBDVDREAD_BUILDLINK3_MK:=	${LIBDVDREAD_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdvdread
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdvdread}
BUILDLINK_PACKAGES+=	libdvdread

.if !empty(LIBDVDREAD_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libdvdread+=		libdvdread>=0.9.4
BUILDLINK_RECOMMENDED.libdvdread+=	libdvdread>=0.9.4nb1
BUILDLINK_PKGSRCDIR.libdvdread?=	../../multimedia/libdvdread
.endif	# LIBDVDREAD_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
