# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/11/24 02:09:31 minskim Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TECKIT_BUILDLINK3_MK:=	${TECKIT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	TECkit
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NTECkit}
BUILDLINK_PACKAGES+=	TECkit
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}TECkit

.if ${TECKIT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.TECkit+=	TECkit>=2.5.1
BUILDLINK_PKGSRCDIR.TECkit?=	../../converters/TECkit
.endif	# TECKIT_BUILDLINK3_MK

.include "../../devel/zlib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
