$NetBSD: patch-Cargo.toml,v 1.13 2022/08/30 20:39:22 pin Exp $

Don't force ncurses backend.
Disable Windows only features to again avoid forcing ncurses.

--- Cargo.toml.orig	2022-08-20 22:07:08.000000000 +0000
+++ Cargo.toml
@@ -29,7 +29,6 @@ librespot-core = "0.4.2"
 librespot-playback = "0.4.2"
 librespot-protocol = "0.4.2"
 log = "0.4.16"
-pancurses = {version = "0.17.0", optional = true}
 parse_duration = "2.1.1"
 platform-dirs = "0.3.0"
 rand = "0.8"
@@ -70,7 +69,7 @@ cover = ["ioctl-rs"] # Support displayin
 default = ["share_clipboard", "pulseaudio_backend", "mpris", "notify", "termion_backend"]
 mpris = ["dbus", "dbus-tree"] # Allow ncspot to be controlled via MPRIS API
 notify = ["notify-rust"] # Show what's playing via a notification
-pancurses_backend = ["cursive/pancurses-backend", "pancurses/win32"]
+pancurses_backend = ["cursive/pancurses-backend"]
 portaudio_backend = ["librespot-playback/portaudio-backend"]
 pulseaudio_backend = ["librespot-playback/pulseaudio-backend"]
 rodio_backend = ["librespot-playback/rodio-backend"]
