# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/07/21 16:22:42 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PKG_CONFIG_BUILDLINK3_MK:=	${PKG_CONFIG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pkg-config
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npkg-config}
BUILDLINK_PACKAGES+=	pkg-config

.if !empty(PKG_CONFIG_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pkg-config+=	pkg-config>=0.15.0
BUILDLINK_PKGSRCDIR.pkg-config?=	../../devel/pkg-config
BUILDLINK_DEPMETHOD.pkg-config?=	build

PKG_CONFIG_LIBDIR?=	${BUILDLINK_DIR}/lib/pkgconfig
CONFIGURE_ENV+=		PKG_CONFIG=${BUILDLINK_PREFIX.pkg-config}/bin/pkg-config
CONFIGURE_ENV+=		PKG_CONFIG_LIBDIR=${PKG_CONFIG_LIBDIR:Q}
MAKE_ENV+=		PKG_CONFIG=${BUILDLINK_PREFIX.pkg-config}/bin/pkg-config
MAKE_ENV+=		PKG_CONFIG_LIBDIR=${PKG_CONFIG_LIBDIR:Q}

.endif	# PKG_CONFIG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
