# $NetBSD: buildlink3.mk,v 1.1 2025/09/21 15:09:03 wiz Exp $

BUILDLINK_TREE+=	OpenJPH

.if !defined(OPENJPH_BUILDLINK3_MK)
OPENJPH_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.OpenJPH+=	OpenJPH>=0.23.1
BUILDLINK_PKGSRCDIR.OpenJPH?=	../../graphics/OpenJPH

.endif	# OPENJPH_BUILDLINK3_MK

BUILDLINK_TREE+=	-OpenJPH
