# $NetBSD: buildlink3.mk,v 1.5 2026/09/26 09:43:02 wiz Exp $

BUILDLINK_TREE+=	OpenJPH

.if !defined(OPENJPH_BUILDLINK3_MK)
OPENJPH_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.OpenJPH+=	OpenJPH>=0.23.1
BUILDLINK_ABI_DEPENDS.OpenJPH?=	OpenJPH>=0.32.0
BUILDLINK_PKGSRCDIR.OpenJPH?=	../../graphics/OpenJPH

.endif	# OPENJPH_BUILDLINK3_MK

BUILDLINK_TREE+=	-OpenJPH
