# $NetBSD: buildlink3.mk,v 1.3 2026/06/23 09:35:25 wiz Exp $

BUILDLINK_TREE+=	OpenJPH

.if !defined(OPENJPH_BUILDLINK3_MK)
OPENJPH_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.OpenJPH+=	OpenJPH>=0.23.1
BUILDLINK_ABI_DEPENDS.OpenJPH?=	OpenJPH>=0.30.1
BUILDLINK_PKGSRCDIR.OpenJPH?=	../../graphics/OpenJPH

.endif	# OPENJPH_BUILDLINK3_MK

BUILDLINK_TREE+=	-OpenJPH
