# $NetBSD: buildlink3.mk,v 1.8 2004/05/17 21:32:33 seb Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
AUDIOFILE_BUILDLINK3_MK:=	${AUDIOFILE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	audiofile
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Naudiofile}
BUILDLINK_PACKAGES+=	audiofile

.if !empty(AUDIOFILE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.audiofile+=	libaudiofile>=0.2.1
BUILDLINK_PKGSRCDIR.audiofile?=	../../audio/libaudiofile
.endif	# AUDIOFILE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
