$NetBSD: patch-common.h,v 1.1 2026/04/14 14:26:36 christos Exp $

Use our hacked ctype.h

--- common.h.orig	2026-04-14 10:11:39.960134314 -0400
+++ common.h	2026-04-14 10:11:57.914301169 -0400
@@ -7,7 +7,7 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 
-#include <ctype.h>
+#include "myctype.h"
 #include "config.h"	/* generated by installation script */
 #include "config2.h"
 
