/* $NetBSD: config.h,v 1.1 2002/01/22 12:16:21 kent Exp $ */
#define HAVE_ALLOCA 1
#define pid_t int
#define STDC_HEADERS 1
#define HAVE_SYS_ERRLIST 1
#define HAVE_SYS_NERR 1
#define HAVE_STRERROR 1
#define HAVE_ATEXIT 1
#define HAVE_CALLOC 1
#define HAVE_CLOCK 1
#define HAVE_GETCWD 1
#define HAVE_MEMCHR 1
#define HAVE_MEMCMP 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMSET 1
#define HAVE_PUTENV 1
#define HAVE_RENAME 1
#define HAVE_STRCASECMP 1
#define HAVE_STRCHR 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOD 1
#define HAVE_STRTOL 1
#define HAVE_STRTOUL 1
#define HAVE_TMPNAM 1
#define HAVE_VFPRINTF 1
#define HAVE_VPRINTF 1
#define HAVE_VSPRINTF 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
