# $NetBSD: buildlink3.mk,v 1.8 2004/10/03 00:14:51 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLUT_BUILDLINK3_MK:=	${GLUT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glut
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglut}
BUILDLINK_PACKAGES+=	glut

.if !empty(GLUT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.glut+=	glut>=${_MESA_REQD}
BUILDLINK_RECOMMENDED.glut+=	glut>=6.0.1nb1
BUILDLINK_PKGSRCDIR.glut?=	../../graphics/glut
.endif	# GLUT_BUILDLINK3_MK

MESA_REQD+=	6.0

.include "../../graphics/MesaLib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
