# $NetBSD: buildlink3.mk,v 1.1 2008/06/15 10:33:38 gavan Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
QRENCODE_BUILDLINK3_MK:=	${QRENCODE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	qrencode
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nqrencode}
BUILDLINK_PACKAGES+=	qrencode
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}qrencode

.if ${QRENCODE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.qrencode+=	qrencode>=3.0.3
BUILDLINK_PKGSRCDIR.qrencode?=	../../converters/qrencode
.endif	# QRENCODE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
