# $NetBSD: Makefile,v 1.25 2016/04/26 09:04:23 markd Exp $

DISTNAME=	phonon-backend-gstreamer-4.9.0

COMMENT=	Multimedia API for KDE and QT - GStreamer backend

.include "Makefile.common"

DEPENDS+=	phonon-backend-gstreamer-shared-4.9.0:../../multimedia/phonon-backend-gstreamer-shared

.include "../../multimedia/phonon/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
