# $NetBSD: Makefile,v 1.10 2006/10/27 20:18:58 markd Exp $

KOFFICE_LANGUAGE=	Czech
KOFFICE_LANGCODE=	cs
PKGREVISION=		5

DEPENDS+=	koffice-[0-9]*:../../misc/koffice

.include "../../misc/koffice/i18n.mk"
.include "../../mk/bsd.pkg.mk"
