# $NetBSD: buildlink3.mk,v 1.5 2004/03/05 19:25:11 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBMM_BUILDLINK3_MK:=	${LIBMM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmm}
BUILDLINK_PACKAGES+=	libmm

.if !empty(LIBMM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libmm+=	libmm>=1.2.1
BUILDLINK_PKGSRCDIR.libmm?=	../../devel/libmm
.endif	# LIBMM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
