# $NetBSD: buildlink3.mk,v 1.9 2006/07/08 23:10:45 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBMM_BUILDLINK3_MK:=	${LIBMM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmm}
BUILDLINK_PACKAGES+=	libmm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmm

.if !empty(LIBMM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libmm+=	libmm>=1.2.1
BUILDLINK_ABI_DEPENDS.libmm+=	libmm>=1.2.2nb1
BUILDLINK_PKGSRCDIR.libmm?=	../../devel/libmm
.endif	# LIBMM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
