# $NetBSD: Makefile,v 1.2 2022/02/12 08:50:39 pho Exp $

DISTNAME=	th-lift-instances-0.1.19
PKGREVISION=	1
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Lift instances for template-haskell for common data types
LICENSE=	modified-bsd

.include "../../devel/hs-th-lift/buildlink3.mk"
.include "../../devel/hs-vector/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
