$NetBSD: patch-pyproject.toml,v 1.1 2026/02/16 19:02:57 adam Exp $

Don't install unnecessay files.

--- pyproject.toml.orig	2026-02-16 18:51:29.071444830 +0000
+++ pyproject.toml
@@ -49,9 +49,9 @@ module-name = "uv"
 python-source = "python"
 strip = true
 include = [
-    { path = "rust-toolchain.toml", format = ["sdist", "wheel"] },
+    { path = "rust-toolchain.toml", format = "sdist" },
     # this one isn't discovered by maturin because it's behind a feature flag
-    { path = "crates/uv-performance-memory-allocator/**/*", format = ["sdist", "wheel"] },
+    { path = "crates/uv-performance-memory-allocator/**/*", format = "sdist" },
     { path = "crates/uv-trampoline-builder/trampolines/*", format = "sdist" },
     { path = "LICENSE-APACHE", format = "sdist" },
     { path = "LICENSE-MIT", format = "sdist" },
