# $NetBSD: Makefile,v 1.6 2021/05/03 19:01:04 pho Exp $

DISTNAME=	transformers-compat-0.6.6
PKGREVISION=	1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Small compatibility shim exposing the new types
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-fail/buildlink3.mk"
.include "../../devel/hs-generic-deriving/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
