# $NetBSD: Makefile,v 1.13 2021/01/16 13:17:38 taca Exp $

DISTNAME=	websocket-1.2.9
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	ruby www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/imanel/websocket-ruby
COMMENT=	Universal Ruby library to handle WebSocket protocol
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
