$NetBSD: patch-makefile.conf,v 1.2 2025/10/03 11:54:06 dkazankov Exp $

Add externally settable options for gprbuild
Add NetBSD support

--- makefile.conf.orig	2024-12-20 16:02:53.000000000 +0200
+++ makefile.conf
@@ -5,7 +5,7 @@
 #
 # IMPORTANT: each time you change the definitions here make sure you run
 #            $ make setup
-
+GPRBUILD_OPTIONS =
 #  Is out of tree build
 ifneq ($(BLD_DIR), $(SRC_DIR))
 GPROOTOPTS = --relocate-build-tree=$(BLD_DIR) --root-dir=$(SRC_DIR)
@@ -50,7 +50,7 @@
 ENABLE_SHARED=$(shell gprbuild -c -q -p $(GPROOTOPTS) \
                 -XTARGET=$(TARGET) -XPRJ_TARGET=$(PRJ_TARGET) \
                 -XTGT_DIR=$(TGT_DIR) \
-		-P$(SRC_DIR)/config/setup/test_shared 2>/dev/null \
+		-P$(SRC_DIR)/config/setup/test_shared $(GPRBUILD_OPTIONS) 2>/dev/null \
                 && echo "true")
 
 ##############################################################################
@@ -92,7 +92,7 @@
 ZLIB	= $(shell gprbuild -q -p $(GPROOTOPTS) \
                   -XTARGET=$(TARGET) -XPRJ_TARGET=$(PRJ_TARGET) \
                   -XTGT_DIR=$(TGT_DIR) \
-                  -Pconfig/setup/test_zlib 2>/dev/null \
+                  -Pconfig/setup/test_zlib $(GPRBUILD_OPTIONS) 2>/dev/null \
                   && $(BLD_DIR)/$(TARGET)/setup/zobj/mzlib \
 		  && echo "true")
 
@@ -213,8 +213,12 @@
 ifeq ($(strip $(findstring freebsd, $(TARGET))),freebsd)
    PRJ_TARGET = freebsd
 else
+ifeq ($(strip $(findstring netbsd, $(TARGET))),netbsd)
+   PRJ_TARGET = freebsd
+else
    PRJ_TARGET = UNIX
 endif
+endif
 OS      = UNIX
 endif
 endif
@@ -289,7 +293,7 @@
 		-XPRJ_TARGET=$(PRJ_TARGET) -XTARGET=$(TARGET) \
 	        -XTHREAD_SANITIZER=$(THREAD_SANITIZER) \
                 -XSSL_DYNAMIC=$(SSL_DYNAMIC) -XTGT_DIR=$(TGT_DIR) \
-		$(GPROOTOPTS)
+		$(GPROOTOPTS) $(GPRBUILD_OPTIONS)
 export GPROPTS
 
 GPR_STATIC = -XLIBRARY_TYPE=static -XXMLADA_BUILD=static
