# $NetBSD: buildlink3.mk,v 1.5 2006/04/12 10:27:08 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GTL_BUILDLINK3_MK:=	${GTL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gtl
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngtl}
BUILDLINK_PACKAGES+=	gtl

.if !empty(GTL_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.gtl+=		gtl>=1.2.0
BUILDLINK_PKGSRCDIR.gtl?=	../../devel/gtl
.endif	# GTL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
