$NetBSD: patch-boost_test_impl_execution__monitor.ipp,v 1.3 2019/07/01 04:00:10 ryoon Exp $

--- boost/test/impl/execution_monitor.ipp.orig	2019-04-09 19:36:35.000000000 +0000
+++ boost/test/impl/execution_monitor.ipp
@@ -171,7 +171,8 @@ namespace { void _set_se_translator( voi
 #  if defined(SIGPOLL) && !defined(__CYGWIN__)                              && \
       !(defined(macintosh) || defined(__APPLE__) || defined(__APPLE_CC__))  && \
       !defined(__NetBSD__)                                                  && \
-      !defined(__QNXNTO__)
+      !defined(__QNXNTO__)                                                  && \
+      !defined(__DragonFly__)
 #    define BOOST_TEST_CATCH_SIGPOLL
 #  endif
 
@@ -391,14 +392,18 @@ system_signal_exception::report() const
         report_error( execution_exception::system_error,
                       "signal: the expiration of a timer set by timer_settimer()" );
         break;
+#if defined(SI_ASYNCIO)
     case SI_ASYNCIO:
         report_error( execution_exception::system_error,
                       "signal: generated by the completion of an asynchronous I/O request" );
         break;
+#endif
+#if defined(SI_MESGQ)
     case SI_MESGQ:
         report_error( execution_exception::system_error,
                       "signal: generated by the the arrival of a message on an empty message queue" );
         break;
+#endif
     default:
         break;
     }
