# $NetBSD: buildlink3.mk,v 1.2 2007/06/18 22:17:07 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
G_WRAP196_BUILDLINK3_MK:=	${G_WRAP196_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	g-wrap196
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ng-wrap196}
BUILDLINK_PACKAGES+=	g-wrap196
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}g-wrap196

.if !empty(G_WRAP196_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.g-wrap196+=	g-wrap>=1.9.5<1.9.7
BUILDLINK_ABI_DEPENDS.g-wrap196?=	g-wrap>=1.9.6nb1
BUILDLINK_PKGSRCDIR.g-wrap196?=		../../devel/g-wrap196
.endif	# G_WRAP196_BUILDLINK3_MK

.include "../../lang/guile/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
