# $NetBSD: Makefile,v 1.1.1.1 2009/07/07 23:25:17 minskim Exp $
# TeX Live Revision 10804

DISTNAME=	IEEEtran.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.7a

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-IEEEtran

CONFLICTS+=	tex-IEEEtran<=1.7nb1

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
