# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:35 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBZIP_BUILDLINK3_MK:=	${LIBZIP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libzip
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibzip}
BUILDLINK_PACKAGES+=	libzip
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libzip

.if !empty(LIBZIP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libzip+=	libzip>=0.7.1
BUILDLINK_PKGSRCDIR.libzip?=	../../archivers/libzip
.endif	# LIBZIP_BUILDLINK3_MK

.include "../../devel/zlib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
