# $NetBSD: buildlink3.mk,v 1.1 2004/03/12 02:54:50 dmcmahill Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BISON_BUILDLINK3_MK:=	${BISON_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	bison
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbison}
BUILDLINK_PACKAGES+=	bison

.if !empty(BISON_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.bison+=	bison>=1.875nb1
BUILDLINK_PKGSRCDIR.bison?=	../../devel/bison
BUILDLINK_DEPMETHOD.bison?=	build
.endif	# BISON_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
