# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/12/20 17:24:48 ahoka Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBDAEMON_BUILDLINK3_MK:=	${LIBDAEMON_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libdaemon
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdaemon}
BUILDLINK_PACKAGES+=	libdaemon
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libdaemon

.if ${LIBDAEMON_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libdaemon+=	libdaemon>=0.10
BUILDLINK_PKGSRCDIR.libdaemon?=		../../devel/libdaemon
.endif	# LIBDAEMON_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
