$NetBSD: patch-gsoap_wsdl_service.cpp,v 1.1 2020/03/27 20:53:32 joerg Exp $

--- gsoap/wsdl/service.cpp.orig	2020-03-27 20:15:35.783223754 +0000
+++ gsoap/wsdl/service.cpp
@@ -1834,7 +1834,7 @@ static void ident()
   char tmp[256];
   int i;
   strftime(tmp, 256, "%Y-%m-%d %H:%M:%S GMT", gmtime(p));
-  fprintf(stream, "/* %s\n   Generated by wsdl2h "VERSION" from ", outfile?outfile:"");
+  fprintf(stream, "/* %s\n   Generated by wsdl2h " VERSION " from ", outfile?outfile:"");
   if (infiles)
   { for (i = 0; i < infiles; i++)
       fprintf(stream, "%s ", infile[i]);
