# $NetBSD: Makefile,v 1.1.1.1 2009/08/07 20:09:32 minskim Exp $
# TeX Live Revision 19

DISTNAME=	kotex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.1.1
MASTER_SITES=	http://ftp.ktug.or.kr/KTUG/texlive/2008/archive/

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://project.ktug.or.kr/ko.TeX/
COMMENT=	Documentation for tex-kotex

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
