# $NetBSD: Makefile,v 1.4 2017/09/06 16:49:43 wiz Exp $

DISTNAME=	rotating.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.16b
TEXLIVE_REV=	16832

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-rotating
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
