# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/02/29 13:06:36 obache Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGCROOTS_BUILDLINK3_MK:=	${LIBGCROOTS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libgcroots
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgcroots}
BUILDLINK_PACKAGES+=	libgcroots
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libgcroots

.if ${LIBGCROOTS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libgcroots+=	libgcroots>=0.2.1
BUILDLINK_PKGSRCDIR.libgcroots?=	../../devel/libgcroots
.endif	# LIBGCROOTS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
