# $NetBSD: buildlink3.mk,v 1.7 2006/04/12 10:27:31 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MPICH_BUILDLINK3_MK:=	${MPICH_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	mpich
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmpich}
BUILDLINK_PACKAGES+=	mpich

.if !empty(MPICH_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.mpich+=	mpich>=1.2.6
BUILDLINK_ABI_DEPENDS.mpich?=	mpich>=1.2.6nb3
BUILDLINK_PKGSRCDIR.mpich?=	../../parallel/mpi-ch
BUILDLINK_DEPMETHOD.mpich?=	build
.endif	# MPICH_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
