# $NetBSD: buildlink3.mk,v 1.1 2004/02/12 16:50:53 recht Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MPICH_BUILDLINK3_MK:=	${MPICH_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	mpich
.endif

.if !empty(MPICH_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=			mpich
BUILDLINK_DEPENDS.mpich+=		mpich>=1.2.5.2
BUILDLINK_PKGSRCDIR.mpich?=		../../parallel/mpi-ch

.endif # MPICH_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
