# $NetBSD: buildlink3.mk,v 1.2 2009/03/02 21:08:34 manu Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XMLSEC1_BUILDLINK3_MK:=	${XMLSEC1_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xmlsec1
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxmlsec1}
BUILDLINK_PACKAGES+=	xmlsec1
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xmlsec1

.if ${XMLSEC1_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xmlsec1+=	xmlsec1>=1.2.6nb6
BUILDLINK_PKGSRCDIR.xmlsec1?=	../../security/xmlsec1
BUILDLINK_INCDIRS.xmlsec1+=	include/xmlsec1
BUILDLINK_CPPFLAGS.xmlsec1+=	-DXMLSEC_CRYPTO_OPENSSL
BUILDLINK_LIBS.xmlsec1+=	-lxmlsec1-openssl
.endif	# XMLSEC1_BUILDLINK3_MK

.include "../../security/openssl/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
