# $NetBSD: Makefile,v 1.3 2020/01/18 23:32:26 rillig Exp $

DISTNAME=	metago.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.9
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/metago
COMMENT=	Documentation for tex-metago
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
