# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/10 21:03:58 agc Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CUNIT_BUILDLINK3_MK:=	${CUNIT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	CUnit
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NCUnit}
BUILDLINK_PACKAGES+=	CUnit
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}CUnit

.if ${CUNIT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.CUnit+=	CUnit>=2.1
BUILDLINK_PKGSRCDIR.CUnit?=	../../devel/cunit
.endif	# CUNIT_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
