# $NetBSD: buildlink3.mk,v 1.7 2008/01/16 07:54:01 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EXIV2_BUILDLINK3_MK:=	${EXIV2_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	exiv2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nexiv2}
BUILDLINK_PACKAGES+=	exiv2
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}exiv2

.if ${EXIV2_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.exiv2+=	exiv2>=0.14
BUILDLINK_ABI_DEPENDS.exiv2+=	exiv2>=0.16
BUILDLINK_PKGSRCDIR.exiv2?=	../../graphics/exiv2
.endif	# EXIV2_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
