# $NetBSD: Makefile,v 1.4 2003/07/17 21:45:32 grant Exp $

DISTNAME=	tinyscheme-1.33
CATEGORIES=	lang
MASTER_SITES=	http://tinyscheme.sourceforge.net/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://tinyscheme.sourceforge.net/home.html
COMMENT=	BSD-licensed R5RS small embeddable scheme implementation

MAKEFILE=	makefile
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
