.\"	$NetBSD: diffbreaker.1,v 1.1 2020/05/24 16:44:20 nat Exp $
.\"
.\" Copyright (c) 2020 Nathanial Sloss <nathanialsloss@yahoo.com.au>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 10, 2020
.Dt DIFFBREAKER 1
.Os
.Sh NAME
.Nm diffbreaker
.Nd unified diff cherry picker / patch set editor
.Sh SYNOPSIS
.Nm
.Op Fl s
.Fl i Ar input file
.Fl o Ar output file
.Sh DESCRIPTION
The
.Nm
command allows the user to create incremental patches from a single unified diff
interactively using
.Xr curses 3 .
.Bl -tag -indent width
.It Fl i Ar input file
Unified diff input file.
.It Fl o Ar output file / beginning of file path.
Output location / file.
A file name of "-" means to write to stderr, useful for redirecting the output.
.It Op Fl s 
If the
.Op Fl s
switch is given the output file argument is a prefix and path for files to be
output.
Files are written from output file.1.diff etc.
.PP
If no
.Op Fl s
switch is
.Em not
given the output file is appended to on each subsequent
write.
.El
.Sh KEYS
.Nm
accepts the following keys:
.Bl -tag -indent width
.It [SPACE]
Select / Un-select change.
.It [l]
Redraw the current screen.
.It [j]
Move down 1 line.
.It [k]
Move up 1 line.
.It [G]
Move to the beginning of the diff.
.It [g]
Move to the end of the diff.
.It [w]
Write changes to output file(s).
Clearing sections from the screen in which all changes within a block or file
have been written and return to the top of the diff.
.It [q]
Quit the program,
.Em DISCARDING
any unsaved changes.
.Sh STATUS LINE
At the bottom of the screen the number of unwritten lines in the buffer is
displayed.
.Sh SEE ALSO
.Xr curses 3
.Xr diff 1
.Xr patch 1
.Sh AUTHORS
Nathanial Sloss
