# $NetBSD: Makefile.common,v 1.11 2018/08/04 21:19:39 minskim Exp $
#
# used by devel/protobuf/Makefile
# used by devel/py-protobuf/Makefile

PROTOBUFVER=	3.6.0

MASTER_SITES=	${MASTER_SITE_GITHUB:=google/}
GITHUB_PROJECT=	protobuf
GITHUB_RELEASE=	v${PKGVERSION_NOREV}

CATEGORIES=	devel
HOMEPAGE=       https://github.com/google/protobuf
LICENSE=	modified-bsd

WRKSRC=		${WRKDIR}/protobuf-${PKGVERSION_NOREV}

PATCHDIR=	${.CURDIR}/../../devel/protobuf/patches
