# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:43 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBARGPARSE_BUILDLINK3_MK:=	${LIBARGPARSE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libargparse
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibargparse}
BUILDLINK_PACKAGES+=	libargparse
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libargparse

.if !empty(LIBARGPARSE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libargparse+=	libargparse>=0.1.0000
BUILDLINK_ABI_DEPENDS.libargparse+=	libargparse>=0.1.0000nb1
BUILDLINK_PKGSRCDIR.libargparse?=	../../devel/libargparse
.endif	# LIBARGPARSE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
