# $NetBSD: buildlink3.mk,v 1.1 2004/04/25 17:12:30 snj Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBARGPARSE_BUILDLINK3_MK:=	${LIBARGPARSE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libargparse
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibargparse}
BUILDLINK_PACKAGES+=	libargparse

.if !empty(LIBARGPARSE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libargparse+=	libargparse>=0.1.0000
BUILDLINK_PKGSRCDIR.libargparse?=	../../devel/libargparse
.endif	# LIBARGPARSE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
