# $NetBSD: buildlink3.mk,v 1.2 2004/01/04 23:34:05 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DB4_BUILDLINK3_MK:=	${DB4_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	db4
.endif

.if !empty(DB4_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		db4
BUILDLINK_DEPENDS.db4?=		db4>=4.1.25
BUILDLINK_PKGSRCDIR.db4?=	../../databases/db4
BUILDLINK_CPPFLAGS.db4?=	-I${BUILDLINK_PREFIX.db4}/include/db4
.endif	# DB4_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:C/\+$//}
