.\" $NetBSD: pcps.1,v 1.2 2001/12/03 19:03:24 wiz Exp $
.Dd December 3, 2001
.Dt PCPS 1
.Sh NAME
.Nm pcps
.Nd utility to print text files on a PostScript(tm) printer
.Sh DESCRIPTION
Many features are included: word wrapping, scaling, rotation,
2-up and 4-up printing, duplex, banners, etc.  See
@PREFIX@/share/doc/pcps/pcps.man for
additional details, or run the program
without arguments.  This is shareware and requires payment.  See
@PREFIX@/share/doc/pcps/license.doc for details.
