.TH PCPS 1
.SH NAME
pcps \- A utility to print text files on a PostScript(tm) printer.
.SH DESCRIPTION
Many features are included: word wrapping, scaling, rotation,
2-up and 4-up printing, duplex, banners, etc.  See
share/doc/pcps/pcps.man (within your package tree) for
additonal details, or run the program
without arguments.  This is shareware and requires payment.  See
share/doc/pcps/license.doc for details.
