# $NetBSD: Makefile,v 1.3 2004/02/07 10:39:39 wiz Exp $
#

DISTNAME=	xtend-1.2beta4
PKGNAME=	${DISTNAME}
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.jabberwocky.com/pub/xtend/

MAINTAINER=	damon@brodiefamily.org
HOMEPAGE=	http://www.jabberwocky.com/software/xtend/
COMMENT=	Monitors X10 commands using heyu to automate UNIX functions

DEPENDS+=	heyu>=1.35:../../misc/heyu

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
