# $NetBSD: Makefile,v 1.12 2016/01/10 11:49:10 szptvlfn Exp $

DISTNAME=	scientific-0.3.3.5
PKGREVISION=	4
CATEGORIES=	math

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Numbers represented using scientific notation
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-hashable/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
