# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/04/19 18:36:02 xtraeme Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FREEGLUT_BUILDLINK3_MK:=	${FREEGLUT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	freeglut
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfreeglut}
BUILDLINK_PACKAGES+=	freeglut

.if !empty(FREEGLUT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.freeglut+=	freeglut>=2.2.0
BUILDLINK_PKGSRCDIR.freeglut?=	../../graphics/freeglut
.endif	# FREEGLUT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
