# $NetBSD: buildlink3.mk,v 1.1 2004/05/08 07:37:41 snj Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
P5_SOCKET6_BUILDLINK3_MK:=	${P5_SOCKET6_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	p5-Socket6
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-Socket6}
BUILDLINK_PACKAGES+=	p5-Socket6

.if !empty(P5_SOCKET6_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.p5-Socket6+=	p5-Socket6>=0.12
BUILDLINK_PKGSRCDIR.p5-Socket6?=	../../net/p5-Socket6
.endif	# P5_SOCKET6_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
