# $NetBSD: buildlink3.mk,v 1.1 2009/03/10 23:12:29 gdt Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GPSD_BUILDLINK3_MK:=	${GPSD_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	gpsd
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngpsd}
BUILDLINK_PACKAGES+=	gpsd
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}gpsd

.if ${GPSD_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.gpsd+=	gpsd>=2.37nb1
BUILDLINK_PKGSRCDIR.gpsd?=	../../geography/gpsd
.endif	# GPSD_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
