$NetBSD: patch-pyproject.toml,v 1.3 2026/02/17 06:32:37 adam Exp $

Fix installing stray files into site-packages.
https://github.com/pyca/cryptography/pull/14319

--- pyproject.toml.orig	2026-02-17 06:28:14.341949179 +0000
+++ pyproject.toml
@@ -106,10 +106,10 @@ module-name = "cryptography.hazmat.bindi
 locked = true
 sdist-generator = "git"
 include = [
-    "CHANGELOG.rst",
-    "CONTRIBUTING.rst",
+    { path = "CHANGELOG.rst", format = "sdist" },
+    { path = "CONTRIBUTING.rst", format = "sdist" },
 
-    "docs/**/*",
+    { path = "docs/**/*", format = "sdist" },
 
     { path = "src/_cffi_src/**/*.py", format = "sdist" },
     { path = "src/_cffi_src/**/*.c", format = "sdist" },
@@ -121,7 +121,7 @@ include = [
     { path = "src/rust/**/Cargo.lock", format = "sdist" },
     { path = "src/rust/**/*.rs", format = "sdist" },
 
-    "tests/**/*.py",
+    { path = "tests/**/*.py", format = "sdist" },
 ]
 exclude = [
     "vectors/**/*",
