# $NetBSD: Makefile,v 1.16 2024/02/18 10:33:54 markd Exp $

DISTNAME=	newtx.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.738
TEXLIVE_REV=	69756

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/newtx
COMMENT=	Documentation for tex-newtx
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
