# $NetBSD: buildlink3.mk,v 1.1 2004/04/13 23:19:24 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SLATEC_BUILDLINK3_MK:=	${SLATEC_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	slatec
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nslatec}
BUILDLINK_PACKAGES+=	slatec

.if !empty(SLATEC_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.slatec+=	slatec>=4.1nb1
BUILDLINK_PKGSRCDIR.slatec?=	../../math/slatec
.endif	# SLATEC_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
