# $NetBSD: Makefile,v 1.4 2020/01/18 23:31:13 rillig Exp $

DISTNAME=	bartel-chess-fonts.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2014
TEXLIVE_REV=	20619

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/bartel-chess-fonts
COMMENT=	Documentation for tex-bartel-chess-fonts
LICENSE=	gnu-gpl-v2

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
