#! /bin/sh
#
# $NetBSD: INSTALL,v 1.6 2000/08/02 06:35:45 jlam Exp $
#

PKGNAME=$1
STAGE=$2

case ${STAGE} in
PRE-INSTALL)
	;;
POST-INSTALL)
	CONFDIR=${PKG_PREFIX}/etc/nmh

	echo "Installing configuration files:"
	for file in \
		mhn.defaults \
		mts.conf
	do
		if [ -f ${CONFDIR}/${file} ]
		then
			echo "    ${CONFDIR}/${file} already exists"
		else
			echo "    ${CONFDIR}/${file}"
			cp ${CONFDIR}/${file}.dist ${CONFDIR}/${file}
			chmod 644 ${CONFDIR}/${file}
		fi
	done
	cat << EOF
=============================================================

Some files you might need to customize include the following:

    ${PKG_PREFIX}/etc/nmh/mhn.defaults
    ${PKG_PREFIX}/etc/nmh/mts.conf

=============================================================
EOF
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
