# $NetBSD: Makefile,v 1.5 2019/10/11 16:16:45 adam Exp $

DISTNAME=	asn1crypto-1.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	security python
MASTER_SITES=	${MASTER_SITE_PYPI:=a/asn1crypto/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/wbond/asn1crypto
COMMENT=	Fast, pure Python library for parsing and serializing ASN.1 structures
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
