# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:59 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BLAS_BUILDLINK3_MK:=	${BLAS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	blas
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nblas}
BUILDLINK_PACKAGES+=	blas
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}blas

.if !empty(BLAS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.blas+=	blas>=1.0nb2
BUILDLINK_ABI_DEPENDS.blas+=	blas>=1.0nb3
BUILDLINK_PKGSRCDIR.blas?=	../../math/blas
.endif	# BLAS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
