# $NetBSD: Makefile,v 1.9 2004/10/08 06:23:08 martti Exp $

.include "../../meta-pkgs/xfce4/Makefile.common"

XFCE4_VERSION=	0.3.1

DISTNAME=	xfce4-datetime-plugin-${XFCE4_VERSION}
CATEGORIES=	time
MASTER_SITES=	http://download.berlios.de/xfce-goodies/
COMMENT=	XFce4 calendar plugin

.include "../../x11/xfce4-panel/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
