# $NetBSD: Makefile,v 1.8 2005/05/30 14:57:28 dillo Exp $

PKGNAME=	ghostscript-esp-${GS_VERS}
PKGREVISION=	4
COMMENT=	ESP/CUPS Postscript interpreter

USE_X11=		# defined
CONFIGURE_ARGS+=	--with-x

.include "Makefile.common"
