# $NetBSD: Makefile,v 1.7 2023/01/26 09:35:13 pho Exp $

DISTNAME=	text-conversions-0.3.1.1
CATEGORIES=	converters

MAINTAINER=	pho@cielonegro.org
COMMENT=	Safe conversions between textual types
LICENSE=	isc

.include "../../converters/hs-base16-bytestring/buildlink3.mk"
.include "../../converters/hs-base64-bytestring/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
