$NetBSD: patch-util_verto_verto-k5ev.c,v 1.1 2024/01/05 23:46:29 adam Exp $

Fix include file path

--- util/verto/verto-k5ev.c.orig	2018-05-03 14:34:47.000000000 +0000
+++ util/verto/verto-k5ev.c
@@ -35,7 +35,7 @@
 
 #include <verto.h>
 #include <verto-module.h>
-#include "rename.h"
+#include "gssrpc/rename.h"
 
 /* Ignore some warnings generated by the libev code, which the libev maintainer
  * isn't interested in avoiding. */
