.\"	$NetBSD: list_todo.1,v 1.1 2013/02/09 21:00:12 wiz Exp $
.\"
.Dd February 9, 2013
.Dt LIST_TODO 1
.Sh NAME
.Nm list_todo
.Nd list entries for installed packages in pkgsrc/doc/TODO
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
lists from the pkgsrc TODO file for installed packages.
.Sh FILES
.Bl -tag -width 20n
.It Pa pkgsrc/doc/TODO
.Nm
list entries from file.
.El
.Sh AUTHORS
.An Thomas Klausner Aq wiz@NetBSD.org
