# $NetBSD: buildlink3.mk,v 1.11 2009/03/20 19:24:35 joerg Exp $

BUILDLINK_TREE+=	GLXKit

.if !defined(GLXKIT_BUILDLINK3_MK)
GLXKIT_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.GLXKit+=	GLXKit>=0.3.1r2nb3
BUILDLINK_ABI_DEPENDS.GLXKit?=	GLXKit>=0.3.1r2nb12
BUILDLINK_PKGSRCDIR.GLXKit?=	../../graphics/GLXKit

.include "../../graphics/RenderKit/buildlink3.mk"
.endif # GLXKIT_BUILDLINK3_MK

BUILDLINK_TREE+=	-GLXKit
