# $NetBSD: Makefile,v 1.4 2005/07/03 19:48:22 recht Exp $
#

DISTNAME=	Python-2.4.1
PKGNAME=	python24-pth-2.4.1
CATEGORIES=	lang python
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	recht@NetBSD.org
HOMEPAGE=	http://www.python.org/
COMMENT=	Interpreted, interactive, object-oriented programming language

DEPENDS+=	python24>=2.4:../../lang/python24

EXTRACT_ONLY=	# empty
NO_CHECKSUM=	yes
NO_CONFIGURE=	yes
NO_BUILD=	yes
NO_MTREE=	yes

do-install:	# empty

.include "../../mk/bsd.pkg.mk"
