# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/11/22 13:48:23 jmcneill Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBVOLUME_ID_BUILDLINK3_MK:=	${LIBVOLUME_ID_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libvolume_id
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibvolume_id}
BUILDLINK_PACKAGES+=	libvolume_id
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libvolume_id

.if ${LIBVOLUME_ID_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libvolume_id+=	libvolume_id>=0.81.0
BUILDLINK_PKGSRCDIR.libvolume_id?=	../../devel/libvolume_id
.endif	# LIBVOLUME_ID_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
