# $NetBSD: Makefile,v 1.8 2006/02/05 23:11:49 joerg Exp $
#

DISTNAME=	xtoolwait-1.3
PKGREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	http://www.hacom.nl/~richard/software/

MAINTAINER=	minoura@NetBSD.org
HOMEPAGE=	http://www.hacom.nl/~richard/software/xtoolwait.html
COMMENT=	Free implementation of SunOS toolwait(1)

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
