# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 22:39:00 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LADSPA_BUILDLINK3_MK:=	${LADSPA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ladspa
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nladspa}
BUILDLINK_PACKAGES+=	ladspa
BUILDLINK_ORDER+=	ladspa

.if !empty(LADSPA_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=			ladspa
BUILDLINK_ORDER+=			ladspa
BUILDLINK_API_DEPENDS.ladspa+=		ladspa>=1.12
BUILDLINK_ABI_DEPENDS.ladspa?=		ladspa>=1.12nb1
BUILDLINK_PKGSRCDIR.ladspa?=		../../audio/ladspa
.endif # LADSPA_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
