# $NetBSD: Makefile,v 1.4 2019/08/08 19:53:44 brook Exp $

R_PKGNAME=	MatrixModels
R_PKGVER=	0.4-1
CATEGORIES=	math

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Modelling with sparse and dense matrices
LICENSE=	gnu-gpl-v2 OR gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
