# $NetBSD: Makefile,v 1.12 2020/05/02 02:27:44 markd Exp $

DISTNAME=	microtype.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.7d
TEXLIVE_REV=	52853

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/microtype
COMMENT=	Documentation for tex-microtype
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
