# $NetBSD: buildlink3.mk,v 1.1 2004/04/25 07:06:14 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EXDBM_BUILDLINK3_MK:=	${EXDBM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	eXdbm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NeXdbm}
BUILDLINK_PACKAGES+=	eXdbm

.if !empty(EXDBM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.eXdbm+=	eXdbm>=1.0b1
BUILDLINK_PKGSRCDIR.eXdbm?=	../../devel/eXdbm
BUILDLINK_DEPMETHOD.eXdbm?=	build
.endif	# EXDBM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
