# $NetBSD: Makefile,v 1.18 2008/01/19 09:16:21 wiz Exp $
#

DISTNAME=	gemdropx-0.9
PKGREVISION=	5
CATEGORIES=	games x11
MASTER_SITES=	ftp://ftp.billsgames.com/unix/x/gemdropx/src/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.newbreedsoftware.com/gemdropx/
COMMENT=	Color puzzle game for X11 similar to Gem Drop

USE_TOOLS+=	gmake

.include "../../devel/SDL/buildlink3.mk"
.include "../../audio/SDL_mixer/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
