# $NetBSD: buildlink3.mk,v 1.8 2005/03/30 22:31:30 xtraeme Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PKGCONFIG_BUILDLINK3_MK:=	${PKGCONFIG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pkgconfig
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npkgconfig}
BUILDLINK_PACKAGES+=	pkgconfig

.if !empty(PKGCONFIG_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pkgconfig+=	pkgconfig>=0.15.0
BUILDLINK_PKGSRCDIR.pkgconfig?=	../../devel/pkgconfig
BUILDLINK_DEPMETHOD.pkgconfig?=	build

PKG_CONFIG_PATH?=	${BUILDLINK_DIR}/lib/pkgconfig
CONFIGURE_ENV+=		PKG_CONFIG=${BUILDLINK_PREFIX.pkgconfig}/bin/pkg-config
CONFIGURE_ENV+=		PKG_CONFIG_PATH=${PKG_CONFIG_PATH:Q}
MAKE_ENV+=		PKG_CONFIG=${BUILDLINK_PREFIX.pkgconfig}/bin/pkg-config
MAKE_ENV+=		PKG_CONFIG_PATH=${PKG_CONFIG_PATH:Q}

.endif	# PKGCONFIG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
