$NetBSD: patch-Cargo.toml,v 1.23 2025/08/20 09:55:53 adam Exp $

Depends on unpublished crates. Can't use cargo.mk to fetch it.

--- Cargo.toml.orig	1970-01-01 00:00:00.000000000 +0000
+++ Cargo.toml
@@ -118,7 +118,7 @@ libc = { version = "0.2.153" }
 libcst = { version = "1.1.0", default-features = false }
 log = { version = "0.4.17" }
 lsp-server = { version = "0.7.6" }
-lsp-types = { git = "https://github.com/astral-sh/lsp-types.git", rev = "3512a9f", features = [
+lsp-types = { path = "../lsp-types-3512a9f33eadc5402cfab1b8f7340824c8ca1439", features = [
     "proposed",
 ] }
 matchit = { version = "0.8.1" }
@@ -143,7 +143,7 @@ regex-automata = { version = "0.4.9" }
 rustc-hash = { version = "2.0.0" }
 rustc-stable-hash = { version = "0.1.2" }
 # When updating salsa, make sure to also update the revision in `fuzz/Cargo.toml`
-salsa = { git = "https://github.com/salsa-rs/salsa.git", rev = "918d35d873b2b73a0237536144ef4d22e8d57f27", default-features = false, features = [
+salsa = { path = "../salsa-918d35d873b2b73a0237536144ef4d22e8d57f27", default-features = false, features = [
     "compact_str",
     "macros",
     "salsa_unstable",
