# $NetBSD: Makefile,v 1.7 2023/10/24 08:28:16 pho Exp $

DISTNAME=	network-byte-order-0.1.7
CATEGORIES=	net

MAINTAINER=	pho@cielonegro.org
COMMENT=	Network byte order utilities
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
