$NetBSD: patch-accelerator.py,v 1.1 2016/07/24 02:34:32 kamil Exp $

Adapt for new API.

--- accelerator.py.orig	2016-07-20 19:56:58.692780436 +0000
+++ accelerator.py
@@ -274,7 +274,7 @@ def DisplayInit():
 	glColorMaterial(GL_FRONT,GL_AMBIENT_AND_DIFFUSE)
 	glMaterialfv(GL_FRONT,GL_SHININESS,128)
 	glMaterialfv(GL_FRONT,GL_SPECULAR,(0.5,0.5,0.5,1))
-	glLightModel(GL_LIGHT_MODEL_COLOR_CONTROL_EXT,GL_SEPARATE_SPECULAR_COLOR_EXT) # GL_LIGHT_MODEL_COLOR_CONTROL, GL_SEPARATE_SPECULAR_COLOR
+	glLightModeli(GL_LIGHT_MODEL_COLOR_CONTROL_EXT,GL_SEPARATE_SPECULAR_COLOR_EXT) # GL_LIGHT_MODEL_COLOR_CONTROL, GL_SEPARATE_SPECULAR_COLOR
 	glEnable(GL_LINE_SMOOTH)
 	glEnable(GL_NORMALIZE)
 	#glPolygonMode(GL_FRONT,GL_LINE)
