$NetBSD: patch-bin_m2.conf,v 1.5 2025/08/12 01:28:38 ktnb Exp $

Follow pkgsrc path convention.

--- bin/m2.conf.orig	2025-06-01 18:42:27.000000000 +0000
+++ bin/m2.conf
@@ -3,8 +3,8 @@ main is org.apache.maven.cli.MavenCli fr
 set maven.conf default ${maven.home}/conf
 
 [plexus.core]
-load       ${maven.conf}/logging
-optionally ${maven.home}/lib/ext/redisson/*.jar
-optionally ${maven.home}/lib/ext/hazelcast/*.jar
-optionally ${maven.home}/lib/ext/*.jar
-load       ${maven.home}/lib/*.jar
+load       @PKG_SYSCONFDIR@/logging
+optionally ${maven.home}/lib/java/maven/ext/redisson/*.jar
+optionally ${maven.home}/lib/java/maven/ext/hazelcast/*.jar
+optionally ${maven.home}/lib/java/maven/ext/*.jar
+load       ${maven.home}/lib/java/maven/*.jar
