# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/02/26 18:56:19 minskim Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
EVAS_BUFFER_BUILDLINK3_MK:=	${EVAS_BUFFER_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	evas-buffer
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nevas-buffer}
BUILDLINK_PACKAGES+=	evas-buffer
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}evas-buffer

.if ${EVAS_BUFFER_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.evas-buffer+=	evas-buffer>=0.9.9.050
BUILDLINK_PKGSRCDIR.evas-buffer?=	../../graphics/evas-buffer
.endif	# EVAS_BUFFER_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
