# $NetBSD: buildlink3.mk,v 1.12 2007/03/28 21:18:52 dmcmahill Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SCILAB_BUILDLINK3_MK:=	${SCILAB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	scilab
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nscilab}
BUILDLINK_PACKAGES+=	scilab
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}scilab

.if !empty(SCILAB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.scilab+=	scilab>=4.1
BUILDLINK_ABI_DEPENDS.scilab?=	scilab>=4.1
BUILDLINK_PKGSRCDIR.scilab?=	../../math/scilab

BUILDLINK_FILES.scilab+=	lib/scilab-${SCIVERSION}/Version.incl
.endif	# SCILAB_BUILDLINK3_MK

SCI=	${BUILDLINK_DIR}/lib/scilab-4.1
CONFIGURE_ENV+=	SCI=${SCI:Q}
MAKE_ENV+=	SCI=${SCI:Q}

SCIVERSION=	4.1

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
