# $NetBSD: buildlink3.mk,v 1.14 2004/05/17 21:32:34 seb Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DB_BUILDLINK3_MK:=	${DB_BUILDLINK3_MK}+

.include "../../mk/bsd.prefs.mk"

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	db2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndb2}
BUILDLINK_PACKAGES+=	db2

.if !empty(DB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.db2+=		db>=2.7.3
BUILDLINK_PKGSRCDIR.db2?=	../../databases/db
.  if defined(USE_DB185)
BUILDLINK_INCDIRS.db2?=		include/db2
BUILDLINK_TRANSFORM+=		l:db:db2
.  endif
.endif	# DB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
