# $NetBSD: buildlink3.mk,v 1.2 2007/07/11 14:37:25 obache Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBVNCSERVER_BUILDLINK3_MK:=	${LIBVNCSERVER_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libVNCServer
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NlibVNCServer}
BUILDLINK_PACKAGES+=	libVNCServer
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libVNCServer

.if ${LIBVNCSERVER_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libVNCServer+=	libVNCServer>=0.9.1
BUILDLINK_PKGSRCDIR.libVNCServer?=	../../net/libvncserver
.endif	# LIBVNCSERVER_BUILDLINK3_MK

.include "../../devel/zlib/buildlink3.mk"
.include "../../graphics/jpeg/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
