# $NetBSD: Makefile,v 1.24 2026/02/17 10:43:34 markd Exp $

DISTNAME=	luatex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.21.0.76924
TEXLIVE_REV=	76924

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://www.luatex.org/
COMMENT=	Documentation for tex-luatex
LICENSE=	gnu-gpl-v2

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
