# $NetBSD: Makefile,v 1.25 2026/04/03 06:05:48 markd Exp $

DISTNAME=	luatex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.24.0
TEXLIVE_REV=	78218

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/luatex
COMMENT=	Documentation for tex-luatex
LICENSE=	gnu-gpl-v2

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
