$NetBSD: patch-cmake_curl.cmake,v 1.1 2022/04/17 04:07:14 jnemeth Exp $

--- cmake/curl.cmake.orig	2021-09-14 09:08:08.000000000 +0000
+++ cmake/curl.cmake
@@ -34,7 +34,6 @@ MACRO(MYSQL_CHECK_CURL)
      ENDIF()
      MESSAGE(STATUS "CURL_LIBRARY = ${CURL_LIBRARY}")
    ELSEIF(WITH_CURL)
-    LIST(REVERSE CMAKE_FIND_LIBRARY_SUFFIXES)
     FIND_LIBRARY(CURL_LIBRARY
       NAMES curl
       PATHS ${WITH_CURL}
@@ -42,7 +41,6 @@ MACRO(MYSQL_CHECK_CURL)
       NO_CMAKE_ENVIRONMENT_PATH
       NO_SYSTEM_ENVIRONMENT_PATH
     )
-    LIST(REVERSE CMAKE_FIND_LIBRARY_SUFFIXES)
     MESSAGE(STATUS "CURL_LIBRARY = ${CURL_LIBRARY}")
    ELSE()
      MESSAGE(STATUS
