# $NetBSD: Makefile,v 1.3 2000/08/02 11:43:00 abs Exp $

DISTNAME=	netatalk-1.4b2+asun2.1.3
PKGNAME=	netatalk-asun-2.1.3nb2
CATEGORIES=	net print
MASTER_SITES=   ftp://ftp.cobaltnet.com/pub/users/asun/release/ \
		ftp://ftp.hanse.de/sites/transit/mirror/ftp.u.washington.edu/public/asun/

MAINTAINER=	abs@netbsd.org
HOMEPAGE=	http://www.umich.edu/~rsug/netatalk/

CONFLICTS=	netatalk-[0-9]*

.include "../../mk/bsd.pkg.mk"
