# $NetBSD: buildlink3.mk,v 1.6 2006/04/06 06:22:34 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SOCKS4_BUILDLINK3_MK:=	${SOCKS4_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	socks4
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsocks4}
BUILDLINK_PACKAGES+=	socks4

.if !empty(SOCKS4_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.socks4+=	socks4>=2.2
BUILDLINK_PKGSRCDIR.socks4?=	../../net/socks4

BUILDLINK_TRANSFORM+=	l:socks:socks4

.endif	# SOCKS4_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
