# $NetBSD: Makefile,v 1.3 2020/01/18 23:31:28 rillig Exp $

DISTNAME=	epsdice
PKGNAME=	tex-${DISTNAME}-2.1
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/epsdice
COMMENT=	Scalable dice "font"
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
