# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:48 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TRE_BUILDLINK3_MK:=	${TRE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tre
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntre}
BUILDLINK_PACKAGES+=	tre
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}tre

.if !empty(TRE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.tre+=		tre>=0.7.2
BUILDLINK_PKGSRCDIR.tre?=		../../devel/tre
BUILDLINK_DEPMETHOD.tre?=		build
BUILDLINK_CPPFLAGS.tre+=		-I${BUILDLINK_PREFIX.tre}/include/tre
.endif	# TRE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
