# $NetBSD: buildlink3.mk,v 1.3 2006/02/05 23:08:53 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RVM_BUILDLINK3_MK:=	${RVM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	rvm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nrvm}
BUILDLINK_PACKAGES+=	rvm

.if !empty(RVM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.rvm+=	rvm>=1.3
BUILDLINK_RECOMMENDED.rvm+=	rvm>=1.11nb1
BUILDLINK_PKGSRCDIR.rvm?=	../../devel/rvm
.endif	# RVM_BUILDLINK3_MK

.include "../../devel/lwp/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
