# $NetBSD: Makefile,v 1.1.1.1 2008/04/04 15:21:33 jlam Exp $

DISTNAME=	haml-1.8.2
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://haml.hamptoncatlin.com/
COMMENT=	XHTML & CSS markup language & template engine

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
