# $NetBSD: Makefile,v 1.3 2020/01/11 08:56:16 pho Exp $

DISTNAME=	mono-traversable-1.0.15.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Type classes for traversing monomorphic containers
LICENSE=	mit

.include "../../mk/haskell.mk"
.include "../../devel/hs-hashable/buildlink3.mk"
.include "../../devel/hs-split/buildlink3.mk"
.include "../../devel/hs-unordered-containers/buildlink3.mk"
.include "../../devel/hs-vector/buildlink3.mk"
.include "../../devel/hs-vector-algorithms/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
