# $NetBSD: Makefile,v 1.13 2006/12/15 20:33:03 joerg Exp $
#

DISTNAME=	wmi-10
PKGREVISION=	2
CATEGORIES=	wm
MASTER_SITES=	http://wmii.de/download/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://wmii.de/
COMMENT=	Minimalist, flexible and highly customizable window manager

USE_LANGUAGES=	c c++
GNU_CONFIGURE=	yes

.include "../../x11/libXft/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
