# $NetBSD: buildlink3.mk,v 1.1 2021/09/15 18:59:54 adam Exp $

BUILDLINK_TREE+=	cJSON

.if !defined(CJSON_BUILDLINK3_MK)
CJSON_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.cJSON+=	cJSON>=1.7.15
BUILDLINK_PKGSRCDIR.cJSON?=	../../textproc/cJSON
.endif	# CJSON_BUILDLINK3_MK

BUILDLINK_TREE+=	-cJSON
