# $NetBSD: Makefile,v 1.3 2019/12/06 19:04:12 markd Exp $

DISTNAME=	csvsimple.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.21
TEXLIVE_REV=	51010

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/csvsimple
COMMENT=	Documentation for tex-csvsimple
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
