# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/05/15 23:08:14 dmcmahill Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MATIO_BUILDLINK3_MK:=	${MATIO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	matio
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmatio}
BUILDLINK_PACKAGES+=	matio
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}matio

.if !empty(MATIO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.matio+=	matio>=1.3.3
BUILDLINK_PKGSRCDIR.matio?=	../../devel/matio
BUILDLINK_DEPMETHOD.matio?=	build
.endif	# MATIO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
