# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/02/15 16:03:46 jmcneill Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
QUESOGLC_BUILDLINK3_MK:=	${QUESOGLC_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	quesoglc
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nquesoglc}
BUILDLINK_PACKAGES+=	quesoglc
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}quesoglc

.if ${QUESOGLC_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.quesoglc+=	quesoglc>=0.7.1
BUILDLINK_PKGSRCDIR.quesoglc?=	../../graphics/quesoglc
.endif	# QUESOGLC_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
