# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:36 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBMPD_BUILDLINK3_MK:=	${LIBMPD_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmpd
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmpd}
BUILDLINK_PACKAGES+=	libmpd
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmpd

.if !empty(LIBMPD_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libmpd+=	libmpd>=0.12.0
BUILDLINK_PKGSRCDIR.libmpd?=	../../audio/libmpd
.endif	# LIBMPD_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
