# $NetBSD: Makefile,v 1.12 2023/10/24 08:11:43 pho Exp $

DISTNAME=	HsYAML-0.2.1.3
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Pure Haskell YAML 1.2 processor
LICENSE=	gnu-gpl-v2

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
