# $NetBSD: Makefile,v 1.2 2019/12/06 20:21:26 markd Exp $

DISTNAME=	fncychap.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.34
TEXLIVE_REV=	20710

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/fncychap
COMMENT=	Documentation for tex-fncychap
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
