#!@SH@
# $NetBSD: mozilla.sh,v 1.1 2004/09/20 15:48:58 erh Exp $

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:@PREFIX@/lib/@MOZILLA@@MOZ_EXTRA@-@MOZ_PLATFORM@"
export LD_LIBRARY_PATH

exec @PREFIX@/lib/@MOZILLA@@MOZ_EXTRA@-@MOZ_PLATFORM@/@MOZILLA@ "$@"
