# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:42 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FFCALL_BUILDLINK3_MK:=	${FFCALL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ffcall
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nffcall}
BUILDLINK_PACKAGES+=	ffcall
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ffcall

.if !empty(FFCALL_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.ffcall+=	ffcall>=1.9
BUILDLINK_ABI_DEPENDS.ffcall+=	ffcall>=1.10nb1
BUILDLINK_PKGSRCDIR.ffcall?=	../../devel/ffcall
.endif	# FFCALL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
