# $NetBSD: buildlink3.mk,v 1.2 2004/03/06 23:46:06 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FFCALL_BUILDLINK3_MK:=	${FFCALL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ffcall
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nffcall}
BUILDLINK_PACKAGES+=	ffcall

.if !empty(FFCALL_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ffcall+=	ffcall>=1.9
BUILDLINK_PKGSRCDIR.ffcall?=	../../devel/ffcall
.endif	# FFCALL_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
