# $NetBSD: buildlink3.mk,v 1.5 2006/02/05 23:08:40 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CHMLIB_BUILDLINK3_MK:=	${CHMLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	chmlib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nchmlib}
BUILDLINK_PACKAGES+=	chmlib

.if !empty(CHMLIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.chmlib+=	chmlib>=0.31
BUILDLINK_RECOMMENDED.chmlib+=	chmlib>=0.37.4nb2
BUILDLINK_PKGSRCDIR.chmlib?=	../../devel/chmlib
.endif	# CHMLIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
