# $NetBSD: buildlink3.mk,v 1.7 2006/04/12 10:27:07 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CHMLIB_BUILDLINK3_MK:=	${CHMLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	chmlib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nchmlib}
BUILDLINK_PACKAGES+=	chmlib

.if !empty(CHMLIB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.chmlib+=	chmlib>=0.31
BUILDLINK_ABI_DEPENDS.chmlib+=	chmlib>=0.37.4nb2
BUILDLINK_PKGSRCDIR.chmlib?=	../../devel/chmlib
.endif	# CHMLIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
