# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:36 wiz Exp $

DISTNAME=	comfortaa
PKGNAME=	tex-${DISTNAME}-2.3
TEXLIVE_REV=	27536

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/comfortaa
COMMENT=	Sans serif font, with LaTeX support
LICENSE=	lppl-1.3c

TEX_MAP_FILES+=	comfortaa.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
