.\"	$NetBSD: revbump.1,v 1.18 2014/05/06 12:41:46 wiz Exp $
.\"
.\" Copyright (c) 2003, 2004, 2005, 2006, 2010, 2012, 2013, 2014 The NetBSD Foundation, Inc.
.\"
.\" This code was originally contributed to the NetBSD Foundation, Inc.
.\" by Julio Merino <jmmv@NetBSD.org> and Thomas Klausner <wiz@NetBSD.org>.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. Neither the name of author nor the names of its contributors may
.\"    be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND
.\" CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
.\" IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
.\" IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 6, 2014
.Dt REVBUMP 1
.Os
.Sh NAME
.Nm revbump
.Nd tool to help bump PKGREVISIONs automatically
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl p Ar pkgsrcdir
.Op cat1/pkg1 ... catN/pkgN
.Sh DESCRIPTION
.Nm
is a perl script for pkgsrc developers that simplifies bumping
PKGREVISIONs automatically.
Given a package (in
.Ar category/package
format) on the command line or stdin, it will try to increase
the PKGREVISION for that package automatically.
.Pp
.Nm Fl h
displays a short usage.
.Pp
If
.Fl p
is given,
.Ar pkgsrcdir
is used instead of the default
.Pa /usr/pkgsrc .
.Pp
.Nm
reports successful updates on stdout, and prints the package name
(in
.Ar category/package
form) on stdout for each package where it failed.
.Sh EXAMPLES
.Dl revbump devel/gmake x11/glib2
.Pp
would bump the PKGREVISIONs of gmake and glib2, as would
.Bd -literal -offset indent
revbump \*[Lt]\*[Lt] EOF
devel/gmake
x11/glib2
EOF
.Ed
.Pp
The complete procedure for a recursive dependency bump for
category/package using
.Nm
and
.Xr blbump 1
would be:
.Bd -literal -offset indent
cd /usr/pkgsrc
finddepends category/package \*[Gt] allbump
grep buildlink3.mk allbump | sed 's/.buildlink3.mk//' \*[Gt] bl3bump
grep -e Makefile.common -e mk$ allbump > commonbump
[read commonbump and replace entries with all packages including the
 corresponding Makefile.common or *.mk file]
cat allbump commonbump | sed 's,/[^/]*$,,' | sort -u \*[Gt] makebump
revbump \*[Lt] makebump \*[Gt] makebump.manual
[if a package is listed in makebump.manual outside a line
"Updated ... from ... to ...", handle the PKGREVISION bump manually]
blbump \*[Lt] bl3bump \*[Gt] bl3bump.manual
[handle the *ABI_DEPENDS* bumps in bl3bump.manual manually, usually none]
cvs diff `cat makebump` | less
[look for PYPKGPREFIX -\*[Gt] py27
 and RUBY_PKGPREFIX -\*[Gt] ruby200 expansions
 in buildlink files and any unrelated diffs you have in your
 local tree, and fix them]
cvs diff `cat bl3bump makebump` | less
cvs commit `cat bl3bump makebump`
rm allbump bl3bump* makebump* commonbump
.Ed
.Sh SEE ALSO
.Xr blbump 1 ,
.Xr finddepends 1
