.\" $NetBSD: autocue.1,v 1.3 2007/03/02 20:38:21 wiz Exp $
.\"
.\" Copyright © 2006 Alistair Crooks.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd February 24, 2007
.Dt AUTOCUE 1
.Os
.Sh NAME
.Nm autocue
.Nd display text in X11 cut buffers timed depending on size of text
.Sh SYNOPSIS
.Nm
.Op Fl S Ar speed
.Op Fl c Ar maxcut
.Op Fl s Ar symbolic-speed
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility reads a text input file, and sends formatted output
to the X11 cut buffers by using the
.Ar xcb
utility.
.Nm
will then wait for a period of time (dependent upon the speed
settings), before sending the next paragraph of text to the next cut
buffers.
.Pp
The options are as follows:
.Bl -tag -width maxcuts
.It Fl S Ar speed
Takes a numeric value for speed, which is the number of characters
per second that the text can be read.
See also the
.Ar s
argument for some pre-defined rates.
Slow readers can generally read at 3 characters per second, medium
at 7 characters per second, and fast readers at 10 or more characters per
second.
.It Fl c Ar maxcut
Provides the maximum number of X11 cut buffers which will be used.
.It Fl s Ar speed
Provides pre-computed
.Ar fast ,
.Ar medium and
.Ar slow
definitions for the speed.
.Pp
If
.Nm
is going too fast, then a SIGUSR2 signal
delivered via
.Xr kill 1
will make it go one
character per second slower.
If
.Nm
is going too slowly, then a SIGUSR1 signal
delivered via
.Xr kill 1
will make it go
one character per second faster.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and \*[Gt]0 if an error occurs.
.Sh SEE ALSO
.Xr kill 1
.Sh AUTHORS
The
.Nm
was written by
.An Alistair Crooks Aq agc@NetBSD.org .
