.\"	$NetBSD: distfetch.1,v 1.1.1.1 2002/09/30 08:37:13 martti Exp $
.\"
.\" Copyright (c) 2002 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Martti Kuparinen.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by the NetBSD
.\"        Foundation, Inc. and its contributors.
.\" 4. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 30, 2002
.Dt DISTFETCH 1
.Os
.Sh NAME
.Nm distfetch
.Nd fetch distribution files for packages
.Sh SYNOPSIS
.Nm
.Op Fl c Ar filename
.Op Fl d Ar destdir
.Op Fl h
.Op Fl s Ar srcdir
.Op Fl v
.Sh DESCRIPTION
.Nm
is a tool to fetch only required distfiles for the packages you
are going to install.
The packages are defined in a configuration file.
.Pp
The distfiles are stored in
.Pa /usr/pkgsrc/distfiles
but this can be changed by using the
.Fl d Ar destdir
argument or by setting the
.Pa DISTDIR
variable in
.Pa /etc/mk.conf .
.Pp
Usage information is shown with the
.Fl h
flag.
To get a better idea what's going on, use the
.Fl v
flag.
.Sh ENVIRONMENT
.Bl -tag -width PKGSRCDIR
.It Ev PKGSRCDIR
Location of the
.Nx
Package System.
By default this is
.Pa /usr/pkgsrc
but it can be changed either with the
.Fl s Ar srcdir
argument or by defining the
.Ev PKGSRCDIR
variable.
.El
.Sh FILES
The default configuration file is
.Pa __PREFIX__/etc/distfetch.conf
but this can be changed with the
.Fl c Ar filename
argument.
.Pp
An example of the configuration file can be found in the
.Pa __PREFIX__/share/examples/distfetch
directory.
.Sh AUTHORS
This script was written by
.An Martti Kuparinen Aq martti@netbsd.org
and improved by several other
.Nx
users.
.Sh BUGS
It is not possible to use
.Fl d Ar destdir
if
.Pa /etc/mk.conf
has a
.Pa DISTDIR
setting.
