$NetBSD: patch-acme-client.conf,v 1.1 2025/10/20 19:09:17 vins Exp $

acme-client configuration for pkgsrc.

--- acme-client.conf.orig	2025-10-20 17:42:55.426948159 +0000
+++ acme-client.conf
@@ -0,0 +1,31 @@
+#
+# $OpenBSD: acme-client.conf,v 1.4 2020/09/17 09:13:06 florian Exp $
+#
+authority letsencrypt {
+	api url "https://acme-v02.api.letsencrypt.org/directory"
+	account key "@PKG_SYSCONFDIR@/acme/letsencrypt-privkey.pem"
+}
+
+authority letsencrypt-staging {
+	api url "https://acme-staging-v02.api.letsencrypt.org/directory"
+	account key "@PKG_SYSCONFDIR@/acme/letsencrypt-staging-privkey.pem"
+}
+
+authority buypass {
+	api url "https://api.buypass.com/acme/directory"
+	account key "@PKG_SYSCONFDIR@/acme/buypass-privkey.pem"
+	contact "mailto:me@example.com"
+}
+
+authority buypass-test {
+	api url "https://api.test4.buypass.no/acme/directory"
+	account key "@PKG_SYSCONFDIR@/acme/buypass-test-privkey.pem"
+	contact "mailto:me@example.com"
+}
+
+domain example.com {
+	alternative names { secure.example.com }
+	domain key "@SSLDIR@/acme/private/example.com.key"
+	domain full chain certificate "@SSLDIR@/acme/example.com.fullchain.pem"
+	sign with letsencrypt
+}
