# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/01/16 02:00:33 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SQLITE3_BUILDLINK3_MK:=	${SQLITE3_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sqlite3
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsqlite3}
BUILDLINK_PACKAGES+=	sqlite3

.if !empty(SQLITE3_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.sqlite3+=	sqlite3>=3.0.8
BUILDLINK_PKGSRCDIR.sqlite3?=	../../databases/sqlite3
.endif	# SQLITE3_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
