# $NetBSD: Makefile,v 1.5 2023/04/01 11:11:57 markd Exp $

DISTNAME=	gillius
PKGNAME=	tex-${DISTNAME}-2022
TEXLIVE_REV=	64865

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/gillius
COMMENT=	Gillius fonts with LaTeX support
LICENSE=	gnu-gpl-v2 AND lppl-1.3c

TEX_MAP_FILES+=	gillius.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
