# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 23:11:02 jlam Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBOGG_BUILDLINK3_MK:=	${LIBOGG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libogg
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibogg}
BUILDLINK_PACKAGES+=	libogg
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libogg

.if !empty(LIBOGG_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libogg+=	libogg>=1.1
BUILDLINK_ABI_DEPENDS.libogg+=	libogg>=1.1.2nb1
BUILDLINK_PKGSRCDIR.libogg?=	../../multimedia/libogg
.endif	# LIBOGG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
