# $NetBSD: buildlink3.mk,v 1.3 2004/10/03 00:14:48 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
AALIB_BUILDLINK3_MK:=	${AALIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	aalib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Naalib}
BUILDLINK_PACKAGES+=	aalib

.if !empty(AALIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.aalib+=	aalib>=1.4.0.4
BUILDLINK_RECOMMENDED.aalib+=	aalib>=1.4.0.4nb2
BUILDLINK_PKGSRCDIR.aalib?=	../../graphics/aalib
.endif	# AALIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
