# $NetBSD: buildlink3.mk,v 1.21 2006/04/06 06:21:57 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ZLIB_BUILDLINK3_MK:=	${ZLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	zlib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nzlib}
BUILDLINK_PACKAGES+=	zlib

.if !empty(ZLIB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.zlib+=	zlib>=1.1.4nb1
BUILDLINK_ABI_DEPENDS.zlib+=	zlib>=1.2.3
BUILDLINK_PKGSRCDIR.zlib?=	../../devel/zlib
.endif	# ZLIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
