# $NetBSD: Makefile,v 1.7 2023/10/09 04:54:57 pho Exp $

DISTNAME=	unix-time-0.4.8
PKGREVISION=	2
CATEGORIES=	time

MAINTAINER=	pho@cielonegro.org
COMMENT=	Unix time parser/formatter and utilities
LICENSE=	modified-bsd

.include "../../time/hs-old-time/buildlink3.mk"
.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
