# $NetBSD: buildlink3.mk,v 1.1.1.1 2010/05/19 11:47:15 obache Exp $

BUILDLINK_TREE+=	TinySVM

.if !defined(TINYSVM_BUILDLINK3_MK)
TINYSVM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.TinySVM+=	TinySVM>=0.09
BUILDLINK_PKGSRCDIR.TinySVM?=	../../math/TinySVM
.endif # TINYSVM_BUILDLINK3_MK

BUILDLINK_TREE+=	-TinySVM
