# $NetBSD: Makefile,v 1.2 2019/12/06 20:04:20 markd Exp $

DISTNAME=	dviincl.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.00
TEXLIVE_REV=	29349

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/dviincl
COMMENT=	Documentation for tex-dviincl
LICENSE=	public-domain

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
