# $NetBSD: Makefile,v 1.4 2022/01/18 02:48:14 pho Exp $

DISTNAME=	timeit-2.0
PKGREVISION=	2
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Time monadic computations with an IO base
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
