# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:35 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SZIP_BUILDLINK3_MK:=	${SZIP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	szip
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nszip}
BUILDLINK_PACKAGES+=	szip
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}szip

.if !empty(SZIP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.szip+=	szip>=2.0
BUILDLINK_PKGSRCDIR.szip?=	../../archivers/szip
.endif	# SZIP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
