# $NetBSD: buildlink3.mk,v 1.6 2006/07/08 23:10:35 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LZO_BUILDLINK3_MK:=	${LZO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lzo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlzo}
BUILDLINK_PACKAGES+=	lzo
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}lzo

.if !empty(LZO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.lzo+=		lzo>=2.01
BUILDLINK_PKGSRCDIR.lzo?=	../../archivers/lzo
.endif	# LZO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
