# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/07/14 20:02:48 wiz Exp $
# XXX	BUILDLINK_DEPMETHOD.lzo?=	build

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LZO_BUILDLINK3_MK:=	${LZO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lzo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlzo}
BUILDLINK_PACKAGES+=	lzo

.if !empty(LZO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.lzo+=		lzo>=2.01
BUILDLINK_PKGSRCDIR.lzo?=	../../archivers/lzo
.endif	# LZO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
