# $NetBSD: options.mk,v 1.2 2023/08/12 13:34:02 tnn Exp $
PKG_OPTIONS_VAR=	PKG_OPTIONS.vtk

PKG_SUPPORTED_OPTIONS=	qt
PKG_SUGGESTED_OPTIONS=	qt

.include "../../mk/bsd.options.mk"

PLIST_VARS+=	qt
.if !empty(PKG_OPTIONS:Mqt)
CMAKE_ARGS+=	-DVTK_MODULE_ENABLE_VTK_GUISupportQt=YES
CMAKE_ARGS+=	-DVTK_MODULE_ENABLE_VTK_GUISupportQtSQL=NO
CMAKE_ARGS+=	-DVTK_MODULE_ENABLE_VTK_RenderingQt=YES
CMAKE_ARGS+=	-DVTK_MODULE_ENABLE_VTK_ViewsQt=YES
CMAKE_ARGS+=	-DVTK_QT_VERSION=5
PLIST.qt=	yes
.include "../../x11/qt5-qtbase/buildlink3.mk"
.else
CMAKE_ARGS+=	-DVTK_GROUP_ENABLE_Qt=NO
.endif
