# $NetBSD: Makefile,v 1.3 2020/03/24 17:08:44 taca Exp $

DISTNAME=	temple-0.8.2
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/judofyr/temple
COMMENT=	Template compilation framework in Ruby
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
