$NetBSD: patch-Cargo.toml,v 1.18 2022/09/11 11:36:15 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2

--- Cargo.toml.orig	2022-09-11 02:46:38.000000000 +0000
+++ Cargo.toml
@@ -63,7 +63,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.8.3"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.5.1"
