$NetBSD: patch-Cargo.toml,v 1.7 2021/09/02 11:31:53 pin Exp $

Don't pull the vendored version, use native luajit

--- Cargo.toml.orig	2021-09-02 04:43:17.000000000 +0000
+++ Cargo.toml
@@ -30,7 +30,7 @@ lazy_static = "1.4.0"
 indexmap = { version = "1.7.0", features = ["serde"] }
 natord = "1.0.9"
 humansize = "1.1.1"
-mlua = { version = "0.6.2", features = ["luajit", "vendored", "serialize", "send"] }
+mlua = { version = "0.6.2", features = ["luajit", "serialize", "send"] }
 ansi-to-tui = "0.4.0"
 libc = "0.2.100"
 
