$NetBSD: patch-Cargo.toml,v 1.28 2024/03/18 13:29:06 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2.

--- Cargo.toml.orig	2024-03-18 12:51:05.493724921 +0000
+++ Cargo.toml
@@ -73,7 +73,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.9.6"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.8.0"
