$NetBSD: patch-Cargo.toml,v 1.16 2022/05/21 21:10:56 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2

--- Cargo.toml.orig	2022-05-21 04:21:04.000000000 +0000
+++ Cargo.toml
@@ -67,7 +67,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.7.4"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.4.0"
