$NetBSD: patch-Cargo.toml,v 1.17 2022/06/07 10:11:48 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2

--- Cargo.toml.orig	2022-06-06 15:39:26.000000000 +0000
+++ Cargo.toml
@@ -60,7 +60,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.7.4"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.4.2"
