# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/09/12 22:11:28 ahoka Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSIGSEGV25_BUILDLINK3_MK:=	${LIBSIGSEGV25_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libsigsegv25
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsigsegv25}
BUILDLINK_PACKAGES+=	libsigsegv25
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libsigsegv25

.if !empty(LIBSIGSEGV25_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libsigsegv25+=	libsigsegv25>=2.2
BUILDLINK_PKGSRCDIR.libsigsegv25?=	../../devel/libsigsegv25
.endif	# LIBSIGSEGV25_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
