$NetBSD: patch-pyproject.toml,v 1.1 2025/05/04 08:39:40 adam Exp $

Do not install tests.

--- pyproject.toml.orig	2025-04-26 22:28:35.000000000 +0000
+++ pyproject.toml
@@ -47,9 +47,8 @@ Changelog = "https://github.com/ianare/e
 "EXIF.py" = "exifread.cli:main"
 
 
-[tool.setuptools.packages]
-find = {}
-
+[tool.setuptools.packages.find]
+exclude = ["tests*"]
 
 [tool.setuptools.dynamic]
 version = {attr = "exifread.__version__"}
