# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/06/05 19:03:12 nathanw Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
HOWL_BUILDLINK3_MK:=		${HOWL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=		howl
.endif

BUILDLINK_PACKAGES:=		${BUILDLINK_PACKAGES:Nhowl}
BUILDLINK_PACKAGES+=		howl

.if !empty(HOWL_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.howl+=	howl>=0.9.5
BUILDLINK_PKGSRCDIR.howl?=	../../net/howl
.endif	# HOWL_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
