.\"	$NetBSD: python-versions-check.1,v 1.3 2023/07/03 21:00:46 wiz Exp $
.\"
.\" Copyright (c) 2023 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Thomas Klausner.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 10, 2023
.Dt PYTHON-VERSIONS-CHECK 1
.Os
.Sh NAME
.Nm python-versions-check
.Nd check Python versions for a package and its dependencies and users
.Sh SYNOPSIS
.Nm
.Op Fl dhw
.Op Fl p Ar pkgsrcdir
.Ar category/package
.Sh DESCRIPTION
.Nm
is a script for pkgsrc developers that compares the Python versions
supported by a package to the ones supported by its dependencies and
the packages depending on it.
.Pp
.Nm
checks
.Ar category/package
or the package in its current working directory, if no argument is
provided.
.Pp
.Nm
supports the following options:
.Bl -tag -width 12n -offset indent
.It Fl d
Debug mode - print each file name when its parsed.
.It Fl h
Show the usage.
.It Fl p Ar pkgsrcdir
Use
.Ar pkgsrcdir
as root of the pkgsrc tree.
Defaults to the value of the environment variable
.Ev PKGSRCDIR ,
and falls back to
.Pa /usr/pkgsrc
if that is not set.
.It Fl w
When looking for packages using the package, also check the
.Pa wip/
subtree.
.El
.Sh EXAMPLES
Example for the output if there is a problem:
.Bd -literal
# python-versions-check.py math/py-numpy
Supported Python versions for math/py-numpy: [39, 310, 311]
Checking packages used by math/py-numpy:
Checking packages using math/py-numpy:
math/py-scipy: supports [38, 39, 310, 311], missing: [38]
.Ed
This means that while
.Pa math/py-numpy
only supports Python version 3.9, 3.10, and 3.11,
.Pa math/py-scipy
also supports Python version 3.8.
This will break e.g. bulk builds because the required
.Pa py38-numpy
package will not exist.
.Sh BUGS
.Nm
does not handle any conditionals, so if some dependencies
are only intended for some Python versions,
.Nm
will report false warnings.
