# $NetBSD: Makefile.common,v 1.9 2025/03/03 20:29:28 wiz Exp $
# used by net/ndiff/Makefile
# used by net/nmap/Makefile
# used by net/zenmap/Makefile

DISTNAME=	nmap-7.95
CATEGORIES=	net security
MASTER_SITES=	http://nmap.org/dist/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER?=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://nmap.org/
LICENSE=	gnu-gpl-v2

CONFLICTS=	nmap<=7.70

CHECK_PORTABILITY_SKIP+=	libssh2/Makefile.in
