# $NetBSD: buildlink3.mk,v 1.1 2004/04/11 18:36:55 xtraeme Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LESSTIF12_BUILDLINK3_MK:=	${LESSTIF12_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	lesstif12
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlesstif12}
BUILDLINK_PACKAGES+=	lesstif12

.if !empty(LESSTIF12_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.lesstif12+=	lesstif12>=0.91.4
BUILDLINK_PKGSRCDIR.lesstif12?=	../../x11/lesstif12
.endif	# LESSTIF12_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
