# $NetBSD: buildlink3.mk,v 1.3 2006/04/06 06:21:58 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SAM_BUILDLINK3_MK:=	${SAM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sam
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsam}
BUILDLINK_PACKAGES+=	sam

.if !empty(SAM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.sam+=	sam>=4.3nb1
BUILDLINK_ABI_DEPENDS.sam?=	sam>=4.3nb3
BUILDLINK_PKGSRCDIR.sam?=	../../editors/sam
BUILDLINK_DEPMETHOD.sam?=	build
.endif	# SAM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
