# $NetBSD: buildlink3.mk,v 1.11 2006/07/08 23:10:43 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLIB_BUILDLINK3_MK:=	${GLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglib}
BUILDLINK_PACKAGES+=	glib
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}glib

.if !empty(GLIB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.glib+=	glib>=1.2.10nb5
BUILDLINK_ABI_DEPENDS.glib+=	glib>=1.2.10nb7
BUILDLINK_PKGSRCDIR.glib?=	../../devel/glib

PTHREAD_OPTS+=	require
.endif	# GLIB_BUILDLINK3_MK

.include "../../mk/pthread.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
