# $NetBSD: buildlink3.mk,v 1.8 2006/04/06 06:21:49 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLIB_BUILDLINK3_MK:=	${GLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglib}
BUILDLINK_PACKAGES+=	glib

.if !empty(GLIB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.glib+=	glib>=1.2.10nb5
BUILDLINK_ABI_DEPENDS.glib+=	glib>=1.2.10nb7
BUILDLINK_PKGSRCDIR.glib?=	../../devel/glib
.endif	# GLIB_BUILDLINK3_MK

PTHREAD_OPTS+=	require

.include "../../mk/pthread.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
