$NetBSD: patch-pyproject.toml,v 1.1 2026/08/12 21:49:25 wiz Exp $

Fix build with flit_core 4.

--- pyproject.toml.orig	2026-08-12 21:48:26.984565319 +0000
+++ pyproject.toml
@@ -1,19 +1,19 @@
 [build-system]
-requires = ["flit_core"]
+requires = ["flit_core >=3.2,<5"]
 build-backend = "flit_core.buildapi"
 
-[tool.flit.metadata]
-module = "cloudpickle"
-author = "The cloudpickle developer team"
-author-email='cloudpipe@googlegroups.com'
-home-page = "https://github.com/cloudpipe/cloudpickle"
-description-file = "README.md"
+[project]
+name = "cloudpickle"
+authors = [
+    { name = "The cloudpickle developer team", email = "cloudpipe@googlegroups.com" },
+]
+readme = "README.md"
 requires-python = ">=3.8"
 license = "BSD-3-Clause"
+dynamic = ["version", "description"]
 classifiers = [
     'Development Status :: 5 - Production/Stable',
     'Intended Audience :: Developers',
-    'License :: OSI Approved :: BSD License',
     'Operating System :: POSIX',
     'Operating System :: Microsoft :: Windows',
     'Operating System :: MacOS :: MacOS X',
@@ -30,6 +30,9 @@ classifiers = [
     'Topic :: Scientific/Engineering',
     'Topic :: System :: Distributed Computing',
 ]
+
+[project.urls]
+Homepage = "https://github.com/cloudpipe/cloudpickle"
 
 [tool.black]
 line-length = 88
