# $NetBSD: Makefile,v 1.3 2019/06/30 20:14:54 nia Exp $

DISTNAME=	Devel-Leak-0.04
PKGNAME=	p5-${DISTNAME}
PKGREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/S/SR/SREZIC/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://metacpan.org/release/Devel-Leak
COMMENT=	Perl module to look for objects that are not reclaimed

PERL5_PACKLIST=		auto/Devel/Leak/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
