# $NetBSD: Makefile,v 1.3 2014/10/18 21:27:53 szptvlfn Exp $

DISTNAME=	vector-0.10.12.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient Arrays for Haskell
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-primitive/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
