# $NetBSD: buildlink.mk,v 1.1 2001/11/22 12:58:40 agc Exp $
#
# This Makefile fragment is included by packages that use gsl.
#
# To use this Makefile fragment, simply:
#
# (1) Optionally define BUILDLINK_DEPENDS.gsl to the dependency pattern
#     for the version of gsl desired.
# (2) Include this Makefile fragment in the package Makefile,
# (3) Add ${BUILDLINK_DIR}/include to the front of the C preprocessor's header
#     search path, and
# (4) Add ${BUILDLINK_DIR}/lib to the front of the linker's library search
#     path.

.if !defined(GSL_BUILDLINK_MK)
GSL_BUILDLINK_MK=              # defined

.include "../../mk/bsd.buildlink.mk"  

BUILDLINK_DEPENDS.gsl?=        gsl>=1.0
BUILD_DEPENDS+=                        ${BUILDLINK_DEPENDS.gsl}:../../math/gsl

EVAL_PREFIX+=                  BUILDLINK_PREFIX.gsl=gsl
BUILDLINK_PREFIX.gsl_DEFAULT=  ${LOCALBASE}
BUILDLINK_FILES.gsl=   include/gsl/gsl_blas.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_blas_types.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_complex.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_complex_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_complex_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_block_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_cblas.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_chebyshev.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_complex.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_complex_math.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_const.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_const_cgs.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_const_mks.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_const_num.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_dft_complex.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_dft_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_dht.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_diff.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_eigen.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_errno.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft_complex.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft_halfcomplex.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft_halfcomplex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft_real.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fft_real_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_fit.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_heapsort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_histogram.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_histogram2d.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_ieee_utils.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_integration.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_interp.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_linalg.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_machine.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_math.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_complex_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_complex_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_ulong.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_matrix_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_message.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_min.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_mode.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_monte.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_monte_miser.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_monte_plain.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_monte_vegas.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_multifit.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_multifit_nlin.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_multimin.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_multiroots.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_nan.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_ntuple.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_odeiv.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permutation.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_complex_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_complex_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_ushort.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_complex_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_complex_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_permute_vector_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_poly.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_pow_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_precision.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_qrng.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_randist.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_rng.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_roots.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_airy.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_bessel.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_clausen.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_coulomb.h   
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_coupling.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_dawson.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_debye.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_dilog.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_elementary.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_ellint.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_elljac.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_erf.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_exp.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_expint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_fermi_dirac.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_gamma.h   
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_gegenbauer.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_hyperg.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_laguerre.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_lambert.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_legendre.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_log.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_pow_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_psi.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_result.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_synchrotron.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_transport.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_trig.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sf_zeta.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_siman.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_double.h 
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sort_vector_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_specfunc.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_spline.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_uchar.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_uint.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_statistics_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sum.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_sys.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_test.h    
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_char.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_complex.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_complex_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_complex_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_complex_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_float.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_int.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_long.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_long_double.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_short.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_uchar.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_uint.h  
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_ulong.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_vector_ushort.h
BUILDLINK_FILES.gsl+=  include/gsl/gsl_version.h
BUILDLINK_FILES.gsl+=  lib/libgsl.*
          
BUILDLINK_TARGETS.gsl= gsl-buildlink
BUILDLINK_TARGETS+=            ${BUILDLINK_TARGETS.gsl}

pre-configure: ${BUILDLINK_TARGETS.gsl}
gsl-buildlink: _BUILDLINK_USE

.endif # GSL_BUILDLINK_MK
