# $NetBSD: buildlink3.mk,v 1.10 2021/06/01 09:12:22 wiz Exp $

BUILDLINK_TREE+=	gsl

.if !defined(GSL_BUILDLINK3_MK)
GSL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.gsl+=	gsl>=1.4
BUILDLINK_ABI_DEPENDS.gsl+=	gsl>=2.6
BUILDLINK_PKGSRCDIR.gsl?=	../../math/gsl
.endif # GSL_BUILDLINK3_MK

BUILDLINK_TREE+=	-gsl
