.\"     $Emsi: adjustkernel.1,v 1.1 2002/03/01 01:25:37 mjl Exp $
.\"	$NetBSD: adjustkernel.1,v 1.1.1.1 2002/03/01 01:32:14 mjl Exp $
.\"
.Dd February 28, 2002
.Dt adjustkernel 1
.Sh NAME
.Nm adjustkernel
.Nd generate kernel config from dmesg
.Sh SYNOPSIS
.Nm adjustkernel
.Op Fl outfile Ar new-config
.Op Fl mesg Ar dmesg-file
.Op Fl remove
.Op Fl debug
.Fl file Ar source-config
.Sh DESCRIPTION
.Nm
generates a new kernel configuration file from the
current dmesg output and the current kernel config file.
.Pp
The generation can be customized by using the following
options:
.Bl -tag -width Fl
.It Fl debug
be verbose and generate noise (mainly useful for debugging).
.It Fl file Ar source-config
read the currently booted kernel from source-config.
This option is mandatory.
.It Fl outfile Ar new-config
saves the newly generated config file to
.Ar new-config
.It Fl mesg Ar dmesg-file
read the dmesg data from
.Ar dmesg-file,
defaults to calling
.Ar /sbin/dmesg
and using its output.
.It Fl remove
causes the tool to remove entries in the config file instead
of commenting them out.
.El
.Pp
Note that options can be shortened, as long as they can be
unambigously distinguished.
.Sh EXAMPLES
To generate a new kernel config after having booted a
GENERIC kernel,
.Bd -literal
adjustkernel -f GENERIC -o MYKERNEL
.Ed
.Sh SEE ALSO
.Xr options 4
.Sh AUTHORS
Originally created by Hubert Feyrer <hubert.feyrer@informatik.fh-regensburg.de>,
later hacked in shape and packetized by Martin J. Laubach <mjl@netbsd.org>.
.Sh BUGS
On thursdays.
