# $NetBSD: Makefile,v 1.2 2012/10/02 23:47:59 asau Exp $
#

DISTNAME=	mp3wrap-0.5-src
PKGNAME=	mp3wrap-0.5
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=mp3wrap/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://mp3wrap.sourceforge.net/
COMMENT=	Tool to wrap mp3 files into a large one
LICENSE=	gnu-gpl-v2

WRKSRC=		${WRKDIR}/mp3wrap-0.5
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
