.\" (do I need this?)  \# -*- coding: utf-8 -*-
.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DVDBACKUP 1 "July  7, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dvdbackup \- Tool to backup dvd's
.SH SYNOPSIS
.B dvdbackup
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B dvdbackup
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
\fBdvdbackup\fP is a tool to extract data from video dvds.  It has the advantages
of being small, fast, and easy to use.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-i DEVICE
where device is your dvd device
.TP
.B \-v X
where X is the amount of verbosity
.TP
.B \-I
for information about the DVD
.TP
.B \-o directory
where directory is your backup target
.TP
.B \-n name
(optional) set the title \- useful if autodetection fails
.TP
.B \-M
backup the whole DVD
.TP
.B \-F
backup the main feature of the DVD
.TP
.B \-T X
backup title set X
.TP
.B \-t X
backup title X
.TP
.B \-s X
backup from chapter X
.TP
.B \-e X
backup to chapter X
.TP
.B \-a 0
to get aspect ratio 4:3 instead of 16:9 if both are present
.TP
.B \-h
print a brief usage message
.TP
.B \-?
print a brief usage message
.SH Option notes
\-i is mandatory
.br
\-o is mandatory except if you use \-I
.br
\-a is option to the \-F switch and has no effect on other options
.br
\-s and \-e should preferably be used together with \-t
.SH Usage:
To gather info about the dvd:
.br
dvdbackup \-i /dev/dvd \-I
.SH General backup information:
.br
If your backup directory is /my/dvd/backup/dir/ specified with the "\-o" flag. Then dvdbackup will create a DVD\-Video structure under /my/dvd/backup/dir/TITLE_NAME/VIDEO_TS.
.sp 2
Since the title is "unique" you can use the same directory for all your DVD backups. If it happens to have a generic title dvdbackup will exit with a return value of 2, and you will need to specify a title name with the \-n switch.
.sp 2
dvdbackup will always mimic the original DVD\-Video structure. Hence if you e.g. use the \-M (mirror) you will get an exact duplicate of the original. This means that every file will have the same size as the original one. Likewise also for the \-F and the \-T switch.
.sp 2
However the \-t and (\-t \-s/\-e) switch is a bit different the titles sectors will be written to the original file but not at the same offset as the original one since there may be gaps in the cell structure that we don't fill.
.SH To backup the whole DVD
dvdbackup \-M \-i/dev/dvd \-o/my/dvd/backup/dir/
This action creates a valid DVD\-Video structure that can be burned to a DVD\-/+R(W) with help of mkisofs version 1.11a27 or later
.SH To backup the main feature of the DVD:
dvdbackup \-F \-i/dev/dvd \-o/my/dvd/backup/dir/
.sp 2
This action creates a valid DVD\-Video structure of the feature title set.  Note that this will not result in an image immediately watchable - you will need another program like dvdauthor to help construct the IFO files.
.sp 2
dvdbackup defaults to get the 16:9 version of the main feature if a 4:3 is also present on the DVD.  To get the 4:3 version use \-a 0.
.sp 2
dvdbackup makes it best to make a intelligent guess what is the main feature of the DVD \- in case it fails please send a bug report.
.SH To backup a title set
dvdbackup \-T 2 \-i/dev/dvd \-o/my/dvd/backup/dir/
.sp 2
where "\-T 2" specifies that you want to backup title set 2 i.e. all VTS_02_X.XXX files. This action creates a valid DVD\-Video structure of the specified title set.  Note that this will not result in an image immediately watchable - you will need another program like dvdauthor to help construct the IFO files.
.SH To backup a title:
dvdbackup \-t 1 \-i/dev/dvd \-o/my/dvd/backup/dir
.sp 2
This action backups all cells that forms the specified title. Note that there can be sector gaps in between one cell and another. dvdbackup will backup all sectors that belongs to the title but will skip sectors that aren't a part of the title.
.SH To backup a specific chapter or chapters from a title:
dvdbackup \-t 1 \-s 20 \-e 25 \-i/dev/dvd \-o/my/dvd/backup/dir
.sp 2
This action will backup chapter 20 to 25 in title 1, as with the backup of a title there can be sector gaps between one chapter (cell) and on other.  dvdbackup will backup all sectors that belongs to the title 1 chapter 20 to 25 but will skip sectors that aren't a part of the title 1 chapter 20 to 25.
.br
To backup a single chapter e.g. chapter 20 do \-s 20 \-e 20
.br
To backup from chapter 20 to the end chapter use only \-s 20
.br
To backup to chapter 20 from the first chapter use only \-e 20
.sp 2
You can skip the \-t switch and let the program guess the title although it's not recommended.
.sp 2
If you specify a chapter that is higher than the last chapter of the title dvdbackup will truncate to the highest chapter of the title.
.SH Return values:
0 on success
.br
1 on usage error
.br
2 on title name error
.br
\-1 on failure
.SH Todo \- i.e. what's on the agenda.
Make the main feature guessing algorithm better. Not that it doesn't do it's job, but it's implementation isn't that great. I would also like to preserve more information about the main feature since that would let me perform better implementations in other functions that depends on the titles_info_t and title_set_info_t structures. Make it possible to extract cells in a title not just chapters (very easy so it will definitely be in the next version).
.sp 2
Make a split mirror (\-S) option that divides a DVD\-9 to two valid DVD\-5 video structures. This is not a trivial hack and it's my main goal the in next month or so. It involves writing ifoedit and vobedit libraries in order to be able to manipulate both the IFO structures and the VOB files. Out of this will most probably also come tscreate and vtscreate which will enable you to make a very simple DVD\-Video from MPEG\-1/2 source.
.br
.SH AUTHOR
DVDBackup was written by Olaf Beck <olaf_sc@yahoo.com>, but now appears to be dead upstream, and is unmaintained (as far as I know) outside of Debian.
This manual page was written by Stephen Gran <sgran@debian.org>, for the Debian project (but may be used by others).
