# $NetBSD: buildlink3.mk,v 1.12 2006/07/08 23:11:13 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PHP_BUILDLINK3_MK:=	${PHP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	php
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nphp}
BUILDLINK_PACKAGES+=	php
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}php

.if !empty(PHP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.php+=		php-4.4.*
BUILDLINK_ABI_DEPENDS.php+=	php>=4.4.1nb3
BUILDLINK_PKGSRCDIR.php?=	../../www/php4
.endif	# PHP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
