===========================================================================
$NetBSD: MESSAGE.module,v 1.4 2002/12/21 13:39:25 wiz Exp $

To enable this module, add the following to ${PKG_SYSCONFDIR}/php.ini:

    extension=${MODNAME}.so

and make sure extension_dir points to the dir where ${MODNAME}.so is.

Then restart your PHP4-enabled HTTP server to load this module.
===========================================================================
