# $NetBSD: Makefile,v 1.1 2016/07/14 12:02:44 markd Exp $

DISTNAME=	luatex85
PKGNAME=	tex-${DISTNAME}-1.0
TEXLIVE_REV=	39902

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/luatex85
COMMENT=	pdfTeX aliases for LuaTeX
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
