# $NetBSD: buildlink3.mk,v 1.11 2004/10/03 00:14:57 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PNG_BUILDLINK3_MK:=	${PNG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	png
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npng}
BUILDLINK_PACKAGES+=	png

.if !empty(PNG_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.png+=		png>=1.2.4
BUILDLINK_RECOMMENDED.png?=	png>=1.2.6nb1
BUILDLINK_PKGSRCDIR.png?=	../../graphics/png
.endif	# PNG_BUILDLINK3_MK

.include "../../devel/zlib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
