# $NetBSD: buildlink3.mk,v 1.9 2004/08/13 14:20:02 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PNG_BUILDLINK3_MK:=	${PNG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	png
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npng}
BUILDLINK_PACKAGES+=	png

.if !empty(PNG_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.png+=		png>=1.2.6rc1
BUILDLINK_RECOMMENDED.png?=	png>=1.2.6rc2
BUILDLINK_PKGSRCDIR.png?=	../../graphics/png
.endif	# PNG_BUILDLINK3_MK

.include "../../devel/zlib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
