# $NetBSD: buildlink3.mk,v 1.1 2004/04/13 23:32:17 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PARI_BUILDLINK3_MK:=	${PARI_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pari
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npari}
BUILDLINK_PACKAGES+=	pari

.if !empty(PARI_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pari+=	pari>=2.1.5nb1
BUILDLINK_RECOMMENDED.pari+=	pari>=2.1.5nb3
BUILDLINK_PKGSRCDIR.pari?=	../../math/pari
.endif	# PARI_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
