# $NetBSD: Makefile,v 1.6 2012/12/22 02:08:58 dholland Exp $

WBM_NAME=	cluster-webmin
PKGREVISION=	1

COMMENT=	Webmin module to manage Webmin settings across a Webmin cluster

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
