# $NetBSD: buildlink3.mk,v 1.1 2004/07/07 19:06:23 drochner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GROFF_BUILDLINK3_MK:=	${GROFF_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	groff
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngroff}
BUILDLINK_PACKAGES+=	groff

.if !empty(GROFF_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.groff+=	groff>=1.19nb4
BUILDLINK_PKGSRCDIR.groff?=	../../textproc/groff

BUILDLINK_DEPMETHOD.groff?=	build
.endif	# GROFF_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
