# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/11/02 20:32:38 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GTL0_BUILDLINK3_MK:=	${GTL0_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gtl0
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngtl0}
BUILDLINK_PACKAGES+=	gtl0

.if !empty(GTL0_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.gtl0+=	gtl0>=0.3.3nb1
BUILDLINK_PKGSRCDIR.gtl0?=	../../devel/gtl0
.endif	# GTL0_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
