# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:36 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GSM_BUILDLINK3_MK:=	${GSM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gsm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngsm}
BUILDLINK_PACKAGES+=	gsm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}gsm

.if !empty(GSM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.gsm+=		gsm>=1.0.10
BUILDLINK_ABI_DEPENDS.gsm+=	gsm>=1.0.10nb1
BUILDLINK_PKGSRCDIR.gsm?=	../../audio/gsm
.endif	# GSM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
