#!@SH@
# $NetBSD: mozilla.sh,v 1.5 2005/01/22 10:23:22 jdolecek Exp $

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:@PREFIX@/lib/@MOZILLA@@MOZ_EXTRA@-@MOZ_PLATFORM@"
export LD_LIBRARY_PATH

exec @PREFIX@/lib/@MOZILLA@@MOZ_EXTRA@-@MOZ_PLATFORM@/@MOZILLA@ "$@"
