#!@SH@
# $NetBSD: mozilla.sh,v 1.4 2004/01/04 05:01:03 grant Exp $

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:@PREFIX@/lib/@MOZILLA@@MOZ_EXTRA@-@MOZ_PLATFORM@:@PREFIX@/lib"
export LD_LIBRARY_PATH

exec @PREFIX@/lib/@MOZILLA@@MOZ_EXTRA@-@MOZ_PLATFORM@/@MOZILLA@ "$@"
