.TH 822addr 1
.SH NAME
.PP
\fB\fC822addr\fR \- extract email addresses from messages
.SH SYNOPSIS
.PP
.RS
.nf
822addr _field_ ...
.fi
.RE
.SH DESCRIPTION
.PP
The \fB\fC822addr\fR program reads an 822\-format email message from standard input.
For each input header \fB\fC_field_\fR, \fB\fC822addr\fR parses the value of the header as
one or more email addresses and prints the result to standard output. If no
\fB\fC_field_\fR appears, \fB\fC822addr\fR looks for \fB\fC_to_\fR and \fB\fC_cc_\fR\&.
.PP
Output records are null terminated. The first character of each output record
indicates the address type, and the remainder is the value. A delivery address
begins with a \fB\fC+\fR character, and a comment begins with a \fB\fC(\fR character. When
paired, a comment precedes an address.
.PP
The end of the message or the first line that cannot be part of an 822\-format
header field terminates the search.
.SH EXIT STATUS
.PP
If it encounters an error while processing a message, \fB\fC822addr\fR exits 111\&. If
\fB\fC822addr\fR finds any matching headers, it exits 0\&. Otherwise, \fB\fC822addr\fR exits
100.
.SH BUGS
.PP
No formatting options.
.SH AUTHOR
.PP
William Baxter <sst@superscript.com>
.PP
Version 0.56
.br
Last updated 2015\-08\-23 23:24:43 CDT
