.TH checkaddr 1
.SH NAME
.PP
\fB\fCcheckaddr\fR \- check input for matching address
.SH SYNOPSIS
.PP
.RS
.nf
checkaddr _addr_ ...
.fi
.RE
.SH DESCRIPTION
.PP
The \fB\fCcheckaddr\fR program reads email addresses from standard input, and
compares them with each \fB\fC_addr_\fR without regard to case. If no \fB\fC_addr_\fR
appears, \fB\fC822addr\fR uses the environment variable \fB\fC$RECIPIENT\fR as \fB\fC_addr_\fR\&. The
\fB\fCcheckaddr\fR program reads addresses in the form output by
\fB\fC822addr\fR \[la]822addr.html\[ra]\&. It considers only delivery addresses and ignores
address comments.
.SH EXIT STATUS
.PP
If it finds a match, \fB\fCcheckaddr\fR exits 0\&. Otherwise, \fB\fCcheckaddr\fR exits 100.
.SH AUTHOR
.PP
William Baxter <sst@superscript.com>
.PP
Version 0.56
.br
Last updated 2015\-08\-23 23:24:43 CDT
