.TH condtomaildir 1
.SH NAME
.PP
\fB\fCcondtomaildir\fR \- conditionally deliver a message to a maildir
.SH SYNOPSIS
.PP
In \fB\fC\&.qmail\fR:
.PP
.RS
.nf
| condtomaildir _dir_ _prog_
.fi
.RE
.SH DESCRIPTION
.PP
The \fB\fCcondtomaildir\fR runs the program \fB\fC_prog_\fR with an email message on
standard input. It expects \fB\fC_dir_\fR to be a Maildir\-format directory.
.PP
If \fB\fC_prog_\fR exits 0, \fB\fCcondtomaildir\fR writes the email message to the maildir
\fB\fC_dir_\fR, and then exits 99\&. If \fB\fC_prog_\fR exits 111, \fB\fCcondtomaildir\fR exits
111\&. If \fB\fC_prog_\fR exits anything else, or does not exist, \fB\fCcondtomaildir\fR
exits 0.
.SH EXIT STATUS
.PP
If it encounters a permanent error in handling a message, \fB\fCcondtomaildir\fR
exits 100\&. If it encounters a temporary error in handling a message,
\fB\fCcondtomaildir\fR exits 111.
.SH AUTHOR
.PP
William Baxter <sst@superscript.com>
.PP
Version 0.56
.br
Last updated 2015\-08\-23 23:24:43 CDT
