# $NetBSD: Makefile,v 1.4 2010/09/24 21:09:27 minskim Exp $

DISTNAME=	hyph-utf8.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2010
TEXLIVE_REV=	19815

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-hyph-utf8

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
