# $NetBSD: Makefile,v 1.2 2022/01/18 02:48:10 pho Exp $

DISTNAME=	mmap-0.5.9
PKGREVISION=	1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Memory mapped files for POSIX and Windows
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
