# $NetBSD: buildlink3.mk,v 1.4 2006/07/08 22:39:10 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBELF_BUILDLINK3_MK:=	${LIBELF_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libelf
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibelf}
BUILDLINK_PACKAGES+=	libelf
BUILDLINK_ORDER+=	libelf

.if !empty(LIBELF_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libelf+=	libelf>=0.8.5
BUILDLINK_PKGSRCDIR.libelf?=	../../devel/libelf
BUILDLINK_DEPMETHOD.libelf?=	build
.endif	# LIBELF_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
