# $NetBSD: buildlink3.mk,v 1.3 2009/03/05 21:03:35 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XTRANS_BUILDLINK3_MK:=	${XTRANS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xtrans
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxtrans}
BUILDLINK_PACKAGES+=	xtrans
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xtrans

.if ${XTRANS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xtrans?=		xtrans>=1.0.3
BUILDLINK_PKGSRCDIR.xtrans?=		../../x11/xtrans
BUILDLINK_DEPMETHOD.xtrans?=		build
.endif	# XTRANS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
