# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 16:55:55 joerg Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XTRANS_BUILDLINK3_MK:=	${XTRANS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	xtrans
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxtrans}
BUILDLINK_PACKAGES+=	xtrans

.if !empty(XTRANS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.xtrans?=		xtrans>=0.99.1
BUILDLINK_PKGSRCDIR.xtrans?=		../../x11/xtrans
BUILDLINK_DEPMETHOD.xtrans?=		build
.endif # XTRANS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
