# $NetBSD: Makefile,v 1.4 2019/08/08 19:53:39 brook Exp $

R_PKGNAME=	glue
R_PKGVER=	1.3.1
CATEGORIES=	devel

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Interpreted string literals
LICENSE=	mit

USE_LANGUAGES=	c

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
