# $NetBSD: Makefile,v 1.1 2015/05/08 14:09:53 wiz Exp $

DISTNAME=	resumemac.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2014
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/resumemac
COMMENT=	Documentation for tex-resumemac
LICENSE=	public-domain

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
