# $NetBSD: Makefile,v 1.11 2000/05/12 09:50:02 agc Exp $
# FreeBSD Id: Makefile,v 1.3 1996/11/12 02:19:38 obrien Exp
#

DISTNAME=       rc-1.6
CATEGORIES=	shells plan9
MASTER_SITES=   http://www.star.le.ac.uk/%7Etjg/rc/release/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.star.le.ac.uk/%7Etjg/rc/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--with-history

.include "../../mk/bsd.pkg.mk"
