# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:11:04 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SOCKS5_BUILDLINK3_MK:=	${SOCKS5_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	socks5
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsocks5}
BUILDLINK_PACKAGES+=	socks5
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}socks5

.if !empty(SOCKS5_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.socks5+=	socks5>=1.0.2
BUILDLINK_PKGSRCDIR.socks5?=	../../net/socks5
.endif	# SOCKS5_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
