# $NetBSD: buildlink3.mk,v 1.3 2004/01/05 11:05:46 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SOCKS5_BUILDLINK3_MK:=	${SOCKS5_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	socks5
.endif

.if !empty(SOCKS5_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		socks5
BUILDLINK_DEPENDS.socks5?=	socks5>=1.0.2
BUILDLINK_PKGSRCDIR.socks5?=	../../net/socks5
.endif	# SOCKS5_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
