===========================================================================
$NetBSD: MESSAGE.module,v 1.1 2004/11/05 21:40:25 jdolecek Exp $

To enable this module, add the following to ${PKG_SYSCONFDIR}/php.ini:

    extension=${MODNAME}.so

and make sure extension_dir points to the dir where ${MODNAME}.so is.

Then restart your PHP${PKG_PHP_VERSION}-enabled HTTP server to load this module.
===========================================================================
