===========================================================================
$NetBSD: MESSAGE.module,v 1.4 2016/07/17 15:49:44 jdolecek Exp $

Module configuration file was created and module should be autoloaded:
${EXT_CONF_DIR}/${MODNAME}.ini

Make sure to update your ${PKG_SYSCONFDIR}/php.ini to not load this
extension explicitely, remove:
${EXTENSION_DIRECTIVE}=${EXTENSION_FILE}

Restart your ${PKG_PHP}-enabled HTTP server to load this module.
===========================================================================
