===========================================================================
$NetBSD: MESSAGE.module,v 1.5 2016/10/18 19:09:10 jdolecek Exp $

By default, example module configuration file was copied to following
location, and module should be auto-loaded:
${PHP_EXT_CONF_DIR}/${MODNAME}.ini

If you use custom ${PKG_SYSCONFDIR}/php.ini, or nonstandard module
configuration file location, you might need to add explicit load directive:
${EXTENSION_DIRECTIVE}=${EXTENSION_FILE}
===========================================================================
