$NetBSD: patch-SKK-JISYO.L,v 1.1 2026/01/08 15:55:23 ryoon Exp $

--- SKK-JISYO.L.orig	2026-01-07 14:56:18.826286871 +0000
+++ SKK-JISYO.L
@@ -33188,6 +33188,7 @@ musette /ミュゼット/
 muse /ミューズ/
 musee /ミュゼ;(Fr)美術館/
 musette /ミュゼット/
+museum /ミュージアム/
 musharraf /ムシャラフ/
 mushroom /マッシュルーム/
 music /ミュージック/♪;quaver/♯;sharp/♭;flat/∫;※積分記号(integral)/∬;※二重積分記号/
@@ -33198,7 +33199,6 @@ musik /ムジーク;(独語)音楽/
 musicschool /ミュージックスクール/
 musicvideo /ミュージックビデオ/
 musik /ムジーク;(独語)音楽/
-musium /ミュージアム/
 musket /マスケット/
 muslim /ムスリム/
 muslin /モスリン/
