# $NetBSD: buildlink3.mk,v 1.1 2004/01/19 13:15:52 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GMP_BUILDLINK3_MK:=	${GMP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gmp
.endif

.if !empty(GMP_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		gmp
BUILDLINK_DEPENDS.gmp?=		gmp>=4.1.2
BUILDLINK_PKGSRCDIR.gmp?=	../../devel/gmp

.endif # GMP_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
