# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 23:11:03 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBCARES_BUILDLINK3_MK:=	${LIBCARES_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libcares
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibcares}
BUILDLINK_PACKAGES+=	libcares
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libcares

.if !empty(LIBCARES_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libcares+=	libcares>=1.3.0
BUILDLINK_PKGSRCDIR.libcares?=	../../net/libcares
.endif	# LIBCARES_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
