# $NetBSD: buildlink3.mk,v 1.3 2004/10/03 00:12:53 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FACES_BUILDLINK3_MK:=	${FACES_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	faces
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfaces}
BUILDLINK_PACKAGES+=	faces

.if !empty(FACES_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.faces+=	faces>=1.6.1nb1
BUILDLINK_RECOMMENDED.faces+=	faces>=1.6.1nb3
BUILDLINK_PKGSRCDIR.faces?=	../../mail/faces
.endif	# FACES_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
