# $NetBSD: Makefile,v 1.4 2019/12/06 19:32:26 markd Exp $

DISTNAME=	sourcesanspro.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.6
TEXLIVE_REV=	42852

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/sourcesanspro
COMMENT=	Documentation for tex-sourcesanspro
LICENSE=	ofl-v1.1 AND lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
