# $NetBSD: buildlink3.mk,v 1.12 2008/01/18 05:08:26 tnn Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBESMTP_BUILDLINK3_MK:=	${LIBESMTP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libesmtp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibesmtp}
BUILDLINK_PACKAGES+=	libesmtp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libesmtp

.if !empty(LIBESMTP_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libesmtp+=	libesmtp>=1.0rc1nb1
BUILDLINK_ABI_DEPENDS.libesmtp?=	libesmtp>=1.0.4nb1
BUILDLINK_PKGSRCDIR.libesmtp?=	../../mail/libesmtp

LIBESMTP=	-lesmtp

CONFIGURE_ENV+=	LIBESMTP=${LIBESMTP:Q}
MAKE_ENV+=	LIBESMTP=${LIBESMTP:Q}

.endif	# LIBESMTP_BUILDLINK3_MK

.include "../../security/openssl/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
