# $NetBSD: buildlink3.mk,v 1.4 2004/03/26 02:27:44 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBESMTP_BUILDLINK3_MK:=	${LIBESMTP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libesmtp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibesmtp}
BUILDLINK_PACKAGES+=	libesmtp

.if !empty(LIBESMTP_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libesmtp+=	libesmtp>=1.0rc1nb1
BUILDLINK_RECOMMENDED.libesmtp?=	libesmtp>=1.0.1nb2
BUILDLINK_PKGSRCDIR.libesmtp?=	../../mail/libesmtp

LIBESMTP=	-lesmtp

CONFIGURE_ENV+=	LIBESMTP="${LIBESMTP}"
MAKE_ENV+=	LIBESMTP="${LIBESMTP}"

.endif	# LIBESMTP_BUILDLINK3_MK

.include "../../security/openssl/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
