# $NetBSD: Makefile,v 1.21 2020/05/10 03:56:41 markd Exp $

DISTNAME=	koma-script
PKGNAME=	tex-${DISTNAME}-3.30
TEXLIVE_REV=	54825

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/koma-script
COMMENT=	Bundle of versatile classes and packages
LICENSE=	lppl-1.3c

DEPENDS+=	tex-graphics-[0-9]*:../../print/tex-graphics

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
