# $NetBSD: buildlink3.mk,v 1.8 2008/04/09 09:01:52 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TIDY_BUILDLINK3_MK:=	${TIDY_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tidy
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntidy}
BUILDLINK_PACKAGES+=	tidy
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}tidy

.if !empty(TIDY_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.tidy+=	tidy>=20080324
BUILDLINK_PKGSRCDIR.tidy?=	../../www/tidy
.endif	# TIDY_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
