# $NetBSD: buildlink3.mk,v 1.5 2006/04/12 10:27:40 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TIDY_BUILDLINK3_MK:=	${TIDY_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tidy
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntidy}
BUILDLINK_PACKAGES+=	tidy

.if !empty(TIDY_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.tidy+=	tidy>=20031002
BUILDLINK_ABI_DEPENDS.tidy?=	tidy>=20050921nb1
BUILDLINK_PKGSRCDIR.tidy?=	../../www/tidy
.endif	# TIDY_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
