@comment $NetBSD: PLIST.App,v 1.1 2026/03/03 21:24:21 tnn Exp $
Applications/Alacritty.app/Contents/Info.plist
Applications/Alacritty.app/Contents/MacOS/alacritty
Applications/Alacritty.app/Contents/Resources/61/alacritty
Applications/Alacritty.app/Contents/Resources/61/alacritty-direct
Applications/Alacritty.app/Contents/Resources/alacritty-bindings.5.gz
Applications/Alacritty.app/Contents/Resources/alacritty-msg.1.gz
Applications/Alacritty.app/Contents/Resources/alacritty.1.gz
Applications/Alacritty.app/Contents/Resources/alacritty.5.gz
Applications/Alacritty.app/Contents/Resources/alacritty.icns
Applications/Alacritty.app/Contents/Resources/completions/_alacritty
Applications/Alacritty.app/Contents/Resources/completions/alacritty.bash
Applications/Alacritty.app/Contents/Resources/completions/alacritty.fish
Applications/Alacritty.app/Contents/_CodeSignature/CodeResources
