# $NetBSD: buildlink3.mk,v 1.14 2012/05/07 01:53:55 dholland Exp $

BUILDLINK_TREE+=	teTeX-bin

.if !defined(TETEX_BIN_BUILDLINK3_MK)
TETEX_BIN_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.teTeX-bin+=	teTeX-bin>=3.0nb2
BUILDLINK_ABI_DEPENDS.teTeX-bin+=	teTeX-bin>=3.0nb7
BUILDLINK_PKGSRCDIR.teTeX-bin?=	../../print/teTeX3-bin

TEXMFDIST=	${PREFIX}/share/texmf-dist
PLIST_SUBST+=	TEXMFDIST=${TEXMFDIST:C|^${PREFIX}/||}

TEX=etex
PDFTEX=pdfetex
#PKG_TEXMFPREFIX=	${PREFIX}/share/texmf-dist
PKG_TEXMFPREFIX=	${PREFIX}/share/texmf
PKG_LOCALTEXMFPREFIX=	${PREFIX}/share/texmf-local
PLIST_SUBST+=	PKG_TEXMFPREFIX=${PKG_TEXMFPREFIX:C|^${PREFIX}/||}
PLIST_SUBST+=	PKG_LOCALTEXMFPREFIX=${PKG_LOCALTEXMFPREFIX:C|^${PREFIX}/||}
.endif # TETEX_BIN_BUILDLINK3_MK

BUILDLINK_TREE+=	-teTeX-bin
