# $NetBSD: Makefile,v 1.47 2001/01/23 22:32:37 manu Exp $
#

    SUBDIR += atari800
    SUBDIR += bochs
    SUBDIR += compat12
    SUBDIR += compat13
    SUBDIR += darcnes
    SUBDIR += doscmd
    SUBDIR += fmsx
    SUBDIR += freebsd_lib
    SUBDIR += ia64sim
    SUBDIR += linux-locale
    SUBDIR += linuxppc_lib
    SUBDIR += pcemu
    SUBDIR += plex86
    SUBDIR += simh
    SUBDIR += snes9x
    SUBDIR += spim
    SUBDIR += stella
    SUBDIR += suse_audio
    SUBDIR += suse_base
    SUBDIR += suse_compat
    SUBDIR += suse_devel
    SUBDIR += suse_glx
    SUBDIR += suse_gtk
    SUBDIR += suse_libc5
    SUBDIR += suse_libjpeg
    SUBDIR += suse_libpng
    SUBDIR += suse_linux
    SUBDIR += suse_x11
    SUBDIR += suse_xforms
    SUBDIR += swarm
    SUBDIR += uae
    SUBDIR += vice
    SUBDIR += wine
    SUBDIR += wine-current
    SUBDIR += xbeeb
    SUBDIR += xcopilot
    SUBDIR += xm7
    SUBDIR += xmame

.include "../mk/bsd.pkg.subdir.mk"
