$NetBSD: patch-Cargo.toml,v 1.1 2022/10/06 07:43:28 pin Exp $

Allow building on NetBSD

--- Cargo.toml.orig	2022-10-04 22:21:07.000000000 +0000
+++ Cargo.toml
@@ -42,7 +42,7 @@ core-graphics = "0.22.2"
 core-foundation = "0.9.2"
 core-foundation-sys = "0.8.3"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "netbsd"))'.dependencies]
 x11rb = "0.9.0"
 
 [features]
@@ -71,4 +71,4 @@ presentations)
 
 [package.metadata.rpm.targets]
 buildflags = ["--release"]
-t-rec = { path = "/usr/bin/t-rec" }
\ No newline at end of file
+t-rec = { path = "/usr/bin/t-rec" }
