$NetBSD: patch-startkde_config-startplasma.h.cmake,v 1.1 2026/05/04 11:18:46 markd Exp $

From FreeBSD to fix XDG_CONFIG_DIRS

--- startkde/config-startplasma.h.cmake.orig	2025-11-04 15:01:10.000000000 +0000
+++ startkde/config-startplasma.h.cmake
@@ -2,6 +2,7 @@
 
 #define CMAKE_INSTALL_FULL_BINDIR "@CMAKE_INSTALL_FULL_BINDIR@"
 #define KDE_INSTALL_FULL_DATAROOTDIR "@KDE_INSTALL_FULL_DATAROOTDIR@"
+#define KDE_INSTALL_FULL_CONFDIR "@KDE_INSTALL_FULL_CONFDIR@"
 #define CMAKE_INSTALL_FULL_LIBEXECDIR "@CMAKE_INSTALL_FULL_LIBEXECDIR@"
 #define CMAKE_INSTALL_FULL_LIBEXECDIR_KF6 "@CMAKE_INSTALL_FULL_LIBEXECDIR_KF6@"
 #define KWIN_WAYLAND_BIN_PATH "@KWIN_WAYLAND_BIN_PATH@"
