.\" $NetBSD: perllink.1,v 1.2 2006/04/09 06:34:32 jlam Exp $
.\"
.\" Copyright (c) 2005 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Johnny C. Lam.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by the NetBSD
.\"        Foundation, Inc. and its contributors.
.\" 4. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd July 15, 2005
.Dt PERLLINK 1
.Sh NAME
.Nm perllink
.Nd add and delete symlinks in the standard Perl installation
.Sh SYNOPSIS
.Nm perllink
.Op Fl fnv
.Op Fl p Ar prefix
.Ar action
.Op Ar packlist ...
.Sh DESCRIPTION
.Nm
manages the symlinks that match the files listed in the given
packlists.
.Pp
The perl configuration library defines the main directory trees
containing the standard Perl installation in the following variables:
.Bl -column -offset indent
.It Va prefix
.It Va siteprefix
.It Va vendorprefix
.El
.Pp
The perl configuration library also defines the locations of scripts
and manual pages in the following variables:
.Bl -column -offset indent ".Va vendorscript" ".Va vendorman1dir"
.It Va scriptdir Ta Va man1dir
.It Va sitescript Ta Va siteman1dir
.It Va vendorscript Ta Va vendorman1dir
.El
.Pp
For each file listed in the packlists that is in one of the script
or manual page locations,
a relative symbolic link to that file is added or deleted from
. Va prefix Ns Pa /bin
and
. Va prefix Ns Pa /man/man1 .
.Pp
If
.Fl p Ar prefix
is specified, then the script and manual page locations are recomputed
relative to the given
.Ar prefix
instead of to perl's
.Va prefix ,
and the symlinks are managed under the given
.Ar prefix
instead.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Ar action
This required option is either
.Dq add
or
.Dq delete
and determines
whether the managed symlinks are added or deleted.
.It Ar packlist ...
These are paths to packlists containing the files installed as
part of a module.
Each line of a packlist contains a path terminated by a newline.
If no packlists are specified, then the packlist for Perl itself
is used.
.It Fl f , -force
Unlink any already existing files, permitting the new symlinks
to replace the existing ones.
.It Fl n , -noaction
Do not actually make any changes to the files in
.Ar prefix .
.It Fl p Ar prefix , Fl -prefix= Ns Ar prefix
Manage the symlinks in
.Ar prefix .
By default,
.Nm
manages the symlinks in the location referenced by the perl configuration
variable
.Va prefix .
.It Fl v
Be verbose.
Display on standard error the shell-equivalent commands that
are being executed.
.El
.Sh SEE ALSO
.Xr perl 1 ,
.Xr symlink 2
.Sh AUTHORS
.An Johnny C. Lam
.Aq jlam@pkgsrc.org
