# $NetBSD: Makefile,v 1.12 2017/07/16 09:25:34 adam Exp $

DISTNAME=	decorator-4.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=d/decorator/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://pypi.python.org/pypi/decorator
COMMENT=	Generic Python decorator utilities
LICENSE=	2-clause-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
