# $NetBSD: Makefile,v 1.2 2019/12/06 19:30:11 markd Exp $

DISTNAME=	linearA
PKGNAME=	tex-${DISTNAME}-2014
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/linearA
COMMENT=	Linear A script fonts
LICENSE=	lppl-1.3c

TEX_MAP_FILES+=	linearA.map

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
