# $NetBSD: Makefile,v 1.5 1999/09/13 03:33:32 simonb Exp $
#

DISTNAME=		bladeenc-082-src-stable-2
PKGNAME=		bladeenc-0.82pl2
CATEGORIES=		audio
MASTER_SITES=		http://home.swipnet.se/~w-82625/encoder/source/

MAINTAINER=		packages@netbsd.org
HOMEPAGE=		http://bladeenc.cjb.net

#do-install:
#	${INSTALL_SCRIPT} ${WRKDIR}/bladeenc ${PREFIX}/bin/
#	${INSTALL_DATA} ${WRKDIR}/BladeEnc.html ${PREFIX}/share/doc/bladeenc.html

.include "../../mk/bsd.pkg.mk"
