# $NetBSD: buildlink2.mk,v 1.13 2004/02/06 23:01:41 wiz Exp $
#
# This Makefile fragment is included by packages that use koffice.
#
# This file was created automatically using createbuildlink-3.0.
#

.if !defined(KOFFICE_BUILDLINK2_MK)
KOFFICE_BUILDLINK2_MK=	# defined

BUILDLINK_PACKAGES+=			koffice
BUILDLINK_DEPENDS.koffice?=		koffice>=1.3
BUILDLINK_PKGSRCDIR.koffice?=		../../misc/koffice

EVAL_PREFIX+=	BUILDLINK_PREFIX.koffice=koffice
BUILDLINK_PREFIX.koffice_DEFAULT=	${LOCALBASE}
BUILDLINK_FILES.koffice+=	include/KDChartAxisParams.h
BUILDLINK_FILES.koffice+=	include/KDChartCustomBox.h
BUILDLINK_FILES.koffice+=	include/KDChartData.h
BUILDLINK_FILES.koffice+=	include/KDChartDataRegion.h
BUILDLINK_FILES.koffice+=	include/KDChartEnums.h
BUILDLINK_FILES.koffice+=	include/KDChartGlobal.h
BUILDLINK_FILES.koffice+=	include/KDChartListTable.h
BUILDLINK_FILES.koffice+=	include/KDChartParams.h
BUILDLINK_FILES.koffice+=	include/KDChartPropertySet.h
BUILDLINK_FILES.koffice+=	include/KDChartTable.h
BUILDLINK_FILES.koffice+=	include/KDChartTableBase.h
BUILDLINK_FILES.koffice+=	include/KDChartTextPiece.h
BUILDLINK_FILES.koffice+=	include/KDChartVectorTable.h
BUILDLINK_FILES.koffice+=	include/KDChartWidget.h
BUILDLINK_FILES.koffice+=	include/KDFrame.h
BUILDLINK_FILES.koffice+=	include/KDFrameProfileSection.h
BUILDLINK_FILES.koffice+=	include/KoApplicationIface.h
BUILDLINK_FILES.koffice+=	include/KoDocumentIface.h
BUILDLINK_FILES.koffice+=	include/KoMainWindowIface.h
BUILDLINK_FILES.koffice+=	include/KoViewIface.h
BUILDLINK_FILES.koffice+=	include/handler.h
BUILDLINK_FILES.koffice+=	include/kcoloractions.h
BUILDLINK_FILES.koffice+=	include/koApplication.h
BUILDLINK_FILES.koffice+=	include/koCharSelectDia.h
BUILDLINK_FILES.koffice+=	include/koChart.h
BUILDLINK_FILES.koffice+=	include/koChild.h
BUILDLINK_FILES.koffice+=	include/koDocument.h
BUILDLINK_FILES.koffice+=	include/koDocumentChild.h
BUILDLINK_FILES.koffice+=	include/koDocumentInfo.h
BUILDLINK_FILES.koffice+=	include/koDocumentInfoDlg.h
BUILDLINK_FILES.koffice+=	include/koFactory.h
BUILDLINK_FILES.koffice+=	include/koFilter.h
BUILDLINK_FILES.koffice+=	include/koFilterChain.h
BUILDLINK_FILES.koffice+=	include/koFilterManager.h
BUILDLINK_FILES.koffice+=	include/koFrame.h
BUILDLINK_FILES.koffice+=	include/koGlobal.h
BUILDLINK_FILES.koffice+=	include/koInsertLink.h
BUILDLINK_FILES.koffice+=	include/koKoolBar.h
BUILDLINK_FILES.koffice+=	include/koMainWindow.h
BUILDLINK_FILES.koffice+=	include/koPageLayoutDia.h
BUILDLINK_FILES.koffice+=	include/koPartSelectAction.h
BUILDLINK_FILES.koffice+=	include/koPartSelectDia.h
BUILDLINK_FILES.koffice+=	include/koPicture.h
BUILDLINK_FILES.koffice+=	include/koPictureCollection.h
BUILDLINK_FILES.koffice+=	include/koPictureFilePreview.h
BUILDLINK_FILES.koffice+=	include/koPictureKey.h
BUILDLINK_FILES.koffice+=	include/koPoint.h
BUILDLINK_FILES.koffice+=	include/koQueryTrader.h
BUILDLINK_FILES.koffice+=	include/koRect.h
BUILDLINK_FILES.koffice+=	include/koRuler.h
BUILDLINK_FILES.koffice+=	include/koSconfig.h
BUILDLINK_FILES.koffice+=	include/koSize.h
BUILDLINK_FILES.koffice+=	include/koSpell.h
BUILDLINK_FILES.koffice+=	include/koSpellConfig.h
BUILDLINK_FILES.koffice+=	include/koSpelldlg.h
BUILDLINK_FILES.koffice+=	include/koStore.h
BUILDLINK_FILES.koffice+=	include/koStoreDevice.h
BUILDLINK_FILES.koffice+=	include/koTabChooser.h
BUILDLINK_FILES.koffice+=	include/koTemplateChooseDia.h
BUILDLINK_FILES.koffice+=	include/koTemplateCreateDia.h
BUILDLINK_FILES.koffice+=	include/koToolBox.h
BUILDLINK_FILES.koffice+=	include/koUnit.h
BUILDLINK_FILES.koffice+=	include/koUnitWidgets.h
BUILDLINK_FILES.koffice+=	include/koView.h
BUILDLINK_FILES.koffice+=	include/koaspell.h
BUILDLINK_FILES.koffice+=	include/kocommandhistory.h
BUILDLINK_FILES.koffice+=	include/kocontexthelp.h
BUILDLINK_FILES.koffice+=	include/koeditpath.h
BUILDLINK_FILES.koffice+=	include/kofficeversion.h
BUILDLINK_FILES.koffice+=	include/koispell.h
BUILDLINK_FILES.koffice+=	include/kotoolbutton.h
BUILDLINK_FILES.koffice+=	include/kreportviewer.h
BUILDLINK_FILES.koffice+=	include/kugar.h
BUILDLINK_FILES.koffice+=	include/kugarqt.h
BUILDLINK_FILES.koffice+=	include/kword/mailmerge_interface.h
BUILDLINK_FILES.koffice+=	include/mcalcobject.h
BUILDLINK_FILES.koffice+=	include/mdatabasereportengine.h
BUILDLINK_FILES.koffice+=	include/mfieldobject.h
BUILDLINK_FILES.koffice+=	include/mlabelobject.h
BUILDLINK_FILES.koffice+=	include/mlineobject.h
BUILDLINK_FILES.koffice+=	include/mpagecollection.h
BUILDLINK_FILES.koffice+=	include/mpagedisplay.h
BUILDLINK_FILES.koffice+=	include/mreportdetail.h
BUILDLINK_FILES.koffice+=	include/mreportengine.h
BUILDLINK_FILES.koffice+=	include/mreportobject.h
BUILDLINK_FILES.koffice+=	include/mreportsection.h
BUILDLINK_FILES.koffice+=	include/mreportviewer.h
BUILDLINK_FILES.koffice+=	include/mspecialobject.h
BUILDLINK_FILES.koffice+=	include/mutil.h
BUILDLINK_FILES.koffice+=	include/sqlcursor.h
BUILDLINK_FILES.koffice+=	include/tkaction.h
BUILDLINK_FILES.koffice+=	include/tkcoloractions.h
BUILDLINK_FILES.koffice+=	include/tkcombobox.h
BUILDLINK_FILES.koffice+=	include/tktoolbarbutton.h
BUILDLINK_FILES.koffice+=	lib/karbon.*
BUILDLINK_FILES.koffice+=	lib/kchart.*
BUILDLINK_FILES.koffice+=	lib/kde3/clipartthumbnail.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_flattenpathplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_imagetoolplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_insertknotsplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_roundcornersplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_shadoweffectplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_whirlpinchplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/karbon_zoomtoolplugin.*
BUILDLINK_FILES.koffice+=	lib/kde3/kfile_koffice.*
BUILDLINK_FILES.koffice+=	lib/kde3/kfile_ooo.*
BUILDLINK_FILES.koffice+=	lib/kde3/kodocinfopropspage.*
BUILDLINK_FILES.koffice+=	lib/kde3/kofficescan.*
BUILDLINK_FILES.koffice+=	lib/kde3/kofficethumbnail.*
BUILDLINK_FILES.koffice+=	lib/kde3/kwmailmerge_classic.*
BUILDLINK_FILES.koffice+=	lib/kde3/kwmailmerge_qtsqldb.*
BUILDLINK_FILES.koffice+=	lib/kde3/kwmailmerge_qtsqldb_power.*
BUILDLINK_FILES.koffice+=	lib/kde3/libabiwordexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libabiwordimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libamiproexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libamiproimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libapplixspreadimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libapplixwordimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libasciiexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libasciiimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libcsvexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libcsvimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libdbaseimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libdocbookexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libgenerickofilter.*
BUILDLINK_FILES.koffice+=	lib/kde3/libgnumericexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libgnumericimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libhtmlexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libhtmlimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonaiimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonbase.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonepsexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonepsimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonkontourimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonmsodimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonpngexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonsvgexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonsvgimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkarbonxcfexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkchartpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkfolatexexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkfomathmlexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkfomathmlimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkfopngexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkformulapart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkiviopart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkounavailpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkpresenterpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkprkword.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkspelltool.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkspreadcalc.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkspreadhtmlexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkspreadlatexexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkspreadpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkudesignerpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkugarnopimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkugarpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkwordlatexexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libkwordpart.*
BUILDLINK_FILES.koffice+=	lib/kde3/libmswordimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libmswriteexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libmswriteimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libolefilter.*
BUILDLINK_FILES.koffice+=	lib/kde3/libooimpressexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libooimpressimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/liboowriterexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/liboowriterimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libopencalcexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libopencalcimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libpalmdocexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libpalmdocimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libpdfimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libqproimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/librtfexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/librtfimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libthesaurustool.*
BUILDLINK_FILES.koffice+=	lib/kde3/libwmfexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libwmfimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libwmlexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libwmlimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libwpexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libwpimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libxsltexport.*
BUILDLINK_FILES.koffice+=	lib/kde3/libxsltimport.*
BUILDLINK_FILES.koffice+=	lib/kde3/straight_connector.*
BUILDLINK_FILES.koffice+=	lib/kformulamain.*
BUILDLINK_FILES.koffice+=	lib/kivio.*
BUILDLINK_FILES.koffice+=	lib/koshell.*
BUILDLINK_FILES.koffice+=	lib/kpresenter.*
BUILDLINK_FILES.koffice+=	lib/kspread.*
BUILDLINK_FILES.koffice+=	lib/kudesigner.*
BUILDLINK_FILES.koffice+=	lib/kugar.*
BUILDLINK_FILES.koffice+=	lib/kword.*
BUILDLINK_FILES.koffice+=	lib/libkdchart.*
BUILDLINK_FILES.koffice+=	lib/libkformula.*
BUILDLINK_FILES.koffice+=	lib/libkivioconnectortool.*
BUILDLINK_FILES.koffice+=	lib/libkivioselecttool.*
BUILDLINK_FILES.koffice+=	lib/libkiviotexttool.*
BUILDLINK_FILES.koffice+=	lib/libkiviozoomtool.*
BUILDLINK_FILES.koffice+=	lib/libkochart.*
BUILDLINK_FILES.koffice+=	lib/libkofficecore.*
BUILDLINK_FILES.koffice+=	lib/libkofficeui.*
BUILDLINK_FILES.koffice+=	lib/libkopainter.*
BUILDLINK_FILES.koffice+=	lib/libkoscript.*
BUILDLINK_FILES.koffice+=	lib/libkospell.*
BUILDLINK_FILES.koffice+=	lib/libkotext.*
BUILDLINK_FILES.koffice+=	lib/libkowmf.*
BUILDLINK_FILES.koffice+=	lib/libkstore.*
BUILDLINK_FILES.koffice+=	lib/libkudesignercore.*
BUILDLINK_FILES.koffice+=	lib/libkugar.*
BUILDLINK_FILES.koffice+=	lib/libkwmailmerge_interface.*
BUILDLINK_FILES.koffice+=	lib/libkwmf.*
BUILDLINK_FILES.koffice+=	lib/libkwordexportfilters.*

.include "../../converters/wv2/buildlink2.mk"
.include "../../textproc/aspell/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../textproc/libxslt/buildlink2.mk"
.include "../../graphics/ImageMagick/buildlink2.mk"
.include "../../graphics/jasper/buildlink2.mk"
.include "../../graphics/libart2/buildlink2.mk"
.include "../../graphics/tiff/buildlink2.mk"
.include "../../meta-pkgs/kde3/buildlink2.mk"
.include "../../x11/kdebase3/buildlink2.mk"

BUILDLINK_TARGETS+=	koffice-buildlink

koffice-buildlink: _BUILDLINK_USE

.endif	# KOFFICE_BUILDLINK2_MK
