 $NetBSD: Makefile,v 1.28 1999/09/07 13:21:37 ad Exp $
# FreeBSD Id: Makefile,v 1.45 1997/08/13 18:35:22 andreas Exp 
#

#    SUBDIR += bulk_mailer
    SUBDIR += coolmail
    SUBDIR += cucipop
#    SUBDIR += cyrus
    SUBDIR += elm
    SUBDIR += exim
    SUBDIR += exmh
    SUBDIR += faces
    SUBDIR += fetchmail
    SUBDIR += fromto
    SUBDIR += grepmail
    SUBDIR += imap-uw
#    SUBDIR += mailagent
    SUBDIR += mailwrapper
#    SUBDIR += majorcool
    SUBDIR += majordomo
    SUBDIR += metamail
#    SUBDIR += mew
#    SUBDIR += mh
    SUBDIR += mhonarc
    SUBDIR += mush
    SUBDIR += mutt
    SUBDIR += nmh
#    SUBDIR += p5-Mail-Folder
#    SUBDIR += p5-Mail-POP3Client
#    SUBDIR += p5-Mail-Tools
     SUBDIR += p5-MailTools
#    SUBDIR += pgpsendmail
    SUBDIR += pine
#    SUBDIR += popclient
#    SUBDIR += poppassd
#    SUBDIR += popper
#    SUBDIR += premail
    SUBDIR += procmail
    SUBDIR += qpopper
    SUBDIR += sendmail
#    SUBDIR += smail
    SUBDIR += wmmail
#    SUBDIR += xfaces
    SUBDIR += xfmail
#    SUBDIR += xlbiff
    SUBDIR += xmailbox
#    SUBDIR += youbin

.include "../mk/bsd.pkg.subdir.mk"
