@comment $NetBSD: PLIST.emacs,v 1.2 2001/12/11 15:49:26 wiz Exp $
bin/base64-decode
bin/base64-encode
bin/qp-decode
bin/qp-encode
@unexec install-info --delete --info-dir=%D/info %D/info/vm.info
info/vm.info
info/vm.info-1
info/vm.info-2
info/vm.info-3
info/vm.info-4
@exec install-info --info-dir=%D/info %D/info/vm.info
share/emacs/site-lisp/vm/pixmaps/audio_stamp-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/audio_stamp-simple.xpm
share/emacs/site-lisp/vm/pixmaps/autofile-dn.xbm
share/emacs/site-lisp/vm/pixmaps/autofile-dn.xpm
share/emacs/site-lisp/vm/pixmaps/autofile-up.xbm
share/emacs/site-lisp/vm/pixmaps/autofile-up.xpm
share/emacs/site-lisp/vm/pixmaps/autofile-xx.xbm
share/emacs/site-lisp/vm/pixmaps/compose-dn.xbm
share/emacs/site-lisp/vm/pixmaps/compose-dn.xpm
share/emacs/site-lisp/vm/pixmaps/compose-up.xbm
share/emacs/site-lisp/vm/pixmaps/compose-up.xpm
share/emacs/site-lisp/vm/pixmaps/compose-xx.xbm
share/emacs/site-lisp/vm/pixmaps/delete-dn.xbm
share/emacs/site-lisp/vm/pixmaps/delete-dn.xpm
share/emacs/site-lisp/vm/pixmaps/delete-up.xbm
share/emacs/site-lisp/vm/pixmaps/delete-up.xpm
share/emacs/site-lisp/vm/pixmaps/delete-xx.xbm
share/emacs/site-lisp/vm/pixmaps/document-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/document-simple.xpm
share/emacs/site-lisp/vm/pixmaps/file-dn.xbm
share/emacs/site-lisp/vm/pixmaps/file-dn.xpm
share/emacs/site-lisp/vm/pixmaps/file-up.xbm
share/emacs/site-lisp/vm/pixmaps/file-up.xpm
share/emacs/site-lisp/vm/pixmaps/file-xx.xbm
share/emacs/site-lisp/vm/pixmaps/film-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/film-simple.xpm
share/emacs/site-lisp/vm/pixmaps/gear-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/gear-simple.xpm
share/emacs/site-lisp/vm/pixmaps/getmail-dn.xbm
share/emacs/site-lisp/vm/pixmaps/getmail-dn.xpm
share/emacs/site-lisp/vm/pixmaps/getmail-up.xbm
share/emacs/site-lisp/vm/pixmaps/getmail-up.xpm
share/emacs/site-lisp/vm/pixmaps/getmail-xx.xbm
share/emacs/site-lisp/vm/pixmaps/help-dn.xbm
share/emacs/site-lisp/vm/pixmaps/help-dn.xpm
share/emacs/site-lisp/vm/pixmaps/help-up.xbm
share/emacs/site-lisp/vm/pixmaps/help-up.xpm
share/emacs/site-lisp/vm/pixmaps/help-xx.xbm
share/emacs/site-lisp/vm/pixmaps/message-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/message-simple.xpm
share/emacs/site-lisp/vm/pixmaps/mime-colorful-dn.xpm
share/emacs/site-lisp/vm/pixmaps/mime-colorful-up.xpm
share/emacs/site-lisp/vm/pixmaps/mime-colorful-xx.xpm
share/emacs/site-lisp/vm/pixmaps/mime-dn.xbm
share/emacs/site-lisp/vm/pixmaps/mime-simple-dn.xpm
share/emacs/site-lisp/vm/pixmaps/mime-simple-up.xpm
share/emacs/site-lisp/vm/pixmaps/mime-simple-xx.xpm
share/emacs/site-lisp/vm/pixmaps/mime-up.xbm
share/emacs/site-lisp/vm/pixmaps/mime-xx.xbm
share/emacs/site-lisp/vm/pixmaps/mona_stamp-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/mona_stamp-simple.xpm
share/emacs/site-lisp/vm/pixmaps/next-dn.xbm
share/emacs/site-lisp/vm/pixmaps/next-dn.xpm
share/emacs/site-lisp/vm/pixmaps/next-up.xbm
share/emacs/site-lisp/vm/pixmaps/next-up.xpm
share/emacs/site-lisp/vm/pixmaps/next-xx.xbm
share/emacs/site-lisp/vm/pixmaps/previous-dn.xbm
share/emacs/site-lisp/vm/pixmaps/previous-dn.xpm
share/emacs/site-lisp/vm/pixmaps/previous-up.xbm
share/emacs/site-lisp/vm/pixmaps/previous-up.xpm
share/emacs/site-lisp/vm/pixmaps/previous-xx.xbm
share/emacs/site-lisp/vm/pixmaps/print-dn.xbm
share/emacs/site-lisp/vm/pixmaps/print-dn.xpm
share/emacs/site-lisp/vm/pixmaps/print-up.xbm
share/emacs/site-lisp/vm/pixmaps/print-up.xpm
share/emacs/site-lisp/vm/pixmaps/print-xx.xbm
share/emacs/site-lisp/vm/pixmaps/quit-dn.xbm
share/emacs/site-lisp/vm/pixmaps/quit-dn.xpm
share/emacs/site-lisp/vm/pixmaps/quit-up.xbm
share/emacs/site-lisp/vm/pixmaps/quit-up.xpm
share/emacs/site-lisp/vm/pixmaps/quit-xx.xbm
share/emacs/site-lisp/vm/pixmaps/recover-dn.xbm
share/emacs/site-lisp/vm/pixmaps/recover-dn.xpm
share/emacs/site-lisp/vm/pixmaps/recover-up.xbm
share/emacs/site-lisp/vm/pixmaps/recover-up.xpm
share/emacs/site-lisp/vm/pixmaps/recover-xx.xbm
share/emacs/site-lisp/vm/pixmaps/reply-dn.xbm
share/emacs/site-lisp/vm/pixmaps/reply-dn.xpm
share/emacs/site-lisp/vm/pixmaps/reply-up.xbm
share/emacs/site-lisp/vm/pixmaps/reply-up.xpm
share/emacs/site-lisp/vm/pixmaps/reply-xx.xbm
share/emacs/site-lisp/vm/pixmaps/stuffed_box-colorful.xpm
share/emacs/site-lisp/vm/pixmaps/stuffed_box-simple.xpm
share/emacs/site-lisp/vm/pixmaps/undelete-dn.xbm
share/emacs/site-lisp/vm/pixmaps/undelete-dn.xpm
share/emacs/site-lisp/vm/pixmaps/undelete-up.xbm
share/emacs/site-lisp/vm/pixmaps/undelete-up.xpm
share/emacs/site-lisp/vm/pixmaps/undelete-xx.xbm
share/emacs/site-lisp/vm/pixmaps/visit-dn.xbm
share/emacs/site-lisp/vm/pixmaps/visit-dn.xpm
share/emacs/site-lisp/vm/pixmaps/visit-up.xbm
share/emacs/site-lisp/vm/pixmaps/visit-up.xpm
share/emacs/site-lisp/vm/pixmaps/visit-xx.xbm
share/emacs/site-lisp/vm/tapestry.el
share/emacs/site-lisp/vm/tapestry.elc
share/emacs/site-lisp/vm/vm-autoload.el
share/emacs/site-lisp/vm/vm-autoload.elc
share/emacs/site-lisp/vm/vm-byteopts.el
share/emacs/site-lisp/vm/vm-crypto.el
share/emacs/site-lisp/vm/vm-crypto.elc
share/emacs/site-lisp/vm/vm-delete.el
share/emacs/site-lisp/vm/vm-delete.elc
share/emacs/site-lisp/vm/vm-digest.el
share/emacs/site-lisp/vm/vm-digest.elc
share/emacs/site-lisp/vm/vm-easymenu.el
share/emacs/site-lisp/vm/vm-easymenu.elc
share/emacs/site-lisp/vm/vm-edit.el
share/emacs/site-lisp/vm/vm-edit.elc
share/emacs/site-lisp/vm/vm-folder.el
share/emacs/site-lisp/vm/vm-folder.elc
share/emacs/site-lisp/vm/vm-imap.el
share/emacs/site-lisp/vm/vm-imap.elc
share/emacs/site-lisp/vm/vm-license.el
share/emacs/site-lisp/vm/vm-license.elc
share/emacs/site-lisp/vm/vm-macro.el
share/emacs/site-lisp/vm/vm-macro.elc
share/emacs/site-lisp/vm/vm-mark.el
share/emacs/site-lisp/vm/vm-mark.elc
share/emacs/site-lisp/vm/vm-menu.el
share/emacs/site-lisp/vm/vm-menu.elc
share/emacs/site-lisp/vm/vm-message.el
share/emacs/site-lisp/vm/vm-message.elc
share/emacs/site-lisp/vm/vm-mime.el
share/emacs/site-lisp/vm/vm-mime.elc
share/emacs/site-lisp/vm/vm-minibuf.el
share/emacs/site-lisp/vm/vm-minibuf.elc
share/emacs/site-lisp/vm/vm-misc.el
share/emacs/site-lisp/vm/vm-misc.elc
share/emacs/site-lisp/vm/vm-motion.el
share/emacs/site-lisp/vm/vm-motion.elc
share/emacs/site-lisp/vm/vm-mouse.el
share/emacs/site-lisp/vm/vm-mouse.elc
share/emacs/site-lisp/vm/vm-page.el
share/emacs/site-lisp/vm/vm-page.elc
share/emacs/site-lisp/vm/vm-pop.el
share/emacs/site-lisp/vm/vm-pop.elc
share/emacs/site-lisp/vm/vm-reply.el
share/emacs/site-lisp/vm/vm-reply.elc
share/emacs/site-lisp/vm/vm-save.el
share/emacs/site-lisp/vm/vm-save.elc
share/emacs/site-lisp/vm/vm-search.el
share/emacs/site-lisp/vm/vm-search.elc
share/emacs/site-lisp/vm/vm-sort.el
share/emacs/site-lisp/vm/vm-sort.elc
share/emacs/site-lisp/vm/vm-startup.el
share/emacs/site-lisp/vm/vm-startup.elc
share/emacs/site-lisp/vm/vm-summary.el
share/emacs/site-lisp/vm/vm-summary.elc
share/emacs/site-lisp/vm/vm-thread.el
share/emacs/site-lisp/vm/vm-thread.elc
share/emacs/site-lisp/vm/vm-toolbar.el
share/emacs/site-lisp/vm/vm-toolbar.elc
share/emacs/site-lisp/vm/vm-undo.el
share/emacs/site-lisp/vm/vm-undo.elc
share/emacs/site-lisp/vm/vm-user.el
share/emacs/site-lisp/vm/vm-user.elc
share/emacs/site-lisp/vm/vm-vars.el
share/emacs/site-lisp/vm/vm-vars.elc
share/emacs/site-lisp/vm/vm-version.el
share/emacs/site-lisp/vm/vm-version.elc
share/emacs/site-lisp/vm/vm-virtual.el
share/emacs/site-lisp/vm/vm-virtual.elc
share/emacs/site-lisp/vm/vm-window.el
share/emacs/site-lisp/vm/vm-window.elc
share/emacs/site-lisp/vm/vm.el
share/emacs/site-lisp/vm/vm.elc
@dirrm share/emacs/site-lisp/vm/pixmaps
@dirrm share/emacs/site-lisp/vm
@unexec rmdir %D/share/emacs/site-lisp 2>/dev/null || true
