# $NetBSD: buildlink3.mk,v 1.6 2005/10/09 03:23:11 ben Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FAAD2_BUILDLINK3_MK:=	${FAAD2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	faad2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfaad2}
BUILDLINK_PACKAGES+=	faad2

.if !empty(FAAD2_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.faad2+=	faad2>=2.0nb3
BUILDLINK_PKGSRCDIR.faad2?=	../../audio/faad2
BUILDLINK_INCDIRS.faad2?=	include/faad2
.endif	# FAAD2_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
