# $NetBSD: buildlink3.mk,v 1.12 2008/02/25 16:12:34 sborrill Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FAAD2_BUILDLINK3_MK:=	${FAAD2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	faad2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfaad2}
BUILDLINK_PACKAGES+=	faad2
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}faad2

.if !empty(FAAD2_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.faad2+=	faad2>=2.6.1
BUILDLINK_ABI_DEPENDS.faad2?=	faad2>=2.6.1
BUILDLINK_PKGSRCDIR.faad2?=	../../audio/faad2
BUILDLINK_INCDIRS.faad2?=	include/faad2
.endif	# FAAD2_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
