$NetBSD: patch-msvc_mono.props,v 1.2 2026/02/03 15:17:53 ryoon Exp $

--- msvc/mono.props.orig	2025-01-13 19:10:41.000000000 +0000
+++ msvc/mono.props
@@ -26,7 +26,7 @@
     <!-- When true, ported mono projects will build using C++ instead of C compiler. When false, all project will be build using the default compiler.  -->
     <MONO_COMPILE_AS_CPP>false</MONO_COMPILE_AS_CPP>
     <!-- When true, mono binaries will link and include BTLS. When false, mono binaries will not link and include BTLS.  -->
-    <MONO_ENABLE_BTLS>false</MONO_ENABLE_BTLS>
+    <MONO_ENABLE_BTLS>true</MONO_ENABLE_BTLS>
   </PropertyGroup>
   <PropertyGroup Label="MonoDirectories">
     <MonoSourceLocation Condition="'$(MonoSourceLocation)' == '' ">..</MonoSourceLocation>
