# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/11/03 19:54:04 joerg Exp $

BUILDLINK_DEPMETHOD.fontcacheproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FONTCACHEPROTO_BUILDLINK3_MK:=	${FONTCACHEPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	fontcacheproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfontcacheproto}
BUILDLINK_PACKAGES+=	fontcacheproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}fontcacheproto

.if ${FONTCACHEPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.fontcacheproto+=	fontcacheproto>=0.1
BUILDLINK_PKGSRCDIR.fontcacheproto?=	../../x11/fontcacheproto
.endif	# FONTCACHEPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
