# $NetBSD: buildlink3.mk,v 1.10 2009/03/20 19:25:54 joerg Exp $

BUILDLINK_TREE+=	xosd

.if !defined(XOSD_BUILDLINK3_MK)
XOSD_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.xosd+=	xosd>=2.2.12
BUILDLINK_ABI_DEPENDS.xosd+=	xosd>=2.2.12nb2
BUILDLINK_PKGSRCDIR.xosd?=	../../x11/xosd
.endif # XOSD_BUILDLINK3_MK

BUILDLINK_TREE+=	-xosd
