# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:56 wiz Exp $

DISTNAME=	trajan
PKGNAME=	tex-${DISTNAME}-1.1
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/trajan
COMMENT=	Fonts from the Trajan column in Rome
LICENSE=	lppl-1.3c

TEX_MIXEDMAP_FILES+=	trajan.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
