# $NetBSD: buildlink3.mk,v 1.5 2004/02/10 20:45:01 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBOGG_BUILDLINK3_MK:=	${LIBOGG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libogg
.endif

.if !empty(LIBOGG_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		libogg
BUILDLINK_DEPENDS.libogg+=	libogg>=1.1
BUILDLINK_PKGSRCDIR.libogg?=	../../audio/libogg
.endif	# LIBOGG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
