# $NetBSD: Makefile,v 1.10 2022/04/14 03:33:37 markd Exp $

DISTNAME=	titlesec.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.14
TEXLIVE_REV=	59845

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/titlesec
COMMENT=	Documentation for tex-titlesec
LICENSE=	mit

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
