# This plugin needs the data in rrdtool format, so that plugin
# must be enabled in the collectd configuration.
#
# Also, the path below needs to be the same path that is configured
# in the collectd config as data directory for the rrdtool plugin,
# e.g.:
#
# <Plugin rrdtool>
#        DataDir "/var/db/collectd/rrd"
# </Plugin>
#
datadir: "/var/db/collectd/rrd/"
