# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/03/02 12:26:08 obache Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MELL_BUILDLINK3_MK:=	${MELL_BUILDLINK3_MK}+

.include "../../mk/emacs.mk"

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mell
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmell}
BUILDLINK_PACKAGES+=	mell
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mell

.if ${MELL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mell+=	${EMACS_PKGNAME_PREFIX}mell>=1.0.0
BUILDLINK_PKGSRCDIR.mell?=	../../devel/mell
.endif	# MELL_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.mell= ${EGREP} '.*\.el$$|.*\.elc$$'

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
