# $NetBSD: buildlink3.mk,v 1.1 2004/03/28 00:42:10 wiz Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
PY_WXWINDOWS_BUILDLINK3_MK:=	${PY_WXWINDOWS_BUILDLINK3_MK}+

.include "../../lang/python/pyversion.mk"

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	${PYPKGPREFIX}-wxWindows
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:N${PYPKGPREFIX}-wxWindows}
BUILDLINK_PACKAGES+=	${PYPKGPREFIX}-wxWindows

.if !empty(PY_WXWINDOWS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.${PYPKGPREFIX}-wxWindows+=	${PYPKGPREFIX}-wxWindows>=2.4.2.4nb4
BUILDLINK_PKGSRCDIR.${PYPKGPREFIX}-wxWindows?=	../../x11/py-wxWindows

.include "../../x11/wxGTK/buildlink3.mk"

.endif	# PY_WXWINDOWS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
