# $NetBSD: Makefile,v 1.4 2020/03/08 16:48:44 wiz Exp $

GST_PLUGINS1_NAME=	twolame
GST_PLUGINS1_DIRS=	ext/twolame

PKGREVISION= 1
.include "../../multimedia/gst-plugins1-good/Makefile.common"

.include "../../audio/twolame/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
