# $NetBSD: Makefile,v 1.3 2006/03/04 21:28:56 jlam Exp $
#

DISTNAME=		libmusepack-1.0.3
CATEGORIES=		audio
MASTER_SITES=		http://www.saunalahti.fi/grimmel/musepack.net/source/
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://www.musepack.net/
COMMENT=		Portable Musepack decoder library

USE_LANGUAGES=		c++
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
