# $NetBSD: Makefile,v 1.32 2024/10/20 14:03:37 wiz Exp $

PKGREVISION= 8
.include "../../meta-pkgs/mate/Makefile.common"

DISTNAME=	mate-common-${VERSION:R}.0
CATEGORIES=	devel

COMMENT=	Sample files for MATE Application development

.include "../../mk/bsd.pkg.mk"
