# $NetBSD: buildlink3.mk,v 1.3 2006/05/21 11:44:39 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GPLCVER_BUILDLINK3_MK:=	${GPLCVER_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gplcver
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngplcver}
BUILDLINK_PACKAGES+=	gplcver

.if !empty(GPLCVER_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.gplcver+=	gplcver>=2.11a
BUILDLINK_PKGSRCDIR.gplcver?=	../../cad/gplcver
.endif	# GPLCVER_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
