# $NetBSD: Makefile,v 1.45 2004/06/10 12:48:37 markd Exp $

DISTNAME=	kdevelop-3.0.4
CATEGORIES=	devel kde
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	markd@NetBSD.org
HOMEPAGE=       http://www.kdevelop.org/
COMMENT=	Integrated Development Environment for Unix/X11/KDE

DEPENDS+=	c-cpp-reference>=2.0.2nb2:../../devel/c-cpp-reference
DEPENDS+=	kdbg>=1.2.5:../../devel/kdbg

NO_CHECKSUM=	YES
NO_BUILD=	YES

do-install:	# empty

.include "../../mk/bsd.pkg.mk"
