# $NetBSD: Makefile,v 1.2 2020/03/08 15:12:55 taca Exp $

DISTNAME=	regexp_parser-1.7.0
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ammar/regexp_parser
COMMENT=	Scanner, lexer, parser for ruby's regular expressions
LICENSE=	mit

USE_LANGUAGES=	# empty

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
