$NetBSD: patch-third__party_abseil-cpp_absl_debugging_internal_vdso__support.cc,v 1.1 2025/10/19 11:56:56 leot Exp $

* Do not find system_wrappers/syscall.h generated by Firefox.

--- third_party/abseil-cpp/absl/debugging/internal/vdso_support.cc.orig	2025-03-01 04:07:45.625009806 +0000
+++ third_party/abseil-cpp/absl/debugging/internal/vdso_support.cc
@@ -26,9 +26,9 @@
 
 #include <errno.h>
 #include <fcntl.h>
-#if __has_include(<syscall.h>)
+#if defined(__linux__)
 #include <syscall.h>
-#elif __has_include(<sys/syscall.h>)
+#elif defined(__NetBSD__) || defined(__FreeBSD__) || defined(__OpenBSD__)
 #include <sys/syscall.h>
 #endif
 #include <unistd.h>
