# $NetBSD: Makefile,v 1.31 2004/04/29 09:28:21 wiz Exp $
#

PKGNAME=	links-2.1.0.15
COMMENT=	Lynx-like text WWW browser

CONFLICTS+=	links-gui-[0-9]* elinks-0.3*

.include "../../www/links/Makefile.common"
.include "../../mk/bsd.pkg.mk"
