#!/bin/sh
#
# $NetBSD: realplay.sh,v 1.1.1.1 2000/12/25 09:35:58 jlam Exp $
#
REALPLAYER_HOME=@REALPLAYER_HOME@ ; export REALPLAYER_HOME
LD_LIBRARY_PATH=${REALPLAYER_HOME}:${LD_LIBRARY_PATH} ; export LD_LIBRARY_PATH
exec ${REALPLAYER_HOME}/realplay "$@"
