# $NetBSD: buildlink3.mk,v 1.2 2008/10/11 09:31:56 uebayasi Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EMACS_NOX11_BUILDLINK3_MK:=	${EMACS_NOX11_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	emacs-nox11
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nemacs-nox11}
BUILDLINK_PACKAGES+=	emacs-nox11
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}emacs-nox11

.if ${EMACS_NOX11_BUILDLINK3_MK} == "+"
.include "../../editors/emacs/modules.mk"
BUILDLINK_API_DEPENDS.emacs-nox11+=	${_EMACS_REQD}
BUILDLINK_PKGSRCDIR.emacs-nox11?=	${_EMACS_PKGDIR}
.endif	# EMACS_NOX11_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.emacs-nox11=	${EGREP} '.*\.el$$|.*\.elc$$'

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
