# $NetBSD: Makefile,v 1.16 2000/06/28 01:43:34 wiz Exp $
#

    SUBDIR+= gensolpkg
#    SUBDIR+= pax			# only needed on 1.3 systems
#    SUBDIR+= pkg_install		# only install on demand of bsd.pkg.mk
    SUBDIR+= pkg_tarup
    SUBDIR+= pkgdep
    SUBDIR+= pkgdiff
    SUBDIR+= pkglibtool
    SUBDIR+= pkglint
    SUBDIR+= pkgmanpages
    SUBDIR+= port2pkg
    SUBDIR+= url2pkg
#    SUBDIR+= xpkgwedge		# broken

.include "../mk/bsd.pkg.subdir.mk"
