# $NetBSD: buildlink3.mk,v 1.1 2004/02/21 22:54:04 cube Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBUSB_BUILDLINK3_MK:=	${LIBUSB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libusb
.endif

.if !empty(LIBUSB_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=			libusb
BUILDLINK_DEPENDS.libusb+=		libusb>=0.1.7
BUILDLINK_PKGSRCDIR.libusb?=		../../devel/libusb
.endif # LIBUSB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
