# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/12/19 21:48:05 markd Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBICAL_BUILDLINK3_MK:=	${LIBICAL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libical
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibical}
BUILDLINK_PACKAGES+=	libical
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libical

.if ${LIBICAL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libical+=	libical>=0.42
BUILDLINK_PKGSRCDIR.libical?=	../../time/libical
.endif	# LIBICAL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
