# $NetBSD: Makefile,v 1.4 2022/09/01 03:55:26 markd Exp $

DISTNAME=	firstaid
PKGNAME=	tex-${DISTNAME}-1.0r
TEXLIVE_REV=	63514

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/latex-firstaid
COMMENT=	First aid for external LaTeX files and packages that need updating
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
