$NetBSD: patch-rebar.config.script,v 1.2 2019/09/06 09:10:48 jperkin Exp $

Support newer OTP.

--- rebar.config.script.orig	2019-03-05 22:42:20.000000000 +0000
+++ rebar.config.script
@@ -128,7 +128,7 @@ ErlOpts = case os:getenv("ERL_OPTS") of
 end,
 
 AddConfig = [
-    {require_otp_vsn, "17|18|19|20|21"},
+    {require_otp_vsn, "17|18|19|20|21|22"},
     {deps_dir, "src"},
     {deps, lists:map(MakeDep, DepDescs)},
     {sub_dirs, SubDirs},
