# $NetBSD: Makefile,v 1.2 2007/05/31 21:36:52 ghen Exp $

MOZILLA=		thunderbird
COMMENT=		Mozilla mail client

MOZILLA_USE_GTK2=	# yes
MOZILLA_USE_XFT=	YES

.include "../../mail/thunderbird15/Makefile-thunderbird.common"
.include "../../mk/bsd.pkg.mk"
