.\"	$NetBSD: port2pkg.1,v 1.7 2006/09/16 06:37:40 wiz Exp $
.\"
.\" Copyright (c) 1999 by Kazuki Sakamoto (sakamoto@NetBSD.org)
.\" Absolutely no warranty.
.\"
.Dd September 16, 2006
.Dt PORT2PKG 1
.Sh NAME
.Nm port2pkg
.Nd convert a FreeBSD port to a NetBSD package
.Sh SYNOPSIS
.Nm
.Op Fl m Ar maintainer
.Ar portsdir
.Ar pkgsrcdir
.Sh DESCRIPTION
.Nm
tries to convert a
.Fx
port to a
.Nx
package.
.Nm
copies files
from
.Ar portsdir
to
.Ar pkgsrcdir
(if
.Ar pkgsrcdir
doesn't exists, it is created first),
and tries adapting the Makefile, patches and some other files
to
.Nx
pkgsrc.
.Ss Options
.Bl -tag -width Fl
.It Fl m
Adjust maintainer of this package
(default: pkgsrc-users@NetBSD.org).
.El
.Sh EXAMPLES
.Dl port2pkg /mnt/ports/\*[Lt]category\*[Gt]/foo /usr/pkgsrc/\*[Lt]category\*[Gt]/foo
or
.Dl port2pkg -m your@email /mnt/ports/\*[Lt]category\*[Gt]/foo /usr/pkgsrc/\*[Lt]category\*[Gt]/foo
.Sh SEE ALSO
.Xr pkglint 1
Read
.Ar Package Constructor's Guide
in
.Pa pkgsrc/doc/pkgsrc.txt .
.Sh AUTHORS
.An Kazuki Sakamoto Aq sakamoto@NetBSD.org
.Sh BUGS
.Nm
is not a magic wand, please double-check converted pkgsrc.
