# $NetBSD: Makefile,v 1.2 2023/12/17 16:02:18 taca Exp $

DISTNAME=	unicode-scripts-1.9.0
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/janlelis/unicode-scripts
COMMENT=	Which script(s) does a Unicode string belong to?
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
