.\"	$NetBSD: lintpkgsrc.1,v 1.4 1999/08/01 18:34:41 abs Exp $
.\"
.\" Copyright (c) 1999 by David Brownlee (abs@netbsd.org)
.\" Absolutely no warranty.
.\"
.Dd April 19, 1999
.Dt LINTPKGSRC 1
.Sh NAME
.Nm lintpkgsrc
.Nd a verifier for the pkgsrc tree
.Sh SYNOPSIS
.Nm
.Op Fl dhilmor
.Op Fl P Ar pkgsrcdir
.Sh DESCRIPTION
.Nm
tries to verify the entire contents of the pkgsrc tree.
.Nm
uses simple regular-expression matching for verifying
files that make up a pkgsrc directory.
Note that it does NOT implement complete Makefile parser.
.Pp
.Sy Options
.Bl -tag -width Fl
.It Fl P Ar pkgsrcdir
Set pkgsrcdir - otherwise
.Pa /etc/mk.conf is parsed for
.Em PKGSRCDIR .
.It Fl h
Basic help and usage.
.It Fl d
Extract the 'DEPENDS' listing from each pkgsrc package Makefile, then
verify the version specified in each DEPEND correctly matches a current
pkgsrc package.
.It Fl i
Check the version of each installed package against the current version in
pkgsrc.
.It Fl l
Run pkglint on every package in pkgsrc.
.It Fl m
For each current distfile, verify its checksum against the appropriate
package's md5 file. Also report if any package's md5 file references
the same distfile with a different md5 checksum.
.It Fl o
Report any old distfile (not referenced by any package's md5 file).
.It Fl p
Report any old binary packages (in any subdirs of PKGSRCDIR/packages)
.It Fl r
Remove distfiles which are not referenced from any package's md5 file,
or have an incorrect checksum (usually due to an interrupted download),
and any old binary packages. To remove any given type, additionally
specify the -o, -m, or -p flags respectively.
.El
.Sh AUTHOR
David Brownlee <abs@netbsd.org>
.Sh BUGS
Potentially, but non serious to date.
