package main

// This file defines the specific type of some variables.
//
// There are two types of lists:
// * LK_SHELL is a list whose elements are split by shell rules
// * LK_SPACE is a list whose elements are split by whitespace
//
// See vartypecheck.go for how these types are checked.
//
// Last synced with mk/defaults/mk.conf revision 1.118

func (gd *GlobalData) InitVartypes() {
	usr("ALLOW_VULNERABLE_PACKAGES", LK_NONE, CheckvarYes)
	usr("MANINSTALL", LK_SHELL, enum("maninstall catinstall"))
	usr("MANZ", LK_NONE, CheckvarYes)
	usr("GZIP", LK_SHELL, CheckvarShellWord)
	usr("MKCRYPTO", LK_NONE, CheckvarYesNo)
	usr("OBJHOSTNAME", LK_NONE, CheckvarYes)
	usr("OBJMACHINE", LK_NONE, CheckvarYes)
	usr("PKG_SUFX", LK_NONE, CheckvarFilename)
	usr("PKGSRC_LOCKTYPE", LK_NONE, enum("none sleep once"))
	usr("PKGSRC_SLEEPSECS", LK_NONE, CheckvarInteger)
	usr("USETBL", LK_NONE, CheckvarYes)
	usr("ABI", LK_NONE, enum("32 64"))
	usr("PKG_DEVELOPER", LK_NONE, CheckvarYes)
	usr("USE_ABI_DEPENDS", LK_NONE, CheckvarYesNo)
	usr("PKG_REGISTER_SHELLS", LK_NONE, enum("YES NO"))
	usr("PKGSRC_COMPILER", LK_SHELL, enum("ccache ccc clang distcc f2c gcc hp icc ido gcc mipspro mipspro-ucode pcc sunpro xlc"))
	usr("PKGSRC_MESSAGE_RECIPIENTS", LK_SHELL, CheckvarMailAddress)
	usr("PKGSRC_SHOW_BUILD_DEFS", LK_NONE, CheckvarYesNo)
	usr("PKGSRC_SHOW_PATCH_ERRORMSG", LK_NONE, CheckvarYesNo)
	usr("PKGSRC_RUN_TEST", LK_NONE, CheckvarYesNo)
	usr("PREFER_PKGSRC", LK_SHELL, CheckvarIdentifier)
	usr("PREFER_NATIVE", LK_SHELL, CheckvarIdentifier)
	usr("PREFER_NATIVE_PTHREADS", LK_NONE, CheckvarYesNo)
	usr("LOCALBASE", LK_NONE, CheckvarPathname)
	usr("CROSSBASE", LK_NONE, CheckvarPathname)
	usr("VARBASE", LK_NONE, CheckvarPathname)
	usr("X11_TYPE", LK_NONE, enum("modular native"))
	usr("X11BASE", LK_NONE, CheckvarPathname)
	usr("MOTIFBASE", LK_NONE, CheckvarPathname)
	usr("PKGINFODIR", LK_NONE, CheckvarPathname)
	usr("PKGMANDIR", LK_NONE, CheckvarPathname)
	usr("USE_XPKGWEDGE", LK_NONE, CheckvarYesNo)
	usr("BSDSRCDIR", LK_NONE, CheckvarPathname)
	usr("BSDXSRCDIR", LK_NONE, CheckvarPathname)
	usr("DISTDIR", LK_NONE, CheckvarPathname)
	usr("DIST_PATH", LK_NONE, CheckvarPathlist)
	usr("DEFAULT_VIEW", LK_NONE, CheckvarUnchecked)
	usr("FETCH_CMD", LK_NONE, CheckvarShellCommand)
	usr("FETCH_USING", LK_NONE, enum("curl custom fetch ftp manual wget"))
	usr("FETCH_RESUME_ARGS", LK_SHELL, CheckvarShellWord)
	usr("FETCH_OUTPUT_ARGS", LK_SHELL, CheckvarShellWord)
	usr("LIBTOOLIZE_PLIST", LK_NONE, CheckvarYesNo)
	usr("PKG_RESUME_TRANSFERS", LK_NONE, CheckvarYesNo)
	usr("PKG_SYSCONFBASE", LK_NONE, CheckvarPathname)
	usr("RCD_SCRIPTS_DIR", LK_NONE, CheckvarPathname)
	usr("PACKAGES", LK_NONE, CheckvarPathname)
	usr("PKGVULNDIR", LK_NONE, CheckvarPathname)
	usr("PASSIVE_FETCH", LK_NONE, CheckvarYes)
	usr("PATCH_FUZZ_FACTOR", LK_NONE, enum("-F0 -F1 -F2 -F3"))
	usr("ACCEPTABLE_LICENSES", LK_SHELL, CheckvarIdentifier)
	usr("SPECIFIC_PKGS", LK_NONE, CheckvarYes)
	usr("SITE_SPECIFIC_PKGS", LK_SHELL, CheckvarPkgPath)
	usr("HOST_SPECIFIC_PKGS", LK_SHELL, CheckvarPkgPath)
	usr("GROUP_SPECIFIC_PKGS", LK_SHELL, CheckvarPkgPath)
	usr("USER_SPECIFIC_PKGS", LK_SHELL, CheckvarPkgPath)
	usr("FAILOVER_FETCH", LK_NONE, CheckvarYes)
	usr("MASTER_SORT", LK_SHELL, CheckvarUnchecked)
	usr("MASTER_SORT_REGEX", LK_SHELL, CheckvarUnchecked)
	usr("PATCH_DEBUG", LK_NONE, CheckvarYes)
	usr("PKG_FC", LK_NONE, CheckvarShellCommand)
	usr("IMAKE", LK_NONE, CheckvarShellCommand)
	usr("IMAKEOPTS", LK_SHELL, CheckvarShellWord)
	usr("PRE_ROOT_CMD", LK_NONE, CheckvarShellCommand)
	pkg("USE_GAMESGROUP", LK_NONE, CheckvarYesNo)
	usr("SU_CMD", LK_NONE, CheckvarShellCommand)
	usr("SU_CMD_PATH_APPEND", LK_NONE, CheckvarPathlist)
	usr("FATAL_OBJECT_FMT_SKEW", LK_NONE, CheckvarYesNo)
	usr("WARN_NO_OBJECT_FMT", LK_NONE, CheckvarYesNo)
	usr("SMART_MESSAGES", LK_NONE, CheckvarYes)
	usr("BINPKG_SITES", LK_SHELL, CheckvarURL)
	usr("BIN_INSTALL_FLAG", LK_SHELL, CheckvarShellWord)
	usr("LOCALPATCHES", LK_NONE, CheckvarPathname)

	// some other variables, sorted alphabetically

	sys(".CURDIR", LK_NONE, CheckvarPathname)
	sys(".TARGET", LK_NONE, CheckvarPathname)
	acl("ALL_ENV", LK_SHELL, CheckvarShellWord)
	acl("ALTERNATIVES_FILE", LK_NONE, CheckvarFilename)
	acl("ALTERNATIVES_SRC", LK_SHELL, CheckvarPathname)
	pkg("APACHE_MODULE", LK_NONE, CheckvarYes)
	sys("AR", LK_NONE, CheckvarShellCommand)
	sys("AS", LK_NONE, CheckvarShellCommand)
	pkglist("AUTOCONF_REQD", LK_SHELL, CheckvarVersion)
	acl("AUTOMAKE_OVERRIDE", LK_SHELL, CheckvarPathmask)
	pkglist("AUTOMAKE_REQD", LK_SHELL, CheckvarVersion)
	pkg("AUTO_MKDIRS", LK_NONE, CheckvarYesNo)
	usr("BATCH", LK_NONE, CheckvarYes)
	acl("BDB185_DEFAULT", LK_NONE, CheckvarUnchecked)
	sys("BDBBASE", LK_NONE, CheckvarPathname)
	pkg("BDB_ACCEPTED", LK_SHELL, enum("db1 db2 db3 db4 db5"))
	acl("BDB_DEFAULT", LK_NONE, enum("db1 db2 db3 db4 db5"))
	sys("BDB_LIBS", LK_SHELL, CheckvarLdFlag)
	sys("BDB_TYPE", LK_NONE, enum("db1 db2 db3 db4 db5"))
	sys("BINGRP", LK_NONE, CheckvarUserGroupName)
	sys("BINMODE", LK_NONE, CheckvarFileMode)
	sys("BINOWN", LK_NONE, CheckvarUserGroupName)
	acl("BOOTSTRAP_DEPENDS", LK_SPACE, CheckvarDependencyWithPath, "Makefile.common:a", "Makefile:a", "options.mk:a", "*.mk:a")
	pkg("BOOTSTRAP_PKG", LK_NONE, CheckvarYesNo)
	acl("BROKEN", LK_NONE, CheckvarMessage)
	pkg("BROKEN_GETTEXT_DETECTION", LK_NONE, CheckvarYesNo)
	pkglist("BROKEN_EXCEPT_ON_PLATFORM", LK_SHELL, CheckvarPlatformTriple)
	pkglist("BROKEN_ON_PLATFORM", LK_SPACE, CheckvarPlatformTriple)
	sys("BSD_MAKE_ENV", LK_SHELL, CheckvarShellWord)
	acl("BUILDLINK_ABI_DEPENDS.*", LK_SPACE, CheckvarDependency, "*:a")
	acl("BUILDLINK_API_DEPENDS.*", LK_SPACE, CheckvarDependency, "*:a")
	acl("BUILDLINK_CONTENTS_FILTER", LK_SHELL, CheckvarShellWord) // Should better be ShellCommand
	sys("BUILDLINK_CFLAGS", LK_SHELL, CheckvarCFlag)
	bl3list("BUILDLINK_CFLAGS.*", LK_SHELL, CheckvarCFlag)
	sys("BUILDLINK_CPPFLAGS", LK_SHELL, CheckvarCFlag)
	bl3list("BUILDLINK_CPPFLAGS.*", LK_SHELL, CheckvarCFlag)
	acl("BUILDLINK_CONTENTS_FILTER.*", LK_NONE, CheckvarShellCommand, "buildlink3.mk:s")
	acl("BUILDLINK_DEPENDS", LK_SPACE, CheckvarIdentifier, "buildlink3.mk:a")
	acl("BUILDLINK_DEPMETHOD.*", LK_SHELL, CheckvarBuildlinkDepmethod, "buildlink3.mk:ad", "Makefile:as", "Makefile.common:a", "*.mk:a") // FIXME: buildlink3.mk:d may lead to unexpected behavior.
	sys("BUILDLINK_DIR", LK_NONE, CheckvarPathname)
	bl3list("BUILDLINK_FILES.*", LK_SHELL, CheckvarPathmask)
	acl("BUILDLINK_FILES_CMD.*", LK_SHELL, CheckvarShellWord)                  // Should better be ShellCommand
	acl("BUILDLINK_INCDIRS.*", LK_SHELL, CheckvarPathname, "buildlink3.mk:ad") // Should [d]efault really be allowed in buildlink3.mk?
	acl("BUILDLINK_JAVA_PREFIX.*", LK_NONE, CheckvarPathname, "buildlink3.mk:s")
	acl("BUILDLINK_LDADD.*", LK_SHELL, CheckvarLdFlag, "builtin.mk:adsu", "buildlink3.mk:", "Makefile:u", "Makefile.common:u", "*.mk:u")
	sys("BUILDLINK_LDFLAGS", LK_SHELL, CheckvarLdFlag)
	bl3list("BUILDLINK_LDFLAGS.*", LK_SHELL, CheckvarLdFlag)
	bl3list("BUILDLINK_LIBDIRS.*", LK_SHELL, CheckvarPathname)
	acl("BUILDLINK_LIBS.*", LK_SHELL, CheckvarLdFlag, "buildlink3.mk:a")
	acl("BUILDLINK_PASSTHRU_DIRS", LK_SHELL, CheckvarPathname, "Makefile:a", "Makefile.common:a", "buildlink3.mk:a", "hacks.mk:a")
	acl("BUILDLINK_PASSTHRU_RPATHDIRS", LK_SHELL, CheckvarPathname, "Makefile:a", "Makefile.common:a", "buildlink3.mk:a", "hacks.mk:a")
	acl("BUILDLINK_PKGSRCDIR.*", LK_NONE, CheckvarRelativePkgDir, "buildlink3.mk:dp")
	acl("BUILDLINK_PREFIX.*", LK_NONE, CheckvarPathname, "builtin.mk:su", "buildlink3.mk:", "Makefile:u", "Makefile.common:u", "*.mk:u")
	acl("BUILDLINK_RPATHDIRS.*", LK_SHELL, CheckvarPathname, "buildlink3.mk:a")
	acl("BUILDLINK_TARGETS", LK_SHELL, CheckvarIdentifier)
	acl("BUILDLINK_FNAME_TRANSFORM.*", LK_NONE, CheckvarSedCommands, "Makefile:a", "builtin.mk:a", "hacks.mk:a", "buildlink3.mk:a")
	acl("BUILDLINK_TRANSFORM", LK_SHELL, CheckvarWrapperTransform, "*:a")
	acl("BUILDLINK_TREE", LK_SHELL, CheckvarIdentifier, "buildlink3.mk:a")
	acl("BUILD_DEFS", LK_SHELL, CheckvarVarname, "Makefile:a", "Makefile.common:a", "options.mk:a")
	acl("BUILD_DEPENDS", LK_SPACE, CheckvarDependencyWithPath, "Makefile.common:a", "Makefile:a", "options.mk:a", "*.mk:a")
	pkglist("BUILD_DIRS", LK_SHELL, CheckvarWrksrcSubdirectory)
	pkglist("BUILD_ENV", LK_SHELL, CheckvarShellWord)
	sys("BUILD_MAKE_CMD", LK_NONE, CheckvarShellCommand)
	pkglist("BUILD_MAKE_FLAGS", LK_SHELL, CheckvarShellWord)
	pkg("BUILD_TARGET", LK_SHELL, CheckvarIdentifier)
	pkg("BUILD_USES_MSGFMT", LK_NONE, CheckvarYes)
	acl("BUILTIN_PKG", LK_NONE, CheckvarIdentifier, "builtin.mk:psu")
	acl("BUILTIN_PKG.*", LK_NONE, CheckvarPkgName, "builtin.mk:psu")
	acl("BUILTIN_FIND_FILES_VAR", LK_SHELL, CheckvarVarname, "builtin.mk:s")
	acl("BUILTIN_FIND_FILES.*", LK_SHELL, CheckvarPathname, "builtin.mk:s")
	acl("BUILTIN_FIND_GREP.*", LK_NONE, CheckvarString, "builtin.mk:s")
	acl("BUILTIN_FIND_LIBS", LK_SHELL, CheckvarPathname, "builtin.mk:s")
	acl("BUILTIN_IMAKE_CHECK", LK_SHELL, CheckvarUnchecked, "builtin.mk:s")
	acl("BUILTIN_IMAKE_CHECK.*", LK_NONE, CheckvarYesNo)
	sys("BUILTIN_X11_TYPE", LK_NONE, CheckvarUnchecked)
	sys("BUILTIN_X11_VERSION", LK_NONE, CheckvarUnchecked)
	acl("CATEGORIES", LK_SHELL, CheckvarCategory, "Makefile:as", "Makefile.common:ads")
	sys("CC_VERSION", LK_NONE, CheckvarMessage)
	sys("CC", LK_NONE, CheckvarShellCommand)
	pkglist("CFLAGS*", LK_SHELL, CheckvarCFlag) // may also be changed by the user
	acl("CHECK_BUILTIN", LK_NONE, CheckvarYesNo, "builtin.mk:d", "Makefile:s")
	acl("CHECK_BUILTIN.*", LK_NONE, CheckvarYesNo, "*:p")
	acl("CHECK_FILES_SKIP", LK_SHELL, CheckvarBasicRegularExpression, "Makefile:a", "Makefile.common:a")
	pkg("CHECK_FILES_SUPPORTED", LK_NONE, CheckvarYesNo)
	usr("CHECK_HEADERS", LK_NONE, CheckvarYesNo)
	pkglist("CHECK_HEADERS_SKIP", LK_SHELL, CheckvarPathmask)
	usr("CHECK_INTERPRETER", LK_NONE, CheckvarYesNo)
	pkglist("CHECK_INTERPRETER_SKIP", LK_SHELL, CheckvarPathmask)
	usr("CHECK_PERMS", LK_NONE, CheckvarYesNo)
	pkglist("CHECK_PERMS_SKIP", LK_SHELL, CheckvarPathmask)
	usr("CHECK_PORTABILITY", LK_NONE, CheckvarYesNo)
	pkglist("CHECK_PORTABILITY_SKIP", LK_SHELL, CheckvarPathmask)
	acl("CHECK_SHLIBS", LK_NONE, CheckvarYesNo, "Makefile:s")
	pkglist("CHECK_SHLIBS_SKIP", LK_SHELL, CheckvarPathmask)
	acl("CHECK_SHLIBS_SUPPORTED", LK_NONE, CheckvarYesNo, "Makefile:s")
	pkglist("CHECK_WRKREF_SKIP", LK_SHELL, CheckvarPathmask)
	pkg("CMAKE_ARG_PATH", LK_NONE, CheckvarPathname)
	pkglist("CMAKE_ARGS", LK_SHELL, CheckvarShellWord)
	acl("COMMENT", LK_NONE, CheckvarComment, "Makefile:as", "Makefile.common:as")
	sys("COMPILER_RPATH_FLAG", LK_NONE, enum("-Wl,-rpath"))
	pkglist("CONFIGURE_ARGS", LK_SHELL, CheckvarShellWord)
	pkglist("CONFIGURE_DIRS", LK_SHELL, CheckvarWrksrcSubdirectory)
	pkglist("CONFIGURE_ENV", LK_SHELL, CheckvarShellWord)
	pkg("CONFIGURE_HAS_INFODIR", LK_NONE, CheckvarYesNo)
	pkg("CONFIGURE_HAS_LIBDIR", LK_NONE, CheckvarYesNo)
	pkg("CONFIGURE_HAS_MANDIR", LK_NONE, CheckvarYesNo)
	pkg("CONFIGURE_SCRIPT", LK_NONE, CheckvarPathname)
	acl("CONFIG_GUESS_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:as")
	acl("CONFIG_STATUS_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:as")
	acl("CONFIG_SHELL", LK_NONE, CheckvarPathname, "Makefile:s", "Makefile.common:s")
	acl("CONFIG_SUB_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:as")
	pkglist("CONFLICTS", LK_SPACE, CheckvarDependency)
	pkglist("CONF_FILES", LK_SHELL, CheckvarShellWord)
	pkg("CONF_FILES_MODE", LK_NONE, enum("0644 0640 0600 0400"))
	pkglist("CONF_FILES_PERMS", LK_SHELL, CheckvarShellWord)
	sys("COPY", LK_NONE, enum("-c")) // The flag that tells ${INSTALL} to copy a file
	sys("CPP", LK_NONE, CheckvarShellCommand)
	pkglist("CPPFLAGS*", LK_SHELL, CheckvarCFlag)
	acl("CRYPTO", LK_NONE, CheckvarYes, "Makefile:s")
	sys("CXX", LK_NONE, CheckvarShellCommand)
	pkglist("CXXFLAGS*", LK_SHELL, CheckvarCFlag)
	acl("DEINSTALL_FILE", LK_NONE, CheckvarPathname, "Makefile:s")
	acl("DEINSTALL_SRC", LK_SHELL, CheckvarPathname, "Makefile:s", "Makefile.common:ds")
	acl("DEINSTALL_TEMPLATES", LK_SHELL, CheckvarPathname, "Makefile:as", "Makefile.common:ads")
	sys("DELAYED_ERROR_MSG", LK_NONE, CheckvarShellCommand)
	sys("DELAYED_WARNING_MSG", LK_NONE, CheckvarShellCommand)
	pkglist("DEPENDS", LK_SPACE, CheckvarDependencyWithPath)
	usr("DEPENDS_TARGET", LK_SHELL, CheckvarIdentifier)
	acl("DESCR_SRC", LK_SHELL, CheckvarPathname, "Makefile:s", "Makefile.common:ds")
	sys("DESTDIR", LK_NONE, CheckvarPathname)
	acl("DESTDIR_VARNAME", LK_NONE, CheckvarVarname, "Makefile:s", "Makefile.common:s")
	sys("DEVOSSAUDIO", LK_NONE, CheckvarPathname)
	sys("DEVOSSSOUND", LK_NONE, CheckvarPathname)
	pkglist("DISTFILES", LK_SHELL, CheckvarFilename)
	pkg("DISTINFO_FILE", LK_NONE, CheckvarRelativePkgPath)
	pkg("DISTNAME", LK_NONE, CheckvarFilename)
	pkg("DIST_SUBDIR", LK_NONE, CheckvarPathname)
	acl("DJB_BUILD_ARGS", LK_SHELL, CheckvarShellWord)
	acl("DJB_BUILD_TARGETS", LK_SHELL, CheckvarIdentifier)
	acl("DJB_CONFIG_CMDS", LK_SHELL, CheckvarShellWord, "options.mk:s") // ShellCommand, terminated by a semicolon
	acl("DJB_CONFIG_DIRS", LK_SHELL, CheckvarWrksrcSubdirectory)
	acl("DJB_CONFIG_HOME", LK_NONE, CheckvarFilename)
	acl("DJB_CONFIG_PREFIX", LK_NONE, CheckvarPathname)
	acl("DJB_INSTALL_TARGETS", LK_SHELL, CheckvarIdentifier)
	acl("DJB_MAKE_TARGETS", LK_NONE, CheckvarYesNo)
	acl("DJB_RESTRICTED", LK_NONE, CheckvarYesNo, "Makefile:s")
	acl("DJB_SLASHPACKAGE", LK_NONE, CheckvarYesNo)
	acl("DLOPEN_REQUIRE_PTHREADS", LK_NONE, CheckvarYesNo)
	acl("DL_AUTO_VARS", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:s", "options.mk:s")
	acl("DL_LIBS", LK_SHELL, CheckvarLdFlag)
	sys("DOCOWN", LK_NONE, CheckvarUserGroupName)
	sys("DOCGRP", LK_NONE, CheckvarUserGroupName)
	sys("DOCMODE", LK_NONE, CheckvarFileMode)
	sys("DOWNLOADED_DISTFILE", LK_NONE, CheckvarPathname)
	sys("DO_NADA", LK_NONE, CheckvarShellCommand)
	pkg("DYNAMIC_SITES_CMD", LK_NONE, CheckvarShellCommand)
	pkg("DYNAMIC_SITES_SCRIPT", LK_NONE, CheckvarPathname)
	sys("ECHO", LK_NONE, CheckvarShellCommand)
	sys("ECHO_MSG", LK_NONE, CheckvarShellCommand)
	sys("ECHO_N", LK_NONE, CheckvarShellCommand)
	pkg("EGDIR", LK_NONE, CheckvarPathname) // Not defined anywhere, but used in many places like this.
	sys("EMACS_BIN", LK_NONE, CheckvarPathname)
	sys("EMACS_ETCPREFIX", LK_NONE, CheckvarPathname)
	sys("EMACS_FLAVOR", LK_NONE, enum("emacs xemacs"))
	sys("EMACS_INFOPREFIX", LK_NONE, CheckvarPathname)
	sys("EMACS_LISPPREFIX", LK_NONE, CheckvarPathname)
	acl("EMACS_MODULES", LK_SHELL, CheckvarIdentifier, "Makefile:as", "Makefile.common:as")
	sys("EMACS_PKGNAME_PREFIX", LK_NONE, CheckvarIdentifier) // Or the empty string.
	sys("EMACS_TYPE", LK_NONE, enum("emacs xemacs"))
	acl("EMACS_USE_LEIM", LK_NONE, CheckvarYes)
	acl("EMACS_VERSIONS_ACCEPTED", LK_SHELL, enum("emacs25 emacs24 emacs24nox emacs23 emacs23nox emacs22 emacs22nox emacs21 emacs21nox emacs20 xemacs215 xemacs215nox xemacs214 xemacs214nox"), "Makefile:s")
	sys("EMACS_VERSION_MAJOR", LK_NONE, CheckvarInteger)
	sys("EMACS_VERSION_MINOR", LK_NONE, CheckvarInteger)
	acl("EMACS_VERSION_REQD", LK_SHELL, enum("emacs24 emacs24nox emacs23 emacs23nox emacs22 emacs22nox emacs21 emacs21nox emacs20 xemacs215 xemacs214"), "Makefile:as")
	sys("EMULDIR", LK_NONE, CheckvarPathname)
	sys("EMULSUBDIR", LK_NONE, CheckvarPathname)
	sys("OPSYS_EMULDIR", LK_NONE, CheckvarPathname)
	sys("EMULSUBDIRSLASH", LK_NONE, CheckvarPathname)
	sys("EMUL_ARCH", LK_NONE, enum("i386 none"))
	sys("EMUL_DISTRO", LK_NONE, CheckvarIdentifier)
	sys("EMUL_IS_NATIVE", LK_NONE, CheckvarYes)
	pkg("EMUL_MODULES.*", LK_SHELL, CheckvarIdentifier)
	sys("EMUL_OPSYS", LK_NONE, enum("freebsd hpux irix linux osf1 solaris sunos none"))
	pkg("EMUL_PKG_FMT", LK_NONE, enum("plain rpm"))
	usr("EMUL_PLATFORM", LK_NONE, CheckvarEmulPlatform)
	pkg("EMUL_PLATFORMS", LK_SHELL, CheckvarEmulPlatform)
	usr("EMUL_PREFER", LK_SHELL, CheckvarEmulPlatform)
	pkg("EMUL_REQD", LK_SPACE, CheckvarDependency)
	usr("EMUL_TYPE.*", LK_NONE, enum("native builtin suse suse-9.1 suse-9.x suse-10.0 suse-10.x"))
	sys("ERROR_CAT", LK_NONE, CheckvarShellCommand)
	sys("ERROR_MSG", LK_NONE, CheckvarShellCommand)
	acl("EVAL_PREFIX", LK_SPACE, CheckvarShellWord, "Makefile:a", "Makefile.common:a") // XXX: Combining ShellWord with LK_SPACE looks weird.
	sys("EXPORT_SYMBOLS_LDFLAGS", LK_SHELL, CheckvarLdFlag)
	sys("EXTRACT_CMD", LK_NONE, CheckvarShellCommand)
	pkg("EXTRACT_DIR", LK_NONE, CheckvarPathname)
	pkglist("EXTRACT_ELEMENTS", LK_SHELL, CheckvarPathmask)
	pkglist("EXTRACT_ENV", LK_SHELL, CheckvarShellWord)
	pkglist("EXTRACT_ONLY", LK_SHELL, CheckvarPathname)
	acl("EXTRACT_OPTS", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_BIN", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_LHA", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_PAX", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_RAR", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_TAR", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_ZIP", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	acl("EXTRACT_OPTS_ZOO", LK_SHELL, CheckvarShellWord, "Makefile:as", "Makefile.common:as")
	pkg("EXTRACT_SUFX", LK_NONE, CheckvarDistSuffix)
	pkg("EXTRACT_USING", LK_NONE, enum("bsdtar gtar nbtar pax"))
	sys("FAIL_MSG", LK_NONE, CheckvarShellCommand)
	sys("FAMBASE", LK_NONE, CheckvarPathname)
	pkg("FAM_ACCEPTED", LK_SHELL, enum("fam gamin"))
	usr("FAM_DEFAULT", LK_NONE, enum("fam gamin"))
	sys("FAM_TYPE", LK_NONE, enum("fam gamin"))
	acl("FETCH_BEFORE_ARGS", LK_SHELL, CheckvarShellWord, "Makefile:as")
	pkglist("FETCH_MESSAGE", LK_SHELL, CheckvarShellWord)
	pkg("FILESDIR", LK_NONE, CheckvarRelativePkgPath)
	pkglist("FILES_SUBST", LK_SHELL, CheckvarShellWord)
	acl("FILES_SUBST_SED", LK_SHELL, CheckvarShellWord)
	pkglist("FIX_RPATH", LK_SHELL, CheckvarVarname)
	pkglist("FLEX_REQD", LK_SHELL, CheckvarVersion)
	acl("FONTS_DIRS.*", LK_SHELL, CheckvarPathname, "Makefile:as", "Makefile.common:a")
	sys("GAMEDATAMODE", LK_NONE, CheckvarFileMode)
	sys("GAMES_GROUP", LK_NONE, CheckvarUserGroupName)
	sys("GAMEMODE", LK_NONE, CheckvarFileMode)
	sys("GAMES_USER", LK_NONE, CheckvarUserGroupName)
	pkglist("GCC_REQD", LK_SHELL, CheckvarVersion)
	pkglist("GENERATE_PLIST", LK_SHELL, CheckvarShellWord) // List of Shellcommand, terminated with a semicolon
	pkg("GITHUB_PROJECT", LK_NONE, CheckvarIdentifier)
	pkg("GITHUB_TAG", LK_NONE, CheckvarIdentifier)
	pkg("GITHUB_RELEASE", LK_NONE, CheckvarFilename)
	pkg("GITHUB_TYPE", LK_NONE, enum("tag release"))
	acl("GNU_ARCH", LK_NONE, enum("mips"))
	acl("GNU_CONFIGURE", LK_NONE, CheckvarYes, "Makefile.common:s", "Makefile:s")
	acl("GNU_CONFIGURE_INFODIR", LK_NONE, CheckvarPathname, "Makefile:s", "Makefile.common:s")
	acl("GNU_CONFIGURE_LIBDIR", LK_NONE, CheckvarPathname, "Makefile:s", "Makefile.common:s")
	pkg("GNU_CONFIGURE_LIBSUBDIR", LK_NONE, CheckvarPathname)
	acl("GNU_CONFIGURE_MANDIR", LK_NONE, CheckvarPathname, "Makefile:s", "Makefile.common:s")
	acl("GNU_CONFIGURE_PREFIX", LK_NONE, CheckvarPathname, "Makefile:s")
	acl("HAS_CONFIGURE", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:s")
	pkglist("HEADER_TEMPLATES", LK_SHELL, CheckvarPathname)
	pkg("HOMEPAGE", LK_NONE, CheckvarURL)
	acl("IGNORE_PKG.*", LK_NONE, CheckvarYes, "*:sp")
	acl("INCOMPAT_CURSES", LK_SPACE, CheckvarPlatformTriple, "Makefile:as")
	acl("INCOMPAT_ICONV", LK_SPACE, CheckvarPlatformTriple)
	acl("INFO_DIR", LK_NONE, CheckvarPathname) // relative to PREFIX
	pkg("INFO_FILES", LK_NONE, CheckvarYes)
	sys("INSTALL", LK_NONE, CheckvarShellCommand)
	pkglist("INSTALLATION_DIRS", LK_SHELL, CheckvarPrefixPathname)
	pkg("INSTALLATION_DIRS_FROM_PLIST", LK_NONE, CheckvarYes)
	sys("INSTALL_DATA", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_DATA_DIR", LK_NONE, CheckvarShellCommand)
	pkglist("INSTALL_DIRS", LK_SHELL, CheckvarWrksrcSubdirectory)
	pkglist("INSTALL_ENV", LK_SHELL, CheckvarShellWord)
	acl("INSTALL_FILE", LK_NONE, CheckvarPathname, "Makefile:s")
	sys("INSTALL_GAME", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_GAME_DATA", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_LIB", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_LIB_DIR", LK_NONE, CheckvarShellCommand)
	pkglist("INSTALL_MAKE_FLAGS", LK_SHELL, CheckvarShellWord)
	sys("INSTALL_MAN", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_MAN_DIR", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_PROGRAM", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_PROGRAM_DIR", LK_NONE, CheckvarShellCommand)
	sys("INSTALL_SCRIPT", LK_NONE, CheckvarShellCommand)
	acl("INSTALL_SCRIPTS_ENV", LK_SHELL, CheckvarShellWord)
	sys("INSTALL_SCRIPT_DIR", LK_NONE, CheckvarShellCommand)
	acl("INSTALL_SRC", LK_SHELL, CheckvarPathname, "Makefile:s", "Makefile.common:ds")
	pkg("INSTALL_TARGET", LK_SHELL, CheckvarIdentifier)
	acl("INSTALL_TEMPLATES", LK_SHELL, CheckvarPathname, "Makefile:as", "Makefile.common:ads")
	acl("INSTALL_UNSTRIPPED", LK_NONE, CheckvarYesNo, "Makefile:s", "Makefile.common:s")
	pkg("INTERACTIVE_STAGE", LK_SHELL, enum("fetch extract configure build install"))
	acl("IS_BUILTIN.*", LK_NONE, CheckvarYesNo_Indirectly, "builtin.mk:psu")
	sys("JAVA_BINPREFIX", LK_NONE, CheckvarPathname)
	pkg("JAVA_CLASSPATH", LK_NONE, CheckvarShellWord)
	pkg("JAVA_HOME", LK_NONE, CheckvarPathname)
	pkg("JAVA_NAME", LK_NONE, CheckvarFilename)
	pkglist("JAVA_UNLIMIT", LK_SHELL, enum("cmdsize datasize stacksize"))
	pkglist("JAVA_WRAPPERS", LK_SPACE, CheckvarFilename)
	pkg("JAVA_WRAPPER_BIN.*", LK_NONE, CheckvarPathname)
	sys("KRB5BASE", LK_NONE, CheckvarPathname)
	acl("KRB5_ACCEPTED", LK_SHELL, enum("heimdal mit-krb5"))
	usr("KRB5_DEFAULT", LK_NONE, enum("heimdal mit-krb5"))
	sys("KRB5_TYPE", LK_NONE, CheckvarUnchecked)
	sys("LD", LK_NONE, CheckvarShellCommand)
	pkglist("LDFLAGS*", LK_SHELL, CheckvarLdFlag)
	sys("LIBGRP", LK_NONE, CheckvarUserGroupName)
	sys("LIBMODE", LK_NONE, CheckvarFileMode)
	sys("LIBOWN", LK_NONE, CheckvarUserGroupName)
	sys("LIBOSSAUDIO", LK_NONE, CheckvarPathname)
	pkglist("LIBS*", LK_SHELL, CheckvarLdFlag)
	sys("LIBTOOL", LK_NONE, CheckvarShellCommand)
	acl("LIBTOOL_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as")
	pkglist("LIBTOOL_REQD", LK_SHELL, CheckvarVersion)
	acl("LICENCE", LK_NONE, CheckvarLicense, "Makefile:s", "Makefile.common:s", "options.mk:s")
	acl("LICENSE", LK_NONE, CheckvarLicense, "Makefile:s", "Makefile.common:s", "options.mk:s")
	pkg("LICENSE_FILE", LK_NONE, CheckvarPathname)
	sys("LINKER_RPATH_FLAG", LK_NONE, CheckvarShellWord)
	sys("LOWER_OPSYS", LK_NONE, CheckvarIdentifier)
	acl("LTCONFIG_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:a")
	sys("MACHINE_ARCH", LK_NONE, CheckvarIdentifier)
	sys("MACHINE_GNU_PLATFORM", LK_NONE, CheckvarPlatformTriple)
	acl("MAINTAINER", LK_NONE, CheckvarMailAddress, "Makefile:s", "Makefile.common:d")
	sys("MAKE", LK_NONE, CheckvarShellCommand)
	pkglist("MAKEFLAGS", LK_SHELL, CheckvarShellWord)
	acl("MAKEVARS", LK_SHELL, CheckvarVarname, "builtin.mk:a", "buildlink3.mk:a", "hacks.mk:a")
	pkglist("MAKE_DIRS", LK_SHELL, CheckvarPathname)
	pkglist("MAKE_DIRS_PERMS", LK_SHELL, CheckvarShellWord)
	pkglist("MAKE_ENV", LK_SHELL, CheckvarShellWord)
	pkg("MAKE_FILE", LK_NONE, CheckvarPathname)
	pkglist("MAKE_FLAGS", LK_SHELL, CheckvarShellWord)
	usr("MAKE_JOBS", LK_NONE, CheckvarInteger)
	pkg("MAKE_JOBS_SAFE", LK_NONE, CheckvarYesNo)
	pkg("MAKE_PROGRAM", LK_NONE, CheckvarShellCommand)
	acl("MANCOMPRESSED", LK_NONE, CheckvarYesNo, "Makefile:s", "Makefile.common:ds")
	acl("MANCOMPRESSED_IF_MANZ", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:ds")
	sys("MANGRP", LK_NONE, CheckvarUserGroupName)
	sys("MANMODE", LK_NONE, CheckvarFileMode)
	sys("MANOWN", LK_NONE, CheckvarUserGroupName)
	pkglist("MASTER_SITES", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_APACHE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_BACKUP", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_CYGWIN", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_DEBIAN", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_FREEBSD", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_FREEBSD_LOCAL", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_GENTOO", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_GITHUB", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_GNOME", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_GNU", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_GNUSTEP", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_IFARCHIVE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_HASKELL_HACKAGE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_KDE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_LOCAL", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_MOZILLA", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_MOZILLA_ALL", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_MOZILLA_ESR", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_MYSQL", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_NETLIB", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_OPENOFFICE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_OSDN", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_PERL_CPAN", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_R_CRAN", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_RUBYGEMS", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_SOURCEFORGE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_SUNSITE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_SUSE", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_TEX_CTAN", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_XCONTRIB", LK_SHELL, CheckvarFetchURL)
	sys("MASTER_SITE_XEMACS", LK_SHELL, CheckvarFetchURL)
	pkglist("MESSAGE_SRC", LK_SHELL, CheckvarPathname)
	acl("MESSAGE_SUBST", LK_SHELL, CheckvarShellWord, "Makefile.common:a", "Makefile:a", "options.mk:a")
	pkg("META_PACKAGE", LK_NONE, CheckvarYes)
	sys("MISSING_FEATURES", LK_SHELL, CheckvarIdentifier)
	acl("MYSQL_VERSIONS_ACCEPTED", LK_SHELL, enum("51 55 56"), "Makefile:s")
	usr("MYSQL_VERSION_DEFAULT", LK_NONE, CheckvarVersion)
	sys("NM", LK_NONE, CheckvarShellCommand)
	sys("NONBINMODE", LK_NONE, CheckvarFileMode)
	pkg("NOT_FOR_COMPILER", LK_SHELL, enum("ccache ccc clang distcc f2c gcc hp icc ido mipspro mipspro-ucode pcc sunpro xlc"))
	pkglist("NOT_FOR_PLATFORM", LK_SPACE, CheckvarPlatformTriple)
	pkg("NOT_FOR_UNPRIVILEGED", LK_NONE, CheckvarYesNo)
	acl("NO_BIN_ON_CDROM", LK_NONE, CheckvarRestricted, "Makefile:s", "Makefile.common:s")
	acl("NO_BIN_ON_FTP", LK_NONE, CheckvarRestricted, "Makefile:s", "Makefile.common:s")
	acl("NO_BUILD", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:s", "Makefile.*:ds")
	pkg("NO_CHECKSUM", LK_NONE, CheckvarYes)
	pkg("NO_CONFIGURE", LK_NONE, CheckvarYes)
	acl("NO_EXPORT_CPP", LK_NONE, CheckvarYes, "Makefile:s")
	pkg("NO_EXTRACT", LK_NONE, CheckvarYes)
	pkg("NO_INSTALL_MANPAGES", LK_NONE, CheckvarYes) // only has an effect for Imake packages.
	acl("NO_PKGTOOLS_REQD_CHECK", LK_NONE, CheckvarYes, "Makefile:s")
	acl("NO_SRC_ON_CDROM", LK_NONE, CheckvarRestricted, "Makefile:s", "Makefile.common:s")
	acl("NO_SRC_ON_FTP", LK_NONE, CheckvarRestricted, "Makefile:s", "Makefile.common:s")
	pkglist("ONLY_FOR_COMPILER", LK_SHELL, enum("ccc clang gcc hp icc ido mipspro mipspro-ucode pcc sunpro xlc"))
	pkglist("ONLY_FOR_PLATFORM", LK_SPACE, CheckvarPlatformTriple)
	pkg("ONLY_FOR_UNPRIVILEGED", LK_NONE, CheckvarYesNo)
	sys("OPSYS", LK_NONE, CheckvarIdentifier)
	acl("OPSYSVARS", LK_SHELL, CheckvarVarname, "Makefile:a", "Makefile.common:a")
	acl("OSVERSION_SPECIFIC", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:s")
	sys("OS_VERSION", LK_NONE, CheckvarVersion)
	pkg("OVERRIDE_DIRDEPTH*", LK_NONE, CheckvarInteger)
	pkg("OVERRIDE_GNU_CONFIG_SCRIPTS", LK_NONE, CheckvarYes)
	acl("OWNER", LK_NONE, CheckvarMailAddress, "Makefile:s", "Makefile.common:d")
	pkglist("OWN_DIRS", LK_SHELL, CheckvarPathname)
	pkglist("OWN_DIRS_PERMS", LK_SHELL, CheckvarShellWord)
	sys("PAMBASE", LK_NONE, CheckvarPathname)
	usr("PAM_DEFAULT", LK_NONE, enum("linux-pam openpam solaris-pam"))
	acl("PATCHDIR", LK_NONE, CheckvarRelativePkgPath, "Makefile:s", "Makefile.common:ds")
	pkglist("PATCHFILES", LK_SHELL, CheckvarFilename)
	acl("PATCH_ARGS", LK_SHELL, CheckvarShellWord)
	acl("PATCH_DIST_ARGS", LK_SHELL, CheckvarShellWord, "Makefile:as")
	acl("PATCH_DIST_CAT", LK_NONE, CheckvarShellCommand)
	acl("PATCH_DIST_STRIP*", LK_NONE, CheckvarShellWord, "Makefile:s", "Makefile.common:s", "buildlink3.mk:", "builtin.mk:", "*.mk:s")
	acl("PATCH_SITES", LK_SHELL, CheckvarURL, "Makefile:s", "options.mk:s", "Makefile.common:s")
	acl("PATCH_STRIP", LK_NONE, CheckvarShellWord)
	pkg("PERL5_USE_PACKLIST", LK_NONE, CheckvarYesNo)
	acl("PERL5_PACKLIST", LK_SHELL, CheckvarPerl5Packlist, "Makefile:s", "options.mk:sa")
	acl("PERL5_PACKLIST_DIR", LK_NONE, CheckvarPathname)
	sys("PGSQL_PREFIX", LK_NONE, CheckvarPathname)
	acl("PGSQL_VERSIONS_ACCEPTED", LK_SHELL, enum("91 92 93 94"))
	usr("PGSQL_VERSION_DEFAULT", LK_NONE, CheckvarVersion)
	sys("PG_LIB_EXT", LK_NONE, enum("dylib so"))
	sys("PGSQL_TYPE", LK_NONE, enum("postgresql81-client postgresql80-client"))
	sys("PGPKGSRCDIR", LK_NONE, CheckvarPathname)
	sys("PHASE_MSG", LK_NONE, CheckvarShellCommand)
	usr("PHP_VERSION_REQD", LK_NONE, CheckvarVersion)
	sys("PKGBASE", LK_NONE, CheckvarIdentifier)
	acl("PKGCONFIG_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:a")
	pkg("PKGCONFIG_OVERRIDE_STAGE", LK_NONE, CheckvarStage)
	pkg("PKGDIR", LK_NONE, CheckvarRelativePkgDir)
	sys("PKGDIRMODE", LK_NONE, CheckvarFileMode)
	sys("PKGLOCALEDIR", LK_NONE, CheckvarPathname)
	pkg("PKGNAME", LK_NONE, CheckvarPkgName)
	sys("PKGNAME_NOREV", LK_NONE, CheckvarPkgName)
	sys("PKGPATH", LK_NONE, CheckvarPathname)
	acl("PKGREPOSITORY", LK_NONE, CheckvarUnchecked)
	acl("PKGREVISION", LK_NONE, CheckvarPkgRevision, "Makefile:s")
	sys("PKGSRCDIR", LK_NONE, CheckvarPathname)
	acl("PKGSRCTOP", LK_NONE, CheckvarYes, "Makefile:s")
	acl("PKGTOOLS_ENV", LK_SHELL, CheckvarShellWord)
	sys("PKGVERSION", LK_NONE, CheckvarVersion)
	sys("PKGWILDCARD", LK_NONE, CheckvarFilemask)
	sys("PKG_ADMIN", LK_NONE, CheckvarShellCommand)
	sys("PKG_APACHE", LK_NONE, enum("apache22 apache24"))
	pkg("PKG_APACHE_ACCEPTED", LK_SHELL, enum("apache22 apache24"))
	usr("PKG_APACHE_DEFAULT", LK_NONE, enum("apache22 apache24"))
	usr("PKG_CONFIG", LK_NONE, CheckvarYes)
	// ^^ No, this is not the popular command from GNOME, but the setting
	// whether the pkgsrc user wants configuration files automatically
	// installed or not.
	sys("PKG_CREATE", LK_NONE, CheckvarShellCommand)
	sys("PKG_DBDIR", LK_NONE, CheckvarPathname)
	cmdline("PKG_DEBUG_LEVEL", LK_NONE, CheckvarInteger)
	usr("PKG_DEFAULT_OPTIONS", LK_SHELL, CheckvarOption)
	sys("PKG_DELETE", LK_NONE, CheckvarShellCommand)
	acl("PKG_DESTDIR_SUPPORT", LK_SHELL, enum("destdir user-destdir"), "Makefile:s", "Makefile.common:s")
	pkglist("PKG_FAIL_REASON", LK_SHELL, CheckvarShellWord)
	acl("PKG_GECOS.*", LK_NONE, CheckvarMessage, "Makefile:s")
	acl("PKG_GID.*", LK_NONE, CheckvarInteger, "Makefile:s")
	acl("PKG_GROUPS", LK_SHELL, CheckvarShellWord, "Makefile:as")
	pkglist("PKG_GROUPS_VARS", LK_SHELL, CheckvarVarname)
	acl("PKG_HOME.*", LK_NONE, CheckvarPathname, "Makefile:s")
	acl("PKG_HACKS", LK_SHELL, CheckvarIdentifier, "hacks.mk:a")
	sys("PKG_INFO", LK_NONE, CheckvarShellCommand)
	sys("PKG_JAVA_HOME", LK_NONE, CheckvarPathname)
	jvms := enum("{ blackdown-jdk13 jdk jdk14 kaffe run-jdk13 sun-jdk14 sun-jdk15 sun-jdk6 openjdk7 openjdk7-bin sun-jdk7}")
	sys("PKG_JVM", LK_NONE, jvms)
	acl("PKG_JVMS_ACCEPTED", LK_SHELL, jvms, "Makefile:s", "Makefile.common:ds")
	usr("PKG_JVM_DEFAULT", LK_NONE, jvms)
	acl("PKG_LEGACY_OPTIONS", LK_SHELL, CheckvarOption)
	acl("PKG_LIBTOOL", LK_NONE, CheckvarPathname, "Makefile:s")
	acl("PKG_OPTIONS", LK_SPACE, CheckvarOption, "bsd.options.mk:s", "*:pu")
	usr("PKG_OPTIONS.*", LK_SPACE, CheckvarOption)
	acl("PKG_OPTIONS_DEPRECATED_WARNINGS", LK_SHELL, CheckvarShellWord)
	acl("PKG_OPTIONS_GROUP.*", LK_SPACE, CheckvarOption, "options.mk:s", "Makefile:s")
	acl("PKG_OPTIONS_LEGACY_OPTS", LK_SPACE, CheckvarUnchecked, "Makefile:a", "Makefile.common:a", "options.mk:a")
	acl("PKG_OPTIONS_LEGACY_VARS", LK_SPACE, CheckvarUnchecked, "Makefile:a", "Makefile.common:a", "options.mk:a")
	acl("PKG_OPTIONS_NONEMPTY_SETS", LK_SPACE, CheckvarIdentifier)
	acl("PKG_OPTIONS_OPTIONAL_GROUPS", LK_SPACE, CheckvarIdentifier, "options.mk:as")
	acl("PKG_OPTIONS_REQUIRED_GROUPS", LK_SPACE, CheckvarIdentifier, "options.mk:s", "Makefile:s")
	acl("PKG_OPTIONS_SET.*", LK_SPACE, CheckvarOption)
	acl("PKG_OPTIONS_VAR", LK_NONE, CheckvarPkgOptionsVar, "options.mk:s", "Makefile:s", "Makefile.common:s", "bsd.options.mk:p")
	acl("PKG_PRESERVE", LK_NONE, CheckvarYes, "Makefile:s")
	acl("PKG_SHELL", LK_NONE, CheckvarPathname, "Makefile:s", "Makefile.common:s")
	acl("PKG_SHELL.*", LK_NONE, CheckvarPathname, "Makefile:s", "Makefile.common:s")
	acl("PKG_SHLIBTOOL", LK_NONE, CheckvarPathname)
	pkglist("PKG_SKIP_REASON", LK_SHELL, CheckvarShellWord)
	acl("PKG_SUGGESTED_OPTIONS", LK_SHELL, CheckvarOption, "options.mk:as", "Makefile:as", "Makefile.common:s")
	acl("PKG_SUPPORTED_OPTIONS", LK_SHELL, CheckvarOption, "options.mk:as", "Makefile:as", "Makefile.common:s")
	pkg("PKG_SYSCONFDIR*", LK_NONE, CheckvarPathname)
	pkglist("PKG_SYSCONFDIR_PERMS", LK_SHELL, CheckvarShellWord)
	sys("PKG_SYSCONFBASEDIR", LK_NONE, CheckvarPathname)
	pkg("PKG_SYSCONFSUBDIR", LK_NONE, CheckvarPathname)
	acl("PKG_SYSCONFVAR", LK_NONE, CheckvarIdentifier) // FIXME: name/type mismatch.")
	acl("PKG_UID", LK_NONE, CheckvarInteger, "Makefile:s")
	acl("PKG_USERS", LK_SHELL, CheckvarShellWord, "Makefile:as")
	pkg("PKG_USERS_VARS", LK_SHELL, CheckvarVarname)
	acl("PKG_USE_KERBEROS", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:s")
	// PLIST.* has special handling code
	pkglist("PLIST_VARS", LK_SHELL, CheckvarIdentifier)
	pkglist("PLIST_SRC", LK_SHELL, CheckvarRelativePkgPath)
	pkglist("PLIST_SUBST", LK_SHELL, CheckvarShellWord)
	acl("PLIST_TYPE", LK_NONE, enum("dynamic static"))
	acl("PREPEND_PATH", LK_SHELL, CheckvarPathname)
	acl("PREFIX", LK_NONE, CheckvarPathname, "*:u")
	acl("PREV_PKGPATH", LK_NONE, CheckvarPathname, "*:u") // doesn't exist any longer
	acl("PRINT_PLIST_AWK", LK_NONE, CheckvarAwkCommand, "*:a")
	acl("PRIVILEGED_STAGES", LK_SHELL, enum("install package clean"))
	acl("PTHREAD_AUTO_VARS", LK_NONE, CheckvarYesNo, "Makefile:s")
	sys("PTHREAD_CFLAGS", LK_SHELL, CheckvarCFlag)
	sys("PTHREAD_LDFLAGS", LK_SHELL, CheckvarLdFlag)
	sys("PTHREAD_LIBS", LK_SHELL, CheckvarLdFlag)
	acl("PTHREAD_OPTS", LK_SHELL, enum("native optional require"), "Makefile:as", "Makefile.common:a", "buildlink3.mk:a")
	sys("PTHREAD_TYPE", LK_NONE, CheckvarIdentifier) // Or "native" or "none".
	pkg("PY_PATCHPLIST", LK_NONE, CheckvarYes)
	acl("PYPKGPREFIX", LK_NONE, enum("py27 py33 py34"), "*:pu", "pyversion.mk:s", "*:")
	pkg("PYTHON_FOR_BUILD_ONLY", LK_NONE, CheckvarYes)
	pkglist("REPLACE_PYTHON", LK_SHELL, CheckvarPathmask)
	pkg("PYTHON_VERSIONS_ACCEPTED", LK_SHELL, CheckvarVersion)
	pkg("PYTHON_VERSIONS_INCOMPATIBLE", LK_SHELL, CheckvarVersion)
	usr("PYTHON_VERSION_DEFAULT", LK_NONE, CheckvarVersion)
	usr("PYTHON_VERSION_REQD", LK_NONE, CheckvarVersion)
	pkglist("PYTHON_VERSIONED_DEPENDENCIES", LK_SHELL, CheckvarPythonDependency)
	sys("RANLIB", LK_NONE, CheckvarShellCommand)
	pkglist("RCD_SCRIPTS", LK_SHELL, CheckvarFilename)
	acl("RCD_SCRIPT_SRC.*", LK_SHELL, CheckvarPathname, "Makefile:s")
	acl("REPLACE.*", LK_NONE, CheckvarString, "Makefile:s")
	pkglist("REPLACE_AWK", LK_SHELL, CheckvarPathmask)
	pkglist("REPLACE_BASH", LK_SHELL, CheckvarPathmask)
	pkglist("REPLACE_CSH", LK_SHELL, CheckvarPathmask)
	acl("REPLACE_EMACS", LK_SHELL, CheckvarPathmask)
	acl("REPLACE_FILES.*", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:as")
	acl("REPLACE_INTERPRETER", LK_SHELL, CheckvarIdentifier, "Makefile:a", "Makefile.common:a")
	pkglist("REPLACE_KSH", LK_SHELL, CheckvarPathmask)
	pkglist("REPLACE_LOCALEDIR_PATTERNS", LK_SHELL, CheckvarFilemask)
	pkglist("REPLACE_LUA", LK_SHELL, CheckvarPathmask)
	pkglist("REPLACE_PERL", LK_SHELL, CheckvarPathmask)
	pkglist("REPLACE_PYTHON", LK_SHELL, CheckvarPathmask)
	pkglist("REPLACE_SH", LK_SHELL, CheckvarPathmask)
	pkglist("REQD_DIRS", LK_SHELL, CheckvarPathname)
	pkglist("REQD_DIRS_PERMS", LK_SHELL, CheckvarShellWord)
	pkglist("REQD_FILES", LK_SHELL, CheckvarPathname)
	pkg("REQD_FILES_MODE", LK_NONE, enum("0644 0640 0600 0400"))
	pkglist("REQD_FILES_PERMS", LK_SHELL, CheckvarShellWord)
	pkg("RESTRICTED", LK_NONE, CheckvarMessage)
	usr("ROOT_USER", LK_NONE, CheckvarUserGroupName)
	usr("ROOT_GROUP", LK_NONE, CheckvarUserGroupName)
	usr("RUBY_VERSION_REQD", LK_NONE, CheckvarVersion)
	sys("RUN", LK_NONE, CheckvarShellCommand)
	acl("SCRIPTS_ENV", LK_SHELL, CheckvarShellWord, "Makefile:a", "Makefile.common:a")
	usr("SETUID_ROOT_PERMS", LK_SHELL, CheckvarShellWord)
	sys("SHAREGRP", LK_NONE, CheckvarUserGroupName)
	sys("SHAREMODE", LK_NONE, CheckvarFileMode)
	sys("SHAREOWN", LK_NONE, CheckvarUserGroupName)
	sys("SHCOMMENT", LK_NONE, CheckvarShellCommand)
	acl("SHLIB_HANDLING", LK_NONE, enum("YES NO no"))
	acl("SHLIBTOOL", LK_NONE, CheckvarShellCommand)
	acl("SHLIBTOOL_OVERRIDE", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:a")
	acl("SITES.*", LK_SHELL, CheckvarFetchURL, "Makefile:asu", "Makefile.common:asu", "options.mk:asu")
	pkglist("SPECIAL_PERMS", LK_SHELL, CheckvarShellWord)
	sys("STEP_MSG", LK_NONE, CheckvarShellCommand)
	acl("SUBDIR", LK_SHELL, CheckvarFilename, "Makefile:a", "*:")
	acl("SUBST_CLASSES", LK_SHELL, CheckvarIdentifier, "Makefile:a", "Makefile.common:a", "hacks.mk:a", "Makefile.*:a")
	acl("SUBST_FILES.*", LK_SHELL, CheckvarPathmask, "Makefile:as", "Makefile.common:as", "hacks.mk:as", "options.mk:as", "Makefile.*:as")
	acl("SUBST_FILTER_CMD.*", LK_NONE, CheckvarShellCommand, "Makefile:s", "Makefile.common:s", "hacks.mk:s", "options.mk:s", "Makefile.*:s")
	acl("SUBST_MESSAGE.*", LK_NONE, CheckvarMessage, "Makefile:s", "Makefile.common:s", "hacks.mk:s", "options.mk:s", "Makefile.*:s")
	acl("SUBST_SED.*", LK_NONE, CheckvarSedCommands, "Makefile:as", "Makefile.common:as", "hacks.mk:as", "options.mk:as", "Makefile.*:as")
	pkg("SUBST_STAGE.*", LK_NONE, CheckvarStage)
	pkglist("SUBST_VARS.*", LK_SHELL, CheckvarVarname)
	pkglist("SUPERSEDES", LK_SPACE, CheckvarDependency)
	pkglist("TEST_DIRS", LK_SHELL, CheckvarWrksrcSubdirectory)
	pkglist("TEST_ENV", LK_SHELL, CheckvarShellWord)
	acl("TEST_TARGET", LK_SHELL, CheckvarIdentifier, "Makefile:s", "Makefile.common:ds", "options.mk:as")
	acl("TEX_ACCEPTED", LK_SHELL, enum("teTeX1 teTeX2 teTeX3"), "Makefile:s", "Makefile.common:s")
	acl("TEX_DEPMETHOD", LK_NONE, enum("build run"), "Makefile:s", "Makefile.common:s")
	pkglist("TEXINFO_REQD", LK_SHELL, CheckvarVersion)
	acl("TOOL_DEPENDS", LK_SPACE, CheckvarDependencyWithPath, "Makefile.common:a", "Makefile:a", "options.mk:a", "*.mk:a")
	sys("TOOLS_ALIASES", LK_SHELL, CheckvarFilename)
	sys("TOOLS_BROKEN", LK_SHELL, CheckvarTool)
	sys("TOOLS_CREATE", LK_SHELL, CheckvarTool)
	sys("TOOLS_DEPENDS.*", LK_SPACE, CheckvarDependencyWithPath)
	sys("TOOLS_GNU_MISSING", LK_SHELL, CheckvarTool)
	sys("TOOLS_NOOP", LK_SHELL, CheckvarTool)
	sys("TOOLS_PATH.*", LK_NONE, CheckvarPathname)
	sys("TOOLS_PLATFORM.*", LK_NONE, CheckvarShellCommand)
	sys("TOUCH_FLAGS", LK_SHELL, CheckvarShellWord)
	pkglist("UAC_REQD_EXECS", LK_SHELL, CheckvarPrefixPathname)
	acl("UNLIMIT_RESOURCES", LK_SHELL, enum("datasize stacksize memorysize"), "Makefile:as", "Makefile.common:a")
	usr("UNPRIVILEGED_USER", LK_NONE, CheckvarUserGroupName)
	usr("UNPRIVILEGED_GROUP", LK_NONE, CheckvarUserGroupName)
	pkglist("UNWRAP_FILES", LK_SHELL, CheckvarPathmask)
	usr("UPDATE_TARGET", LK_SHELL, CheckvarIdentifier)
	pkg("USE_BSD_MAKEFILE", LK_NONE, CheckvarYes)
	acl("USE_BUILTIN.*", LK_NONE, CheckvarYesNo_Indirectly, "builtin.mk:s")
	pkg("USE_CMAKE", LK_NONE, CheckvarYes)
	acl("USE_CROSSBASE", LK_NONE, CheckvarYes, "Makefile:s")
	pkg("USE_FEATURES", LK_SHELL, CheckvarIdentifier)
	pkg("USE_GCC_RUNTIME", LK_NONE, CheckvarYesNo)
	pkg("USE_GNU_CONFIGURE_HOST", LK_NONE, CheckvarYesNo)
	acl("USE_GNU_ICONV", LK_NONE, CheckvarYes, "Makefile:s", "Makefile.common:s", "options.mk:s")
	acl("USE_IMAKE", LK_NONE, CheckvarYes, "Makefile:s")
	pkg("USE_JAVA", LK_NONE, enum("run yes build"))
	pkg("USE_JAVA2", LK_NONE, enum("YES yes no 1.4 1.5 6 7 8"))
	acl("USE_LANGUAGES", LK_SHELL, enum("ada c c99 c++ fortran fortran77 java objc"), "Makefile:s", "Makefile.common:s", "options.mk:s")
	pkg("USE_LIBTOOL", LK_NONE, CheckvarYes)
	pkg("USE_MAKEINFO", LK_NONE, CheckvarYes)
	pkg("USE_MSGFMT_PLURALS", LK_NONE, CheckvarYes)
	pkg("USE_NCURSES", LK_NONE, CheckvarYes)
	pkg("USE_OLD_DES_API", LK_NONE, CheckvarYesNo)
	pkg("USE_PKGINSTALL", LK_NONE, CheckvarYes)
	pkg("USE_PKGLOCALEDIR", LK_NONE, CheckvarYesNo)
	usr("USE_PKGSRC_GCC", LK_NONE, CheckvarYes)
	acl("USE_TOOLS", LK_SHELL, CheckvarTool, "*:a")
	pkg("USE_X11", LK_NONE, CheckvarYes)
	sys("WARNING_MSG", LK_NONE, CheckvarShellCommand)
	sys("WARNING_CAT", LK_NONE, CheckvarShellCommand)
	acl("WRAPPER_REORDER_CMDS", LK_SHELL, CheckvarWrapperReorder, "buildlink3.mk:a", "Makefile.common:a", "Makefile:a")
	acl("WRAPPER_TRANSFORM_CMDS", LK_SHELL, CheckvarWrapperTransform, "buildlink3.mk:a", "Makefile.common:a", "Makefile:a")
	sys("WRKDIR", LK_NONE, CheckvarPathname)
	pkg("WRKSRC", LK_NONE, CheckvarWrkdirSubdirectory)
	sys("X11_PKGSRCDIR.*", LK_NONE, CheckvarPathname)
	usr("XAW_TYPE", LK_NONE, enum("3d neXtaw standard xpm"))
	acl("XMKMF_FLAGS", LK_SHELL, CheckvarShellWord)
}

func enum(values string) *VarChecker {
	vmap := make(map[string]bool)
	for _, value := range splitOnSpace(values) {
		vmap[value] = true
	}
	name := "enum: " + values + " " // See IsEnum
	return &VarChecker{name, func(ctx *VartypeCheck) {
		if !vmap[ctx.value] {
			ctx.line.warnf("%q is not valid for %s. Use one of { %s } instead.", ctx.value, ctx.varname, values)
		}
	}}
}

func acl(varname string, kindOfList KindOfList, checker *VarChecker, aclentries ...string) {
	m := mustMatch(`^([A-Z_.][A-Z0-9_]*)(|\*|\.\*)$`, varname)
	varbase, varparam := m[1], m[2]

	vtype := &Vartype{kindOfList, checker, parseAclEntries(aclentries), NOT_GUESSED}

	if G.globalData.vartypes == nil {
		G.globalData.vartypes = make(map[string]*Vartype)
	}
	if varparam == "" || varparam == "*" {
		G.globalData.vartypes[varbase] = vtype
	}
	if varparam == "*" || varparam == ".*" {
		G.globalData.vartypes[varbase+".*"] = vtype
	}
}

func parseAclEntries(args []string) []AclEntry {
	var result []AclEntry
	for _, arg := range args {
		m := mustMatch(`^([\w.*]+|_):([adpsu]*)$`, arg)
		glob, perms := m[1], m[2]
		result = append(result, AclEntry{glob, perms})
	}
	return result
}

// A package-defined variable may be set in all Makefiles except buildlink3.mk and builtin.mk.
func pkg(varname string, kindOfList KindOfList, checker *VarChecker) {
	acl(varname, kindOfList, checker, "Makefile:su", "Makefile.common:dsu", "buildlink3.mk:", "builtin.mk:", "*.mk:dsu")
}

// A package-defined list may be appended to in all Makefiles except buildlink3.mk and builtin.mk.
// Simple assignment (instead of appending) is only allowed in Makefile and Makefile.common.
func pkglist(varname string, kindOfList KindOfList, checker *VarChecker) {
	acl(varname, kindOfList, checker, "Makefile:asu", "Makefile.common:asu", "buildlink3.mk:", "builtin.mk:", "*.mk:au")
}

// A user-defined or system-defined variable must not be set by any
// package file. It also must not be used in buildlink3.mk and
// builtin.mk files or at load-time, since the system/user preferences
// may not have been loaded when these files are included.
func sys(varname string, kindOfList KindOfList, checker *VarChecker) {
	acl(varname, kindOfList, checker, "buildlink3.mk:", "builtin.mk:u", "*:u")
}
func usr(varname string, kindOfList KindOfList, checker *VarChecker) {
	acl(varname, kindOfList, checker, "buildlink3.mk:", "builtin.mk:", "*:u")
}
func bl3list(varname string, kindOfList KindOfList, checker *VarChecker) {
	acl(varname, kindOfList, checker, "buildlink3.mk:a", "builtin.mk:a")
}
func cmdline(varname string, kindOfList KindOfList, checker *VarChecker) {
	acl(varname, kindOfList, checker, "buildlink3.mk:", "builtin.mk:", "*:pu")
}
