# $NetBSD: Makefile,v 1.18 2004/01/26 15:20:31 jmmv Exp $
#

COMMENT=	Multimedia utilities

SUBDIR+=	alevt
SUBDIR+=	avidemux
SUBDIR+=	avifile
SUBDIR+=	avifile-devel
SUBDIR+=	divxplayer
SUBDIR+=	flashplayer
SUBDIR+=	fxtv
SUBDIR+=	gmencoder
SUBDIR+=	gmplayer
SUBDIR+=	gst-plugins
SUBDIR+=	gstreamer
SUBDIR+=	gxine
SUBDIR+=	kmplayer
SUBDIR+=	libflash
SUBDIR+=	mencoder
SUBDIR+=	mjpegtools
SUBDIR+=	moz-bin-flash
SUBDIR+=	moz-flash
SUBDIR+=	moz-mplayer
SUBDIR+=	mplayer
SUBDIR+=	mplayer-share
SUBDIR+=	mplex
SUBDIR+=	ns-flash
SUBDIR+=	realplayer
SUBDIR+=	realplayer-codecs
SUBDIR+=	trplayer
SUBDIR+=	win32-codecs
SUBDIR+=	xanim
SUBDIR+=	xawtv
SUBDIR+=	xine-lib
SUBDIR+=	xine-ui
SUBDIR+=	xvidcore

.include "../mk/bsd.pkg.subdir.mk"
