$NetBSD: patch-meli_Cargo.toml,v 1.3 2026/01/25 17:31:18 vins Exp $

Avoid static linking of vendored libraries.

--- meli/Cargo.toml.orig	2026-01-04 12:37:15.000000000 +0000
+++ meli/Cargo.toml
@@ -31,7 +31,6 @@ default = [
     "gpgme",
     "cli-docs",
     "jmap",
-    "static",
 ]
 notmuch = ["melib/notmuch"]
 jmap = ["melib/jmap"]
@@ -48,7 +47,7 @@ http-static = ["melib/http-static"]
 sqlite3-static = ["melib/sqlite3-static"]
 dbus-static = ["dep:notify-rust", "notify-rust?/d_vendored"]
 libz-static = ["dep:libz-sys", "libz-sys?/static"]
-static = ["tls-static", "http-static", "sqlite3-static", "dbus-static", "libz-static"]
+#static = ["tls-static", "http-static", "sqlite3-static", "dbus-static", "libz-static"]
 
 # Print tracing logs as meli runs in stderr
 # enable for debug tracing logs: build with --features=debug-tracing and export MELI_DEBUG_STDERR
