# $NetBSD: buildlink3.mk,v 1.2 2005/05/05 19:37:22 kei Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
JA_FREEWNN_LIB_BUILDLINK3_MK:=	${JA_FREEWNN_LIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ja-FreeWnn-lib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nja-FreeWnn-lib}
BUILDLINK_PACKAGES+=	ja-FreeWnn-lib

.if !empty(JA_FREEWNN_LIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ja-FreeWnn-lib+=	ja-FreeWnn-lib>=1.10nb3
BUILDLINK_PKGSRCDIR.ja-FreeWnn-lib?=	../../inputmethod/ja-freewnn-lib
BUILDLINK_DEPMETHOD.ja-freewnn?=	build
.endif	# JA_FREEWNN_LIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
