# $NetBSD: Makefile,v 1.15 2023/01/09 23:18:55 sekiya Exp $

DISTNAME=	rlpr-2.06
PKGREVISION=	3
CATEGORIES=	print
MASTER_SITES=	# ftp://truffula.com/pub/

MAINTAINER=	pkgsrc-users@NetBSD.org
#HOMEPAGE=	http://truffula.com/rlpr/
COMMENT=	Work-alike of lpr to print directly to remote printer
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=		yes

.include "../../devel/gettext-lib/buildlink3.mk"
.include "../../converters/libiconv/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
