@comment $NetBSD: PLIST.App,v 1.1 2025/05/05 08:39:56 tnn Exp $
Applications/Deskflow.app/Contents/Info.plist
Applications/Deskflow.app/Contents/MacOS/Deskflow
Applications/Deskflow.app/Contents/MacOS/deskflow-client
Applications/Deskflow.app/Contents/MacOS/deskflow-server
Applications/Deskflow.app/Contents/Resources/Deskflow.icns
Applications/Deskflow.app/Contents/Resources/LICENSE
Applications/Deskflow.app/Contents/Resources/LICENSE_EXCEPTION
