# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 22:39:14 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RX_BUILDLINK3_MK:=	${RX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	rx
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nrx}
BUILDLINK_PACKAGES+=	rx
BUILDLINK_ORDER+=	rx

.if !empty(RX_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.rx+=		rx>=1.5
BUILDLINK_PKGSRCDIR.rx?=	../../devel/rx
.endif	# RX_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
