# $NetBSD: buildlink3.mk,v 1.3 2006/04/06 06:21:56 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RX_BUILDLINK3_MK:=	${RX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	rx
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nrx}
BUILDLINK_PACKAGES+=	rx

.if !empty(RX_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.rx+=		rx>=1.5
BUILDLINK_PKGSRCDIR.rx?=	../../devel/rx
.endif	# RX_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
