# $NetBSD: buildlink3.mk,v 1.3 2005/11/14 21:57:00 tonio Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
TETEX_BIN_BUILDLINK3_MK:=	${TETEX_BIN_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	teTeX-bin
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NteTeX-bin}
BUILDLINK_PACKAGES+=	teTeX-bin

.if !empty(TETEX_BIN_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.teTeX-bin+=	teTeX-bin-2.[0-9]*
BUILDLINK_PKGSRCDIR.teTeX-bin?=	../../print/teTeX-bin
.endif	# TETEX_BIN_BUILDLINK3_MK

TEX=tex
PDFTEX=pdftex

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
