# $NetBSD: buildlink3.mk,v 1.1 2007/10/29 04:44:04 uebayasi Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
AUCTEX_BUILDLINK3_MK:=	${AUCTEX_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	auctex
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nauctex}
BUILDLINK_PACKAGES+=	auctex
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}auctex

.if ${AUCTEX_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.auctex+=	${EMACS_PKGNAME_PREFIX}auctex>=11
BUILDLINK_PKGSRCDIR.auctex?=	../../print/auctex
.endif	# AUCTEX_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.auctex=	${EGREP} '.*\.el$$|.*\.elc$$'

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
