# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/08/30 17:03:28 drochner Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
DJVULIBRE_LIB_BUILDLINK3_MK:=	${DJVULIBRE_LIB_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	djvulibre-lib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndjvulibre-lib}
BUILDLINK_PACKAGES+=	djvulibre-lib
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}djvulibre-lib

.if ${DJVULIBRE_LIB_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.djvulibre-lib+=	djvulibre-lib>=3.5.17
BUILDLINK_PKGSRCDIR.djvulibre-lib?=	../../graphics/djvulibre-lib
.endif	# DJVULIBRE_LIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
