$NetBSD: patch-Include_asdl.h,v 1.1 2025/04/29 09:33:56 tnn Exp $

* don't redefine bool

--- Include/asdl.h.orig	2025-04-29 09:29:58.921412365 +0000
+++ Include/asdl.h
@@ -6,8 +6,12 @@ typedef PyObject * string;
 typedef PyObject * object;
 
 #ifndef __cplusplus
+#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
+#include <stdbool.h>
+#else
 typedef enum {false, true} bool;
 #endif
+#endif
 
 /* It would be nice if the code generated by asdl_c.py was completely
    independent of Python, but it is a goal the requires too much work
