# $NetBSD: Makefile,v 1.4 2001/02/16 14:46:07 wiz Exp $
#

DISTNAME=	jmk-x11-fonts-3.0
PKGNAME=	jmk-fonts-3.0
CATEGORIES=	fonts x11
MASTER_SITES=	${MASTER_SITE_SUNSITE:=X11/fonts/}

MAINTAINER=	jwise@netbsd.org
HOMEPAGE=	http://www.ntrnet.net/~jmknoble/fonts/
COMMENT=	Jim Knoble's font collection for X11

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
