# $NetBSD: buildlink3.mk,v 1.2 2008/10/07 13:26:57 kefren Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MONO_TOOLS_BUILDLINK3_MK:=	${MONO_TOOLS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mono-tools
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmono-tools}
BUILDLINK_PACKAGES+=	mono-tools
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mono-tools

.if ${MONO_TOOLS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mono-tools+=	mono-tools>=2.0
BUILDLINK_PKGSRCDIR.mono-tools?=	../../devel/mono-tools
.endif	# MONO_TOOLS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
