# $NetBSD: Makefile,v 1.1.1.1 1999/08/16 15:29:37 rh Exp $
#

DISTNAME=	lzo-1.04
PKGNAME=	liblzo-1.04
CATEGORIES=	archivers
MASTER_SITES=	http://wildsau.idv.uni-linz.ac.at/mfx/lzo-download/ \
		ftp://wildsau.idv.uni-linz.ac.at/pub/mfx/lzo/ \
		ftp://metalab.unc.edu/pub/Linux/libs/compression/ \
		ftp://ftp.elf.stuba.sk/pub/pc/pack/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://wildsau.idv.uni-linz.ac.at/mfx/lzo.html

GNU_CONFIGURE=	YES
USE_LIBTOOL=	YES

.include "../../mk/bsd.pkg.mk"
