# $NetBSD: Makefile,v 1.30 2010/03/15 15:41:40 joerg Exp $
#

COMMENT=	Software for geographical-related uses

SUBDIR+=	cm2gpx
SUBDIR+=	cmconvert
SUBDIR+=	epsg
SUBDIR+=	epsg-docs
SUBDIR+=	garmin-utils
SUBDIR+=	garmintools
SUBDIR+=	gdal-lib
SUBDIR+=	geos
SUBDIR+=	gpsbabel
SUBDIR+=	gpsd
SUBDIR+=	gpsdrive
SUBDIR+=	gpspoint
SUBDIR+=	gpsutils
SUBDIR+=	libdrg
SUBDIR+=	mapserver
SUBDIR+=	merkaartor
SUBDIR+=	p5-Geo-Distance
SUBDIR+=	p5-Geo-ShapeFile
SUBDIR+=	proj
SUBDIR+=	proj-swig
SUBDIR+=	py-proj
SUBDIR+=	qlandkartegt
SUBDIR+=	qlandkartegt-garmindev
SUBDIR+=	qlandkartem
SUBDIR+=	shapelib
SUBDIR+=	viking
SUBDIR+=	vis5d+
SUBDIR+=	xrmap
SUBDIR+=	xrmap-anthems
SUBDIR+=	xrmap-base
SUBDIR+=	xrmap-data
SUBDIR+=	xrmap-factbook_html
SUBDIR+=	xrmap-factbook_text
SUBDIR+=	xrmap-flags
SUBDIR+=	xrmap-hymns
SUBDIR+=	xrmap-pdfmaps

.include "../mk/misc/category.mk"
