# $NetBSD: Makefile,v 1.1 2018/05/02 18:16:25 minskim Exp $

DISTNAME=	network_interface-0.0.2
CATEGORIES=	net

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/rapid7/network_interface
COMMENT=	Tool to get information on network interfaces
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
