# $NetBSD: buildlink3.mk,v 1.1 2008/06/05 19:29:46 drochner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBSMI_BUILDLINK3_MK:=	${LIBSMI_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libsmi
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsmi}
BUILDLINK_PACKAGES+=	libsmi
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libsmi

.if ${LIBSMI_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libsmi+=	libsmi>=0.4.5nb1
BUILDLINK_PKGSRCDIR.libsmi?=	../../devel/libsmi
.endif	# LIBSMI_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
