$NetBSD: patch-Cargo.toml,v 1.2 2026/03/12 12:21:15 adam Exp $

Local path to defguard_version crate.

--- Cargo.toml.orig	2025-10-21 13:05:14.884614632 +0000
+++ Cargo.toml
@@ -7,7 +7,7 @@ homepage = "https://github.com/DefGuard/
 repository = "https://github.com/DefGuard/proxy"
 
 [dependencies]
-defguard_version = { git = "https://github.com/DefGuard/defguard.git", rev = "8649a9ba225d7bd2066a09c9e1347705c34bd158" }
+defguard_version = { path = "../defguard-1.6.4/crates/defguard_version" }
 # base `axum` deps
 axum = { version = "0.8", features = ["ws"] }
 axum-client-ip = "0.7"
