# $NetBSD: buildlink3.mk,v 1.2 2004/10/03 00:13:15 tv Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBYAHOO_BUILDLINK3_MK:=	${LIBYAHOO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libyahoo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibyahoo}
BUILDLINK_PACKAGES+=	libyahoo

.if !empty(LIBYAHOO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libyahoo+=	libyahoo>=0.18.4
BUILDLINK_RECOMMENDED.libyahoo+=	libyahoo>=0.18.4nb1
BUILDLINK_PKGSRCDIR.libyahoo?=	../../chat/libyahoo
BUILDLINK_INCDIRS.libyahoo+=	include/libyahoo
.endif	# LIBYAHOO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
