# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/08/19 17:51:14 bjs Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BABL_BUILDLINK3_MK:=	${BABL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	babl
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbabl}
BUILDLINK_PACKAGES+=	babl
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}babl

.if ${BABL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.babl+=	babl>=0.0.22
BUILDLINK_PKGSRCDIR.babl?=	../../graphics/babl
.endif	# BABL_BUILDLINK3_MK

.include "../../mk/dlopen.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
