# $NetBSD: Makefile,v 1.117 2003/05/02 11:56:43 wiz Exp $

MOZILLA=	mozilla
MOZILLA_BIN=	mozilla-bin
MOZ_VER=	1.3
PKGREVISION=	1
EXTRACT_SUFX=	.tar.bz2

COMMENT=	Open-source version of the Netscape browser

USE_CXX=	yes
BUILD_SVG=	# defined
BUILD_CALENDAR=	# defined

.include	"../../www/mozilla/Makefile.common"
