# $NetBSD: buildlink3.mk,v 1.9 2006/07/08 23:10:41 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDL_GFX_BUILDLINK3_MK:=	${SDL_GFX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	SDL_gfx
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NSDL_gfx}
BUILDLINK_PACKAGES+=	SDL_gfx
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}SDL_gfx

.if !empty(SDL_GFX_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.SDL_gfx+=	SDL_gfx>=2.0.3nb2
BUILDLINK_ABI_DEPENDS.SDL_gfx?=	SDL_gfx>=2.0.13nb4
BUILDLINK_PKGSRCDIR.SDL_gfx?=	../../devel/SDL_gfx
.endif	# SDL_GFX_BUILDLINK3_MK

.include "../../devel/SDL/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
