# $NetBSD: buildlink3.mk,v 1.1 2004/03/07 04:21:55 snj Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDL_GFX_BUILDLINK3_MK:=	${SDL_GFX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	SDL_gfx
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NSDL_gfx}
BUILDLINK_PACKAGES+=	SDL_gfx

.if !empty(SDL_GFX_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.SDL_gfx+=	SDL_gfx>=2.0.3nb2
BUILDLINK_PKGSRCDIR.SDL_gfx?=	../../devel/SDL_gfx

.include "../../devel/SDL/buildlink3.mk"

.endif	# SDL_GFX_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
