# $NetBSD: Makefile,v 1.8 2006/03/04 21:29:13 jlam Exp $

DISTNAME=	cvslock-0.2
CATEGORIES=	devel
MASTER_SITES=	ftp://riemann.iam.uni-bonn.de/pub/users/roessler/cvslock/

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Safely manipulate and inspect CVS repositories

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
