# $NetBSD: buildlink3.mk,v 1.5 2006/07/08 23:10:36 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GOOM_BUILDLINK3_MK:=	${GOOM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	goom
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngoom}
BUILDLINK_PACKAGES+=	goom
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}goom

.if !empty(GOOM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.goom+=	goom>=2004.0
BUILDLINK_PKGSRCDIR.goom?=	../../audio/goom
.endif	# GOOM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
