# $NetBSD: buildlink3.mk,v 1.1 2007/10/29 12:41:18 uebayasi Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MEW_BUILDLINK3_MK:=	${MEW_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mew
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmew}
BUILDLINK_PACKAGES+=	mew
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mew

.if ${MEW_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mew+=	${EMACS_PKGNAME_PREFIX}mew>=5
BUILDLINK_PKGSRCDIR.mew?=	../../mail/mew
.endif	# MEW_BUILDLINK3_MK

BUILDLINK_CONTENTS_FILTER.mew=	${EGREP} '.*\.el$$|.*\.elc$$'

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
