# $NetBSD: Makefile,v 1.3 2020/01/18 23:31:48 rillig Exp $

DISTNAME=	pigpen.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.2
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/pigpen
COMMENT=	Documentation for tex-pigpen
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
