# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/09/05 03:32:53 bjs Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
DRI2PROTO_BUILDLINK3_MK:=	${DRI2PROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	dri2proto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndri2proto}
BUILDLINK_PACKAGES+=	dri2proto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}dri2proto

.if ${DRI2PROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.dri2proto+=	dri2proto>=1.1
BUILDLINK_PKGSRCDIR.dri2proto?=	../../x11/dri2proto
BUILDLINK_DEPMETHOD.dri2proto?=	build
.endif	# DRI2PROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
