# $NetBSD: buildlink3.mk,v 1.2 2004/03/06 23:46:06 jlam Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
UNPROVEN_PTHREADS_BUILDLINK3_MK:=	${UNPROVEN_PTHREADS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	unproven-pthreads
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nunproven-pthreads}
BUILDLINK_PACKAGES+=	unproven-pthreads

.if !empty(UNPROVEN_PTHREADS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.unproven-pthreads+=	unproven-pthreads>=0.17
BUILDLINK_PKGSRCDIR.unproven-pthreads?=	../../devel/unproven-pthreads
.endif	# UNPROVEN_PTHREADS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
