# $NetBSD: Makefile,v 1.2 2019/12/06 19:30:04 markd Exp $

DISTNAME=	gillcm
PKGNAME=	tex-${DISTNAME}-1.1
TEXLIVE_REV=	19878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/gillcm
COMMENT=	Alternative unslanted italic Computer Modern fonts
LICENSE=	modified-bsd

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
