# $NetBSD: Makefile,v 1.3 2020/01/18 23:31:34 rillig Exp $

DISTNAME=	gillcm
PKGNAME=	tex-${DISTNAME}-1.1
TEXLIVE_REV=	19878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/gillcm
COMMENT=	Alternative unslanted italic Computer Modern fonts
LICENSE=	modified-bsd

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
