# $NetBSD: buildlink3.mk,v 1.1 2019/09/11 11:32:26 tm Exp $

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE4_BUILDLINK3_MK)
SOPE4_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=4.0.8
BUILDLINK_ABI_DEPENDS.SOPE+=	SOPE>=4.0.8
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE4
.endif # SOPE4_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
