# $NetBSD: buildlink3.mk,v 1.2 2019/09/12 04:45:27 wiz Exp $

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE_BUILDLINK3_MK)
SOPE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=4.0.8
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE4
.endif # SOPE_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
