$NetBSD: patch-Cargo.toml,v 1.4 2026/02/26 12:56:12 pin Exp $

Depends on an unpublished crate. Can't use cargo.mk to fetch it.

--- Cargo.toml.orig	2026-02-26 12:07:51.632391359 +0000
+++ Cargo.toml
@@ -38,7 +38,7 @@ parking_lot = "0.12"
 signal-hook = "0.4"
 human-panic = "2.0"
 parking_lot = "0.12"
-nucleo = { git = "https://github.com/alexpasmantier/nucleo.git", branch = "television" }
+nucleo = { path = "../nucleo-4a5b53c7fa7abb8d777c49dc5850033ae108683e" }
 toml = "0.9"
 lazy-regex = { version = "3.4", features = ["lite"], default-features = false }
 ansi-to-tui = "8.0"
