# $NetBSD: Makefile,v 1.1 2015/05/16 10:30:18 markd Exp $

DISTNAME=	pict2e
PKGNAME=	tex-${DISTNAME}-0.2z
TEXLIVE_REV=	32658

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/pict2e
COMMENT=	New implementation of picture commands
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
