$NetBSD: patch-buildbot_db_migrations_alembic.ini,v 1.1 2026/02/18 10:47:08 wiz Exp $

Fix deprecation warning from alembic >= 1.16.0
https://github.com/buildbot/buildbot/pull/8707

--- buildbot/db/migrations/alembic.ini.orig	2025-05-12 21:31:16.000000000 +0000
+++ buildbot/db/migrations/alembic.ini
@@ -8,7 +8,8 @@ file_template = %%(rev)s_%%(year)d-%%(month).2d-%%(day
 file_template = %%(rev)s_%%(year)d-%%(month).2d-%%(day).2d_%%(slug)s
 
 # sys.path path, will be prepended to sys.path if present.
-# defaults to the current working directory.
+# defaults to the current working directory.  for multiple paths, the path separator
+# is defined by "path_separator" below.
 prepend_sys_path = .
 
 # timezone to use when rendering the date
@@ -29,6 +30,33 @@ version_locations = %(here)s/versions
 # sourceless = false
 
 version_locations = %(here)s/versions
+
+# path_separator; This indicates what character is used to split lists of file
+# paths, including version_locations and prepend_sys_path within configparser
+# files such as alembic.ini.
+# The default rendered in new alembic.ini files is "os", which uses os.pathsep
+# to provide os-dependent path splitting.
+#
+# Note that in order to support legacy alembic.ini files, this default does NOT
+# take place if path_separator is not present in alembic.ini.  If this
+# option is omitted entirely, fallback logic is as follows:
+#
+# 1. Parsing of the version_locations option falls back to using the legacy
+#    "version_path_separator" key, which if absent then falls back to the legacy
+#    behavior of splitting on spaces and/or commas.
+# 2. Parsing of the prepend_sys_path option falls back to the legacy
+#    behavior of splitting on spaces, commas, or colons.
+#
+# Valid values for path_separator are:
+#
+# path_separator = :
+# path_separator = ;
+# path_separator = space
+# path_separator = newline
+#
+# Use os.pathsep. Default configuration used for new projects.
+path_separator = os
+
 
 # the output encoding used when revision files are written from script.py.mako
 output_encoding = utf-8
