# $NetBSD: buildlink3.mk,v 1.19 2005/01/14 05:10:37 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LINUX_PAM_BUILDLINK3_MK:=	${LINUX_PAM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	linux-pam
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlinux-pam}
BUILDLINK_PACKAGES+=	linux-pam

.if !empty(LINUX_PAM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.linux-pam+=		PAM>=0.75
BUILDLINK_RECOMMENDED.linux-pam+=	PAM>=0.77nb4
BUILDLINK_PKGSRCDIR.linux-pam?=		../../security/PAM
.endif	# LINUX_PAM_BUILDLINK3_MK

.include "../../mk/dlopen.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
