# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/09/03 12:53:29 wiz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBXMLPP_BUILDLINK3_MK:=	${LIBXMLPP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libxmlpp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibxmlpp}
BUILDLINK_PACKAGES+=	libxmlpp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libxmlpp

.if ${LIBXMLPP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libxmlpp+=	libxml++>=1.0.5
BUILDLINK_PKGSRCDIR.libxmlpp?=	../../zzz/libxml++
.endif	# LIBXMLPP_BUILDLINK3_MK

.include "../../textproc/libxml2/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
