# $NetBSD: buildlink3.mk,v 1.3 2004/11/10 09:10:46 xtraeme Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBRADIUS_LINUX_BUILDLINK3_MK:=	${LIBRADIUS_LINUX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libradius
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibradius}
BUILDLINK_PACKAGES+=	libradius

.if !empty(LIBRADIUS_LINUX_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libradius+=	libradius>=20040827
BUILDLINK_PKGSRCDIR.libradius?=	../../net/libradius
BUILDLINK_DEPMETHOD.libradius?=	build
.endif	# LIBRADIUS_LINUX_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
