# $NetBSD: Makefile,v 1.1.1.1 2004/10/20 22:45:30 manu Exp $
#

DISTNAME=	libradius-linux-20040827
CATEGORIES=	net
MASTER_SITES=	http://portal-to-web.de/tacacs/

MAINTAINER=	manu@netbsd.org
COMMENT=	RADIUS client library

WRKSRC=		${WRKDIR}/libradius-linux

.include "../../mk/bsd.pkg.mk"
