# $NetBSD: Makefile,v 1.11 2018/04/13 13:55:33 jaapb Exp $

DISTNAME=	ocamlmod-0.0.8
PKGREVISION=	3
CATEGORIES=	devel
MASTER_SITES=	http://forge.ocamlcore.org/frs/download.php/1544/

MAINTAINER=	jaapb@NetBSD.org
HOMEPAGE=	http://forge.ocamlcore.org/projects/ocamlmod/
COMMENT=	Generate OCaml modules from source files
LICENSE=	gnu-lgpl-v2.1

OCAML_USE_OASIS=	yes
OCAML_FINDLIB_REGISTER=	no

.include "../../mk/ocaml.mk"
.include "../../mk/bsd.pkg.mk"
