# $NetBSD: buildlink3.mk,v 1.4 2006/07/08 23:10:37 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSIDPLAY2_BUILDLINK3_MK:=	${LIBSIDPLAY2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libsidplay2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsidplay2}
BUILDLINK_PACKAGES+=	libsidplay2
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libsidplay2

.if !empty(LIBSIDPLAY2_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libsidplay2+=	libsidplay2>=2.0.9
BUILDLINK_PKGSRCDIR.libsidplay2?=	../../audio/libsidplay2
.endif	# LIBSIDPLAY2_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
