# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/04/09 13:12:02 joerg Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSIDPLAY2_BUILDLINK3_MK:=	${LIBSIDPLAY2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libsidplay2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsidplay2}
BUILDLINK_PACKAGES+=	libsidplay2

.if !empty(LIBSIDPLAY2_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libsidplay2+=	libsidplay2>=2.0.9
BUILDLINK_PKGSRCDIR.libsidplay2?=	../../audio/libsidplay2
.endif	# LIBSIDPLAY2_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
