# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:52 wiz Exp $

DISTNAME=	pacioli
PKGNAME=	tex-${DISTNAME}-2014
TEXLIVE_REV=	24947

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/pacioli
COMMENT=	Fonts designed by Fra Luca de Pacioli in 1497
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
