.\"     $NetBSD: free.1,v 1.2 2003/10/15 19:54:56 wiz Exp $
.Dd August 29, 2003
.Dt FREE 1
.Os
.Sh NAME
.Nm free
.Nd display amount of free and used memory in the system
.Sh SYNOPSIS
.Nm
.Op Fl hkm
.Sh DESCRIPTION
The
.Nm
script displays the amount of free and used memory in the system.
.Pp
Possible options are:
.Bl -tag -width xxx
.It Fl h
Show usage.
.It Fl k
Display the values in kilobyte.
(Default.)
.It Fl m
Display the values in megabyte.
.El
.Pp
The
.Fl k
and
.Fl m
flags are obviously conflicting -- the first
one found will win.
.Sh SEE ALSO
.Xr vmstat 1
.Sh HISTORY
The
.Nm
utility and manpage were written by
.An Karsten Kruse
.Aq tecneeq@tecneeq.de .
