# $NetBSD: Makefile,v 1.8 2003/07/17 21:30:30 grant Exp $

DISTNAME=	fortran-utils-1.1
WRKSRC=		${WRKDIR}/fortran-utils
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	tech-pkg@NetBSD.org
COMMENT=	Utilities for Fortran programmers

NO_SRC_ON_FTP=	Already in MASTER_SITE_LOCAL

.include "../../mk/bsd.pkg.mk"
