@comment $NetBSD: PLIST.emacs,v 1.1.1.1 2000/12/01 06:18:16 jtb Exp $
@unexec install-info --delete --info-dir=%D/info %D/info/w3-faq.info
@unexec install-info --delete --info-dir=%D/info %D/info/w3.info
info/w3-faq.info
info/w3.info
info/w3.info-1
info/w3.info-2
info/w3.info-3
info/w3.info-4
info/w3.info-5
@exec install-info --info-dir=%D/info %D/info/w3-faq.info
@exec install-info --info-dir=%D/info %D/info/w3.info
share/default.css
share/emacs/site-lisp/w3/auto-autoloads.el
share/emacs/site-lisp/w3/auto-autoloads.elc
share/emacs/site-lisp/w3/base64.el
share/emacs/site-lisp/w3/base64.elc
share/emacs/site-lisp/w3/css.el
share/emacs/site-lisp/w3/css.elc
share/emacs/site-lisp/w3/custom-load.el
share/emacs/site-lisp/w3/custom-load.elc
share/emacs/site-lisp/w3/devices.el
share/emacs/site-lisp/w3/devices.elc
share/emacs/site-lisp/w3/docomp.el
share/emacs/site-lisp/w3/dsssl-flow.el
share/emacs/site-lisp/w3/dsssl-flow.elc
share/emacs/site-lisp/w3/dsssl.el
share/emacs/site-lisp/w3/dsssl.elc
share/emacs/site-lisp/w3/font.el
share/emacs/site-lisp/w3/font.elc
share/emacs/site-lisp/w3/images.el
share/emacs/site-lisp/w3/images.elc
share/emacs/site-lisp/w3/md5.el
share/emacs/site-lisp/w3/md5.elc
share/emacs/site-lisp/w3/mm.el
share/emacs/site-lisp/w3/mm.elc
share/emacs/site-lisp/w3/mule-sysdp.el
share/emacs/site-lisp/w3/mule-sysdp.elc
share/emacs/site-lisp/w3/socks.el
share/emacs/site-lisp/w3/socks.elc
share/emacs/site-lisp/w3/ssl.el
share/emacs/site-lisp/w3/ssl.elc
share/emacs/site-lisp/w3/url-auth.el
share/emacs/site-lisp/w3/url-auth.elc
share/emacs/site-lisp/w3/url-cache.el
share/emacs/site-lisp/w3/url-cache.elc
share/emacs/site-lisp/w3/url-cid.el
share/emacs/site-lisp/w3/url-cookie.el
share/emacs/site-lisp/w3/url-cookie.elc
share/emacs/site-lisp/w3/url-file.el
share/emacs/site-lisp/w3/url-file.elc
share/emacs/site-lisp/w3/url-gopher.el
share/emacs/site-lisp/w3/url-gopher.elc
share/emacs/site-lisp/w3/url-gw.el
share/emacs/site-lisp/w3/url-gw.elc
share/emacs/site-lisp/w3/url-http.el
share/emacs/site-lisp/w3/url-http.elc
share/emacs/site-lisp/w3/url-irc.el
share/emacs/site-lisp/w3/url-irc.elc
share/emacs/site-lisp/w3/url-ldap.el
share/emacs/site-lisp/w3/url-ldap.elc
share/emacs/site-lisp/w3/url-mail.el
share/emacs/site-lisp/w3/url-mail.elc
share/emacs/site-lisp/w3/url-misc.el
share/emacs/site-lisp/w3/url-misc.elc
share/emacs/site-lisp/w3/url-news.el
share/emacs/site-lisp/w3/url-news.elc
share/emacs/site-lisp/w3/url-nfs.el
share/emacs/site-lisp/w3/url-nfs.elc
share/emacs/site-lisp/w3/url-ns.el
share/emacs/site-lisp/w3/url-ns.elc
share/emacs/site-lisp/w3/url-parse.el
share/emacs/site-lisp/w3/url-parse.elc
share/emacs/site-lisp/w3/url-vars.el
share/emacs/site-lisp/w3/url-vars.elc
share/emacs/site-lisp/w3/url.el
share/emacs/site-lisp/w3/url.elc
share/emacs/site-lisp/w3/w3-about.el
share/emacs/site-lisp/w3/w3-about.elc
share/emacs/site-lisp/w3/w3-auto.el
share/emacs/site-lisp/w3/w3-auto.elc
share/emacs/site-lisp/w3/w3-cfg.el
share/emacs/site-lisp/w3/w3-cfg.elc
share/emacs/site-lisp/w3/w3-cus.el
share/emacs/site-lisp/w3/w3-cus.elc
share/emacs/site-lisp/w3/w3-display.el
share/emacs/site-lisp/w3/w3-display.elc
share/emacs/site-lisp/w3/w3-e19.el
share/emacs/site-lisp/w3/w3-e19.elc
share/emacs/site-lisp/w3/w3-e20.el
share/emacs/site-lisp/w3/w3-e20.elc
share/emacs/site-lisp/w3/w3-elisp.el
share/emacs/site-lisp/w3/w3-elisp.elc
share/emacs/site-lisp/w3/w3-emulate.el
share/emacs/site-lisp/w3/w3-emulate.elc
share/emacs/site-lisp/w3/w3-forms.el
share/emacs/site-lisp/w3/w3-forms.elc
share/emacs/site-lisp/w3/w3-hot.el
share/emacs/site-lisp/w3/w3-hot.elc
share/emacs/site-lisp/w3/w3-hotindex.el
share/emacs/site-lisp/w3/w3-hotindex.elc
share/emacs/site-lisp/w3/w3-imap.el
share/emacs/site-lisp/w3/w3-imap.elc
share/emacs/site-lisp/w3/w3-java.el
share/emacs/site-lisp/w3/w3-java.elc
share/emacs/site-lisp/w3/w3-jscript.el
share/emacs/site-lisp/w3/w3-jscript.elc
share/emacs/site-lisp/w3/w3-keyword.el
share/emacs/site-lisp/w3/w3-keyword.elc
share/emacs/site-lisp/w3/w3-latex.el
share/emacs/site-lisp/w3/w3-latex.elc
share/emacs/site-lisp/w3/w3-menu.el
share/emacs/site-lisp/w3/w3-menu.elc
share/emacs/site-lisp/w3/w3-mouse.el
share/emacs/site-lisp/w3/w3-mouse.elc
share/emacs/site-lisp/w3/w3-parse.el
share/emacs/site-lisp/w3/w3-parse.elc
share/emacs/site-lisp/w3/w3-print.el
share/emacs/site-lisp/w3/w3-print.elc
share/emacs/site-lisp/w3/w3-props.el
share/emacs/site-lisp/w3/w3-props.elc
share/emacs/site-lisp/w3/w3-script.el
share/emacs/site-lisp/w3/w3-script.elc
share/emacs/site-lisp/w3/w3-speak-table.el
share/emacs/site-lisp/w3/w3-speak-table.elc
share/emacs/site-lisp/w3/w3-speak.el
share/emacs/site-lisp/w3/w3-speak.elc
share/emacs/site-lisp/w3/w3-style.el
share/emacs/site-lisp/w3/w3-style.elc
share/emacs/site-lisp/w3/w3-sysdp.el
share/emacs/site-lisp/w3/w3-toolbar.el
share/emacs/site-lisp/w3/w3-toolbar.elc
share/emacs/site-lisp/w3/w3-vars.el
share/emacs/site-lisp/w3/w3-vars.elc
share/emacs/site-lisp/w3/w3-widget.el
share/emacs/site-lisp/w3/w3-widget.elc
share/emacs/site-lisp/w3/w3-xemac.el
share/emacs/site-lisp/w3/w3-xemac.elc
share/emacs/site-lisp/w3/w3.el
share/emacs/site-lisp/w3/w3.elc
@dirrm share/emacs/site-lisp/w3
