# $NetBSD: Makefile,v 1.1 2015/05/08 11:27:49 wiz Exp $

DISTNAME=	mdsymbol.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.5
TEXLIVE_REV=	28399

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/mdsymbol
COMMENT=	Documentation for tex-mdsymbol
LICENSE=	ofl-v1.1

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
