# $NetBSD: Makefile,v 1.4 2020/01/18 23:33:58 rillig Exp $

DISTNAME=	currvita
PKGNAME=	tex-${DISTNAME}-2016
TEXLIVE_REV=	15878

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/currvita
COMMENT=	Typeset a curriculum vitae
LICENSE=	gnu-gpl-v2

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
