# $NetBSD: Makefile,v 1.6 2024/05/09 01:32:12 pho Exp $

DISTNAME=	sop-core-0.5.0.2
PKGREVISION=	4
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	True Sums of Products
LICENSE=	modified-bsd

HASKELL_UNRESTRICT_DEPENDENCIES+=	\
	base \
	deepseq

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
