# $NetBSD: buildlink3.mk,v 1.9.2.2 2006/08/14 17:14:12 ghen Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
SQUIRRELMAIL_BUILDLINK3_MK:=	${SQUIRRELMAIL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	squirrelmail
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsquirrelmail}
BUILDLINK_PACKAGES+=	squirrelmail

.if !empty(SQUIRRELMAIL_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.squirrelmail+=	squirrelmail>=1.4.8
BUILDLINK_PKGSRCDIR.squirrelmail?=	../../mail/squirrelmail
.endif	# SQUIRRELMAIL_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
