# $NetBSD: Makefile,v 1.6 2015/04/22 22:45:21 markd Exp $

DISTNAME=	graphics.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.0p
TEXLIVE_REV=	35577

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-graphics

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
