# $NetBSD: Makefile,v 1.10 2017/06/21 07:24:06 markd Exp $

DISTNAME=	graphics.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.2a
TEXLIVE_REV=	44579

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://ctan.org/pkg/latex-graphics
COMMENT=	Documentation for tex-graphics
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
