# $NetBSD: Makefile,v 1.3 2020/01/18 23:31:20 rillig Exp $

DISTNAME=	cmll.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2014
TEXLIVE_REV=	17964

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/cmll
COMMENT=	Documentation for tex-cmll
LICENSE=	lppl-1.3c

TEXLIVE_UNVERSIONED=	yes
.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
