# $NetBSD: buildlink3.mk,v 1.2 2006/03/07 19:11:54 peter Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PFLKM_BUILDLINK3_MK:=	${PFLKM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pflkm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npflkm}
BUILDLINK_PACKAGES+=	pflkm

.if !empty(PFLKM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pflkm+=	pflkm>=20040501
BUILDLINK_PKGSRCDIR.pflkm?=	../../security/pflkm
.endif	# PFLKM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
