# $NetBSD: buildlink3.mk,v 1.1 2005/03/30 15:23:53 adam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLPK_BUILDLINK3_MK:=	${GLPK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glpk
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglpk}
BUILDLINK_PACKAGES+=	glpk

.if !empty(GLPK_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.glpk+=	glpk>=4.8nb1
BUILDLINK_PKGSRCDIR.glpk?=	../../math/glpk
.endif	# GLPK_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
