# $NetBSD: buildlink3.mk,v 1.8 2007/01/04 22:38:49 adam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLPK_BUILDLINK3_MK:=	${GLPK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glpk
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglpk}
BUILDLINK_PACKAGES+=	glpk
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}glpk

.if !empty(GLPK_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.glpk+=	glpk>=4.8nb1
BUILDLINK_ABI_DEPENDS.glpk+=	glpk>=4.9nb1
BUILDLINK_PKGSRCDIR.glpk?=	../../math/glpk
.endif	# GLPK_BUILDLINK3_MK

.include "../../devel/gmp/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
