# $NetBSD: buildlink3.mk,v 1.4 2006/04/12 10:27:33 rillig Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBIDENT_BUILDLINK3_MK:=	${LIBIDENT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libident
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibident}
BUILDLINK_PACKAGES+=	libident

.if !empty(LIBIDENT_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libident+=	libident>=0.22
BUILDLINK_ABI_DEPENDS.libident+=	libident>=0.22nb1
BUILDLINK_PKGSRCDIR.libident?=	../../security/libident
.endif	# LIBIDENT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
