# $NetBSD: buildlink3.mk,v 1.1 2004/04/12 20:37:17 snj Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBIDENT_BUILDLINK3_MK:=	${LIBIDENT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libident
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibident}
BUILDLINK_PACKAGES+=	libident

.if !empty(LIBIDENT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libident+=	libident>=0.22
BUILDLINK_PKGSRCDIR.libident?=	../../security/libident
.endif	# LIBIDENT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
