.\" $NetBSD: kver.3,v 1.2 2004/04/24 10:53:03 grant Exp $
.\"
.Dd December 13, 2003
.Os
.Dt KVER 3
.Sh NAME
.Nm kver
.Nd override system version library
.Sh SYNOPSIS
LD_PRELOAD=.../libkver.so uname -a
.Sh DESCRIPTION
The
.Nm
library provides implementations of
.Xr sysctl 3 and
.Xr uname 3 that
shadow the real implementation and could be configured to override the
information identifying the current system.
The library is usually loaded by the run-time link-editor via the
LD_PRELOAD hook.
.Pp
This is useful for, among other things, building packages in a
sandbox/chrooted environment for a different
.Nx
release then the system hosting the sandbox.
.Pp
The library must be configured for reporting a specific
.Nx
release or else it emits a warning message on the standard error output.
The value of the environment variable
.Ev LIBKVER_OSRELEASE
or the ``name'' of the file referenced by the symbolic link named
.Pa /libkver_osrelease
are checked in that order for the
.Nx
release number the library should reports information for.
.Sh EXAMPLES
.Dl env LD_PRELOAD=/lib/libkver.so LIBKVER_OSRELEASE=1.5 uname -r
.Pp
.Dl ln -s 1.6.2 /libkver_osrelease
.Dl env LD_PRELOAD=/lib/libkver.so uname -r
.Sh SEE ALSO
.Xr ld.so 1 ,
.Xr sysctl 3 ,
.Xr uname 3
.Sh AUTHORS
.An Stoned Elipot Aq seb@NetBSD.org
